{
  "hash": "f0bfb077ce78181f7b9473599bf77ac8",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Hands-on Exercise 5\"\nsubtitle: \"Global and Local Measures of Spatial Autocorrelation\"\nauthor: \"An Loc\"\ndate: \"21 September 2026\"\ndate-modified: \"last-modified\"\ndate-format: \"D MMM YYYY\"\nformat:\n  html:\n    toc: true\n    toc-depth: 4\n    toc-expand: true\n    code-fold: false\n    code-copy: true\n    fig-width: 9\n    fig-height: 7\nexecute:\n  echo: true\n  eval: true\n  warning: false\n  message: false\n  freeze: true\n---\n\n# Overview\n\nExercise 4 built a spatial weights matrix and used it to compute a spatially lagged GDP per capita\n(GDPPC) for each of Hunan's 88 counties. At the end of that exercise, the scatterplot of GDPPC\nagainst its spatial lag had a positive slope. This suggested that counties with high GDPPC are\nadjacent to other counties with high GDPPC. No test was made of whether that slope is larger than\nspatial randomness would produce.\n\nThis exercise tests for spatial autocorrelation in two ways. A **global** measure is a single\nstatistic for the whole province, tested against the null hypothesis of spatial randomness. A\n**local** measure is computed for each county, and identifies the counties that belong to a cluster\nand the counties that differ from their neighbours.\n\n**Part 1** reproduces r4gdsa chapter 9, Global Measures of Spatial Autocorrelation: Moran's I,\nGeary's C, their Monte Carlo versions and the spatial correlogram. **Part 2** reproduces chapter 10,\nLocal Measures of Spatial Autocorrelation: local Moran's I with the LISA cluster map, and the\nGetis-Ord Gi\\* hot spot map. **Part 3** examines the method of the two chapters and adds the parts\nof the lecture that neither chapter covers.\n\n::: {.callout-note appearance=\"simple\"}\n\n## Sources\n\nThe hands-on exercise is two chapters, both assigned for Lesson 5:\n\n- [Chapter 9: Global Measures of Spatial Autocorrelation](https://r4gdsa.netlify.app/chap09.html)\n- [Chapter 10: Local Measures of Spatial Autocorrelation](https://r4gdsa.netlify.app/chap10.html)\n\nThe Lesson 5 outline sets five papers as self-reading. Each is used in a specific section.\n\n| Reading | What it contributes | Used in |\n|---|---|---|\n| **Moran (1950)**, \"Notes on Continuous Stochastic Phenomena\" | The statistic, derived for a regular lattice; the expectation −1/(N−1); and the statement that the variance needs a normality assumption while the expectation does not | 3.3, 5.5 |\n| **Geary (1954)**, \"The Contiguity Ratio and Statistical Mapping\" | The squared-difference form, and the clearest statement of what each of the two null models assumes | 3.4, 5.5, 5.6 |\n| **Getis and Ord (1992)**, \"The Analysis of Spatial Association by Use of Distance Statistics\" | The G statistic in both forms, the binary symmetric weights it is defined on, the requirement of a natural origin, and the demonstration that Moran's I cannot tell high-value clustering from low-value clustering | 4.2, 5.4 |\n| **Anselin (1995)**, \"Local Indicators of Spatial Association - LISA\" | The two conditions a statistic must satisfy to be a LISA; a Bonferroni-corrected worked example run on 9,999 permutations; and the claim that permutation inference is identical for the local Moran and both of Gi and Gi\\* | 4.1, 5.3, 5.8 |\n| **Ord and Getis (1995)**, \"Local Spatial Autocorrelation Statistics: Distributional Issues and an Application\" | Simulation evidence for when a normal approximation to a local statistic fails, the extension of Gi to nonbinary weights, and the Bonferroni recommendation | 5.2, 5.3 |\n\nThe outline also lists eight references. Three of them are used on this page:\n\n| Reference | What it contributes | Used in |\n|---|---|---|\n| **Anselin (1996)**, \"The Moran Scatterplot as an ESDA Tool\" | Moran's I as the slope of the regression of the spatial lag on the variable, and the four-quadrant reading of the scatterplot | 4.1.4 |\n| **Getis (2010)**, \"Spatial Autocorrelation\", chapter B.3 of the *Handbook of Applied Spatial Analysis* | The problem of dependent multiple tests in local statistics, and the false discovery rate as one response to it | 5.3.1 |\n| **Mack and Kam (2018)**, \"Is There Space for Violence?\" | A tabulation of neighbour counts across weights definitions before one is chosen | 5.7.1 |\n\nThe other five references on the outline are not used on this page.\n\n:::\n\n## Differences from the chapters\n\n| | The chapter | This page | Why | Where |\n|---|---|---|---|---|\n| **Projected CRS** | chapter 10 uses EPSG:32650, chapter 9 does not project at all | EPSG:32649 throughout | Hunan spans 108.78°E to 114.25°E, so it lies in UTM zone 49N. Zone 50N starts at 114°E. The wrong zone narrows the fixed bandwidth from 62,955 m to 60,800 m, a 3.4% change on the correct figure | 5.1 |\n| **Local p-values** | `nsim = 99` is passed, then `p_ii` is used | `p_ii_sim`, with `nsim = 999` | Both come from the same permutations, but `p_ii` is a normal approximation to a distribution the same call reports as skewed. The choice changes the count of significant counties from 13 to 16 and changes which ones | 5.2 |\n| **Number of simulations** | chapter 10 uses 99 for the local statistics | 999 | A rank-based p-value cannot fall below `2 / (nsim + 1)`, so at 99 its minimum is 0.02, above the Bonferroni bound for 88 counties. Chapter 9 already uses 999 | 5.2, 5.3 |\n| **Multiple comparisons** | not mentioned | measured, with the positions of both assigned papers | Ord and Getis (1995) recommend Bonferroni and Anselin (1995) applies it. 88 tests at α = 0.05 expect about four false positives, and at `nsim = 999` no county remains significant under either correction | 5.3 |\n| **Natural origin of the G variable** | standardises `GDPPC` for the scatterplot and uses the raw values for Gi\\*, without saying why | tested by shifting GDPPC | Getis and Ord (1992) state that G is scale-invariant but not location-invariant. Adding 100,000 to GDPPC changes the p-value of global G from 0.0012 to 0.19 and leaves Moran's I unchanged | 5.4.1 |\n| **Gi against the local Moran** | presented as separate analyses | the permutation inference compared directly | Anselin (1995) claims it is identical for the local Moran, Gi and Gi\\*. On these weights it holds for all three, up to simulation error, so chapter 10's two maps differ in their weights and in how they label counties | 5.8 |\n| **Standardised Moran scatterplot** | `scale(lag_GDPPC)` on the vertical axis | the lag of the standardised variable, as in Anselin (1996) | Standardising the lag separately makes the slope of the fitted line 0.485, the Pearson correlation of GDPPC with its lag, where Moran's I is 0.301 | 4.1.4 |\n| **Choice of `k` for Gi\\*** | `k = 6`, not examined | `k` = 4, 6 and 8 compared | Significant counties rise from 17 to 25 with `k`; twelve keep the same classification under every value | 5.7.1 |\n| **Getis-Ord global G** | not covered | added, with `globalG.test()` | Slides 16 and 17 cover it and neither chapter reaches it | 5.4 |\n| **Local Geary's c** | not covered | added, with `local_c_perm()` | Slide 26 names it as the other LISA. It finds 21 significant counties where local Moran's I finds 16 | 5.6 |\n| **Adaptive distance weights** | computed as `hunan_adw`, never used | used, and compared against the fixed band | The chapter builds the object and then runs Gi\\* on the fixed-band weights only. The two disagree on 15 of the 88 counties | 5.7 |\n| **Moran's I null model** | `randomisation = TRUE` default, not discussed | the three null models explained from the assigned readings | The default z-score and the permutation test in Part 1 rest on different assumptions, and Moran's own variance assumes normality | 5.5 |\n\n::: {.callout-note collapse=\"true\"}\n## Mapping of chapters 9 and 10 to this page\n\nEvery substantive section of both chapters is covered. Chapter 10 repeats chapter 9's data import\nin its sections 10.2 and 10.3, so those rows are not duplicated below.\n\n| Chapter | This page |\n|---|---|\n| 9.1 Overview | 1 Overview |\n| 9.2 Getting started | 2.1 Packages |\n| 9.3.1 Import shapefile | 2.2.1 County boundaries |\n| 9.3.2 Import csv | 2.2.2 Development indicators |\n| 9.3.3 Performing relational join | 2.3 Joining the two |\n| 9.3.4 Visualising regional development indicator | 3.1 Mapping GDPPC |\n| 9.4.1 Computing contiguity spatial weights | 3.2 Contiguity weights |\n| 9.4.2 Row-standardised weights matrix | 3.2 Contiguity weights |\n| 9.5.1 Moran's I test | 3.3.1 The test |\n| 9.5.2 Computing Monte Carlo Moran's I | 3.3.2 The permutation test |\n| 9.5.3 Visualising Monte Carlo Moran's I | 3.3.3 The simulated distribution |\n| 9.6.1 Geary's C test | 3.4.1 The test |\n| 9.6.2 Computing Monte Carlo Geary's C | 3.4.2 The permutation test |\n| 9.6.3 Visualising the Monte Carlo Geary's C | 3.4.3 The simulated distribution |\n| 9.7.1 Compute Moran's I correlogram | 3.5 Spatial correlogram |\n| 9.7.2 Compute Geary's C correlogram | 3.5 Spatial correlogram |\n| 10.4.1 Computing contiguity spatial weights | 4.1.1 Weights the sfdep way |\n| 10.4.2 Row-standardised weights matrix | 4.1.1 Weights the sfdep way |\n| 10.4.3 Computing local Moran's I | 4.1.2 Local Moran's I |\n| 10.4.3.1 to 10.4.3.4 Mapping | 4.1.3 The two maps |\n| 10.4.4.1 Plotting Moran scatterplot | 4.1.4 Moran scatterplot |\n| 10.4.4.2 Standardised variable | 4.1.4 Moran scatterplot |\n| 10.4.4.3 Preparing LISA map classes | 4.1.5 LISA cluster map |\n| 10.4.4.4 Plotting and visualising LISA map | 4.1.5 LISA cluster map |\n| 10.5.1 Deriving distance weight matrix | 4.2.1 Distance weights |\n| 10.5.2 Computing local Gi\\* | 4.2.2 Local Gi\\* |\n| 10.5.3 Preparing and visualising HCSA map | 4.2.3 Hot and cold spot map |\n:::\n\n# Getting started\n\n## Packages\n\n`spdep` provides the global statistics and the correlogram. `sfdep` provides the local statistics,\nreturning them as columns of a data frame. The two give identical local Moran values. `sfdep` avoids\nthe matrix that `spdep` returns, which has to be bound to the sf object by row position.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(sf, spdep, sfdep, tmap, tidyverse, knitr)\n```\n:::\n\n\n::: {.callout-note collapse=\"false\" title=\"How the code works\"}\nThe block uses one function:\n\n```r\npacman::p_load(..., install = TRUE)                       # pacman\n```\n\n- `p_load()` loads each package named in `...`, and first installs any that are missing, because\n  `install = TRUE` is the default. It replaces a separate `install.packages()` and `library()` call\n  for each package.\n- The `pacman::` prefix calls the function from `pacman` without attaching the package itself.\n:::\n\n## The data\n\nBoth chapters use the same two files as Chapter 8, described in Exercise 4.\n\n| Layer | Format | Features | Native CRS | Contents |\n|---|---|---|---|---|\n| `Hunan` | ESRI shapefile | 88 polygons | WGS 84, EPSG:4326 | County boundaries of Hunan province |\n| `Hunan_2012` | CSV | 88 rows, 29 fields | not spatial | 2012 development indicators by county |\n\n### County boundaries\n\nThe shapefile is in geographic coordinates (degrees). Contiguity is defined by shared boundaries and\nis unaffected by the projection, but every distance-based weight depends on the projection. Section\n5.1 identifies the UTM zone for Hunan as zone 49N (EPSG:32649), and the layer is projected to that\nzone here so that one CRS is used throughout the page.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan <- st_read(dsn = \"data/geospatial\", layer = \"Hunan\", quiet = TRUE) |>\n  st_transform(crs = 32649)\nst_crs(hunan)$input\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"EPSG:32649\"\n```\n\n\n:::\n\n```{.r .cell-code}\nnrow(hunan)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 88\n```\n\n\n:::\n:::\n\n\n::: {.callout-note collapse=\"false\" title=\"How the code works\"}\nThe block uses three functions and the pipe:\n\n```r\nst_read(dsn, layer, quiet = FALSE)                        # sf\nst_transform(x, crs)                                      # sf\nst_crs(x)                                                 # sf\n```\n\n- `st_read()` reads a vector data file into an sf data frame: one row per feature, with attribute\n  columns and a geometry column. For a shapefile, `dsn` is the folder and `layer` is the file name\n  without its extension. `quiet = TRUE` suppresses the summary it otherwise prints, which begins\n  with the full path of the data folder on the computer that renders the page.\n- `|>` is R's native pipe. It passes the result on its left as the first argument of the function on\n  its right, so `st_transform()` receives the layer from `st_read()` as its `x`.\n- `st_transform()` recalculates every coordinate in the CRS given in `crs`, here EPSG:32649, UTM\n  zone 49N, in metres. `st_set_crs()` would change only the label, and leave the coordinates in\n  degrees.\n- `st_crs()` returns the CRS of an object, and `$input` extracts the code it was set from. `nrow()`\n  counts the counties.\n\nThe figure shows what `st_transform()` does to the layer.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Hands-on_Ex05_files/figure-html/unnamed-chunk-3-1.png){width=864}\n:::\n:::\n\n:::\n\n### Development indicators\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan2012 <- read_csv(\"data/aspatial/Hunan_2012.csv\", show_col_types = FALSE)\ndim(hunan2012)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 88 29\n```\n\n\n:::\n:::\n\n\n::: {.callout-note collapse=\"false\" title=\"How the code works\"}\nThe block uses one function:\n\n```r\nread_csv(file, show_col_types = should_show_types())      # readr\n```\n\n- `read_csv()` reads a comma-separated file into a tibble and guesses the type of each column from\n  its values. `show_col_types = FALSE` suppresses the message that lists those guesses.\n- `dim()` returns the number of rows and columns.\n\nThe two files are read by different functions, which return different kinds of object:\n\n| | `read_csv()` | `st_read()` |\n|---|---|---|\n| Package | `readr`, part of the tidyverse | `sf` |\n| Reads | a table of values, here a CSV file | a spatial file, here a shapefile |\n| Returns | a tibble (`tbl_df`), a kind of data frame | an sf data frame: a data frame with a geometry column |\n| Geometry and CRS | none | one polygon per row, with its CRS |\n| On this page | `Hunan_2012`: 88 rows, 29 columns of indicators | `Hunan`: 88 county polygons with 7 attribute fields |\n| Role on this page | supplies GDPPC, the variable every statistic tests | supplies the county boundaries, from which the maps are drawn and the neighbours found |\n\n`left_join()` in the next section attaches the CSV's columns to the county polygons, so that GDPPC\nand the geometry are in one sf object.\n:::\n\n## Joining the two\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan <- left_join(hunan, hunan2012, by = \"County\") |>\n  select(1:4, 7, 15)\nnames(hunan)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"NAME_2\"    \"ID_3\"      \"NAME_3\"    \"ENGTYPE_3\" \"County\"    \"GDPPC\"    \n[7] \"geometry\" \n```\n\n\n:::\n:::\n\n\n::: {.callout-note collapse=\"false\" title=\"How the code works\"}\nThe block uses two functions:\n\n```r\nleft_join(x, y, by = NULL)                                # dplyr\nselect(.data, ...)                                        # dplyr\n```\n\n- `left_join()` keeps every row of `x`, here `hunan` with its geometry, and adds the columns of `y`\n  from the matching row. `by` names the column to match on. With the default, `NULL`, it matches on\n  every column name the two tables share and prints a message naming them. Chapter 9 relies on that\n  default. This chunk names `by = \"County\"`, as in Exercise 4, which fixes the match to one column.\n- `select()` keeps the columns listed in `...`, given as names or as positions. `1:4, 7, 15` are\n  positions in the joined table. On an sf object the geometry column is kept without being listed.\n\nThe joined table has 36 columns. Columns 8 to 35 come from the CSV. The columns that `select()`\nkeeps are shaded:\n\n<table class=\"table table-sm\">\n<tr><th style=\"background: rgba(255, 193, 7, 0.30)\">1</th><th style=\"background: rgba(255, 193, 7, 0.30)\">2</th><th style=\"background: rgba(255, 193, 7, 0.30)\">3</th><th style=\"background: rgba(255, 193, 7, 0.30)\">4</th><th>5</th><th>6</th><th style=\"background: rgba(255, 193, 7, 0.30)\">7</th><th>8</th><th>…</th><th style=\"background: rgba(255, 193, 7, 0.30)\">15</th><th>…</th><th style=\"background: rgba(255, 193, 7, 0.30)\">36</th></tr>\n<tr><td style=\"background: rgba(255, 193, 7, 0.30)\">NAME_2</td><td style=\"background: rgba(255, 193, 7, 0.30)\">ID_3</td><td style=\"background: rgba(255, 193, 7, 0.30)\">NAME_3</td><td style=\"background: rgba(255, 193, 7, 0.30)\">ENGTYPE_3</td><td>Shape_Leng</td><td>Shape_Area</td><td style=\"background: rgba(255, 193, 7, 0.30)\">County</td><td>City</td><td>…</td><td style=\"background: rgba(255, 193, 7, 0.30)\">GDPPC</td><td>…</td><td style=\"background: rgba(255, 193, 7, 0.30)\">geometry</td></tr>\n</table>\n\nSelection by position depends on this column order. The printed names confirm that the six\nattributes kept are the ones intended.\n\nThe same columns can be selected by name, which does not depend on the column order and states what\nis kept:\n\n```r\nhunan <- left_join(hunan, hunan2012, by = \"County\") |>\n  select(NAME_2, ID_3, NAME_3, ENGTYPE_3, County, GDPPC)\n```\n\nBoth versions return the same object. The page keeps the chapter's positions so that its code\nmatches chapter 9.\n:::\n\n# Part 1: Global measures of spatial autocorrelation\n\nThis part follows r4gdsa [Chapter 9](https://r4gdsa.netlify.app/chap09.html). Each statistic in it\nis a single value for the whole province, tested against the null hypothesis of spatial randomness.\n\n## Mapping GDPPC\n\n\n::: {.cell}\n\n```{.r .cell-code}\nequal <- tm_shape(hunan) +\n  tm_polygons(fill = \"GDPPC\",\n              fill.scale = tm_scale_intervals(style = \"equal\", n = 5,\n                                              values = \"brewer.blues\"),\n              fill.legend = tm_legend(title = \"GDPPC\",\n                                      position = tm_pos_out(\"right\", \"center\"))) +\n  tm_borders(col_alpha = 0.5) +\n  tm_title(\"Equal interval classification\")\n\nquantile <- tm_shape(hunan) +\n  tm_polygons(fill = \"GDPPC\",\n              fill.scale = tm_scale_intervals(style = \"quantile\", n = 5,\n                                              values = \"brewer.blues\"),\n              fill.legend = tm_legend(title = \"GDPPC\",\n                                      position = tm_pos_out(\"right\", \"center\"))) +\n  tm_borders(col_alpha = 0.5) +\n  tm_title(\"Quantile classification\")\n\ntmap_arrange(equal, quantile, asp = 1, ncol = 2)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05_files/figure-html/unnamed-chunk-6-1.png){width=864}\n:::\n:::\n\n\n::: {.callout-note collapse=\"false\" title=\"How the code works\"}\nThe block uses eight functions:\n\n```r\ntm_shape(shp)                                             # tmap\ntm_polygons(fill, fill.scale, fill.legend)                # tmap\ntm_scale_intervals(n = 5, style = \"pretty\", values = NA)  # tmap\ntm_legend(title, position)                                # tmap\ntm_pos_out(cell.h, cell.v)                                # tmap\ntm_borders(col, col_alpha)                                # tmap\ntm_title(text)                                            # tmap\ntmap_arrange(..., ncol = NA, asp = 0)                     # tmap\n```\n\n- `tm_shape()` names the sf object that the layers after it draw. Each `+` adds a layer or a\n  setting.\n- `tm_polygons()` draws the polygons. Each visual property in tmap v4 has three arguments: `fill`\n  names the variable that sets the colour, `fill.scale` sets how its values map to colours, and\n  `fill.legend` sets the legend.\n- `tm_scale_intervals()` divides a numeric variable into `n` classes by the method in `style`, and\n  colours them from the palette in `values`, here the ColorBrewer Blues palette. The default style\n  is `\"pretty\"`. Only `style` differs between the two maps.\n- `tm_legend()` sets the legend title and position. `tm_pos_out(\"right\", \"center\")` places the\n  legend outside the map frame, to the right and centred vertically, so that it covers no county.\n- `tm_borders()` adds a layer that draws only the county boundaries, here at half opacity\n  (`col_alpha = 0.5`). `tm_polygons()` already draws the boundaries, in dark grey at full opacity,\n  so on these maps the extra layer changes little. Chapter 9 includes the same layer.\n- `tm_title()` adds the title above the map.\n- `tmap_arrange()` places stored maps side by side in `ncol` columns. `asp = 1` gives each map an\n  aspect ratio of 1, where the default, `0`, fits each map to its cell.\n:::\n\nIn the chapters, the two maps illustrate the effect of the classification method on the apparent\npattern. With a right-skewed variable such as GDPPC, equal-interval breaks place most of the\nprovince in the lowest class and Changsha alone in the highest. Quantile breaks assign an equal\nnumber of counties to each class and show higher GDPPC in the north east than in the west.\n\nChapter 10 asks two questions of these maps:\n\n- **Do they reveal outliers or clusters?** Changsha stands out as an outlier, the only county in the\n  highest equal-interval class. The quantile map suggests a cluster of higher GDPPC in the north\n  east and of lower GDPPC in the west.\n- **Do they indicate hot spots or cold spots?** They suggest where these may lie, around Changsha\n  and in the west, but a choropleth cannot show whether the pattern is significant. Section 3.3\n  tests it for the province, and sections 4.1 and 4.2 for each county.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(hunan$GDPPC)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n   8497   14566   20433   24405   27224   88656 \n```\n\n\n:::\n:::\n\n\n## Contiguity weights\n\nChapter 9 builds the neighbour list with Queen contiguity and divides each county's weights by its\nneighbour count. Exercise 4 built the same matrix.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_q <- poly2nb(hunan, queen = TRUE)\nsummary(wm_q)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNeighbour list object:\nNumber of regions: 88 \nNumber of nonzero links: 448 \nPercentage nonzero weights: 5.785124 \nAverage number of links: 5.090909 \nLink number distribution:\n\n 1  2  3  4  5  6  7  8  9 11 \n 2  2 12 16 24 14 11  4  2  1 \n2 least connected regions:\n30 65 with 1 link\n1 most connected region:\n85 with 11 links\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrswm_q <- nb2listw(wm_q, style = \"W\", zero.policy = TRUE)\nrswm_q\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCharacteristics of weights list object:\nNeighbour list object:\nNumber of regions: 88 \nNumber of nonzero links: 448 \nPercentage nonzero weights: 5.785124 \nAverage number of links: 5.090909 \n\nWeights style: W \nWeights constants summary:\n   n   nn S0       S1       S2\nW 88 7744 88 37.86334 365.9147\n```\n\n\n:::\n:::\n\n\n::: {.callout-note collapse=\"false\" title=\"How the code works\"}\nThe two blocks above use two functions:\n\n```r\npoly2nb(pl, queen = TRUE)                                 # spdep\nnb2listw(neighbours, style = \"W\", zero.policy = NULL)     # spdep\n```\n\n- `poly2nb()` builds a neighbour list from polygons: for each county, the row numbers of the\n  counties whose boundaries touch it. With `queen = TRUE`, the default, one shared boundary point is\n  enough, and `queen = FALSE` requires a shared edge. The call states the default, as chapter 9\n  does.\n- `nb2listw()` turns the neighbour list into a weights object, which the spdep tests take as their\n  `listw` argument. `style = \"W\"`, the default, row-standardises the weights.\n- `zero.policy = TRUE` allows a county with no neighbours. With the default, `NULL`, spdep uses its\n  global option, under which a county with no neighbours stops the function with an error.\n\nThe figure follows one county, Anxiang in row 1, through the two functions. `poly2nb()` records\nthe row numbers of the five counties that touch it, and `nb2listw()` gives each of them a weight of\n1/5.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Hands-on_Ex05_files/figure-html/unnamed-chunk-10-1.png){width=864}\n:::\n:::\n\n:::\n\nRow standardisation makes each county's weights sum to 1. A lagged value is thus a weighted average\nof the neighbouring values, on the same scale as the variable itself. Every global statistic below\nis computed on this weights object.\n\n## Moran's I\n\n### The test\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmoran.test(hunan$GDPPC,\n           listw = rswm_q,\n           zero.policy = TRUE,\n           na.action = na.omit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMoran I test under randomisation\n\ndata:  hunan$GDPPC  \nweights: rswm_q    \n\nMoran I statistic standard deviate = 4.7351, p-value = 1.095e-06\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n      0.300749970      -0.011494253       0.004348351 \n```\n\n\n:::\n:::\n\n\n::: {.callout-note collapse=\"false\" title=\"How the code works\"}\nThe block uses one function:\n\n```r\nmoran.test(x, listw, randomisation = TRUE, zero.policy = attr(listw, \"zero.policy\"),\n           alternative = \"greater\", na.action = na.fail)                  # spdep\n```\n\n- `moran.test()` computes Moran's I for `x` with the weights in `listw`, and tests it against its\n  expectation under spatial randomness. It reports I, its expectation and variance, and the\n  z-score, labelled \"standard deviate\", with its p-value.\n- `randomisation = TRUE`, the default, sets the null model for the variance of I. Section 5.5\n  explains the choice.\n- `alternative` sets the direction of the test. The three options are:\n\n  | `alternative` | Tests whether I is | Pattern it looks for |\n  |---|---|---|\n  | `\"greater\"`, the default | above its expectation | clustering: neighbouring values tend to be similar |\n  | `\"less\"` | below its expectation | dispersion: neighbouring values tend to be dissimilar |\n  | `\"two.sided\"` | different from its expectation in either direction | either pattern |\n\n  This page keeps the default, because the question is whether GDPPC clusters. `moran.mc()` in\n  section 3.3.2 has the same default. The local statistics of Part 2 default to `\"two.sided\"`.\n- `zero.policy = TRUE` permits counties with no neighbours. Hunan has no such county, so the\n  argument has no effect here.\n- `na.action = na.omit` drops counties with missing values, where the default, `na.fail`, stops\n  with an error. GDPPC has no missing values, so this argument also has no effect.\n\nThe figure places the z-score of this test on the standard normal curve. The shaded bands mark how\nfar a z-score lies from zero, and the red line marks the result for GDPPC.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Hands-on_Ex05_files/figure-html/unnamed-chunk-12-1.png){width=864}\n:::\n:::\n\n:::\n\nChapter 9 asks what statistical conclusion the output supports:\n\n- **Moran's I:** 0.301, against an expectation of −0.0115 under spatial randomness. The\n  expectation, −1/(n−1), is slightly negative, because a county is not its own neighbour.\n- **Test:** z = 4.74 and p = 1.1 × 10⁻⁶, so the null hypothesis of spatial randomness is rejected.\n\nSlide 10 of the Lesson 5 lecture gives the reading of I, shown below on a scale from negative to\npositive with the value for GDPPC marked.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\ni_obs <- round(unname(moran.test(hunan$GDPPC, listw = rswm_q)$estimate[1]), 3)\nggplot() +\n  annotate(\"rect\", xmin = -1, xmax = -0.1, ymin = -0.25, ymax = 0.25, fill = \"#67a9cf\", alpha = 0.5) +\n  annotate(\"rect\", xmin = -0.1, xmax = 0.1, ymin = -0.25, ymax = 0.25, fill = \"#fff7bc\") +\n  annotate(\"rect\", xmin = 0.1, xmax = 1, ymin = -0.25, ymax = 0.25, fill = \"#ef8a62\", alpha = 0.5) +\n  annotate(\"segment\", x = -1.05, xend = 1.08, y = 0, yend = 0, linewidth = 0.8,\n           arrow = arrow(ends = \"both\", length = unit(0.3, \"cm\"))) +\n  annotate(\"text\", x = c(-0.55, 0, 0.55), y = 0.55, fontface = \"bold\", size = 4,\n           label = c(\"Negative: dispersed\", \"About zero: random\", \"Positive: clustered\")) +\n  annotate(\"text\", x = c(-0.55, 0, 0.55), y = -0.5, size = 3.2,\n           label = c(\"neighbours tend to be dissimilar\", \"no spatial pattern\",\n                     \"neighbours tend to be similar\")) +\n  annotate(\"point\", x = i_obs, y = 0, size = 3.5, colour = \"darkred\") +\n  annotate(\"label\", x = i_obs, y = 0.25, vjust = -0.2, size = 3.2,\n           label = paste0(\"GDPPC, I = \", i_obs)) +\n  annotate(\"text\", x = c(-1, 0, 1), y = -0.18, label = c(\"-1\", \"0\", \"+1\"), size = 3) +\n  coord_cartesian(xlim = c(-1.15, 1.15), ylim = c(-0.7, 0.75)) +\n  theme_void()\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05_files/figure-html/unnamed-chunk-13-1.png){width=864}\n:::\n:::\n\n\nThe width of the middle band is schematic: whether a value of I is close enough to zero is decided\nby the test above. GDPPC is in the positive case: counties have values more similar to those of\ntheir neighbours than a random allocation of the same 88 values would produce. The test confirms\nthat the higher GDPPC in the north east and lower GDPPC in the west, shown by the quantile map in\nsection 3.1, is not an artefact of the visual interpretation of a choropleth.\n\n### The permutation test\n\nMoran's I has an analytical null distribution. It assumes either that the values are drawn from a\nnormal distribution or that they are a random permutation of the observed values. For a right-skewed\nvariable such as GDPPC, a test that does not depend on this assumption is preferable. A Monte Carlo\ntest constructs the null distribution empirically: the 88 values are randomly reassigned to the 88\ncounties many times, and I is computed for each permutation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nbperm <- moran.mc(hunan$GDPPC,\n                  listw = rswm_q,\n                  nsim = 999,\n                  zero.policy = TRUE,\n                  na.action = na.omit)\nbperm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Moran I\n\ndata:  hunan$GDPPC \nweights: rswm_q  \nnumber of simulations + 1: 1000 \n\nstatistic = 0.30075, observed rank = 1000, p-value = 0.001\nalternative hypothesis: greater\n```\n\n\n:::\n:::\n\n\n::: {.callout-note collapse=\"false\" title=\"How the code works\"}\nThe block uses two functions:\n\n```r\nset.seed(seed)                                            # base R\nmoran.mc(x, listw, nsim, zero.policy = attr(listw, \"zero.policy\"),\n         alternative = \"greater\", na.action = na.fail)    # spdep\n```\n\n- `set.seed()` fixes the starting point of R's random number generator. The permutations are then\n  the same on every render, and the reported p-value does not change between renders.\n- `moran.mc()` runs the Monte Carlo test: it reassigns the values of `x` to the counties at random\n  `nsim` times and computes I for each assignment. `nsim` has no default. With `nsim = 999` the\n  observed I is ranked among 1,000 values, so the smallest attainable pseudo p-value is 1/1000.\n- `alternative = \"greater\"`, the default, tests for positive spatial autocorrelation. `na.action =\n  na.omit` drops counties with missing values, where the default, `na.fail`, stops with an error.\n  GDPPC has no missing values, so the argument has no effect here. `zero.policy` defaults to the\n  setting stored in the weights object, and `rswm_q` was built with `zero.policy = TRUE`, so setting\n  it again changes nothing.\n- `bperm$res` holds the 999 simulated values followed by the observed I as its 1,000th element. The\n  summaries and the histogram below use `bperm$res[1:999]`, which excludes the observed value.\n  Chapter 9 plots the whole of `bperm$res`.\n:::\n\nChapter 9 asks what statistical conclusion the output supports:\n\n- **Rank:** the observed I ranks 1000th of 1000 values, above all 999 permuted values.\n- **Pseudo p-value:** 0.001, the smallest attainable with 999 simulations.\n- **Conclusion:** the null hypothesis of spatial randomness is rejected, as in section 3.3.1.\n\n### The simulated distribution\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(bperm$res[1:999])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.01504572\n```\n\n\n:::\n\n```{.r .cell-code}\nvar(bperm$res[1:999])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.004371574\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(bperm$res[1:999])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. \n-0.18339 -0.06168 -0.02125 -0.01505  0.02611  0.27593 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(tibble(I = bperm$res[1:999]), aes(x = I)) +\n  geom_histogram(bins = 20, fill = \"grey70\", colour = \"black\") +\n  geom_vline(xintercept = -1 / (nrow(hunan) - 1), colour = \"red\") +\n  labs(x = \"Simulated Moran's I\", y = \"Count\",\n       title = \"Monte Carlo null distribution, 999 permutations\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05_files/figure-html/unnamed-chunk-16-1.png){width=864}\n:::\n:::\n\n\n::: {.callout-note collapse=\"false\" title=\"How the code works\"}\nThe block uses these functions:\n\n```r\ntibble(...)                                               # tibble\nggplot(data, aes(x))                                      # ggplot2\ngeom_histogram(bins, fill, colour)                        # ggplot2\ngeom_vline(xintercept, colour)                            # ggplot2\nlabs(x, y, title)                                         # ggplot2\ntheme_minimal()                                           # ggplot2\n```\n\n- `tibble(I = bperm$res[1:999])` builds a data frame with one column, holding the 999 simulated\n  values of Moran's I. The name `I` is chosen here and is only a column name.\n- `ggplot()` starts a plot from that data frame. `aes()` sets the aesthetic mapping: which column\n  controls which visual property of the plot, such as position, colour or size. `aes(x = I)` places\n  the values of column `I` along the horizontal axis. The observed I is not among them, and the text\n  below the plot compares it with the simulated values.\n- Each `+` adds a layer or a setting. `geom_histogram()` sorts the values into `bins = 20` intervals\n  and draws a bar for each, with `fill` setting the colour of the bars and `colour` their outline.\n- `geom_vline()` draws a vertical line at `xintercept`, here the expectation −1/(n−1).\n- `labs()` sets the axis labels and the title, and `theme_minimal()` removes the grey background.\n:::\n\nChapter 9 asks what statistical observation the histogram supports:\n\n- **Centre:** the simulated values are distributed approximately symmetrically around the\n  expectation −1/(n−1), marked by the red line. Chapter 9 draws the line at zero, which at n = 88 is\n  0.0115 away and indistinguishable on this axis.\n- **Observed value:** 0.301, beyond the largest of the 999 simulated values, 0.276.\n\nChapter 9 also sets a challenge: to plot the values with `ggplot2` instead of base graphics. The\nhistogram above is drawn with `ggplot2`.\n\n## Geary's C\n\n### The test\n\nMoran's I is based on the deviation of each county from the provincial mean. Geary's C is based on\nthe squared differences between each county and its neighbours, so it is more sensitive to local\ndifferences between neighbouring values.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngeary.test(hunan$GDPPC, listw = rswm_q)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tGeary C test under randomisation\n\ndata:  hunan$GDPPC \nweights: rswm_q   \n\nGeary C statistic standard deviate = 3.6108, p-value = 0.0001526\nalternative hypothesis: Expectation greater than statistic\nsample estimates:\nGeary C statistic       Expectation          Variance \n        0.6907223         1.0000000         0.0073364 \n```\n\n\n:::\n:::\n\n\n::: {.callout-note collapse=\"false\" title=\"How the code works\"}\nThe block uses one function:\n\n```r\ngeary.test(x, listw, randomisation = TRUE, zero.policy = attr(listw, \"zero.policy\"),\n           alternative = \"greater\")                                        # spdep\n```\n\n- `geary.test()` computes Geary's C for `x` with the weights in `listw`, and tests it against its\n  expectation of 1 under spatial randomness. The call passes only `x` and `listw`, so every other\n  argument keeps its default.\n- The \"standard deviate\" in the output is (1 − C) divided by the standard deviation of C, so it is\n  positive when C is below 1. `alternative = \"greater\"` therefore tests for clustering, as it does\n  for Moran's I, although clustering makes C smaller than its expectation.\n- `randomisation = TRUE`, the default, sets the null model for the variance of C, as for\n  `moran.test()` in section 3.3.1.\n\nThe two maps compare the statistics on one county, Anxiang, and its five neighbours from section\n3.2. Moran's I compares every county with the provincial mean. Geary's C compares Anxiang directly\nwith each neighbour and squares the difference, so the mean plays no part.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Hands-on_Ex05_files/figure-html/unnamed-chunk-18-1.png){width=864}\n:::\n:::\n\n:::\n\nChapter 9 asks what statistical conclusion the output supports. Geary's C for GDPPC is 0.691,\nagainst an expectation of exactly 1 (z = 3.61, p = 1.5 × 10⁻⁴), so the null hypothesis of spatial\nrandomness is rejected.\n\nIts scale is inverted relative to Moran's I. Slide 12 of the Lesson 5 lecture states that C\napproaches 0 and I approaches 1 when similar values cluster:\n\n| Pattern | Moran's I | Geary's C |\n|---|---|---|\n| clustered: neighbouring values similar | positive, towards 1 | below 1, towards 0 |\n| random | about its expectation, −0.0115 | about 1 |\n| dispersed: neighbouring values dissimilar | negative | above 1 |\n| **GDPPC** | **0.301** | **0.691** |\n\nBoth values are on the clustered side, so like Moran's I, C indicates significant positive spatial\nautocorrelation.\n\n### The permutation test\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nbperm <- geary.mc(hunan$GDPPC,\n                  listw = rswm_q,\n                  nsim = 999)\nbperm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Geary C\n\ndata:  hunan$GDPPC \nweights: rswm_q  \nnumber of simulations + 1: 1000 \n\nstatistic = 0.69072, observed rank = 1, p-value = 0.001\nalternative hypothesis: greater\n```\n\n\n:::\n:::\n\n\n::: {.callout-note collapse=\"false\" title=\"How the code works\"}\nThe block uses one function:\n\n```r\ngeary.mc(x, listw, nsim, zero.policy = attr(listw, \"zero.policy\"),\n         alternative = \"greater\")                                          # spdep\n```\n\n- `geary.mc()` runs the Monte Carlo test for Geary's C in the same way as `moran.mc()` in section\n  3.3.2: it reassigns the values of `x` to the counties at random `nsim` times and computes C for\n  each assignment. `set.seed(1234)` again makes the permutations the same on every render.\n- With `alternative = \"greater\"`, the pseudo p-value counts the permuted values of C that are at or\n  below the observed one, since a small C indicates clustering.\n- The result is stored in `bperm`, which replaces the Moran's I result of section 3.3.2. As before,\n  `bperm$res` holds the 999 simulated values followed by the observed C as its 1,000th element.\n:::\n\nChapter 9 asks what statistical conclusion the output supports:\n\n- **Rank:** the observed C, 0.69072, ranks first of the 1000 values, below all 999 permuted values.\n- **Pseudo p-value:** 0.001, the smallest attainable with 999 simulations.\n- **Conclusion:** the null hypothesis of spatial randomness is rejected, as in section 3.4.1.\n\n### The simulated distribution\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(bperm$res[1:999])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.004402\n```\n\n\n:::\n\n```{.r .cell-code}\nvar(bperm$res[1:999])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.007436493\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(bperm$res[1:999])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n 0.7142  0.9502  1.0052  1.0044  1.0595  1.2722 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(tibble(C = bperm$res[1:999]), aes(x = C)) +\n  geom_histogram(bins = 20, fill = \"grey70\", colour = \"black\") +\n  geom_vline(xintercept = 1, colour = \"red\") +\n  labs(x = \"Simulated Geary's C\", y = \"Count\",\n       title = \"Monte Carlo null distribution, 999 permutations\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05_files/figure-html/unnamed-chunk-21-1.png){width=864}\n:::\n:::\n\n\nChapter 9 asks what statistical observation the histogram supports:\n\n- **Centre:** the reference line at 1 is the expectation under spatial randomness, and the simulated\n  mean is approximately equal to it.\n- **Observed value:** 0.691 lies beyond the left tail, which for Geary's C is the side that\n  indicates clustering.\n\n## Spatial correlogram\n\nBoth statistics so far were computed on first-order neighbours only. A spatial correlogram computes\nthe statistic at successive lag orders, where lag 2 comprises the neighbours of the neighbours, and\nshows the range of lags over which spatial autocorrelation persists.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nMI_corr <- sp.correlogram(wm_q,\n                          hunan$GDPPC,\n                          order = 6,\n                          method = \"I\",\n                          style = \"W\")\nplot(MI_corr)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05_files/figure-html/unnamed-chunk-22-1.png){width=864}\n:::\n:::\n\n\n::: {.callout-note collapse=\"false\" title=\"How the code works\"}\nThe block uses one function:\n\n```r\nsp.correlogram(neighbours, var, order = 1, method = \"corr\", style = \"W\")   # spdep\n```\n\n- `sp.correlogram()` computes a spatial autocorrelation statistic at each lag from 1 to `order`. It\n  takes the neighbour list `wm_q` because it builds the higher-order neighbours itself, so it needs\n  no weights object. The lag-2 neighbours of a county are the neighbours of its neighbours,\n  excluding the county itself and its lag-1 neighbours, and so on up to `order = 6`.\n- `method` selects the statistic. The default, `\"corr\"`, is a correlation coefficient, so\n  `method = \"I\"` is needed for Moran's I. The Geary correlogram below uses `method = \"C\"`.\n- `style = \"W\"` row-standardises the weights at each lag. `plot()` draws the value at each lag with\n  a bar two standard deviations either side, and a horizontal line at the expected value under\n  spatial randomness.\n\nThe map shows the lags that `sp.correlogram()` builds, counted from one county, Changsha. Each\ncounty is coloured by the number of steps across shared boundaries that separate it from Changsha.\nAt lag 1 Changsha is compared with its immediate neighbours, and at lags 5 and 6 with counties in the\nwest and south of the province.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Hands-on_Ex05_files/figure-html/unnamed-chunk-23-1.png){width=864}\n:::\n:::\n\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(MI_corr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpatial correlogram for hunan$GDPPC \nmethod: Moran's I\n         estimate expectation   variance standard deviate Pr(I) two sided    \n1 (88)  0.3007500  -0.0114943  0.0043484           4.7351       2.189e-06 ***\n2 (88)  0.2060084  -0.0114943  0.0020962           4.7505       2.029e-06 ***\n3 (88)  0.0668273  -0.0114943  0.0014602           2.0496        0.040400 *  \n4 (88)  0.0299470  -0.0114943  0.0011717           1.2107        0.226015    \n5 (88) -0.1530471  -0.0114943  0.0012440          -4.0134       5.984e-05 ***\n6 (88) -0.1187070  -0.0114943  0.0016791          -2.6164        0.008886 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nChapter 9 asks what statistical observation the correlogram supports:\n\n- **Decline:** Moran's I falls from 0.30 at lag 1 to 0.03 at lag 4.\n- **Sign change:** it turns negative between lags 4 and 5, and is significantly negative at lags 5\n  and 6.\n- **Reason:** negative values at the higher lags reflect the geometry of the province as well as the\n  distribution of GDPPC. At lag 5 the neighbour sets of a county extend across the province.\n  Counties in the north east are then compared with counties in the west, and the values at the two\n  ends differ.\n\nLag 4 is the first order at which the null hypothesis of no spatial autocorrelation is not rejected.\nLag 3 is significant at p = 0.04, a marginal result that warrants adjustment, since six tests are\nreported in one table. A correction raises the evidence a test must reach, so that a lag counts as\nsignificant only on stronger evidence than 0.05. Holm's correction ranks the six p-values and\napplies the strictest threshold to the smallest, then a looser threshold to each in turn.\n`print.spcor()` defaults to `p.adj.method = \"none\"`, so the first table reported unadjusted\np-values.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(MI_corr, p.adj.method = \"holm\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpatial correlogram for hunan$GDPPC \nmethod: Moran's I\n         estimate expectation   variance standard deviate Pr(I) two sided    \n1 (88)  0.3007500  -0.0114943  0.0043484           4.7351       1.217e-05 ***\n2 (88)  0.2060084  -0.0114943  0.0020962           4.7505       1.217e-05 ***\n3 (88)  0.0668273  -0.0114943  0.0014602           2.0496       0.0808001 .  \n4 (88)  0.0299470  -0.0114943  0.0011717           1.2107       0.2260150    \n5 (88) -0.1530471  -0.0114943  0.0012440          -4.0134       0.0002394 ***\n6 (88) -0.1187070  -0.0114943  0.0016791          -2.6164       0.0266570 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nUnder Holm's correction lag 3 is no longer significant (p = 0.081), and the p-value at lag 6\nincreases to 0.027. At lags 1, 2 and 5 the p-values all increase and all remain below 0.001. Only\nlag 4 is unchanged, since it already had the largest p-value in the table. Section 5.3 addresses the\nsame multiple-comparisons problem on a much larger scale, for the 88 local statistics.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nGC_corr <- sp.correlogram(wm_q,\n                          hunan$GDPPC,\n                          order = 6,\n                          method = \"C\",\n                          style = \"W\")\nplot(GC_corr)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05_files/figure-html/unnamed-chunk-26-1.png){width=864}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(GC_corr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpatial correlogram for hunan$GDPPC \nmethod: Geary's C\n        estimate expectation  variance standard deviate Pr(I) two sided    \n1 (88) 0.6907223   1.0000000 0.0073364          -3.6108       0.0003052 ***\n2 (88) 0.7630197   1.0000000 0.0049126          -3.3811       0.0007220 ***\n3 (88) 0.9397299   1.0000000 0.0049005          -0.8610       0.3892612    \n4 (88) 1.0098462   1.0000000 0.0039631           0.1564       0.8757128    \n5 (88) 1.2008204   1.0000000 0.0035568           3.3673       0.0007592 ***\n6 (88) 1.0773386   1.0000000 0.0058042           1.0151       0.3100407    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nGeary's C increases from 0.69 towards 1 and then exceeds it. Its correlogram has the shape of the\nMoran correlogram with the vertical axis reversed. Their p-values, however, do not follow the same\npattern.\n\n| Lag | Moran p | Geary p |\n|---|---|---|\n| 1 | 2.2e-06 | 3.1e-04 |\n| 2 | 2.0e-06 | 7.2e-04 |\n| 3 | 0.040 | 0.389 |\n| 4 | 0.226 | 0.876 |\n| 5 | 6.0e-05 | 7.6e-04 |\n| 6 | 0.0089 | 0.310 |\n\nMoran's I and Geary's C agree at lags 1, 2, 4 and 5. At lags 3 and 6 Moran's I is significant and\nGeary's C is not. This difference follows from the structure of the two statistics. Moran's I is\nbased on deviations from the provincial mean, and a gradual trend across the province contributes to\nit. Geary's C is based on differences between neighbouring values, and a weak trend that leaves\nadjacent pairs similar contributes little to it. Section 5.6 finds the opposite for the local forms:\nlocal Geary's c identifies more significant counties than local Moran's I, 21 against 16.\n\n# Part 2: Local measures of spatial autocorrelation\n\nThis part follows r4gdsa [Chapter 10](https://r4gdsa.netlify.app/chap10.html). Each statistic in it\nis computed for every county, and the results are mapped. Chapter 10 repeats the data import and the\nGDPPC maps of chapter 9, which are in sections 2 and 3.1 of this page and are not repeated here.\n\n## Local indicators of spatial association\n\nA global statistic summarises the whole province in a single value. It shows neither where the\nclustering is concentrated nor which individual counties differ from their neighbours. A local\nindicator of spatial association (LISA) is computed for each county and answers both questions.\nAnselin (1995) defines a LISA as any statistic that satisfies two requirements:\n\n1. **Local clustering.** It \"gives an indication of the extent of significant spatial clustering of\n   similar values around that observation\".\n2. **Link to the global statistic.** \"The sum of LISAs for all observations is proportional to a\n   global indicator of spatial association\".\n\nLocal Moran's I satisfies both. Under the second requirement, its 88 local values sum to a quantity\nproportional to the global Moran's I of section 3.3, as slide 22 of the Lesson 5 lecture shows.\n\n### Weights the sfdep way\n\n`sfdep` stores the neighbour list and the weights as columns of the sf object, each holding a list.\nEach row holds a county's geometry, its attributes, its neighbours and its weights.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_q <- hunan |>\n  mutate(nb = st_contiguity(geometry),\n         wt = st_weights(nb, style = \"W\"),\n         .before = 1)\nsummary(wm_q$nb)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNeighbour list object:\nNumber of regions: 88 \nNumber of nonzero links: 448 \nPercentage nonzero weights: 5.785124 \nAverage number of links: 5.090909 \nLink number distribution:\n\n 1  2  3  4  5  6  7  8  9 11 \n 2  2 12 16 24 14 11  4  2  1 \n2 least connected regions:\n30 65 with 1 link\n1 most connected region:\n85 with 11 links\n```\n\n\n:::\n:::\n\n\n::: {.callout-note collapse=\"false\" title=\"How the code works\"}\nThe block uses three functions:\n\n```r\nmutate(.data, name = value, ..., .before = NULL)          # dplyr\nst_contiguity(geometry, queen = TRUE)                     # sfdep\nst_weights(nb, style = \"W\", allow_zero = NULL)            # sfdep\n```\n\n- `mutate()` adds columns to a data frame. Each `name = value` pair creates one column, here `nb`\n  and `wt`. A later pair can use a column created by an earlier one, so `wt` is computed from the\n  `nb` created on the line above.\n- `.before` sets where the new columns go, and takes a column position or a column name. `.before =\n  1` places them before the column now in position 1, so they become the first two columns. The\n  default, `NULL`, adds them after the existing columns. Placing them first makes them visible at\n  the start of each printed row.\n- `st_contiguity()` finds, for each polygon, the polygons that share a boundary with it, and returns\n  a neighbour list: for each county, a vector of the row numbers of its neighbours. With `queen =\n  TRUE`, the default, a single shared boundary point is enough. `queen = FALSE` requires a shared\n  edge. The function calls `poly2nb()` from section 3.2, so it returns the same list.\n- `st_weights()` gives each neighbour a weight. With `style = \"W\"`, the default, each of a county's\n  weights is 1 divided by its number of neighbours, so its weights sum to 1. The function calls\n  `nb2listw()` from section 3.2 and keeps only the weights. `allow_zero` concerns counties without\n  neighbours, and Hunan has none.\n\n`hunan` before the block, first three counties:\n\n<table class=\"table table-sm\">\n<tr><th>NAME_2</th><th>…</th><th>County</th><th>GDPPC</th><th>geometry</th></tr>\n<tr><td>Changde</td><td>…</td><td>Anxiang</td><td>23667</td><td>polygon</td></tr>\n<tr><td>Changde</td><td>…</td><td>Hanshou</td><td>20981</td><td>polygon</td></tr>\n<tr><td>Changde</td><td>…</td><td>Jinshi</td><td>34592</td><td>polygon</td></tr>\n<tr><td>…</td><td>…</td><td>…</td><td>…</td><td>…</td></tr>\n</table>\n\n`wm_q` after the block, with the two new columns shaded:\n\n<table class=\"table table-sm\">\n<tr><th style=\"background: rgba(255, 193, 7, 0.30)\">nb</th><th style=\"background: rgba(255, 193, 7, 0.30)\">wt</th><th>NAME_2</th><th>…</th><th>County</th><th>GDPPC</th><th>geometry</th></tr>\n<tr><td style=\"background: rgba(255, 193, 7, 0.30)\">2, 3, 4, 57, 85</td><td style=\"background: rgba(255, 193, 7, 0.30)\">0.2, 0.2, 0.2, 0.2, 0.2</td><td>Changde</td><td>…</td><td>Anxiang</td><td>23667</td><td>polygon</td></tr>\n<tr><td style=\"background: rgba(255, 193, 7, 0.30)\">1, 57, 58, 78, 85</td><td style=\"background: rgba(255, 193, 7, 0.30)\">0.2, 0.2, 0.2, 0.2, 0.2</td><td>Changde</td><td>…</td><td>Hanshou</td><td>20981</td><td>polygon</td></tr>\n<tr><td style=\"background: rgba(255, 193, 7, 0.30)\">1, 4, 5, 85</td><td style=\"background: rgba(255, 193, 7, 0.30)\">0.25, 0.25, 0.25, 0.25</td><td>Changde</td><td>…</td><td>Jinshi</td><td>34592</td><td>polygon</td></tr>\n<tr><td style=\"background: rgba(255, 193, 7, 0.30)\">…</td><td style=\"background: rgba(255, 193, 7, 0.30)\">…</td><td>…</td><td>…</td><td>…</td><td>…</td><td>…</td></tr>\n</table>\n\nEach cell of `nb` and `wt` holds a vector, one element per neighbour. Anxiang has five neighbours,\nso each receives a weight of 1/5 = 0.2, and Jinshi has four, each weighted 0.25.\n\nThe figure follows Anxiang through the two functions, as the figure in section 3.2 does for\n`poly2nb()` and `nb2listw()`.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Hands-on_Ex05_files/figure-html/unnamed-chunk-29-1.png){width=864}\n:::\n:::\n\n:::\n\nThe neighbour summary matches `poly2nb()` exactly: 448 links across 88 counties, average 5.09.\n\n### Local Moran's I\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nlisa <- wm_q |>\n  mutate(local_moran = local_moran(GDPPC, nb, wt, nsim = 999),\n         .before = 1) |>\n  unnest(local_moran)\nglimpse(lisa)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 88\nColumns: 21\n$ ii           <dbl> -1.468468e-03, 2.587817e-02, -1.198765e-02, 1.022468e-03,…\n$ eii          <dbl> 5.194905e-05, 3.386676e-03, -2.050725e-02, 1.677027e-06, …\n$ var_ii       <dbl> 5.170509e-04, 1.050470e-02, 1.160620e-01, 5.577212e-06, 1…\n$ z_ii         <dbl> -0.06686456, 0.21944543, 0.02500774, 0.43224316, 0.425129…\n$ p_ii         <dbl> 9.466895e-01, 8.263031e-01, 9.800488e-01, 6.655647e-01, 6…\n$ p_ii_sim     <dbl> 0.798, 0.970, 0.774, 0.580, 0.606, 0.748, 0.048, 0.112, 0…\n$ p_folded_sim <dbl> 0.399, 0.485, 0.387, 0.290, 0.303, 0.374, 0.024, 0.056, 0…\n$ skewness     <dbl> -1.0728711, -0.9674141, 1.1031694, 1.0937498, 0.8918350, …\n$ kurtosis     <dbl> 1.2305223, 1.0166190, 1.1714030, 1.2281892, 0.6858284, 0.…\n$ mean         <fct> Low-High, Low-Low, High-Low, High-High, High-High, High-L…\n$ median       <fct> High-High, High-High, High-High, High-High, High-High, Hi…\n$ pysal        <fct> Low-High, Low-Low, High-Low, High-High, High-High, High-L…\n$ nb           <nb> <2, 3, 4, 57, 85>, <1, 57, 58, 78, 85>, <1, 4, 5, 85>, <1,…\n$ wt           <list> <0.2, 0.2, 0.2, 0.2, 0.2>, <0.2, 0.2, 0.2, 0.2, 0.2>, <0…\n$ NAME_2       <chr> \"Changde\", \"Changde\", \"Changde\", \"Changde\", \"Changde\", \"C…\n$ ID_3         <int> 21098, 21100, 21101, 21102, 21103, 21104, 21109, 21110, 2…\n$ NAME_3       <chr> \"Anxiang\", \"Hanshou\", \"Jinshi\", \"Li\", \"Linli\", \"Shimen\", …\n$ ENGTYPE_3    <chr> \"County\", \"County\", \"County City\", \"County\", \"County\", \"C…\n$ County       <chr> \"Anxiang\", \"Hanshou\", \"Jinshi\", \"Li\", \"Linli\", \"Shimen\", …\n$ GDPPC        <dbl> 23667, 20981, 34592, 24473, 25554, 27137, 63118, 62202, 7…\n$ geometry     <POLYGON [m]> POLYGON ((602726.4 3292136,..., POLYGON ((619553.…\n```\n\n\n:::\n:::\n\n\n::: {.callout-note collapse=\"false\" title=\"How the code works\"}\nThe block uses three functions:\n\n```r\nlocal_moran(x, nb, wt, alternative = \"two.sided\", nsim = 499)   # sfdep\nunnest(data, cols)                                              # tidyr\nglimpse(x)                                                      # dplyr\n```\n\n- `local_moran()` computes local Moran's I for each county and tests it by conditional permutation.\n  It returns a data frame with one row per county and one column per result. `nsim` defaults to\n  499, and the call sets 999 to match section 3.3.2. With `alternative = \"two.sided\"`, the default,\n  both unusually high and unusually low values of Ii count as significant.\n- Inside `mutate()` (section 4.1.1), that data frame is stored as a single column named\n  `local_moran`, and `.before = 1` places it first.\n- `unnest()` replaces the column named in `cols` with the columns it contains, so the 12 results\n  become 12 columns.\n- `glimpse()` prints the name, type and first values of every column, one column per line.\n\nBefore `unnest()`, `local_moran` is a single column that holds a 12-column data frame, one row per\ncounty:\n\n<table class=\"table table-sm\">\n<tr><th style=\"background: rgba(255, 193, 7, 0.30)\">local_moran</th><th>nb</th><th>wt</th><th>…</th><th>County</th><th>geometry</th></tr>\n<tr><td style=\"background: rgba(255, 193, 7, 0.30)\">ii, eii, …, pysal: 12 values</td><td>2, 3, 4, 57, 85</td><td>0.2, …</td><td>…</td><td>Anxiang</td><td>polygon</td></tr>\n<tr><td style=\"background: rgba(255, 193, 7, 0.30)\">ii, eii, …, pysal: 12 values</td><td>1, 57, 58, 78, 85</td><td>0.2, …</td><td>…</td><td>Hanshou</td><td>polygon</td></tr>\n<tr><td style=\"background: rgba(255, 193, 7, 0.30)\">…</td><td>…</td><td>…</td><td>…</td><td>…</td><td>…</td></tr>\n</table>\n\nAfter `unnest()`, its 12 columns, shaded, replace it:\n\n<table class=\"table table-sm\">\n<tr><th style=\"background: rgba(255, 193, 7, 0.30)\">ii</th><th style=\"background: rgba(255, 193, 7, 0.30)\">eii</th><th style=\"background: rgba(255, 193, 7, 0.30)\">…</th><th style=\"background: rgba(255, 193, 7, 0.30)\">p_ii_sim</th><th style=\"background: rgba(255, 193, 7, 0.30)\">…</th><th style=\"background: rgba(255, 193, 7, 0.30)\">mean</th><th style=\"background: rgba(255, 193, 7, 0.30)\">median</th><th style=\"background: rgba(255, 193, 7, 0.30)\">pysal</th><th>nb</th><th>…</th><th>geometry</th></tr>\n<tr><td style=\"background: rgba(255, 193, 7, 0.30)\">−0.0015</td><td style=\"background: rgba(255, 193, 7, 0.30)\">…</td><td style=\"background: rgba(255, 193, 7, 0.30)\">…</td><td style=\"background: rgba(255, 193, 7, 0.30)\">0.798</td><td style=\"background: rgba(255, 193, 7, 0.30)\">…</td><td style=\"background: rgba(255, 193, 7, 0.30)\">Low-High</td><td style=\"background: rgba(255, 193, 7, 0.30)\">…</td><td style=\"background: rgba(255, 193, 7, 0.30)\">…</td><td>2, 3, 4, 57, 85</td><td>…</td><td>polygon</td></tr>\n<tr><td style=\"background: rgba(255, 193, 7, 0.30)\">0.0259</td><td style=\"background: rgba(255, 193, 7, 0.30)\">…</td><td style=\"background: rgba(255, 193, 7, 0.30)\">…</td><td style=\"background: rgba(255, 193, 7, 0.30)\">0.970</td><td style=\"background: rgba(255, 193, 7, 0.30)\">…</td><td style=\"background: rgba(255, 193, 7, 0.30)\">Low-Low</td><td style=\"background: rgba(255, 193, 7, 0.30)\">…</td><td style=\"background: rgba(255, 193, 7, 0.30)\">…</td><td>1, 57, 58, 78, 85</td><td>…</td><td>polygon</td></tr>\n<tr><td style=\"background: rgba(255, 193, 7, 0.30)\">…</td><td style=\"background: rgba(255, 193, 7, 0.30)\">…</td><td style=\"background: rgba(255, 193, 7, 0.30)\">…</td><td style=\"background: rgba(255, 193, 7, 0.30)\">…</td><td style=\"background: rgba(255, 193, 7, 0.30)\">…</td><td style=\"background: rgba(255, 193, 7, 0.30)\">…</td><td style=\"background: rgba(255, 193, 7, 0.30)\">…</td><td style=\"background: rgba(255, 193, 7, 0.30)\">…</td><td>…</td><td>…</td><td>…</td></tr>\n</table>\n\nThe values shown are those of the first two counties, Anxiang and Hanshou.\n:::\n\nSection 5.2 compares two of these p-value columns, `p_ii` and `p_ii_sim`. Each column is described\nbelow.\n\n| Column | What it holds |\n|---|---|\n| `ii` | the local Moran's I value for that county |\n| `eii`, `var_ii`, `z_ii` | the permutation sample mean, variance and standardised deviate. With `nsim` supplied these are computed from the simulations, not from the analytical null |\n| `p_ii` | a p-value from `pnorm()` on `z_ii`, so a normal approximation to the permutation distribution |\n| `p_ii_sim` | a rank-based p-value from the same permutations, two-sided, on a [0, 1] scale |\n| `p_folded_sim` | the same ranking folded onto a [0, 1] range of 0.5, so close to half of `p_ii_sim` |\n| `mean`, `median`, `pysal` | three labellings of the county into one of the four scatterplot quadrants |\n\nUnder the analytical randomisation null hypothesis with row-standardised weights, every county has\nthe same expectation, −1/(n−1) = −0.0115. The printed values of `eii` differ between counties, so\nthey are sample means over the permutations.\n\nChapter 10 uses `p_ii`. This page uses `p_ii_sim`, for the reasons given in section 5.2.\n\n### The two maps\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(lisa) +\n  tm_polygons(fill = \"ii\",\n              fill.scale = tm_scale_intervals(style = \"pretty\", n = 5,\n                                              values = \"brewer.rd_bu\"),\n              fill.legend = tm_legend(title = \"Local Moran's I\",\n                                      position = tm_pos_out())) +\n  tm_borders(col_alpha = 0.5) +\n  tm_title(\"Local Moran's I of GDPPC, Queen contiguity\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05_files/figure-html/unnamed-chunk-31-1.png){width=864}\n:::\n:::\n\n\nA large positive value indicates a county whose neighbours have similar values. A negative value\nindicates a county whose value differs from those of its neighbours. On its own, Ii does not\nindicate whether the association is significant. The p-value map below provides that information.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(lisa) +\n  tm_polygons(fill = \"p_ii_sim\",\n              fill.scale = tm_scale_intervals(\n                breaks = c(0, 0.01, 0.05, 0.1, 1),\n                values = \"-brewer.reds\"),\n              fill.legend = tm_legend(title = \"simulated p-value\",\n                                      position = tm_pos_out())) +\n  tm_borders(col_alpha = 0.5) +\n  tm_title(\"Simulated p-values of local Moran's I, 999 permutations\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05_files/figure-html/unnamed-chunk-32-1.png){width=864}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmin(lisa$p_ii_sim)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.002\n```\n\n\n:::\n:::\n\n\nThe legend breaks differ from those of the chapter. `p_ii_sim` is a rank-based p-value, and its\nsmallest attainable value is `2 / (nsim + 1)`, which is 0.002 at `nsim = 999` and 0.02 at the\nchapter's `nsim = 99`. The breaks are set at values attainable with `nsim = 999` (section 5.2).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nii.map <- tm_shape(lisa) +\n  tm_polygons(fill = \"ii\",\n              fill.scale = tm_scale_intervals(style = \"pretty\", n = 5,\n                                              values = \"brewer.rd_bu\"),\n              fill.legend = tm_legend(title = \"Local Moran's I\",\n                                      position = tm_pos_out(\"right\", \"center\"))) +\n  tm_borders(col_alpha = 0.5) +\n  tm_title(\"Local Moran's I\")\n\np_ii.map <- tm_shape(lisa) +\n  tm_polygons(fill = \"p_ii_sim\",\n              fill.scale = tm_scale_intervals(\n                breaks = c(0, 0.01, 0.05, 0.1, 1),\n                values = \"-brewer.reds\"),\n              fill.legend = tm_legend(title = \"p-value\",\n                                      position = tm_pos_out(\"right\", \"center\"))) +\n  tm_borders(col_alpha = 0.5) +\n  tm_title(\"Simulated p-value\")\n\ntmap_arrange(ii.map, p_ii.map, asp = 1, ncol = 2)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05_files/figure-html/unnamed-chunk-34-1.png){width=864}\n:::\n:::\n\n\nNeither map is sufficient on its own. Several counties with a large value of `ii` are not\nsignificant, and the set of significant counties is smaller than the set of counties with prominent\nvalues on the first map.\n\n### Moran scatterplot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlisa <- lisa |>\n  mutate(lag_GDPPC = st_lag(GDPPC, nb, wt), .before = 1)\n```\n:::\n\n\n::: {.callout-note collapse=\"false\" title=\"How the code works\"}\nThe block uses one function:\n\n```r\nst_lag(x, nb, wt)                                         # sfdep\n```\n\n- `st_lag()` computes the spatial lag of `x`: for each county, the sum of its neighbours' values,\n  each multiplied by its weight. With row-standardised weights this is the average GDPPC of the\n  neighbours, which the scatterplot below plots against the county's own GDPPC.\n\nThe figure works through the lag for Anxiang. Each of its five neighbours has a weight of 0.2, so\nits lag is the average GDPPC of the five.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Hands-on_Ex05_files/figure-html/unnamed-chunk-36-1.png){width=864}\n:::\n:::\n\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = lisa, aes(x = GDPPC, y = lag_GDPPC)) +\n  geom_point() +\n  geom_smooth(method = \"lm\", se = FALSE, colour = \"red\") +\n  labs(x = \"GDPPC\",\n       y = \"Spatial lag of GDPPC\",\n       title = \"Moran scatterplot\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05_files/figure-html/unnamed-chunk-37-1.png){width=864}\n:::\n:::\n\n\n::: {.callout-note collapse=\"false\" title=\"How the code works\"}\nThe block uses two new functions:\n\n```r\ngeom_point(size)                                          # ggplot2\ngeom_smooth(method = NULL, se = TRUE, colour)             # ggplot2\n```\n\n- `aes(x = GDPPC, y = lag_GDPPC)` places each county's GDPPC on the horizontal axis and its spatial\n  lag on the vertical axis.\n- `geom_point()` draws one point per county.\n- `geom_smooth()` adds a fitted line. `method = \"lm\"` fits a straight line by least squares, and\n  `se = FALSE` leaves out the grey confidence band that is drawn by default.\n:::\n\nThis is the scatterplot from the end of Hands-on Exercise 4, with a fitted regression line added.\nWith row-standardised weights, Moran's I is the least-squares slope of the spatial lag on the\nvariable in deviations from its mean. Anselin (1996) writes I = y'Wy / y'y and treats the plot as\nthe regression of Wy on y. The slope of the line above is therefore Moran's I.\n\nAnselin (1996) standardises the variable and then takes the spatial lag of the standardised values,\nso the vertical axis is Wz. Chapter 10 standardises the lag separately, with `scale(lag_GDPPC)`.\nThis page follows Anselin (1996):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlisa <- lisa |>\n  mutate(z_GDPPC = as.numeric(scale(GDPPC)),\n         z_lag_GDPPC = st_lag(z_GDPPC, nb, wt),\n         .before = 1)\n```\n:::\n\n\n::: {.callout-note collapse=\"false\" title=\"How the code works\"}\nThe block uses two functions:\n\n```r\nscale(x, center = TRUE, scale = TRUE)                     # base R\nas.numeric(x)                                             # base R\n```\n\n- `scale()` standardises a variable: it subtracts the mean and divides by the standard deviation, so\n  the result has mean 0 and standard deviation 1.\n- `scale()` returns an 88 × 1 matrix, and `as.numeric()` turns it back into a plain vector, so that\n  it can be stored as an ordinary column.\n- `st_lag()` then takes the spatial lag of the standardised values, which is Anselin's (1996)\n  construction.\n:::\n\nThe two constructions, the lag of the standardised variable and the separately standardised lag,\ngive different slopes on the same 88 counties:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(construction = c(\"Moran's I (section 3.3.1)\",\n                        \"lag of GDPPC on GDPPC\",\n                        \"Anselin (1996): lag of z on z\",\n                        \"chapter 10: scale(lag) on z\"),\n       slope = c(moran.test(hunan$GDPPC, rswm_q)$estimate[1],\n                 coef(lm(lag_GDPPC ~ GDPPC, data = lisa))[2],\n                 coef(lm(z_lag_GDPPC ~ z_GDPPC, data = lisa))[2],\n                 coef(lm(as.numeric(scale(lag_GDPPC)) ~ z_GDPPC, data = lisa))[2])) |>\n  kable(digits = 4)\n```\n\n::: {.cell-output-display}\n\n\n|construction                  |  slope|\n|:-----------------------------|------:|\n|Moran's I (section 3.3.1)     | 0.3007|\n|lag of GDPPC on GDPPC         | 0.3007|\n|Anselin (1996): lag of z on z | 0.3007|\n|chapter 10: scale(lag) on z   | 0.4846|\n\n\n:::\n:::\n\n\n::: {.callout-note collapse=\"false\" title=\"How the code works\"}\nThe block uses three new functions:\n\n```r\nlm(formula, data)                                         # stats\ncoef(object)                                              # stats\nkable(x, digits)                                          # knitr\n```\n\n- `lm()` fits a linear regression. The formula `lag_GDPPC ~ GDPPC` reads \"lag_GDPPC explained by\n  GDPPC\": the variable before `~` is on the vertical axis of the scatterplot and the one after it on\n  the horizontal axis.\n- `coef()` returns the fitted coefficients, the intercept first and the slope second, so `[2]`\n  takes the slope.\n- `kable()` prints a data frame as a formatted table, and `digits = 4` rounds the numbers to four\n  decimal places.\n:::\n\nThe chapter's figure is titled a Moran scatterplot, but its regression line does not have Moran's I\nas its slope. Under the chapter's construction the slope is 0.485, the Pearson correlation between\nGDPPC and its spatial lag. The lag is an average of neighbouring values and varies less than GDPPC\n(standard deviations of about 9,300 and 15,000 yuan), so standardising it by its own standard\ndeviation stretches it. Under Anselin's (1996) construction the slope is 0.301, equal to Moran's I.\nThe assignment of counties to quadrants is the same under both constructions for this data.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = lisa, aes(x = z_GDPPC, y = z_lag_GDPPC, colour = mean)) +\n  geom_point(size = 2) +\n  geom_smooth(method = \"lm\", se = FALSE, colour = \"black\") +\n  geom_hline(yintercept = 0, lty = 2) +\n  geom_vline(xintercept = 0, lty = 2) +\n  scale_colour_manual(values = c(\"High-High\" = \"red\",\n                                 \"Low-Low\" = \"blue\",\n                                 \"Low-High\" = \"lightblue\",\n                                 \"High-Low\" = \"pink\")) +\n  labs(x = \"Standardised GDPPC\",\n       y = \"Standardised spatial lag of GDPPC\",\n       colour = \"Quadrant\",\n       title = \"Standardised Moran scatterplot with LISA quadrants\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05_files/figure-html/unnamed-chunk-40-1.png){width=864}\n:::\n:::\n\n\n::: {.callout-note collapse=\"false\" title=\"How the code works\"}\nThe block uses two new functions:\n\n```r\ngeom_hline(yintercept, lty)                               # ggplot2\nscale_colour_manual(values)                               # ggplot2\n```\n\n- `colour = mean` inside `aes()` colours each point by its quadrant label in the `mean` column.\n- `geom_hline()` and `geom_vline()` (section 3.3.3) draw the dashed lines at zero, and `lty = 2`\n  sets a dashed line.\n- `scale_colour_manual()` sets the colour of each quadrant by name, matching the colours of the\n  LISA cluster map in section 4.1.5.\n:::\n\nThe dashed lines mark zero, the mean of a standardised variable.\n\nIn the LISA cluster map, counties are classified by the four quadrants:\n\n| Quadrant | Position | Reading |\n|---|---|---|\n| High-High | top right | a high value surrounded by high values, the core of a cluster |\n| Low-Low | bottom left | a low value surrounded by low values |\n| High-Low | bottom right | a high value surrounded by low values, a spatial outlier |\n| Low-High | top left | a low value surrounded by high values, a spatial outlier |\n\nCounties in the High-High and Low-Low quadrants have a positive local I, and counties in the\nHigh-Low and Low-High quadrants have a negative local I. The sign of Ii alone does not identify the\nquadrant: a positive value may indicate a High-High or a Low-Low cluster, and a negative value a\nHigh-Low or a Low-High outlier (Anselin 1995).\n\n### LISA cluster map\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsignif <- 0.05\n\nlisa <- lisa |>\n  mutate(LISA_cluster = ifelse(p_ii_sim < signif, as.character(mean), \"Insignificant\"),\n         LISA_cluster = factor(LISA_cluster,\n                               levels = c(\"Insignificant\", \"Low-Low\", \"Low-High\",\n                                          \"High-Low\", \"High-High\")))\ntable(lisa$LISA_cluster)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nInsignificant       Low-Low      Low-High      High-Low     High-High \n           72             9             1             0             6 \n```\n\n\n:::\n:::\n\n\n::: {.callout-note collapse=\"false\" title=\"How the code works\"}\nThe block uses three functions:\n\n```r\nifelse(test, yes, no)                                     # base R\nas.character(x)                                           # base R\nfactor(x, levels)                                         # base R\n```\n\n- `signif <- 0.05` stores the significance threshold once. The hot and cold spot classification in\n  section 4.2.3 uses it again.\n- `ifelse()` works element by element: for each county it returns `yes` where `test` is true and\n  `no` where it is false. A significant county takes its quadrant label from the `mean` column, and\n  the others are labelled \"Insignificant\".\n- `as.character()` converts the factor `mean` to its text labels. Without it, `ifelse()` would\n  return the factor's integer codes.\n- The second line of `mutate()` (section 4.1.1) overwrites the column created on the first.\n  `factor()` converts the labels to a factor, and `levels` fixes the order of its five classes. The\n  paragraph after the map gives the reason. `table()` counts the counties in each class.\n\nA factor stores a set of labels as numbers, together with an ordered list of the labels, called its\nlevels. The example follows four counties through the second line of `mutate()`:\n\n<div style=\"display: flex; align-items: center; gap: 1em; flex-wrap: wrap;\">\n<div>After <code>ifelse()</code>: text<br><table class=\"table table-sm\" style=\"width: auto; margin: 0;\"><tr><th>County</th><th>LISA_cluster</th></tr><tr><td>Anxiang</td><td>Insignificant</td></tr><tr><td>Yuanling</td><td>Low-Low</td></tr><tr><td>Pingjiang</td><td>Low-High</td></tr><tr><td>Liuyang</td><td>High-High</td></tr></table></div>\n<div style=\"font-size: 1.8em;\">&rarr;</div>\n<div>After <code>factor(levels = ...)</code><br><table class=\"table table-sm\" style=\"width: auto; margin: 0;\"><tr><th>County</th><th style=\"background: rgba(255, 193, 7, 0.30)\">stored as</th><th>shown as</th></tr><tr><td>Anxiang</td><td style=\"background: rgba(255, 193, 7, 0.30)\">1</td><td>Insignificant</td></tr><tr><td>Yuanling</td><td style=\"background: rgba(255, 193, 7, 0.30)\">2</td><td>Low-Low</td></tr><tr><td>Pingjiang</td><td style=\"background: rgba(255, 193, 7, 0.30)\">3</td><td>Low-High</td></tr><tr><td>Liuyang</td><td style=\"background: rgba(255, 193, 7, 0.30)\">5</td><td>High-High</td></tr></table></div>\n<div>Its levels, in order<br><table class=\"table table-sm\" style=\"width: auto; margin: 0;\"><tr><th style=\"background: rgba(255, 193, 7, 0.30)\">level</th><th>label</th></tr><tr><td style=\"background: rgba(255, 193, 7, 0.30)\">1</td><td>Insignificant</td></tr><tr><td style=\"background: rgba(255, 193, 7, 0.30)\">2</td><td>Low-Low</td></tr><tr><td style=\"background: rgba(255, 193, 7, 0.30)\">3</td><td>Low-High</td></tr><tr><td style=\"background: rgba(255, 193, 7, 0.30)\">4</td><td>High-Low</td></tr><tr><td style=\"background: rgba(255, 193, 7, 0.30)\">5</td><td>High-High</td></tr></table></div>\n</div>\n\nEach county is stored as the number of its level, and the label is shown in its place. The order of\nthe levels decides the order of the classes in `table()`, in the legend and in the colours of the\nmap. High-Low is level 4 although no county has it, so it keeps its place in that order.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(lisa) +\n  tm_polygons(fill = \"LISA_cluster\",\n              fill.scale = tm_scale_categorical(\n                values = c(\"grey80\", \"blue\", \"lightblue\", \"pink\", \"red\")),\n              fill.legend = tm_legend(title = \"LISA cluster\",\n                                      position = tm_pos_out(\"right\", \"center\"))) +\n  tm_borders() +\n  tm_title(\"Local Moran's I clusters of GDPPC, p < 0.05\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05_files/figure-html/unnamed-chunk-42-1.png){width=864}\n:::\n:::\n\n\n::: {.callout-note collapse=\"false\" title=\"How the code works\"}\nThe block uses one new function:\n\n```r\ntm_scale_categorical(values = NA, levels.drop = FALSE)    # tmap\n```\n\n- `tm_scale_categorical()` gives each category of a factor its own colour, in the order of the\n  factor's levels. The vector of colours has to be written in the same order as the `levels`\n  argument of section 4.1.5's `factor()` call, and the levels are set explicitly for that reason.\n- `levels.drop = FALSE`, the default, keeps a level in the legend even when no county has it, so the\n  colours stay fixed.\n\nThe colours are matched to the levels by position. With the levels set in section 4.1.5, each\nclass gets its intended colour. Without them, R sorts the classes alphabetically and drops High-Low,\nwhich no county has, so the same five colours are matched to four levels in a different order:\n\n<div style=\"display: flex; align-items: flex-start; gap: 1.5em; flex-wrap: wrap;\">\n<div>Levels set in section 4.1.5<br><table class=\"table table-sm\" style=\"width: auto; margin: 0;\"><tr><th>Level, in order</th><th>Counties</th><th>Colour given</th></tr><tr><td>Insignificant</td><td>72</td><td><span style=\"display:inline-block;width:1em;height:1em;vertical-align:middle;border:1px solid #999;background:#CCCCCC\"></span> grey80</td></tr><tr><td>Low-Low</td><td>9</td><td><span style=\"display:inline-block;width:1em;height:1em;vertical-align:middle;border:1px solid #999;background:#0000FF\"></span> blue</td></tr><tr><td>Low-High</td><td>1</td><td><span style=\"display:inline-block;width:1em;height:1em;vertical-align:middle;border:1px solid #999;background:#ADD8E6\"></span> lightblue</td></tr><tr><td>High-Low</td><td>0</td><td><span style=\"display:inline-block;width:1em;height:1em;vertical-align:middle;border:1px solid #999;background:#FFC0CB\"></span> pink</td></tr><tr><td>High-High</td><td>6</td><td><span style=\"display:inline-block;width:1em;height:1em;vertical-align:middle;border:1px solid #999;background:#FF0000\"></span> red</td></tr></table></div>\n<div>Levels left to R, alphabetical<br><table class=\"table table-sm\" style=\"width: auto; margin: 0;\"><tr><th>Level, in order</th><th>Counties</th><th>Colour given</th></tr><tr><td>High-High</td><td>6</td><td><span style=\"display:inline-block;width:1em;height:1em;vertical-align:middle;border:1px solid #999;background:#CCCCCC\"></span> grey80</td></tr><tr><td>Insignificant</td><td>72</td><td><span style=\"display:inline-block;width:1em;height:1em;vertical-align:middle;border:1px solid #999;background:#0000FF\"></span> blue</td></tr><tr><td>Low-High</td><td>1</td><td><span style=\"display:inline-block;width:1em;height:1em;vertical-align:middle;border:1px solid #999;background:#ADD8E6\"></span> lightblue</td></tr><tr><td>Low-Low</td><td>9</td><td><span style=\"display:inline-block;width:1em;height:1em;vertical-align:middle;border:1px solid #999;background:#FFC0CB\"></span> pink</td></tr></table></div>\n</div>\n\nIn the second case the six High-High counties would be drawn grey and the 72 insignificant counties\nblue.\n:::\n\nChapter 10 asks what statistical observations the LISA map supports:\n\n- **Significant counties:** 16 of the 88, of which six are High-High, nine Low-Low and one\n  Low-High. The other 72 are not significant at p < 0.05.\n- **High-High cluster:** around Changsha in the north east.\n- **Low-Low cluster:** in the west.\n- **Spatial outlier:** Pingjiang, the single Low-High county, which lies between the two groups and\n  has low GDPPC with high-GDPPC neighbours.\n\nThese are uncorrected results. Section 5.3 shows how many remain significant after a correction\nfor 88 tests.\n\n## Hot and cold spots\n\nLocal Moran's I and Getis-Ord Gi\\* measure different concepts of spatial association.\n\n| Statistic | What it measures | Significant positive value | Significant negative value |\n|---|---|---|---|\n| local Moran's I | similarity between a county and its neighbours | the county is similar to its neighbours, High-High or Low-Low | a spatial outlier, High-Low or Low-High |\n| Gi\\* | whether the sum of values in the neighbourhood is larger or smaller than expected under spatial randomness | clustering of high values, a hot spot | clustering of low values, a cold spot |\n\nGi\\* has no outlier category.\n\nGetis and Ord (1992) state that the variable \"has a natural origin and is positive\", because G is\ncomputed from the values themselves and not from their deviations from the mean, so a zero that does\nnot represent absence of the quantity changes the statistic (section 5.4.1). GDPPC is positive in\nevery county.\n\n### Distance weights\n\nGetis and Ord (1992) define Gi\\* on a distance band: it measures the concentration of values within\na given distance of each county. Slide 36 of the Lesson 5 lecture requires the band to be wide\nenough that every county has at least one neighbour.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nct <- critical_threshold(st_geometry(hunan))\nct\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 62954.89\n```\n\n\n:::\n:::\n\n\n::: {.callout-note collapse=\"false\" title=\"How the code works\"}\nThe block uses two functions:\n\n```r\nst_geometry(x)                                            # sf\ncritical_threshold(geometry, k = 1)                       # sfdep\n```\n\n- `st_geometry()` extracts the geometry column of an sf object, without the attributes.\n- `critical_threshold()` finds each county's distance to its nearest neighbour (`k = 1`) and\n  returns the largest of these distances. A distance band of that width gives every county at least\n  one neighbour. The distance is in metres, because `hunan` is in EPSG:32649.\n\n`st_geometry(hunan)` keeps only the shaded column, the polygons:\n\n<div style=\"display: flex; align-items: center; gap: 1em; flex-wrap: wrap;\">\n<div><code>hunan</code>, an sf data frame<br><table class=\"table table-sm\" style=\"width: auto; margin: 0;\"><tr><th>NAME_2</th><th>ID_3</th><th>NAME_3</th><th>ENGTYPE_3</th><th>County</th><th>GDPPC</th><th style=\"background: rgba(255, 193, 7, 0.30)\">geometry</th></tr><tr><td>Changde</td><td>21098</td><td>Anxiang</td><td>County</td><td>Anxiang</td><td>23667</td><td style=\"background: rgba(255, 193, 7, 0.30)\">POLYGON ((602726.4 3292136, …))</td></tr><tr><td>Changde</td><td>21100</td><td>Hanshou</td><td>County</td><td>Hanshou</td><td>20981</td><td style=\"background: rgba(255, 193, 7, 0.30)\">POLYGON ((619553.5 3221554, …))</td></tr><tr><td>…</td><td>…</td><td>…</td><td>…</td><td>…</td><td>…</td><td style=\"background: rgba(255, 193, 7, 0.30)\">…</td></tr></table></div>\n<div style=\"font-size: 1.8em;\">&rarr;</div>\n<div><code>st_geometry(hunan)</code>, an <code>sfc_POLYGON</code><br><table class=\"table table-sm\" style=\"width: auto; margin: 0;\"><tr><th style=\"background: rgba(255, 193, 7, 0.30)\">geometry</th></tr><tr><td style=\"background: rgba(255, 193, 7, 0.30)\">POLYGON ((602726.4 3292136, …))</td></tr><tr><td style=\"background: rgba(255, 193, 7, 0.30)\">POLYGON ((619553.5 3221554, …))</td></tr><tr><td style=\"background: rgba(255, 193, 7, 0.30)\">…</td></tr></table></div>\n</div>\n\nThe result has no attributes, so `critical_threshold()` receives only the 88 shapes it measures.\n\nThe figure draws, for every county, a line to its nearest neighbour. The longest of these lines,\nin red, is the value `critical_threshold()` returns.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Hands-on_Ex05_files/figure-html/unnamed-chunk-44-1.png){width=864}\n:::\n:::\n\n:::\n\n`critical_threshold()` returns the smallest distance at which every county has at least one\nneighbour, which is the rule on slide 36. Under EPSG:32649 the threshold is 62,955 m. Chapter 10\nreports 60,800 m, the value of the same function under EPSG:32650. Section 5.1 examines the\ndifference.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan_fdw <- hunan |>\n  mutate(nb = include_self(st_dist_band(geometry, upper = ct)),\n         wt = st_weights(nb, style = \"W\"),\n         .before = 1)\n\nsummary(lengths(hunan_fdw$nb))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  2.000   4.000   5.000   5.023   6.000   8.000 \n```\n\n\n:::\n:::\n\n\n::: {.callout-note collapse=\"false\" title=\"How the code works\"}\nThe block uses three functions:\n\n```r\nst_dist_band(geometry, lower = 0,\n             upper = critical_threshold(geometry))        # sfdep\ninclude_self(nb)                                          # sfdep\nlengths(x)                                                # base R\n```\n\n- `st_dist_band()` makes a county the neighbour of every county whose distance from it lies between\n  `lower` and `upper`, here up to `ct` metres, since `hunan` is in EPSG:32649. For polygons, `sfdep`\n  measures the distance between points on the surface of each county, from `st_point_on_surface()`,\n  and `critical_threshold()` uses the same points.\n- `upper` defaults to `critical_threshold(geometry)`, so passing `ct` gives the same band and shows\n  the value used.\n- `include_self()` adds each county to its own neighbour list, which turns Gi into Gi\\*.\n  `st_weights()` then row-standardises the weights as in section 4.1.1.\n- `lengths()` returns the length of each element of a list, here the number of neighbours of each\n  county, and `summary()` gives their minimum, quartiles, mean and maximum.\n\nThe figure applies the band to Taoyuan, the county that sets `ct`. The circle has radius `ct`\naround Taoyuan's point, and a county is a neighbour when its point lies inside the circle.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Hands-on_Ex05_files/figure-html/unnamed-chunk-46-1.png){width=864}\n:::\n:::\n\n\nTaoyuan's only neighbour is Hanshou, whose point lies exactly on the circle, and `include_self()`\nadds Taoyuan itself. This is the sparsest neighbourhood in the province.\n:::\n\n`include_self()` distinguishes Gi\\* from Gi. Gi excludes the county from its own neighbourhood, and\nGi\\* includes it. Slide 27 gives both forms, and the chapter uses Gi\\* throughout.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan_adw <- hunan |>\n  mutate(nb = include_self(st_knn(geometry, k = 6)),\n         wt = st_weights(nb, style = \"W\"),\n         .before = 1)\n\nsummary(lengths(hunan_adw$nb))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n      7       7       7       7       7       7 \n```\n\n\n:::\n:::\n\n\n::: {.callout-note collapse=\"false\" title=\"How the code works\"}\nThe block uses one new function:\n\n```r\nst_knn(geometry, k = 1, symmetric = FALSE)                # sfdep\n```\n\n- `st_knn()` makes each county's `k` nearest counties its neighbours, measured between points on\n  the surface of each county, as for `st_dist_band()` above. `k = 6` gives each county six.\n- With `symmetric = FALSE`, the default, the list need not be symmetric: county A can be among\n  B's six nearest without B being among A's.\n- `include_self()` and `st_weights()` then work as in the fixed-band block above.\n:::\n\nAn adaptive scheme fixes the number of neighbours instead of the distance. Neighbourhoods are then\nsmaller where counties are small and larger where they are large. Slide 31 gives the case for\nadaptive weights. Slides 30 and 35 give the basis for `k = 6`: both suggest about eight neighbours\nper feature for a skewed variable, and slide 35 calls this a rule of thumb. `k = 6` plus the county\nitself gives seven.\n\nChapter 10 creates this object but does not use it. Section 5.7 computes Gi\\* on both sets of\nweights.\n\n### Local Gi\\*\n\nGi\\* is reported as a z-score. Under a standard normal distribution, an absolute value above 1.96\ncorresponds to p < 0.05 in a two-sided test.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nHCSA_fdw <- hunan_fdw |>\n  mutate(gistar = local_gstar_perm(GDPPC, nb, wt, nsim = 999),\n         .before = 1) |>\n  unnest(gistar)\nglimpse(HCSA_fdw)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 88\nColumns: 19\n$ gi_star      <dbl> 0.38306332, -0.34046184, 0.23257243, 0.36406563, 0.217412…\n$ cluster      <fct> Low, Low, High, High, High, High, High, High, High, Low, …\n$ e_gi         <dbl> 0.011238957, 0.010946123, 0.012084226, 0.011477310, 0.011…\n$ var_gi       <dbl> 6.543550e-06, 7.557345e-06, 7.548837e-06, 9.812248e-06, 6…\n$ std_dev      <dbl> 0.460762839, -0.223671403, -0.005585977, 0.360108382, 0.2…\n$ p_value      <dbl> 6.449688e-01, 8.230130e-01, 9.955431e-01, 7.187661e-01, 8…\n$ p_sim        <dbl> 0.544, 0.996, 0.810, 0.536, 0.696, 0.938, 0.052, 0.034, 0…\n$ p_folded_sim <dbl> 0.272, 0.498, 0.405, 0.268, 0.348, 0.469, 0.026, 0.017, 0…\n$ skewness     <dbl> 1.0844673, 0.9983501, 1.1184257, 1.2759585, 0.9431153, 1.…\n$ kurtosis     <dbl> 1.4615396, 0.8064166, 1.4782723, 1.6020628, 0.6884654, 2.…\n$ nb           <nb> <1, 3, 4, 5, 57, 64>, <2, 57, 58, 78, 85>, <1, 3, 4, 5, 57…\n$ wt           <list> <0.1666667, 0.1666667, 0.1666667, 0.1666667, 0.1666667, …\n$ NAME_2       <chr> \"Changde\", \"Changde\", \"Changde\", \"Changde\", \"Changde\", \"C…\n$ ID_3         <int> 21098, 21100, 21101, 21102, 21103, 21104, 21109, 21110, 2…\n$ NAME_3       <chr> \"Anxiang\", \"Hanshou\", \"Jinshi\", \"Li\", \"Linli\", \"Shimen\", …\n$ ENGTYPE_3    <chr> \"County\", \"County\", \"County City\", \"County\", \"County\", \"C…\n$ County       <chr> \"Anxiang\", \"Hanshou\", \"Jinshi\", \"Li\", \"Linli\", \"Shimen\", …\n$ GDPPC        <dbl> 23667, 20981, 34592, 24473, 25554, 27137, 63118, 62202, 7…\n$ geometry     <POLYGON [m]> POLYGON ((602726.4 3292136,..., POLYGON ((619553.…\n```\n\n\n:::\n:::\n\n\n::: {.callout-note collapse=\"false\" title=\"How the code works\"}\nThe block uses one function:\n\n```r\nlocal_gstar_perm(x, nb, wt, nsim = 499, alternative = \"two.sided\")   # sfdep\n```\n\n- `local_gstar_perm()` computes Gi\\* for each county and tests it by conditional permutation. It\n  follows the pattern of `local_moran()` in section 4.1.2: it returns a data frame of results, which\n  is stored as the column `gistar` and spread into columns by `unnest()`. `nsim` defaults to 499.\n- `unnest()` spreads the 10 results into 10 columns: `gi_star`, `cluster`, `e_gi`, `var_gi`,\n  `std_dev`, `p_value`, `p_sim`, `p_folded_sim`, `skewness` and `kurtosis`. Of these, `gi_star` is\n  the statistic as a z-score, and `p_sim` the rank-based p-value from the 999 permutations.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngi.map <- tm_shape(HCSA_fdw) +\n  tm_polygons(fill = \"gi_star\",\n              fill.scale = tm_scale_intervals(style = \"pretty\", n = 6,\n                                              values = \"-brewer.rd_bu\"),\n              fill.legend = tm_legend(title = \"Gi*\",\n                                      position = tm_pos_out(\"right\", \"center\"))) +\n  tm_borders(col_alpha = 0.5) +\n  tm_title(\"Local Gi* of GDPPC\")\n\np.map <- tm_shape(HCSA_fdw) +\n  tm_polygons(fill = \"p_sim\",\n              fill.scale = tm_scale_intervals(\n                                breaks = c(0, 0.01, 0.05, 0.1, 1),\n                values = \"-brewer.reds\"),\n              fill.legend = tm_legend(title = \"p-value\",\n                                      position = tm_pos_out(\"right\", \"center\"))) +\n  tm_borders(col_alpha = 0.5) +\n  tm_title(\"Simulated p-value of Gi*\")\n\ntmap_arrange(gi.map, p.map, asp = 1, ncol = 2)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05_files/figure-html/unnamed-chunk-49-1.png){width=864}\n:::\n:::\n\n\n::: {.callout-note collapse=\"false\" title=\"How the code works\"}\nThe block sets the colours with arguments of `tm_scale_intervals()`:\n\n```r\ntm_scale_intervals(n = 5, style = \"pretty\", breaks = NULL, values = NA)   # tmap\n```\n\n- `values` names the palette. `\"brewer.rd_bu\"` is the ColorBrewer \"RdBu\" palette, which runs from\n  red to blue, and `\"brewer.reds\"` runs from light to dark red.\n- A leading minus reverses a palette. In the Gi\\* map, `\"-brewer.rd_bu\"` puts blue at the low end\n  and red at the high end, so that negative Gi\\* (cold spots) is blue and positive Gi\\* (hot spots)\n  is red:\n\n<div style=\"margin: 0.3em 0 0.8em 1.5em;\">\n<code>&quot;brewer.rd_bu&quot;</code>, low to high: <span style=\"display:inline-block;width:2.2em;height:1.1em;background:#B2182B;border:1px solid #ccc\"></span><span style=\"display:inline-block;width:2.2em;height:1.1em;background:#EF8A62;border:1px solid #ccc\"></span><span style=\"display:inline-block;width:2.2em;height:1.1em;background:#FDDBC7;border:1px solid #ccc\"></span><span style=\"display:inline-block;width:2.2em;height:1.1em;background:#D1E5F0;border:1px solid #ccc\"></span><span style=\"display:inline-block;width:2.2em;height:1.1em;background:#67A9CF;border:1px solid #ccc\"></span><span style=\"display:inline-block;width:2.2em;height:1.1em;background:#2166AC;border:1px solid #ccc\"></span><br>\n<code>&quot;-brewer.rd_bu&quot;</code>, low to high: <span style=\"display:inline-block;width:2.2em;height:1.1em;background:#2166AC;border:1px solid #ccc\"></span><span style=\"display:inline-block;width:2.2em;height:1.1em;background:#67A9CF;border:1px solid #ccc\"></span><span style=\"display:inline-block;width:2.2em;height:1.1em;background:#D1E5F0;border:1px solid #ccc\"></span><span style=\"display:inline-block;width:2.2em;height:1.1em;background:#FDDBC7;border:1px solid #ccc\"></span><span style=\"display:inline-block;width:2.2em;height:1.1em;background:#EF8A62;border:1px solid #ccc\"></span><span style=\"display:inline-block;width:2.2em;height:1.1em;background:#B2182B;border:1px solid #ccc\"></span>\n</div>\n\n- `style = \"pretty\"` with `n = 6` chooses about six classes with rounded break points.\n- In the p-value map, `breaks = c(0, 0.01, 0.05, 0.1, 1)` fixes the class boundaries at the usual\n  significance levels, and `\"-brewer.reds\"` makes the smallest p-values the darkest red.\n:::\n\n### Hot and cold spot map\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHCSA_fdw <- HCSA_fdw |>\n  mutate(HCSA_cluster = case_when(\n           p_sim >= signif ~ \"Insignificant\",\n           gi_star > 0 ~ \"Hot spot\",\n           TRUE ~ \"Cold spot\"),\n         HCSA_cluster = factor(HCSA_cluster,\n                               levels = c(\"Insignificant\", \"Hot spot\", \"Cold spot\")))\ntable(HCSA_fdw$HCSA_cluster)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nInsignificant      Hot spot     Cold spot \n           76             7             5 \n```\n\n\n:::\n:::\n\n\n::: {.callout-note collapse=\"false\" title=\"How the code works\"}\nThe block uses two functions:\n\n```r\ncase_when(condition ~ value, ...)                         # dplyr\nfactor(x, levels)                                         # base R\n```\n\n- `case_when()` tests its conditions in order and, for each county, returns the value of the first\n  condition that holds. A county with `p_sim >= signif` is labelled \"Insignificant\" whatever its\n  Gi\\*, and `TRUE ~ \"Cold spot\"` labels every county not yet labelled, which is significant with a\n  Gi\\* of zero or below. With three outcomes, `ifelse()` (section 4.1.5) would need one call inside\n  another.\n- As in section 4.1.5, `factor()` fixes the order of the classes, and with it the order of the\n  colours in the map.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(HCSA_fdw) +\n  tm_polygons(fill = \"HCSA_cluster\",\n              fill.scale = tm_scale_categorical(\n                values = c(\"grey80\", \"red\", \"blue\")),\n              fill.legend = tm_legend(title = \"Gi* cluster\",\n                                      position = tm_pos_out(\"right\", \"center\"))) +\n  tm_borders() +\n  tm_title(\"Hot and cold spots of GDPPC, fixed distance band, p < 0.05\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05_files/figure-html/unnamed-chunk-51-1.png){width=864}\n:::\n:::\n\n\nChapter 10 asks what statistical observations the hot and cold spot map supports:\n\n- **Significant counties:** 12 of the 88, seven hot spots and five cold spots. The other 76 are not\n  significant at p < 0.05.\n- **Hot spot:** Changsha and the surrounding counties.\n- **Cold spot:** in the west.\n- **Comparison with the LISA map of section 4.1.5:** both place the division between high and low\n  GDPPC in the same location, and differ in how far the clusters on each side of it extend. In the\n  west, where the counties are fewer and larger, the fixed distance band on which Gi\\* is computed\n  reaches further than contiguity.\n\n# Part 3: Review and extension\n\nParts 1 and 2 reproduced chapters 9 and 10 of r4gdsa. This part examines their method, and adds the\nparts of the Lesson 5 lecture and readings that the two chapters do not cover.\n\n| Section | What I do | Source |\n|----|--------------------------------------|------------|\n| | **Checking chapter 10's method** | |\n| 5.1 | Measure distances in the correct UTM zone | UTM zone boundaries |\n| 5.2 | Choose the local p-value and the number of simulations | Ord and Getis (1995) |\n| 5.3 | Correct the LISA map for 88 simultaneous tests | Ord and Getis (1995), Anselin (1995), Getis (2010) |\n| | **Adding what the chapters leave out** | |\n| 5.4 | Test whether high or low values drive the clustering | slides 16 and 17 |\n| 5.4.1 | Test how G responds to adding a constant to GDPPC | Getis and Ord (1992) |\n| 5.5 | Compare the null models for Moran's I | Moran (1950), Geary (1954) |\n| 5.6 | Compare local Geary's c with local Moran's I | slide 26 |\n| 5.7 | Use the adaptive weights that chapter 10 builds but does not use | slides 30 and 35 |\n| 5.7.1 | Vary `k` to find the hot and cold spots that do not depend on it | Mack and Kam (2018) |\n| 5.8 | Test Anselin's claim that Gi, Gi\\* and local Moran's I share one inference | Anselin (1995) |\n\n## Projected CRS: zone 49N versus zone 50N\n\nSection 2.2.1 projected the Hunan layer to EPSG:32649, and section 4.2.1 computed from it a fixed\nbandwidth of 62,955 m, against the 60,800 m reported in chapter 10. Both values are computed by the\nsame function on the same polygons. The difference arises from the coordinate system in which the\ndistances are measured.\n\nIn the Universal Transverse Mercator (UTM) system:\n\n- the world is divided into sixty zones, each six degrees of longitude wide;\n- each zone is projected onto its own plane with its own central meridian;\n- coordinates in a zone are metres on that plane, and a distance computed from them is measured on\n  that plane and not on the ellipsoid;\n- distortion is smallest near the central meridian and increases away from it.\n\nThe map below shows the zones over East Asia, with Hunan in orange.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\ns2_was <- sf_use_s2(FALSE)                      # crop in plain longitude and latitude\nworld <- spData::world |> st_crop(xmin = 80, xmax = 150, ymin = 0, ymax = 60)\nsf_use_s2(s2_was)\n\nbounds <- seq(84, 144, by = 6)                  # zone boundaries, 6 degrees apart\nzone_lines <- st_sfc(lapply(bounds, function(x) st_linestring(cbind(x, seq(0, 56, 0.5)))),\n                     crs = 4326)\nzone_labels <- st_sf(label = paste0(45:54, \"N\"),\n                     geometry = st_sfc(lapply(bounds[-length(bounds)] + 3,\n                                              function(x) st_point(c(x, 4))), crs = 4326))\n\nggplot() +\n  geom_sf(data = world, fill = \"grey90\", colour = \"grey60\", linewidth = 0.2) +\n  geom_sf(data = st_transform(hunan, 4326),\n          fill = \"darkorange\", colour = NA) +\n  geom_sf(data = zone_lines, colour = \"grey20\", linewidth = 0.4) +\n  geom_sf_text(data = zone_labels, aes(label = label), size = 3.2) +\n  coord_sf(crs = \"+proj=lcc +lat_1=20 +lat_2=45 +lon_0=114 +datum=WGS84\",\n           xlim = c(-2600000, 2600000), ylim = c(-500000, 4300000)) +\n  labs(x = NULL, y = NULL) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05_files/figure-html/unnamed-chunk-52-1.png){width=864}\n:::\n:::\n\n\nHence the zone assigned to a province determines the meridian relative to which its distances are\nmeasured. Chapter 10 projects the data to EPSG:32650 (zone 50N), and chapter 9 does not project\nthem. Neither chapter discusses the choice.\n\nThis section addresses three questions:\n\n1. Which zone contains Hunan?\n2. How much does the fixed bandwidth differ between the two zones?\n3. Does the hot and cold spot map of section 4.2.3 change as a result?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan_raw <- st_read(dsn = \"data/geospatial\", layer = \"Hunan\", quiet = TRUE)\n```\n:::\n\n\nThe map below marks the UTM zones on the unprojected layer. Dashed lines are zone boundaries, and\nsolid lines are the central meridians.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nlines_df <- tibble(lon = c(108, 114, 120, 111, 117),\n                   type = c(rep(\"zone boundary\", 3), rep(\"central meridian\", 2)))\n\nggplot() +\n  geom_sf(data = hunan_raw, fill = \"grey85\", colour = \"white\") +\n  geom_vline(data = lines_df, aes(xintercept = lon, linetype = type)) +\n  annotate(\"label\", x = c(111, 117), y = 30.55, label = c(\"zone 49N\", \"zone 50N\"),\n           label.size = 0, fill = \"white\") +\n  scale_linetype_manual(values = c(\"central meridian\" = \"solid\", \"zone boundary\" = \"dashed\")) +\n  coord_sf(xlim = c(107.5, 120.5), ylim = c(24.5, 30.8), expand = FALSE) +\n  labs(x = NULL, y = NULL, linetype = NULL) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05_files/figure-html/unnamed-chunk-54-1.png){width=864}\n:::\n:::\n\n\nHunan extends from 108.78°E to 114.25°E. UTM zone 49N covers 108°E to 114°E, and zone 50N covers\n114°E to 120°E. All of the province except a narrow strip east of 114°E lies in zone 49N. Its\ncentre, at 111.5°E, is 2.5° west of the western boundary of zone 50N and 5.5° from the central\nmeridian of that zone.\n\nProjection to zone 50N thus measures distances on the grid of the wrong zone. These distances are\nthe input to the fixed distance band.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nct49 <- critical_threshold(st_geometry(st_transform(hunan_raw, 32649)))\nct50 <- critical_threshold(st_geometry(st_transform(hunan_raw, 32650)))\ntibble(zone = c(\"49N (EPSG:32649)\", \"50N (EPSG:32650)\"),\n       critical_threshold_m = c(ct49, ct50)) |>\n  mutate(difference_pct = 100 * (critical_threshold_m - ct49) / ct49) |>\n  kable(digits = 2)\n```\n\n::: {.cell-output-display}\n\n\n|zone             | critical_threshold_m| difference_pct|\n|:----------------|--------------------:|--------------:|\n|49N (EPSG:32649) |             62954.89|           0.00|\n|50N (EPSG:32650) |             60799.91|          -3.42|\n\n\n:::\n:::\n\n\nIn zone 50N the computation reproduces the chapter's value of 60,799.91 m exactly, confirming its\nsource. In the correct zone the bandwidth is 62,954.89 m, 3.4% wider.\n\n**Scale distortion does not explain the difference.** Switching from zone 49N to zone 50N stretches\ndistances across Hunan by only about 0.3%, because the scale factor of UTM increases with distance\nfrom the central meridian. That would make the zone 50N threshold slightly larger, but it is 3.4%\nsmaller.\n\nDistances are least distorted along a zone's central meridian and are stretched more the further a\ncounty lies from it. The zone map above shows Hunan around the central meridian of zone 49N, and 3\nto 8 degrees west of the central meridian of zone 50N.\n\nThe sketch below shows why. A UTM zone is drawn by wrapping a sheet around the globe so that it\ntouches along the central meridian, and projecting each point outward onto the sheet. Where the\nsheet touches the globe, a distance is copied almost exactly. Away from that line the globe curves\naway from the sheet, and the same distance lands on a longer piece of the sheet. The sketch is\nsimplified and its angles are exaggerated. For Hunan in zone 50N the stretch is about 0.3%.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\ndeg <- pi / 180\nsketch_parts <- function(zone, offset) {\n  arc <- seq(offset - 12, offset + 12, by = 1) * deg      # Hunan, 24 degrees wide\n  ends <- tan(range(arc))                                   # where Hunan lands on the sheet\n  list(globe = tibble(zone, a = seq(-90, 90, 1) * deg, x = sin(a), y = cos(a)),\n       hunan = tibble(zone, x = sin(arc), y = cos(arc)),\n       image = tibble(zone, x = ends, y = 1),\n       rays  = tibble(zone, x = 0, y = 0, xend = ends, yend = 1))\n}\nzones <- c(\"Zone 49N: sheet touches inside Hunan\", \"Zone 50N: sheet touches east of Hunan\")\nparts <- map2(zones, c(0, -40), sketch_parts) |> transpose() |> map(bind_rows)\n\nggplot() +\n  annotate(\"segment\", x = -1.6, xend = 1.6, y = 1, yend = 1, colour = \"grey40\") +\n  geom_path(data = parts$globe, aes(x, y), colour = \"grey60\") +\n  geom_segment(data = parts$rays, aes(x, y, xend = xend, yend = yend),\n               linetype = \"dotted\", colour = \"grey50\") +\n  geom_path(data = parts$hunan, aes(x, y), colour = \"darkorange\", linewidth = 2) +\n  geom_line(data = parts$image, aes(x, y), colour = \"darkorange\", linewidth = 2) +\n  annotate(\"point\", x = 0, y = 1, size = 2.5) +\n  facet_wrap(~ zone) +\n  coord_equal(xlim = c(-1.6, 1.6), ylim = c(-0.05, 1.1)) +\n  theme_void() +\n  theme(strip.text = element_text(size = 11, margin = margin(b = 6)))\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05_files/figure-html/unnamed-chunk-56-1.png){width=864}\n:::\n:::\n\n\nIn each panel the grey arc is the globe, the straight line is the sheet, and the black dot is where\nthe sheet touches, on the central meridian. The dotted lines project Hunan outward from the centre\nof the globe. The orange arc is Hunan on the globe, and the orange bar is Hunan on the map. In zone\n49N the bar is almost as long as the arc. In zone 50N it is longer.\n\n**The point inside each county moves.** `critical_threshold()` returns the largest distance from a\ncounty to its nearest neighbour, measured between one point inside each county. In both zones that\ndistance is between Taoyuan and Hanshou. `sfdep` computes the points with `st_point_on_surface()`\nafter projection, and the point chosen depends on the projection: Taoyuan's point in zone 50N lies\nabout 3.3 km from its point in zone 49N. Moving the zone 49N points into zone 50N, without choosing\nthem again, gives 63,160 m, 0.3% longer, as the scale factor predicts.\n\nWhether the difference affects the results is a separate question from which zone is correct. Below,\nthe effect on the hot and cold spot classification is tested.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nh50 <- st_transform(hunan_raw, 32650) |>\n  left_join(hunan2012, by = \"County\") |>\n  select(1:4, 7, 15)\n\nfdw50 <- h50 |>\n  mutate(nb = include_self(st_dist_band(geometry, upper = ct50)),\n         wt = st_weights(nb, style = \"W\"), .before = 1)\n\nset.seed(1234)\ng50 <- local_gstar_perm(fdw50$GDPPC, fdw50$nb, fdw50$wt, nsim = 999)\n\ncls <- function(gi, p) factor(ifelse(p >= 0.05, \"Insignificant\",\n                                     ifelse(gi > 0, \"Hot spot\", \"Cold spot\")),\n                              levels = c(\"Insignificant\", \"Hot spot\", \"Cold spot\"))\n\ntable(zone_49N = HCSA_fdw$HCSA_cluster,\n      zone_50N = cls(g50$gi_star, g50$p_sim))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               zone_50N\nzone_49N        Insignificant Hot spot Cold spot\n  Insignificant            74        1         1\n  Hot spot                  2        5         0\n  Cold spot                 0        0         5\n```\n\n\n:::\n:::\n\n\n::: {.callout-note collapse=\"false\" title=\"How the code works\"}\nThe block repeats earlier steps in zone 50N and defines one function:\n\n```r\ncls <- function(gi, p) ...                                # defined here\n```\n\n- The first three steps repeat, for zone 50N, the join of section 2.3, the fixed band of section\n  4.2.1 and the Gi\\* test of section 4.2.2.\n- `function(gi, p)` defines a new function, `cls()`, with two inputs: the Gi\\* values and their\n  p-values. It applies the classification of section 4.2.3 in one line, so that the two zones are\n  classified in exactly the same way.\n- `table()` then cross-tabulates the two classifications, county by county.\n:::\n\nThe off-diagonal cells of the table count the counties that the two zones classify differently.\nFour of the 88 counties change class: two hot spots in zone 49N are insignificant in zone 50N, and\ntwo insignificant counties in zone 49N become a hot spot and a cold spot. The remaining 84 are\nclassified the same in both zones.\n\n## Local p-values: normal approximation versus rank\n\n`local_moran()` returns two p-values for each county, and they can disagree:\n\n- `p_ii` standardises the observed statistic by the mean and standard deviation of its permutation\n  distribution and passes the result through `pnorm()`. It is a normal approximation to that\n  distribution.\n- `p_ii_sim` is based on the rank of the observed statistic among the permuted values, and requires\n  no assumption about the shape of the distribution.\n\nChapter 10 classifies counties on `p_ii`. This page uses `p_ii_sim`, from the LISA map of section\n4.1.3 onwards, and this section explains the choice.\n\nBoth columns come from the same simulation, so the chapter's `p_ii` also uses the permutations it\nruns. Chapter 10 calls `local_moran(GDPPC, nb, wt, nsim = 99)`, which runs 99 permutations for each\nof the 88 counties, 8,712 in all. Each permutation is conditional: the value of the county is held\nfixed and the remaining 87 values are randomly permuted over the other 87 counties.\n\nTwo questions decide between the two columns, and this section examines them in turn:\n\n1. **Is the permutation distribution close enough to normal for `p_ii` to be valid?** The\n   simulations of Ord and Getis (1995) show when it is not, and `local_moran()` reports the\n   skewness of each county's permutation distribution as a direct check.\n2. **Can 99 permutations produce a p-value small enough to pass a corrected threshold?** With 88\n   counties, the Bonferroni threshold of section 5.3 is 0.05/88. The worked example in\n   Anselin (1995) applies the same kind of correction with 9,999 permutations (section 5.3.2).\n\nThe section ends with `p_folded_sim`, a third p-value column, and the reason this page does not use\nit.\n\nOrd and Getis (1995) is the assigned reading on the conditions under which the normal approximation\nfails. They examine the question by simulation, with five thousand random permutations on a 10 by 10\nlattice under four distributions.\n\nTheir simulations concern Gi\\* and Gi and not the local Moran. In their section 4 they show that the\nglobal Moran's I is a weighted average of the local G statistics, and this page takes that relation\nas the basis for applying their results to the local Moran.\n\nThey report the following patterns:\n\n> i. When the underlying distribution is normal, so is that of the test statistics (an exact\n>    result);\n> ii. when the underlying distribution is markedly skew, the distribution of the test statistics is\n>    non-normal, but approaches normality as the distance is increased.\n> iii. the statistics for edge cells approach normality more slowly because they have fewer\n>    neighbors; the convergence for corner cells is still slower.\n\nPatterns (ii) and (iii) both apply to these data. GDPPC is right skewed, as in pattern (ii), and the\ncounties with the fewest neighbours correspond to the edge cells of pattern (iii). `local_moran()`\nreports the skewness and kurtosis of the permutation distribution of each county, so the departure\nfrom normality can be measured directly.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(measure = c(\"skewness\", \"kurtosis\"),\n       min = c(min(lisa$skewness), min(lisa$kurtosis)),\n       median = c(median(lisa$skewness), median(lisa$kurtosis)),\n       max = c(max(lisa$skewness), max(lisa$kurtosis))) |>\n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|measure  |    min| median|   max|\n|:--------|------:|------:|-----:|\n|skewness | -2.043| -0.797| 1.896|\n|kurtosis | -0.066|  0.855| 4.385|\n\n\n:::\n:::\n\n\nA normal distribution has skewness 0 and excess kurtosis 0. Here the permutation distributions have\nneither property, and `pnorm()` treats them as normal.\n\nHow many counties are significant at p < 0.05 under each p-value? The table has four rows:\n\n- **`p_ii`, `nsim = 99`**: the chapter's choice, a normal approximation.\n- **`p_ii_sim`, `nsim = 99`**: the same simulation as the chapter, so only the p-value column\n  changes.\n- **`p_ii_sim`, `nsim = 999`**: this page's choice, used for the LISA map of section 4.1.3.\n- **`p_folded_sim`, `nsim = 999`**: a third column that `local_moran()` returns, examined at the end\n  of this section.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nlm99 <- local_moran(hunan$GDPPC, wm_q$nb, wm_q$wt, nsim = 99)\n\ntibble(p_value = c(\"p_ii (normal approximation)\", \"p_ii_sim, nsim = 99\",\n                   \"p_ii_sim, nsim = 999\", \"p_folded_sim, nsim = 999\"),\n       significant_at_0.05 = c(sum(lm99$p_ii < 0.05),\n                               sum(lm99$p_ii_sim < 0.05),\n                               sum(lisa$p_ii_sim < 0.05),\n                               sum(lisa$p_folded_sim < 0.05))) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|p_value                     | significant_at_0.05|\n|:---------------------------|-------------------:|\n|p_ii (normal approximation) |                  13|\n|p_ii_sim, nsim = 99         |                  16|\n|p_ii_sim, nsim = 999        |                  16|\n|p_folded_sim, nsim = 999    |                  23|\n\n\n:::\n:::\n\n\nBoth the number of significant counties and their identity depend on whether `p_ii` or `p_ii_sim` is\nused.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(chapter_p_ii = ifelse(lm99$p_ii < 0.05, as.character(lm99$mean), \"Insignificant\"),\n      simulated = as.character(lisa$LISA_cluster))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               simulated\nchapter_p_ii    High-High Insignificant Low-High Low-Low\n  High-High             6             2        0       0\n  Insignificant         0            69        0       6\n  Low-High              0             1        1       0\n  Low-Low               0             0        0       3\n```\n\n\n:::\n:::\n\n\nOf the four groups, Low-Low changes most. With the normal-approximation p-value, three counties in\nthe west are classified as Low-Low, and with the simulated p-value, nine. The six additional\ncounties, found by the rank-based p-value from the simulation that the chapter itself runs, have low\nGDPPC and neighbours with low GDPPC, the pattern the LISA map is intended to identify.\n\nChapter 10's `nsim = 99` also limits the smallest attainable p-value, the second condition listed\nabove. A conditional permutation p-value is `(number of simulations at least as extreme + 1) / (nsim\n+ 1)`. Its smallest possible value is `1 / (nsim + 1)`.\n\nFor the two-sided `p_ii_sim` the smallest value is twice that. `local_moran()` also returns\n`p_folded_sim`, the same ranking folded onto the range [0, 0.5], which is not doubled.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(nsim = c(99, 999, 9999),\n       floor_p_ii_sim = 2 / (c(99, 999, 9999) + 1),\n       floor_p_folded_sim = 1 / (c(99, 999, 9999) + 1)) |>\n  kable(digits = 5)\n```\n\n::: {.cell-output-display}\n\n\n| nsim| floor_p_ii_sim| floor_p_folded_sim|\n|----:|--------------:|------------------:|\n|   99|          2e-02|              1e-02|\n|  999|          2e-03|              1e-03|\n| 9999|          2e-04|              1e-04|\n\n\n:::\n:::\n\n\nChapter 10 sets breaks for its Gi\\* p-value maps at 0.001 and 0.01 with `nsim = 99`, whose minimum\nis 0.02, so two of the five classes are empty for any data. This page uses `nsim = 999`, at which\nthe smallest attainable `p_ii_sim` is 0.002. Section 5.3 shows that 999 is still\ninsufficient once a correction for multiple comparisons is applied.\n\n`p_folded_sim` is included in the table to show why this page does not use it. In these data it is\nclose to half of `p_ii_sim`: exactly half in 86 of the 88 rows, with a mean relative difference of\n1.4%.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nall.equal(lisa$p_folded_sim, lisa$p_ii_sim / 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Mean relative difference: 0.01432292\"\n```\n\n\n:::\n:::\n\n\n::: {.callout-note collapse=\"false\" title=\"How the code works\"}\nThe block uses one function:\n\n```r\nall.equal(target, current)                                # base R\n```\n\n- `all.equal()` compares two sets of numbers. It returns `TRUE` if they agree up to rounding\n  error, and otherwise describes how far they differ, here as a mean relative difference.\n:::\n\nThe comparison of a quantity on [0, 0.5] against 0.05 is a one-sided test at the 5% level. It\naccounts for the 23 significant counties under `p_folded_sim` against 16 under `p_ii_sim`. The\nadditional counties follow from the scale of the p-value alone and are not evidence that those\ncounties cluster. This page compares `p_ii_sim` against 0.05 as a two-sided test.\n\n## Multiple comparisons across 88 counties\n\nSection 4.1.5 classified 16 counties as significant at p < 0.05 and mapped them.\n\nA LISA map involves one hypothesis test per county. Each test is evaluated at α = 0.05, the\nprobability of a false positive for a single test. With no spatial pattern present, 88 tests\nevaluated at 0.05 are expected to produce about four significant counties. Section 3.5 met the\nproblem of multiple comparisons on a smaller scale: with six correlogram lags tested in one table,\nlag 3 was no longer significant after Holm's correction.\n\nA correction for multiple comparisons raises the evidence a test must reach, so that a county is\ncalled significant only on stronger evidence than 0.05. Neither chapter applies one. Both assigned\npapers on the local statistics state that a correction is needed: Anselin (1995), which introduced\nthe local Moran, and Ord and Getis (1995), on the distribution of Gi and Gi\\*. They disagree over\nhow many tests the correction should count, and section 5.3.1 sets out the disagreement. Two\ncorrections are used here, both taken from the readings:\n\n- **Bonferroni** divides α by the number of tests, so every county is evaluated at 0.05/88, the\n  same fixed penalty for all. Ord and Getis (1995) recommend it, and Anselin (1995) applies it in\n  his worked example.\n- **Benjamini-Hochberg** is less severe. It controls the false discovery rate (FDR), the expected\n  proportion of false positives among the rejections, and rejects the ith smallest p-value when p(i)\n  ≤ i × 0.05 / 88, so its threshold increases with rank. Getis (2010) cites it, from Benjamini and\n  Hochberg (1995), among the attempts to address multiple testing in local statistics.\n\nHow many of the 16 counties remain significant after each correction, and which conclusions does the\nmap then support?\n\n\n::: {.cell}\n\n```{.r .cell-code}\np <- lisa$p_ii_sim\ntibble(correction = c(\"none\", \"Benjamini-Hochberg (FDR)\", \"Bonferroni\"),\n       significant = c(sum(p < 0.05),\n                       sum(p.adjust(p, method = \"fdr\") < 0.05),\n                       sum(p.adjust(p, method = \"bonferroni\") < 0.05))) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|correction               | significant|\n|:------------------------|-----------:|\n|none                     |          16|\n|Benjamini-Hochberg (FDR) |           0|\n|Bonferroni               |           0|\n\n\n:::\n:::\n\n\n::: {.callout-note collapse=\"false\" title=\"How the code works\"}\nThe block uses one new function:\n\n```r\np.adjust(p, method = p.adjust.methods)                    # stats\n```\n\n- `p.adjust()` adjusts a set of p-values for multiple comparisons, so that each adjusted value can\n  be compared directly with 0.05.\n- `method = \"bonferroni\"` multiplies each p-value by the number of tests, 88, with a ceiling of 1.\n- `method = \"fdr\"` applies the Benjamini-Hochberg procedure.\n- `sum(... < 0.05)` counts the counties whose adjusted p-value is below 0.05.\n:::\n\nUnder either correction, none of the 88 counties remains significant, and no county on the LISA map\nmeets a corrected threshold at this number of simulations.\n\nThis follows from the smallest p-value that 999 permutations can produce (section 5.2).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(floor_at_nsim_999 = min(lisa$p_ii_sim), bonferroni_threshold = 0.05 / 88)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   floor_at_nsim_999 bonferroni_threshold \n        0.0020000000         0.0005681818 \n```\n\n\n:::\n:::\n\n\nAt `nsim = 999` the smallest attainable `p_ii_sim` is 0.002, and the Bonferroni correction for 88\ntests requires p < 0.00057. No rank-based p-value at this number of simulations can meet that bound,\nfor any data.\n\nBenjamini-Hochberg is not limited in the same way. Its threshold admits a p-value of 0.002 from rank\ni = 4 upwards. No county is rejected here: too few counties attain the minimum p-value to meet the\nthresholds at those ranks.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(rank = 1:6,\n       bh_threshold = (1:6) * 0.05 / 88,\n       observed_p = sort(lisa$p_ii_sim)[1:6]) |>\n  mutate(rejected = observed_p <= bh_threshold) |>\n  kable(digits = 5)\n```\n\n::: {.cell-output-display}\n\n\n| rank| bh_threshold| observed_p|rejected |\n|----:|------------:|----------:|:--------|\n|    1|      0.00057|      0.002|FALSE    |\n|    2|      0.00114|      0.002|FALSE    |\n|    3|      0.00170|      0.002|FALSE    |\n|    4|      0.00227|      0.004|FALSE    |\n|    5|      0.00284|      0.004|FALSE    |\n|    6|      0.00341|      0.004|FALSE    |\n\n\n:::\n:::\n\n\nTies at the minimum p-value would increase the number of rejections. If four counties had p = 0.002,\nall four would meet the i = 4 threshold of 0.00227.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nlm_big <- local_moran(hunan$GDPPC, wm_q$nb, wm_q$wt, nsim = 9999)\ntibble(correction = c(\"none\", \"FDR\", \"Bonferroni\"),\n       significant_at_nsim_9999 = c(sum(lm_big$p_ii_sim < 0.05),\n                                    sum(p.adjust(lm_big$p_ii_sim, \"fdr\") < 0.05),\n                                    sum(p.adjust(lm_big$p_ii_sim, \"bonferroni\") < 0.05))) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|correction | significant_at_nsim_9999|\n|:----------|------------------------:|\n|none       |                       17|\n|FDR        |                        3|\n|Bonferroni |                        1|\n\n\n:::\n:::\n\n\nWith `nsim` = 9,999 the minimum attainable p-value falls to 0.0002, below the Bonferroni threshold,\nand both corrections can then distinguish between counties. At 9,999 permutations 17 counties are\nsignificant without correction, one more than at 999. Three of them remain significant under FDR and\none under Bonferroni.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsig_after_fdr <- lisa |>\n  st_drop_geometry() |>\n  mutate(p_fdr = p.adjust(lm_big$p_ii_sim, \"fdr\"),\n         p_bonf = p.adjust(lm_big$p_ii_sim, \"bonferroni\")) |>\n  filter(p_fdr < 0.05) |>\n  select(County, GDPPC, LISA_cluster, p_fdr, p_bonf)\nkable(sig_after_fdr, digits = 5)\n```\n\n::: {.cell-output-display}\n\n\n|County   | GDPPC|LISA_cluster |   p_fdr| p_bonf|\n|:--------|-----:|:------------|-------:|------:|\n|Longhui  |  9572|Low-Low      | 0.04107| 0.0880|\n|Wugang   | 12112|Low-Low      | 0.01760| 0.0176|\n|Xiangtan | 27060|High-High    | 0.04107| 0.1232|\n\n\n:::\n:::\n\n\n::: {.callout-note collapse=\"false\" title=\"How the code works\"}\nThe block uses two new functions:\n\n```r\nst_drop_geometry(x)                                       # sf\nfilter(.data, ...)                                        # dplyr\n```\n\n- `st_drop_geometry()` removes the geometry column, which turns the sf object into an ordinary data\n  frame and keeps the printed table short.\n- `filter()` keeps the rows for which the condition is true, here the counties whose FDR-adjusted\n  p-value is below 0.05.\n- `select()` (section 2.3) then keeps the five columns printed.\n:::\n\n### Size of the Bonferroni correction\n\nThese counts give the number of counties that remain significant under each correction. They do not\ndetermine whether a correction should be applied to a LISA map at all. Two positions are possible.\nIf the map is treated as exploratory, each county's p-value describes only that county and no\ncorrection is required. If the map is treated as 88 simultaneous tests, a correction is required and\nthe remaining question is its size. Neither chapter discusses whether a correction should be\napplied. Anselin (1995) and Ord and Getis (1995) both take the second position.\n\nOrd and Getis (1995) recommend the Bonferroni correction:\n\n> we believe that the limits given by the Bonferroni inequality, possibly with the Tukey\n> approximation, represent a reasonable basis for making inferences until more precise methods are\n> developed.\n\nThey also record a referee's objection in the same paragraph: \"One of the referees has noted that\nthe Bonferroni limits may be unduly conservative when n becomes large. This issue needs to be\nexplored further.\"\n\nAnselin (1995) agrees that a correction is needed and questions its size:\n\n> Due to this correlation, and the associated problem of multiple comparisons, the usual\n> interpretation of significance will be flawed.\n\n> while it is obvious that some correction to the individual significance levels is needed, the\n> extent to which it is indeed necessary to take m = n remains to be further investigated.\n\nHis reason is that the dependence between local statistics is local and bounded: \"the number of\ncommon neighbors does not change with the number of observations\". He notes that on a regular\nlattice under the Queen rule, first-order neighbours share four elements of their neighbourhood\nsets, second-order neighbours three, and higher-order neighbours none. Setting m, the number of\ntests, equal to n, the number of observations, therefore corrects for more tests than are correlated\nwith one another.\n\nHe nevertheless applies m = n in his own worked example on 42 African countries: \"the individual\nsignificance levels for each observation should be taken as 0.05/42, or 0.0012.\"\n\nGetis (2010), a chapter on the Lesson 5 reference list, returns to multiple testing in local\nstatistics fifteen years later. He describes the selection of tests that can withstand \"the\nsimultaneity effects of multiple tests\" as \"a particularly difficult area of research\", since the\nobservations used for one local test are used again for the tests at neighbouring locations, and\ncites Benjamini and Hochberg (1995) and Castro and Singer (2006) among the attempts to resolve it.\nThe Benjamini-Hochberg counts above are reported alongside Bonferroni because Getis (2010) cites\nthat procedure as one of these attempts.\n\n### Permutation count and the p-value floor\n\nAnselin's worked example is also relevant to the choice of `nsim`. A corrected bound cannot be met\nby a p-value whose minimum attainable value exceeds it, so the number of permutations should be\nchosen after the correction. Anselin used **9,999** conditional permutations and gives no reason for\nchoosing 9,999 rather than some smaller number. His bound is 0.05/42 = 0.0012, and a minimum p-value\nof 1/(nsim+1) falls below that bound from about nsim = 840 upwards, so the arithmetic does not\nrequire a count that high. At 9,999 permutations the minimum is well below his bound:\n\n> only Sudan meeting the Bonferroni bound for an overall a = 0.05. For this country, two out of\n> the 9,999 statistics computed from the randomized samples exceed the observed one, clearly\n> labeling the latter as \"extreme.\"\n\nChapter 10 sets `nsim = 99` before any correction is considered.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(setting = c(\"chapter 10, nsim = 99\", \"this page, nsim = 999\",\n                   \"section 5.3, nsim = 9999\", \"Anselin (1995), nsim = 9999, n = 42\"),\n       floor = c(2/100, 2/1000, 2/10000, 1/10000),\n       bonferroni_bound = c(0.05/88, 0.05/88, 0.05/88, 0.05/42)) |>\n  mutate(correction_reachable = floor < bonferroni_bound) |>\n  kable(digits = 5)\n```\n\n::: {.cell-output-display}\n\n\n|setting                             | floor| bonferroni_bound|correction_reachable |\n|:-----------------------------------|-----:|----------------:|:--------------------|\n|chapter 10, nsim = 99               | 2e-02|          0.00057|FALSE                |\n|this page, nsim = 999               | 2e-03|          0.00057|FALSE                |\n|section 5.3, nsim = 9999            | 2e-04|          0.00057|TRUE                 |\n|Anselin (1995), nsim = 9999, n = 42 | 1e-04|          0.00119|TRUE                 |\n\n\n:::\n:::\n\n\nAt chapter 10's setting the minimum attainable p-value (0.02) is about thirty-five times the\nBonferroni bound for 88 counties (0.00057), so no county can be significant after the correction,\nwhatever the data.\n\n### Counties significant after correction\n\nEarlier in this section, no county remained significant under either correction at `nsim = 999`, and\nthree remained significant under FDR at 9,999. Two decisions follow for the LISA map of section\n4.1.5 and the hot and cold spot map of section 4.2.3: whether to redraw them at a corrected\nthreshold, and which claims the text around them can support.\n\nThe map in section 4.1.5 is left uncorrected and treated as exploratory, so that each county's\np-value describes only that county, the first of the two positions in section 5.3.1. The counts\nabove report how many of its counties a correction would retain.\n\nThe two maps below use the same 9,999 permutations, so they differ only in the correction.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nlvls <- c(\"Insignificant\", \"Low-Low\", \"Low-High\", \"High-Low\", \"High-High\")\nlisa_corr <- lisa |>\n  mutate(uncorrected = factor(ifelse(lm_big$p_ii_sim < 0.05,\n                                     as.character(mean), \"Insignificant\"), levels = lvls),\n         fdr = factor(ifelse(p.adjust(lm_big$p_ii_sim, \"fdr\") < 0.05,\n                             as.character(mean), \"Insignificant\"), levels = lvls))\n\ncluster_map <- function(col, title) {\n  tm_shape(lisa_corr) +\n    tm_polygons(fill = col,\n                fill.scale = tm_scale_categorical(\n                  values = c(\"grey80\", \"blue\", \"lightblue\", \"pink\", \"red\")),\n                fill.legend = tm_legend(title = \"LISA cluster\",\n                                        position = tm_pos_out(\"right\", \"center\"))) +\n    tm_title(title)\n}\n\ntmap_arrange(cluster_map(\"uncorrected\", \"No correction, 17 counties\"),\n             cluster_map(\"fdr\", \"Benjamini-Hochberg, 3 counties\"),\n             asp = 1, ncol = 2)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05_files/figure-html/unnamed-chunk-69-1.png){width=864}\n:::\n:::\n\n\nThree counties remain after correction: Longhui and Wugang, Low-Low counties in the west, and\nXiangtan, in the High-High cluster around Changsha. Wugang is the only county that also meets the\nBonferroni bound. The corrected map is therefore weighted towards the Low-Low cluster in the west,\nwhich reverses the emphasis of the uncorrected map. The 16 counties of section 4.1.5 are candidate\nclusters. The Gi\\* map of section 4.2.3 was not tested against a corrected threshold.\n\nThe corrected result also differs from global G in section 5.4, which indicates that high values\ndominate the province-wide pattern. The two results are consistent because the statistics measure\ndifferent things. Global G weights counties by the magnitude of their values. A corrected LISA\nidentifies the individual counties whose statistics meet a threshold corrected for 88 simultaneous\ntests, and two of the three such counties have low GDPPC.\n\nAnselin (1995) raises a further point that no correction addresses. Local statistics are themselves\nspatially autocorrelated, since neighbouring counties share the observations from which their\nstatistics are computed:\n\n> This spatial clustering (or spatial autocorrelation) of both the Gi\\* and the LISA statistics is a\n> result of the way they are constructed, and should be kept in mind when visually interpreting a\n> map of LISAs.\n\nWhen significant counties are adjacent, the map cannot show whether they reflect a pattern shared\nacross the area or one very high value that falls in all of their neighbourhoods.\n\n## Getis-Ord global G\n\nSections 3.3 and 3.4 found positive spatial autocorrelation in GDPPC under both global measures\n(Moran's I = 0.301, Geary's C = 0.691). Neither statistic distinguishes clustering of high values\nfrom clustering of low values.\n\nThe Getis-Ord global G, covered in slides 16 and 17 but in neither chapter, measures the overall\nconcentration of high or low values. Getis and Ord (1992) state the limitation of Moran's I that G\naddresses:\n\n> The I(d) statistic has its peculiar weakness in not being able to discriminate between patterns\n> that have high values dominant within d or low values dominant.\n\nGetis and Ord (1992) conclude that \"any test for spatial association should use both types of\nstatistics.\"\n\nDoes the positive spatial autocorrelation in GDPPC reflect clustering of high values or of low\nvalues?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnb_band <- dnearneigh(st_centroid(st_geometry(hunan)), 0, ct)\nlw_band <- nb2listw(nb_band, style = \"B\", zero.policy = TRUE)\nglobalG.test(hunan$GDPPC, lw_band, zero.policy = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tGetis-Ord global G statistic\n\ndata:  hunan$GDPPC \nweights: lw_band   \n\nstandard deviate = 3.0285, p-value = 0.001229\nalternative hypothesis: greater\nsample estimates:\nGlobal G statistic        Expectation           Variance \n      5.099677e-02       4.362591e-02       5.923594e-06 \n```\n\n\n:::\n:::\n\n\n::: {.callout-note collapse=\"false\" title=\"How the code works\"}\nThe block uses three new functions:\n\n```r\nst_centroid(x)                                            # sf\ndnearneigh(x, d1, d2)                                     # spdep\nglobalG.test(x, listw, zero.policy = attr(listw, \"zero.policy\"),\n             alternative = \"greater\")                     # spdep\n```\n\n- `st_centroid()` replaces each county by its centroid, and `dnearneigh()` makes every pair of\n  centroids between `d1 = 0` and `d2 = ct` metres apart into neighbours.\n- `nb2listw(style = \"B\")` gives each neighbour a weight of 1 without row standardisation, as the\n  definition of G requires.\n- `globalG.test()` computes G and tests it against its expectation under spatial randomness.\n  `alternative = \"greater\"`, the default, tests whether high values are concentrated.\n:::\n\nGetis and Ord (1992) define G on a binary distance-based weights matrix, so `style = \"B\"` follows\nfrom the definition of the statistic. G is the ratio of the weighted sum of the products of value\npairs to the total sum of the products of value pairs. Only the numerator contains the weights, so\nrow standardisation would change the meaning of the ratio.\n\nFor GDPPC, G is 0.0510, against an expectation of 0.0436 (z = 3.03, p = 0.0012). A significant\npositive z-score indicates that high values within d of other high values dominate the pattern.\n\nThis appears to conflict with the LISA map of section 4.1.5, which has nine Low-Low counties and six\nHigh-High counties. The two statistics measure different things:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmu <- mean(hunan$GDPPC)\nlisa |>\n  st_drop_geometry() |>\n  filter(LISA_cluster %in% c(\"High-High\", \"Low-Low\")) |>\n  group_by(LISA_cluster) |>\n  summarise(counties = n(),\n            mean_deviation_from_provincial_mean = round(mean(GDPPC - mu))) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|LISA_cluster | counties| mean_deviation_from_provincial_mean|\n|:------------|--------:|-----------------------------------:|\n|Low-Low      |        9|                              -11576|\n|High-High    |        6|                               28860|\n\n\n:::\n:::\n\n\n::: {.callout-note collapse=\"false\" title=\"How the code works\"}\nThe block uses three new functions:\n\n```r\ngroup_by(.data, ...)                                      # dplyr\nsummarise(.data, ...)                                     # dplyr\nn()                                                       # dplyr\n```\n\n- `filter()` (section 5.3) keeps the High-High and Low-Low counties.\n- `group_by()` splits the rows by cluster, and `summarise()` then computes one row per group.\n- `n()` counts the counties in each group, and `mean(GDPPC - mu)` averages their deviation from the\n  provincial mean, `mu`.\n:::\n\nGlobal G weights each county by the magnitude of its value. On average the six High-High counties\nare about 28,900 yuan above the provincial mean, and the nine Low-Low counties about 11,600 yuan\nbelow it. GDPPC is bounded below by zero and unbounded above, so high values deviate further from\nthe mean than low values, and they dominate a sum-of-products statistic although they are fewer.\n\nThe three statistics therefore describe different aspects of the same pattern. Moran's I indicates\npositive spatial autocorrelation, global G indicates that high values dominate it, and the LISA map\nshows where the clusters are: high values around Changsha and low values in the west.\n\n### Natural origin and location invariance\n\nSection 4.1.4 standardised GDPPC before plotting it against its spatial lag, because the scatterplot\ncompares each county with the provincial mean. Chapter 10 standardises there but computes Gi\\* on\nthe raw values, and does not say why the two differ. The reason is a condition that\nGetis and Ord (1992) place on G, and that neither chapter states.\n\nA variable has a natural origin when zero represents the absence of the quantity measured, as\nopposed to an arbitrary reference point. G is computed from the values themselves, not from their\ndeviations from the mean, so the position of zero on the measurement scale affects the statistic.\nGDPPC has a natural origin, since zero yuan per person corresponds to zero output. Regression\nresiduals do not, since their zero is defined by the fitted line.\n\nGetis and Ord (1992) state two conditions, the first for Gi and the second for G(d):\n\n> Gi is scale-invariant (Yi = bXi yields the same scores as Xi) but not location-invariant\n> (Yi = a + Xi gives different results than Xi). The statistic is intended for use only for those\n> variables that possess a natural origin.\n\n> it is inappropriate to use G(d) to study residuals from regression.\n\nHow far do G and Moran's I change when a constant is added to GDPPC?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshift_test <- function(a) {\n  x <- hunan$GDPPC + a\n  g <- globalG.test(x, lw_band, zero.policy = TRUE)\n  m <- moran.test(x, rswm_q, zero.policy = TRUE)\n  tibble(shift = a, G = g$estimate[1], z_G = g$statistic, p_G = g$p.value,\n         I = m$estimate[1], z_I = m$statistic, p_I = m$p.value)\n}\nbind_rows(shift_test(0), shift_test(10000), shift_test(100000)) |>\n  mutate(across(c(p_G, p_I), ~ format(.x, digits = 3, scientific = TRUE))) |>\n  kable(digits = 4)\n```\n\n::: {.cell-output-display}\n\n\n| shift|      G|       z_G|p_G      |      I|    z_I|p_I      |\n|-----:|------:|---------:|:--------|------:|------:|:--------|\n| 0e+00| 0.0510| 3.0284840|1.23e-03 | 0.3007| 4.7351|1.09e-06 |\n| 1e+04| 0.0475| 2.3578073|9.19e-03 | 0.3007| 4.7351|1.09e-06 |\n| 1e+05| 0.0440| 0.8953641|1.85e-01 | 0.3007| 4.7351|1.09e-06 |\n\n\n:::\n:::\n\n\n::: {.callout-note collapse=\"false\" title=\"How the code works\"}\nThe block defines one function and uses two new ones:\n\n```r\nshift_test <- function(a) ...                             # defined here\nbind_rows(...)                                            # dplyr\nacross(.cols, .fns)                                       # dplyr\n```\n\n- `shift_test()` adds a constant `a` to GDPPC, runs global G and Moran's I on the shifted values,\n  and returns one row of results. Defining it once means the three shifts are computed in exactly\n  the same way.\n- `bind_rows()` stacks the three one-row results into one table.\n- `across(c(p_G, p_I), ~ format(...))` applies the same formatting to both p-value columns, which\n  prints the very small values in scientific notation.\n:::\n\nMoran's I is unchanged: it is computed on deviations from the mean, and adding a constant leaves\nevery deviation unchanged. Global G is no longer significant. Its z-score decreases from 3.03 to\n0.90 and its p-value increases from 0.0012 to 0.19. Multiplying GDPPC by a constant, in place of\nadding one, leaves both statistics unchanged. This is the scale invariance that Getis and Ord\ndescribe.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ng2 <- globalG.test(hunan$GDPPC * 2, lw_band, zero.policy = TRUE)\nm2 <- moran.test(hunan$GDPPC * 2, rswm_q, zero.policy = TRUE)\nc(G_doubled = g2$estimate[1], z_G_doubled = g2$statistic,\n  I_doubled = m2$estimate[1], z_I_doubled = m2$statistic)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  G_doubled.Global G statistic \n                                    0.05099677 \n                  z_G_doubled.standard deviate \n                                    3.02848403 \n                   I_doubled.Moran I statistic \n                                    0.30074997 \nz_I_doubled.Moran I statistic standard deviate \n                                    4.73513201 \n```\n\n\n:::\n:::\n\n\nThe natural-origin requirement makes a G result a statement about the variable on the scale on which\nit was measured. For a variable centred at zero, or for regression residuals,\na significant G would be an artefact of the position of zero on the scale.\n\n## Null models for Moran's I\n\nSection 3.3.1 ran `moran.test()` on GDPPC and reported a z-score of 4.74. Moran (1950), who\nintroduced the statistic, states that its variance, and so this z-score, requires normally\ndistributed values, and GDPPC is right skewed. By default, however, `moran.test()` does not use\nMoran's variance. Its `randomisation` argument, which defaults to `TRUE` and is not mentioned in\neither chapter, selects a different null model. What does each null model assume?\n\nMoran (1950) derives the expectation of I without any distributional assumption, and states that the\nsecond moment (which gives the variance, how widely I spreads around its expectation) requires an\nassumption about the distribution:\n\n> To evaluate the second moment of I we have to assume further that all the xij are distributed\n> normally.\n\n`randomisation = FALSE` is Moran's own variance, which assumes the values are drawn from a normal\ndistribution. Geary (1954) sets out both null models:\n\n> The theory is discussed from the viewpoints of both randomization and classical normal theory.\n> With the randomization approach, the observations themselves are the \"universe\" and no\n> assumption need be made as to the character of the frequency distribution.\n\nHaving found the distribution of c close to normal for Ireland's 26 counties, he concludes that\n\"accordingly, one can have confidence in deciding on significance from the standard error.\"\n\n- **Normality** assumes the 88 values are drawn from a normal distribution, which does not hold for\n  a right-skewed variable such as GDPPC.\n- **Randomisation**, the default used in section 3.3.1, treats the 88 values as fixed and considers\n  every assignment of them to counties. Its z-score still relies on a normal approximation.\n- **Permutation**, used in section 3.3.2, samples 999 of those assignments and needs no\n  approximation.\n\nSections 3.3.1 and 3.3.2 reach the same conclusion under the randomisation and permutation null\nmodels: both reject the null hypothesis of no spatial autocorrelation. I is a sum over all 88\ncounties, so a normal approximation suits it better than a local statistic computed from five\nneighbours, which is the case examined in section 5.2.\n\n## Local Geary's c\n\nSection 3.4 computed Geary's C for the whole province. Section 3.5 compared its correlogram with\nthat of Moran's I, and the two differed in significance at lags 3 and 6.\n\nNeither chapter computes the local form of Geary's C. Slide 26 identifies it as a second LISA,\nalongside local Moran's I. Each of the two local statistics misses a pattern that the other\ndetects, and this section compares them on GDPPC.\n\nLocal Moran's I and local Geary's c differ in construction. Up to scaling constants, for county $i$\nwith neighbours $j$ and weights $w_{ij}$,\n\n$$\nI_i = (x_i - \\bar{x}) \\sum_j w_{ij}(x_j - \\bar{x}), \\qquad c_i = \\sum_j w_{ij}(x_i - x_j)^2 .\n$$\n\n- **Local Moran's I compares the county with the provincial mean.** It multiplies the county's\n  deviation from the mean by the weighted deviations of its neighbours, so for a county near the\n  mean $I_i$ is small, even when the county matches its neighbours closely.\n- **Local Geary's c compares the county with its neighbours.** As slide 26 defines it, $c_i$ adds up\n  the squared differences between the county and each neighbour, and the provincial mean cancels in\n  each difference. $c_i$ is large for a county whose value differs sharply from its neighbours'\n  values. It cannot distinguish High-High from Low-Low, since a cluster of high values and a\n  cluster of low values both give small differences.\n\nSection 4.1.5 found 16 significant counties with local Moran's I. How many does local Geary's c\nfind, and which counties do the two statistics classify differently?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nlgeary <- wm_q |>\n  mutate(local_c = local_c_perm(GDPPC, nb, wt, nsim = 999), .before = 1) |>\n  unnest(local_c)\n\ntibble(statistic = c(\"local Moran's I\", \"local Geary's c\"),\n       significant_at_0.05 = c(sum(lisa$p_ii_sim < 0.05),\n                               sum(lgeary$p_ci_sim < 0.05))) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|statistic       | significant_at_0.05|\n|:---------------|-------------------:|\n|local Moran's I |                  16|\n|local Geary's c |                  21|\n\n\n:::\n:::\n\n\n::: {.callout-note collapse=\"false\" title=\"How the code works\"}\nThe block uses one new function:\n\n```r\nlocal_c_perm(x, nb, wt, nsim = 499, alternative = \"two.sided\")   # sfdep\n```\n\n- `local_c_perm()` computes local Geary's c for each county and tests it by conditional\n  permutation. It follows the pattern of `local_moran()` in section 4.1.2: it returns a data frame\n  of results, stored as the column `local_c` and spread into columns by `unnest()`.\n- `p_ci_sim` is the rank-based p-value from the 999 permutations. `nsim` defaults to 499.\n:::\n\nLocal Geary's c identifies 21 significant counties, against 16 for local Moran's I. Eleven counties\nare significant under one statistic and not the other.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsig_moran <- lisa$p_ii_sim < signif\nsig_geary <- lgeary$p_ci_sim < signif\nz <- (hunan$GDPPC - mean(hunan$GDPPC)) / sd(hunan$GDPPC)\n\ntibble(County = hunan$County, GDPPC = hunan$GDPPC, z_GDPPC = round(z, 2),\n       `local Moran` = sig_moran, `local Geary` = sig_geary) |>\n  filter(sig_moran != sig_geary) |>\n  arrange(z_GDPPC) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|County    | GDPPC| z_GDPPC|local Moran |local Geary |\n|:---------|-----:|-------:|:-----------|:-----------|\n|Jianghua  | 15801|   -0.57|FALSE       |TRUE        |\n|Jiangyong | 17168|   -0.48|FALSE       |TRUE        |\n|Hanshou   | 20981|   -0.23|FALSE       |TRUE        |\n|Hengnan   | 21911|   -0.17|FALSE       |TRUE        |\n|Taoyuan   | 22879|   -0.10|FALSE       |TRUE        |\n|Yuanling  | 24194|   -0.01|TRUE        |FALSE       |\n|Changning | 24418|    0.00|FALSE       |TRUE        |\n|Hengshan  | 25172|    0.05|FALSE       |TRUE        |\n|Miluo     | 42497|    1.21|TRUE        |FALSE       |\n|Shaoshan  | 55570|    2.08|FALSE       |TRUE        |\n|Liuyang   | 63118|    2.58|TRUE        |FALSE       |\n\n\n:::\n:::\n\n\n::: {.callout-note collapse=\"false\" title=\"How the code works\"}\nThe block uses two new functions:\n\n```r\nsd(x)                                                     # stats\narrange(.data, ...)                                       # dplyr\n```\n\n- `sd()` returns the standard deviation, so `z` is each county's GDPPC in standard deviations from\n  the provincial mean.\n- `filter(sig_moran != sig_geary)` keeps the counties that are significant under one statistic and\n  not the other.\n- `arrange()` sorts the rows, here from the lowest `z_GDPPC` to the highest.\n:::\n\nOf the eleven:\n\n- **Eight are significant only under local Geary's c.** Six of them have GDPPC within half a\n  standard deviation of the provincial mean, where local Moran's I is small whatever the neighbours'\n  values are. The exceptions are Jianghua in the south and Shaoshan, whose GDPPC is about two\n  standard deviations above the mean.\n- **Three are significant only under local Moran's I.** Liuyang and Miluo lie in or beside the\n  Changsha hot spot, and Yuanling sits close to the provincial mean.\n\n## Gi\\* weights: fixed band versus k nearest neighbours\n\nSection 4.2.1 created `hunan_adw` as chapter 10 does, but chapter 10 never uses it. Section 4.2.2\ncomputed Gi\\* on the fixed distance band only.\n\nFixed and adaptive schemes hold different quantities constant:\n\n- **A fixed distance band fixes the radius.** One radius applies to the whole province, so a county\n  surrounded by large counties has few neighbours, and a county in an area of small counties has\n  many.\n- **An adaptive scheme fixes the number of neighbours.** Every county has the same number, and the\n  radius varies.\n\nThe maps below show this for two counties: Yuanling, a large county in the west, and Shaodong, a\nsmaller one in the centre.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nshow_nb <- function(nb, title) {\n  yl <- which(hunan$County == \"Yuanling\")\n  sd <- which(hunan$County == \"Shaodong\")\n  hunan |>\n    mutate(group = case_when(row_number() %in% nb[[yl]] ~ \"Yuanling and its neighbours\",\n                             row_number() %in% nb[[sd]] ~ \"Shaodong and its neighbours\",\n                             TRUE ~ \"Other\"),\n           group = factor(group, levels = c(\"Yuanling and its neighbours\",\n                                            \"Shaodong and its neighbours\", \"Other\"))) |>\n    tm_shape() +\n    tm_polygons(fill = \"group\",\n                fill.scale = tm_scale_categorical(values = c(\"purple\", \"orange\", \"grey90\")),\n                fill.legend = tm_legend(title = \"\", position = tm_pos_out(\"right\", \"center\"))) +\n    tm_title(title)\n}\n\ntmap_arrange(show_nb(hunan_fdw$nb, \"Fixed band, 62,955 m\"),\n             show_nb(hunan_adw$nb, \"Adaptive, k = 6 plus self\"),\n             asp = 1, ncol = 2)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05_files/figure-html/unnamed-chunk-76-1.png){width=864}\n:::\n:::\n\n\nFor Gi\\*, reported as a z-score, the number of neighbours matters. According to slide 30, a sparse\nneighbourhood produces a large variance of the estimate, which reduces the z-score of Gi\\* towards\nzero, so the county is less likely to reach significance. Slide 35 gives a rule of thumb of about\neight neighbours per feature for a skewed variable.\n\nHow many counties do the two schemes classify differently, and are the differences mainly in one\ndirection?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nHCSA_adw <- hunan_adw |>\n  mutate(gistar = local_gstar_perm(GDPPC, nb, wt, nsim = 999), .before = 1) |>\n  unnest(gistar) |>\n  mutate(HCSA_cluster = case_when(p_sim >= signif ~ \"Insignificant\",\n                                  gi_star > 0 ~ \"Hot spot\",\n                                  TRUE ~ \"Cold spot\"),\n         HCSA_cluster = factor(HCSA_cluster,\n                               levels = c(\"Insignificant\", \"Hot spot\", \"Cold spot\")))\n\ntable(fixed_band = HCSA_fdw$HCSA_cluster,\n      adaptive_k = HCSA_adw$HCSA_cluster)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               adaptive_k\nfixed_band      Insignificant Hot spot Cold spot\n  Insignificant            65        5         6\n  Hot spot                  1        6         0\n  Cold spot                 3        0         2\n```\n\n\n:::\n:::\n\n\nThe two schemes classify 15 of the 88 counties differently, and most of the differences are in one\ndirection:\n\n- **Eleven** counties are significant under the adaptive weights and not under the fixed band.\n- **Four** are significant under the fixed band and not under the adaptive weights.\n\nThe map below is the adaptive counterpart of the map in section 4.2.3.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(HCSA_adw) +\n  tm_polygons(fill = \"HCSA_cluster\",\n              fill.scale = tm_scale_categorical(\n                values = c(\"grey80\", \"red\", \"blue\")),\n              fill.legend = tm_legend(title = \"Gi* cluster\",\n                                      position = tm_pos_out(\"right\", \"center\"))) +\n  tm_borders() +\n  tm_title(\"Hot and cold spots of GDPPC, adaptive k = 6 plus self, p < 0.05\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05_files/figure-html/unnamed-chunk-78-1.png){width=864}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(scheme = c(\"fixed band\", \"adaptive k\"),\n       min_neighbours = c(min(lengths(hunan_fdw$nb)), min(lengths(hunan_adw$nb))),\n       median_neighbours = c(median(lengths(hunan_fdw$nb)), median(lengths(hunan_adw$nb))),\n       max_neighbours = c(max(lengths(hunan_fdw$nb)), max(lengths(hunan_adw$nb)))) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|scheme     | min_neighbours| median_neighbours| max_neighbours|\n|:----------|--------------:|-----------------:|--------------:|\n|fixed band |              2|                 5|              8|\n|adaptive k |              7|                 7|              7|\n\n\n:::\n:::\n\n\nThe neighbour counts explain the direction of the differences:\n\n- **Fixed band: as few as two neighbours.** Some counties have as few as two neighbours, including\n  themselves, which is the sparse case described on slide 30. The median county has five.\n- **Adaptive: seven for every county.** No county has a small neighbourhood because of its location\n  among large counties. Seven is also close to the eight suggested on slide 35.\n\nThe adaptive scheme looks preferable, but a larger count of significant counties does not show that\na scheme is more accurate. A larger neighbourhood alone produces more significant counties, with no\nchange in the data: more neighbours lower the variance of Gi\\* (slide 30), which moves its z-score\naway from zero. The eight neighbours of slide 35 is a guideline. Section 5.7.1 therefore varies `k`\nand checks which classifications change.\n\n### Sensitivity to the number of neighbours\n\nSection 4.2.1 set `k = 6` as chapter 10 does, and the comparison above uses that value alone.\n\nMack and Kam (2018) take a different approach to the same decision in their study of conflict in\nAfrica. Before choosing a weights matrix, they tabulate two quantities under several definitions:\n\n- the number of regions left without neighbours;\n- the average number of links.\n\nThey reject the widest definition because an average of 52 links \"may skew the analysis\".\n\nThe same check can be applied to `k`. A county whose Gi\\* classification is the same under several\nneighbourhood sizes depends less on any one of them.\n\nHow many counties are significant at `k` = 4, 6 and 8, and which keep the same classification under\nall three?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnb_k4 <- include_self(st_knn(st_geometry(hunan), k = 4))\nset.seed(1234)\ngi_k4 <- local_gstar_perm(hunan$GDPPC, nb_k4, st_weights(nb_k4), nsim = 999)\n\nnb_k8 <- include_self(st_knn(st_geometry(hunan), k = 8))\nset.seed(1234)\ngi_k8 <- local_gstar_perm(hunan$GDPPC, nb_k8, st_weights(nb_k8), nsim = 999)\n\nk_compare <- tibble(\n  County = hunan$County,\n  k4 = case_when(gi_k4$p_sim >= signif ~ \"Insignificant\",\n                 gi_k4$gi_star > 0 ~ \"Hot spot\", TRUE ~ \"Cold spot\"),\n  k6 = as.character(HCSA_adw$HCSA_cluster),\n  k8 = case_when(gi_k8$p_sim >= signif ~ \"Insignificant\",\n                 gi_k8$gi_star > 0 ~ \"Hot spot\", TRUE ~ \"Cold spot\"))\n\ntibble(k = c(4, 6, 8),\n       significant_counties = c(sum(k_compare$k4 != \"Insignificant\"),\n                                sum(k_compare$k6 != \"Insignificant\"),\n                                sum(k_compare$k8 != \"Insignificant\"))) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|  k| significant_counties|\n|--:|--------------------:|\n|  4|                   17|\n|  6|                   19|\n|  8|                   25|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nk_compare |>\n  filter(k4 == k6, k6 == k8, k4 != \"Insignificant\") |>\n  select(County, class = k6) |>\n  arrange(class, County) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|County     |class     |\n|:----------|:---------|\n|Jingzhou   |Cold spot |\n|Suining    |Cold spot |\n|Wugang     |Cold spot |\n|Xinning    |Cold spot |\n|Changsha   |Hot spot  |\n|Liuyang    |Hot spot  |\n|Pingjiang  |Hot spot  |\n|Shaoshan   |Hot spot  |\n|Taojiang   |Hot spot  |\n|Wangcheng  |Hot spot  |\n|Xiangxiang |Hot spot  |\n|Xiangyin   |Hot spot  |\n\n\n:::\n:::\n\n\nThe number of significant counties rises with `k`, from 17 at `k = 4` to 25 at `k = 8`, as expected\nfrom slide 30: a larger neighbourhood reduces the variance of Gi\\* and moves its z-score away from\nzero. Twelve counties keep the same classification under all three values:\n\n- **eight hot spots** around Changsha;\n- **four cold spots** in the south west: Jingzhou, Suining, Wugang and Xinning. Wugang is also the\n  county that meets the Bonferroni bound in section 5.3.3.\n\nThe classification of the other significant counties depends on `k`.\n\n## Gi and local Moran's I under permutation\n\nSection 4.1 produced a LISA map from the local Moran and section 4.2 a hot and cold spot map from\nGi\\*. Chapter 10 presents the two as separate analyses.\n\nAnselin (1995) argues that the two share one permutation test:\n\n1. Under conditional permutation, only the numerator of each statistic varies.\n2. The varying term is the same in both statistics.\n3. Therefore:\n\n   > the randomization method applied to [the local Moran] will yield the same empirical reference\n   > distribution as when applied to the Getis and Ord Gi and Gi\\* statistics. Hence, inference\n   > based on this nonparametric approach will be identical for the two statistics.\n\nOn the Queen contiguity weights of section 4.1.1, do Gi and Gi\\* give the same permutation p-values\nas the local Moran? A second run of Gi\\* with a different random seed shows how much two runs differ\nby chance alone.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(7); li  <- local_moran(hunan$GDPPC, wm_q$nb, wm_q$wt, nsim = 9999)\nset.seed(7); gi  <- local_g_perm(hunan$GDPPC, wm_q$nb, wm_q$wt, nsim = 9999)\nset.seed(7); gs  <- local_gstar_perm(hunan$GDPPC, wm_q$nb, wm_q$wt, nsim = 9999)\nset.seed(8); gs2 <- local_gstar_perm(hunan$GDPPC, wm_q$nb, wm_q$wt, nsim = 9999)\n\ntibble(comparison = c(\"Gi against local Moran\",\n                      \"Gi* against local Moran\",\n                      \"Gi* against Gi*, different random seed\"),\n       largest_difference = c(max(abs(gi$p_sim - li$p_ii_sim)),\n                              max(abs(gs$p_sim - li$p_ii_sim)),\n                              max(abs(gs$p_sim - gs2$p_sim))),\n       counties_significant_in_one_only = c(\n         sum((gi$p_sim < signif) != (li$p_ii_sim < signif)),\n         sum((gs$p_sim < signif) != (li$p_ii_sim < signif)),\n         sum((gs$p_sim < signif) != (gs2$p_sim < signif)))) |>\n  kable(digits = 4)\n```\n\n::: {.cell-output-display}\n\n\n|comparison                             | largest_difference| counties_significant_in_one_only|\n|:--------------------------------------|------------------:|--------------------------------:|\n|Gi against local Moran                 |             0.0002|                                0|\n|Gi* against local Moran                |             0.0328|                                1|\n|Gi* against Gi*, different random seed |             0.0290|                                0|\n\n\n:::\n:::\n\n\n::: {.callout-note collapse=\"false\" title=\"How the code works\"}\nThe block uses one new function:\n\n```r\nlocal_g_perm(x, nb, wt, nsim = 499, alternative = \"two.sided\")   # sfdep\n```\n\n- `local_g_perm()` computes Gi, which excludes the county itself, where `local_gstar_perm()`\n  (section 4.2.2) computes Gi\\*, which includes it. All three statistics use the Queen contiguity\n  weights of section 4.1.1 and 9,999 permutations.\n- `set.seed()` (section 3.3.2) before each call starts every statistic from the same random numbers,\n  except the second Gi\\* run, which uses a different seed to measure simulation error.\n- `abs()` takes absolute differences, and `max()` keeps the largest across the 88 counties.\n:::\n\n- **Gi agrees with the local Moran to within 0.0002**, one step of the p-value grid at 9,999\n  permutations.\n- **Gi\\* differs from the local Moran by up to 0.033**, but two runs of Gi\\* differ from each other\n  by a similar amount, 0.029.\n\nThe difference between Gi\\* and the local Moran is therefore simulation error, and Anselin's (1995)\nclaim holds for both Gi and Gi\\* on these data.\n\nGi\\* and the local Moran also reach the same decision at p < 0.05 for every county except Yongshun,\nwhose p-value is 0.051 under the local Moran and 0.047 under Gi\\*. A difference of that size lies\nwithin the simulation error shown in the table.\n\nWhere Gi\\* and the local Moran give the same p-value, they differ in what a significant result says\nabout the county:\n\n- **The local Moran identifies similarity and outliers.** A significant positive local Moran\n  indicates that the county and its neighbours have similar values, without indicating whether\n  those values are high or low. The local Moran also identifies the High-Low and Low-High outliers,\n  which Gi\\* does not.\n- **Gi\\* indicates whether the values are high or low.** A positive value marks a cluster of high\n  values and a negative value a cluster of low values (Anselin 1995).\n\nThis is the sense of the recommendation by Getis and Ord (1992) in section 5.4 that \"any\ntest for spatial association should use both types of statistics\".\n\nOn the same weights, the permutation tests behind chapter 10's LISA map and hot and cold spot map\nwould give the same p-values. The two maps differ for two reasons: they use different weights, Queen\ncontiguity against a fixed distance band, and they classify the significant counties differently.\n\n# Reflection\n\nChapter 10 frames the analysis as three questions (section 10.2.1). The answers on this page are:\n\n- **Is development evenly distributed across the province?** No. GDPPC ranges from 8,497 yuan in\n  Guidong to 88,656 yuan in Changsha.\n- **Is there sign of spatial clustering?** Yes. Moran's I is 0.301 and Geary's C is 0.691, both\n  significant under the analytical and the permutation tests (sections 3.3 and 3.4).\n- **Where are the clusters?** A cluster of high GDPPC around Changsha in the north east and a\n  cluster of low GDPPC in the west (sections 4.1.5 and 4.2.3). After correction for 88 tests, three\n  counties remain significant, two of them in the western cluster (section 5.3.3).\n\nChapters 9 and 10 address the question left open by Exercise 4. In the lag scatterplot, the positive\nslope reflects significant positive spatial autocorrelation in GDPPC (Moran's I = 0.301, permutation\np = 0.001), and Geary's C, on its inverted scale, gives a consistent result. Global G indicates that\nthe association is dominated by high values.\n\nThe local statistics locate the clusters. Sixteen counties are significant: the High-High group\ncomprises Changsha and its surroundings, and the Low-Low group is in the west. Gi\\* on the same data\nidentifies a hot spot in the same area. Under every weighting scheme tested here, the division\nbetween high and low GDPPC lies between the north east and the west.\n\nThese methods are less independent of one another than their number suggests. Global Moran's I,\nglobal G and the LISA map are all computed from the same 88 values, and in section 5.8 I found that\nGi, Gi\\* and the local Moran are the same permutation test when the weights are the same. The\ncomparisons of weighting schemes in sections 5.7 and 5.7.1 are the only places where the location\nof the division between high and low GDPPC was tested against an alternative.\n\nThe more specific results depended on choices of method. With the data held the same:\n\n- changing only the p-value column changed the count of significant counties from 13 to 16;\n- changing from local Moran to local Geary changed it from 16 to 21;\n- 15 counties were classified differently under a fixed and an adaptive Gi\\* neighbourhood.\n\nThe multiple-comparisons result in section 5.3, that no county remains significant after correction\nat 999 permutations, changed how I would report a LISA map, and reading the papers changed my view\nof it twice.\n\nIn my first draft of that section I attributed to Anselin the argument that a correction does not\napply directly to a LISA map, because the tests are not independent. His paper does not make that\nargument. He writes that \"it is obvious that some correction to the individual significance levels\nis needed\" and disputes only whether m should equal n, then applies m = n in his own worked example.\nOrd and Getis recommend the Bonferroni bound and record a referee's objection that it may be unduly\nconservative when n is large. Both assigned papers treat the correction as necessary.\n\nMy second change of view came from the number of permutations in Anselin's worked example, 9,999. He\ngives no reason for the number, so the inference that follows is mine. A corrected bound cannot be\nmet by a p-value whose minimum exceeds it, and the minimum depends on `nsim`. I had treated the\nnumber of simulations as a setting for precision, and I now choose it after deciding on the\ncorrection.\n\nTwo of the readings contain claims that I could test directly. Getis and Ord state that G is not\nlocation-invariant. Adding 100,000 to GDPPC changed the p-value of G from 0.0012 to 0.19 and left\nMoran's I unchanged. A G result is thus a statement about the variable on the scale on which it was\nmeasured. Anselin states that permutation inference is identical for the local Moran, Gi and Gi\\*.\nMy first test appeared to show the claim failing for Gi\\*. The gap turned out to be the same size as\nthe gap between two runs of Gi\\* with different random seeds, so it was simulation error, and the\nclaim holds for both.\n\nOrd and Getis's simulation results determined my choice of `p_ii_sim` over `p_ii` in section 5.2.\nBoth of their patterns (ii) and (iii), a skewed variable and few neighbours, apply to these data.\nFor the counties of most interest on the map, the normal-approximation p-value is least reliable.\nSection 5.7 is also affected by these patterns: the adaptive scheme gives every county seven\nneighbours and removes the few-neighbour case of pattern (iii).\n\nMy main practical difficulty in this exercise was the same as in Exercise 4. Three calls in chapter\n10 ran without error and without the effect that the surrounding text described:\n\n- `nsim = 99` ran 8,712 permutations whose rank-based p-value was then not used;\n- `hunan_adw` was created and not used;\n- `signif` was assigned and not used.\n\nI found them by comparing what each call returned with what the surrounding text said it did.\n\nI first left the choice of `k` as a rule of thumb and then tested it, following the tabulation in\nMack and Kam (2018). The count of significant counties depends on `k`, from 17 at `k = 4` to 25 at\n`k = 8`, while twelve counties keep the same classification under every value tested. I would\nreport those twelve as the hot and cold spots of this map and treat the remainder as dependent on\nthe neighbourhood size.\n\nA second open question concerns change over time. All results on this page are for a single year,\n2012, and the division within the province is treated as fixed. Emerging hot spot analysis, on\nslides 37 to 43, would test whether the hot spot around Changsha is intensifying and whether GDPPC\nin the west is converging towards that of the north east. It needs a value for every county in every\nperiod, and the Lesson 5 material provides one year.\n\n# References\n\nCourse materials:\n\n- Kam, T.S. (2026). *Lesson 5: Global and Local Measures of Spatial Association*. ISSS626\n  Geospatial Analytics and Applications, SMU. Slide deck dated 20 September 2026.\n- Kam, T.S. (2026). [*R for Geospatial Data Science and Analytics*, Chapter 9: Global Measures of\n  Spatial Autocorrelation](https://r4gdsa.netlify.app/chap09.html).\n- Kam, T.S. (2026). [*R for Geospatial Data Science and Analytics*, Chapter 10: Local Measures of\n  Spatial Autocorrelation](https://r4gdsa.netlify.app/chap10.html).\n\nAssigned self-reading:\n\n- Moran, P.A.P. (1950). \"Notes on Continuous Stochastic Phenomena\". *Biometrika*, 37(1/2), 17-23.\n- Geary, R.C. (1954). \"The Contiguity Ratio and Statistical Mapping\". *The Incorporated\n  Statistician*, 5(3), 115-127 and 129-146.\n- Getis, A. and Ord, J.K. (1992). \"The Analysis of Spatial Association by Use of Distance\n  Statistics\". *Geographical Analysis*, 24(3), 189-206.\n- Anselin, L. (1995). \"Local Indicators of Spatial Association - LISA\". *Geographical Analysis*,\n  27(2), 93-115.\n- Ord, J.K. and Getis, A. (1995). \"Local Spatial Autocorrelation Statistics: Distributional Issues\n  and an Application\". *Geographical Analysis*, 27(4), 286-306.\n\nReferences listed in the Lesson 5 outline:\n\n- Anselin, L. (1996). \"The Moran Scatterplot as an ESDA Tool to Assess Local Instability in Spatial\n  Association\". In Fischer, M., Scholten, H.J. and Unwin, D. (eds), *Spatial Analytical\n  Perspectives on GIS*. Taylor and Francis, 111-125.\n\n- Getis, A. (2010). \"B.3 Spatial Autocorrelation\". In Fischer, M.M. and Getis, A. (eds), *Handbook\n  of Applied Spatial Analysis: Software Tools, Methods and Applications*. Springer, 255-278.\n\n- Mack, Z.W.V. and Kam, T.S. (2018). \"Is There Space for Violence?: A Data-driven Approach to the\n  Exploration of Spatial-Temporal Dimensions of Conflict\". *Proceedings of the 2nd ACM SIGSPATIAL\n  Workshop on Geospatial Humanities*, Seattle.\n\nSoftware:\n\n- Bivand, R. (2022). \"R Packages for Analyzing Spatial Data: A Comparative Case Study with\n  Areal Data\". *Geographical Analysis*, 54(3), 488-518. The `spdep` reference.\n- Parry, J. (2023). *sfdep: Spatial Neighbors and Statistics*. R package version 0.2.5.\n\n# About this document\n\nWritten and executed in Quarto with R 4.6.1, `spdep` 1.4.2,\n`sfdep` 0.2.5 and `tmap` 4.4.1. All figures and tables\nare generated at render time from the data in `data/`, so nothing on this page is pasted in.\n\nI used AI assistance while working out the approach and the extensions in Part 3. The analysis was\nrun and checked by me.\n",
    "supporting": [
      "Hands-on_Ex05_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}