{
  "hash": "77501b66a72dba67b1868257c4c8938d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Hands-on Exercise 2\"\nsubtitle: \"Spatial Point Patterns Analysis with R\"\nauthor: \"An Loc\"\ndate: \"last-modified\"\ndate-format: \"D MMM YYYY\"\nformat:\n  html:\n    toc: true\n    toc-depth: 4\n    toc-expand: true\n    code-fold: false\n    code-copy: true\n    fig-width: 9\n    fig-height: 7\nexecute:\n  echo: true\n  eval: true\n  warning: false\n  message: false\n  freeze: true\n---\n\n# Overview\n\nThis exercise applies **Spatial Point Patterns Analysis (SPPA)** to the locations of childcare\ncentres in Singapore. It follows the two chapters assigned for Lesson 2: r4gdsa Chapter 4 and\nChapter 5. Where I write \"the chapters\" below, I mean those two.\n\n**Part 1** reproduces the **first-order** methods from r4gdsa Chapter 4: methods that measure\nthe *intensity* of points: the Clark–Evans nearest-neighbour index and kernel density\nestimation, including bandwidth selection, kernel choice, and fixed versus adaptive bandwidth.\n\n**Part 2** reproduces the **second-order** methods from Chapter 5: methods that measure the\n*spatial dependence* between points: the G, F, K and L functions, each tested against Complete\nSpatial Randomness (CSR) using Monte Carlo envelopes, for two contrasting planning areas.\n\n**Part 3** is where most of my time went. It is a working diary: the choices the chapters\nleave to the software, how far the conclusions move when those choices change, what the\nweek's readings add when applied to this data, and where the analysis runs out.\n\n::: {.callout-note appearance=\"simple\"}\n\n## Reference\n\nr4gdsa [Chapter 4: First-order Spatial Point Patterns Analysis\nMethods](https://r4gdsa.netlify.app/chap04.html)\nand [Chapter 5: 2nd Order Spatial Point Patterns Analysis\nMethods](https://r4gdsa.netlify.app/chap05.html).\n:::\n\n# Getting started\n\n## Packages\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(sf, spatstat, terra, tmap, tidyverse)\n```\n:::\n\n\n## The data\n\nTwo datasets are used. Both come from Data.gov.sg, with one caveat to state up front:\n\n- **Childcare centres**: the published table *Listing of Centre Services* is an address list\n  with **no coordinates**, so it cannot be mapped as it stands. The layer used here is\n  `ChildCareServices.kml`, the geocoded version distributed with the chapters, produced by the\n  OneMap workflow Kam demonstrated in Lesson 1.\n- **Planning subzones**: URA 2019 Master Plan subzone boundaries (no sea). This is the same\n  file used in Hands-on Exercise 1, so the wrangling carries straight over.\n\nThe KML stores points as XYZ with a zero Z, which spatstat will not accept, so `st_zm()` drops\nthe third dimension. Both layers are then transformed to SVY21 (EPSG:3414) so that every\ndistance, area and bandwidth below is in metres rather than degrees.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchildcare <- st_read(\"data/geospatial/ChildCareServices.kml\", quiet = TRUE) |>\n  st_zm(drop = TRUE, what = \"ZM\") |>\n  st_transform(3414)\n\nmpsz <- st_read(\"data/geospatial/MasterPlan2019SubzoneBoundaryNoSea.geojson\",\n                quiet = TRUE) |>\n  st_transform(3414)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nst_crs(childcare)$epsg\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3414\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnrow(childcare)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1925\n```\n\n\n:::\n:::\n\n\n# Part 1: First-order methods\n\nFirst-order methods ask **how dense** the points are and **whether that density varies**\nacross space. Two families are covered: the nearest-neighbour approach (Clark–Evans) and\ndensity estimation (KDE).\n\n## From sf to a point pattern\n\nspatstat works with its own object classes: `ppp` for the point pattern and `owin` for the\nobservation window. An `sf` point layer becomes a `ppp` in one step.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchildcare_ppp <- as.ppp(childcare)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(childcare_ppp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMarked planar point pattern:  1925 points\nAverage intensity 2.417323e-06 points per square unit\n\nCoordinates are given to 11 decimal places\n\nMark variables: Name, Description\nSummary:\n        Name         Description  \n Length   :1925   Length   :1925  \n N.unique :1925   N.unique :1925  \n N.blank  :   0   N.blank  :   0  \n Min.nchar:   5   Min.nchar:1068  \n Max.nchar:   8   Max.nchar:1171  \n\nWindow: rectangle = [11810.03, 45404.24] x [25596.33, 49300.88] units\n                    (33590 x 23700 units)\nWindow area = 796335000 square units\n```\n\n\n:::\n:::\n\n\nThe pattern has 1925 points. The observation window is the rectangle enclosing\nthe points,\n**not yet** the study area. That matters, because every first-order measure is computed\nrelative to the window.\n\n## Defining the study area\n\nThe window should be the area we actually want to make claims about. For a national-level\nanalysis, that is the Singapore mainland boundary, which I build by dissolving the subzone\nboundaries.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsg_boundary <- st_union(mpsz)\nsg_owin <- as.owin(sg_boundary)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(sg_owin)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex02_files/figure-html/unnamed-chunk-8-1.png){width=864}\n:::\n:::\n\n\nNow the points are clipped to the window. Any point outside (there should be none in this\ncase) would be dropped here.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchildcareSG_ppp <- childcare_ppp[sg_owin]\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchildcareSG_ppp$n\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1925\n```\n\n\n:::\n:::\n\n\n## Clark–Evans nearest-neighbour test\n\nClark and Evans (1954) compare the mean observed nearest-neighbour distance against what would\nbe expected under **Complete Spatial Randomness (CSR)**. The index *R* is the ratio of the two:\n\n- *R* < 1: points are closer than random, so **clustered**\n- *R* ≈ 1: consistent with CSR\n- *R* > 1: points are further apart than random, so **regular/dispersed**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclarkevans.test(childcareSG_ppp,\n                correction = \"none\",\n                clipregion = sg_owin,\n                alternative = \"clustered\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tClark-Evans test\n\tNo edge correction\n\tZ-test\n\ndata:  childcareSG_ppp\nR = 0.49444, p-value < 2.2e-16\nalternative hypothesis: clustered (R < 1)\n```\n\n\n:::\n:::\n\n\nThe test can also be run as a Monte Carlo simulation rather than the analytic normal\napproximation, which is slower but does not rely on distributional assumptions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclarkevans.test(childcareSG_ppp,\n                correction = \"none\",\n                clipregion = sg_owin,\n                alternative = \"clustered\",\n                method = \"MonteCarlo\",\n                nsim = 999)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tClark-Evans test\n\tNo edge correction\n\tMonte Carlo test based on 999 simulations of CSR with fixed n\n\ndata:  childcareSG_ppp\nR = 0.49444, p-value = 0.001\nalternative hypothesis: clustered (R < 1)\n```\n\n\n:::\n:::\n\n\n## Kernel density estimation\n\nThe Clark–Evans index collapses the whole pattern into one number. KDE keeps the geography:\nit spreads a kernel over each point and sums the surfaces, producing a continuous density\nfield that shows *where* intensity is high and low.\n\n### Automatic bandwidth selection\n\nThe bandwidth (the `sigma` of the kernel) controls how far each point's influence extends,\nand it drives the appearance of the result more than anything else in KDE. The package offers\nseveral automatic selectors; the default is `bw.diggle`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkde_SG_diggle <- density(childcareSG_ppp,\n                         sigma = bw.diggle,\n                         edge = TRUE,\n                         kernel = \"gaussian\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(kde_SG_diggle)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex02_files/figure-html/unnamed-chunk-14-1.png){width=864}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(kde_SG_diggle)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nreal-valued pixel image\n128 x 128 pixel array (ny, nx)\nenclosing rectangle: [2667.538, 56396.44] x [15748.72, 50256.33] units\ndimensions of each pixel: 420 x 269.5907 units\nImage is defined on a subset of the rectangular grid\nSubset area = 784443200.265293 square units\nSubset area fraction = 0.423\nPixel values (inside window):\n\trange = [-9.66262e-21, 3.727443e-05]\n\tintegral = 1927.013\n\tmean = 2.456536e-06\n```\n\n\n:::\n:::\n\n\nThe densities here are in **per square metre** units, which are awkward to read (the integral\nof the surface is the number of points). Rescaling the pattern to kilometres makes the values\ninterpretable as centres per square kilometre.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchildcareSG_ppp_km <- rescale.ppp(childcareSG_ppp, 1000, \"km\")\nkde_childcareSG_km <- density(childcareSG_ppp_km,\n                              sigma = bw.diggle,\n                              edge = TRUE,\n                              kernel = \"gaussian\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(kde_childcareSG_km)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nreal-valued pixel image\n128 x 128 pixel array (ny, nx)\nenclosing rectangle: [2.667538, 56.39644] x [15.74872, 50.25633] km\ndimensions of each pixel: 0.42 x 0.2695907 km\nImage is defined on a subset of the rectangular grid\nSubset area = 784.443200265292 square km\nSubset area fraction = 0.423\nPixel values (inside window):\n\trange = [-1.092987e-14, 37.27443]\n\tintegral = 1927.013\n\tmean = 2.456536\n```\n\n\n:::\n:::\n\n\n### Comparing the selectors\n\nThe four common selectors optimise different criteria, so they return different bandwidths.\nRather than accept the default silently, I compare them.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbw.CvL(childcareSG_ppp_km)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   sigma \n4.543204 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbw.scott(childcareSG_ppp_km)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n sigma.x  sigma.y \n2.159749 1.396455 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbw.ppl(childcareSG_ppp_km)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    sigma \n0.3897071 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbw.diggle(childcareSG_ppp_km)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    sigma \n0.2954419 \n```\n\n\n:::\n:::\n\n\nThere is an order-of-magnitude spread here, from about 0.39 km (`bw.ppl`) to 4.54 km\n(`bw.CvL`). Since all four are defensible choices, the map itself is only as settled as the\nselector behind it. Part 3 works through what that does to the surface.\n\n`bw.scott` stands out here, because it is the rule Donthu and Rust use. They pick the\nbandwidth that would be optimal if the data were bivariate normal, while admitting \"we have no\nreason to actually expect the underlying distribution to be bivariate normal\". On this data\nthat rule returns about 2.2 km against `bw.diggle`'s 0.30 km, roughly seven times wider. Since\ntheir paper uses the density surface to choose a store location, the two rules would suggest\nvisibly different catchments from identical data. The 1989 advice is not wrong, but it is much\nsmoother than a modern\ncross-validation selector, and a siting decision taken from one surface rather than the other\nwould land in a different place.\n\n### The kernel function\n\nThe kernel is the shape of the influence region. spatstat's default is Gaussian; quartic and\nEpanechnikov kernels are common alternatives. At the same bandwidth they produce broadly\nsimilar surfaces, differing mostly in how sharply the tails fall off.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(1, 2))\nplot(density(childcareSG_ppp_km, sigma = 0.296, kernel = \"gaussian\"), main = \"Gaussian\")\nplot(density(childcareSG_ppp_km, sigma = 0.296, kernel = \"quartic\"), main = \"Quartic\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex02_files/figure-html/unnamed-chunk-22-1.png){width=864}\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 1))\n```\n:::\n\n\n### Fixed versus adaptive bandwidth\n\nA fixed bandwidth applies the same smoothing radius everywhere. An **adaptive** bandwidth\nshrinks the radius where points are dense and widens it where they are sparse, which is\nusually the better assumption for a service like childcare whose supply follows population\ndensity closely.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkde_fb <- density(childcareSG_ppp_km, sigma = 0.6, edge = TRUE, kernel = \"gaussian\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkde_ab <- adaptive.density(childcareSG_ppp_km, method = \"kernel\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(1, 2))\nplot(kde_fb, main = \"Fixed bandwidth (0.6 km)\")\nplot(kde_ab, main = \"Adaptive bandwidth\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex02_files/figure-html/unnamed-chunk-25-1.png){width=864}\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 1))\n```\n:::\n\n\n## A cartographic KDE map\n\nThe spatstat density object is a pixel image. To map it properly I convert it to a raster,\nassign the correct CRS, and map with tmap.\n\nA unit note, because it is easy to get wrong: the density computed on the *metre*-based\npattern is in **centres per square metre**, which is awkward to read. I compute it in metres\n(so the raster extent is in metres and the CRS is honest) and multiply the values by 10⁶ to\ndisplay them as centres per km².\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkde_terra <- rast(density(childcareSG_ppp, sigma = bw.diggle, edge = TRUE)) * 1e6\ncrs(kde_terra) <- \"EPSG:3414\"\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkde_terra\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nclass       : SpatRaster\nsize        : 128, 128, 1  (nrow, ncol, nlyr)\nresolution  : 419.757, 269.5907  (x, y)\nextent      : 2667.538, 56396.44, 15748.72, 50256.33  (xmin, xmax, ymin, ymax)\ncoord. ref. : SVY21 / Singapore TM (EPSG:3414)\nsource(s)   : memory\nname        :     lyr.1\nmin value   :        -0\nmax value   : 37.274432\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(mpsz) +\n  tm_borders(col = \"grey60\", lwd = 0.3) +\n  tm_shape(kde_terra) +\n  tm_raster(col.scale = tm_scale_continuous(values = \"viridis\"),\n            col.legend = tm_legend(title = \"Centres per km²\",\n                                   title.size = 0.8,\n                                   text.size = 0.7,\n                                   position = tm_pos_in(\"right\", \"bottom\"),\n                                   bg.color = \"white\",\n                                   bg.alpha = 0.7,\n                                   frame = TRUE)) +\n  tm_graticules(lines = FALSE) +\n  tm_layout(legend.frame = TRUE) +\n  tm_compass(position = tm_pos_in(\"left\", \"top\")) +\n  tm_scalebar(position = tm_pos_in(\"left\", \"bottom\"))\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex02_files/figure-html/unnamed-chunk-28-1.png){width=864}\n:::\n:::\n\n\n## Analysis by planning area\n\nNational-level statistics hide a lot of local variation. The chapters repeat the Clark–Evans\ntest and KDE within individual planning areas. I use the four areas the book uses (Punggol,\nTampines, Choa Chu Kang and Jurong West) because they are demographically and physically\ndifferent from each other.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npg <- mpsz |> filter(PLN_AREA_N == \"PUNGGOL\")\ntm <- mpsz |> filter(PLN_AREA_N == \"TAMPINES\")\nck <- mpsz |> filter(PLN_AREA_N == \"CHOA CHU KANG\")\njw <- mpsz |> filter(PLN_AREA_N == \"JURONG WEST\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchildcare_pg_ppp <- childcare_ppp[as.owin(pg)]\nchildcare_tm_ppp <- childcare_ppp[as.owin(tm)]\nchildcare_ck_ppp <- childcare_ppp[as.owin(ck)]\nchildcare_jw_ppp <- childcare_ppp[as.owin(jw)]\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(punggol = childcare_pg_ppp$n, tampines = childcare_tm_ppp$n,\n  choa_chu_kang = childcare_ck_ppp$n, jurong_west = childcare_jw_ppp$n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      punggol      tampines choa_chu_kang   jurong_west \n           72           117            74           110 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclarkevans.test(childcare_ck_ppp, correction = \"none\", alternative = \"two.sided\", nsim = 999)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tClark-Evans test\n\tNo edge correction\n\tZ-test\n\ndata:  childcare_ck_ppp\nR = 0.84097, p-value = 0.008866\nalternative hypothesis: two-sided\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclarkevans.test(childcare_tm_ppp, correction = \"none\", alternative = \"two.sided\", nsim = 999)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tClark-Evans test\n\tNo edge correction\n\tZ-test\n\ndata:  childcare_tm_ppp\nR = 0.66817, p-value = 6.58e-12\nalternative hypothesis: two-sided\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(2, 2))\nplot(density(rescale.ppp(childcare_pg_ppp, 1000, \"km\"), sigma = bw.diggle), main = \"Punggol\")\nplot(density(rescale.ppp(childcare_tm_ppp, 1000, \"km\"), sigma = bw.diggle), main = \"Tampines\")\nplot(density(rescale.ppp(childcare_ck_ppp, 1000, \"km\"), sigma = bw.diggle), main = \"Choa Chu Kang\")\nplot(density(rescale.ppp(childcare_jw_ppp, 1000, \"km\"), sigma = bw.diggle), main = \"Jurong West\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex02_files/figure-html/unnamed-chunk-34-1.png){width=864}\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 1))\n```\n:::\n\n\n# Part 2: Second-order methods\n\nSecond-order methods ask **how the points are arranged relative to each other**: clustered,\ndispersed or random, and at what distance. Where Part 1 says \"intensity is high here\",\nPart 2 says \"points attract or repel each other at these scales\".\n\nFor each function I compare **Choa Chu Kang** (a mature HDB town with a distinct centre) and\n**Tampines** (a large, densely built town), which lets the same statistic run against two\nquite different urban layouts.\n\n## The G function\n\nThe G function is the cumulative distribution of nearest-neighbour distances: *G(r)* is the\nprobability that a random point has a neighbour within distance *r*. If points cluster, *G(r)*\nrises quickly for small *r*.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nG_ck <- Gest(childcare_ck_ppp, correction = \"border\")\nplot(G_ck, xlim = c(0, 500))\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex02_files/figure-html/unnamed-chunk-35-1.png){width=864}\n:::\n:::\n\n\nTesting against CSR requires a Monte Carlo **envelope**: the function is recomputed on many\nsimulated CSR patterns, and the observed curve is compared against the simulated band.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nG_ck.csr <- envelope(childcare_ck_ppp, Gest, nsim = 999)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGenerating 999 simulated realisations of CSR  ...\n1, 2, 3, ......10.........20.........30.........40.........50.........60..\n.......70.........80.........90.........100.........110.........120.........130\n.........140.........150.........160.........170.........180.........190........\n.200.........210.........220.........230.........240.........250.........260......\n...270.........280.........290.........300.........310.........320.........330....\n.....340.........350.........360.........370.........380.........390.........400..\n.......410.........420.........430.........440.........450.........460.........470\n.........480.........490.........500.........510.........520.........530........\n.540.........550.........560.........570.........580.........590.........600......\n...610.........620.........630.........640.........650.........660.........670....\n.....680.........690.........700.........710.........720.........730.........740..\n.......750.........760.........770.........780.........790.........800.........810\n.........820.........830.........840.........850.........860.........870........\n.880.........890.........900.........910.........920.........930.........940......\n...950.........960.........970.........980.........990........\n999.\n\nDone.\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(G_ck.csr)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex02_files/figure-html/unnamed-chunk-36-1.png){width=864}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nG_tm <- Gest(childcare_tm_ppp, correction = \"best\")\nG_tm.csr <- envelope(childcare_tm_ppp, Gest, correction = \"all\", nsim = 999)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGenerating 999 simulated realisations of CSR  ...\n1, 2, 3, ......10.........20.........30.........40.........50.........60..\n.......70.........80.........90.........100.........110.........120.........130\n.........140.........150.........160.........170.........180.........190........\n.200.........210.........220.........230.........240.........250.........260......\n...270.........280.........290.........300.........310.........320.........330....\n.....340.........350.........360.........370.........380.........390.........400..\n.......410.........420.........430.........440.........450.........460.........470\n.........480.........490.........500.........510.........520.........530........\n.540.........550.........560.........570.........580.........590.........600......\n...610.........620.........630.........640.........650.........660.........670....\n.....680.........690.........700.........710.........720.........730.........740..\n.......750.........760.........770.........780.........790.........800.........810\n.........820.........830.........840.........850.........860.........870........\n.880.........890.........900.........910.........920.........930.........940......\n...950.........960.........970.........980.........990........\n999.\n\nDone.\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(G_tm.csr)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex02_files/figure-html/unnamed-chunk-37-1.png){width=864}\n:::\n:::\n\n\n## The F function\n\nThe F function is the complement view: the distance from **arbitrary locations** to the\nnearest point, not from points to points. Because it measures empty space rather than\nneighbour distances, it responds to gaps in the pattern where G responds to close pairs.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nF_ck.csr <- envelope(childcare_ck_ppp, Fest, nsim = 999)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGenerating 999 simulated realisations of CSR  ...\n1, 2, 3, ......10.........20.........30.........40.........50.........60..\n.......70.........80.........90.........100.........110.........120.........130\n.........140.........150.........160.........170.........180.........190........\n.200.........210.........220.........230.........240.........250.........260......\n...270.........280.........290.........300.........310.........320.........330....\n.....340.........350.........360.........370.........380.........390.........400..\n.......410.........420.........430.........440.........450.........460.........470\n.........480.........490.........500.........510.........520.........530........\n.540.........550.........560.........570.........580.........590.........600......\n...610.........620.........630.........640.........650.........660.........670....\n.....680.........690.........700.........710.........720.........730.........740..\n.......750.........760.........770.........780.........790.........800.........810\n.........820.........830.........840.........850.........860.........870........\n.880.........890.........900.........910.........920.........930.........940......\n...950.........960.........970.........980.........990........\n999.\n\nDone.\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(F_ck.csr)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex02_files/figure-html/unnamed-chunk-38-1.png){width=864}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nF_tm.csr <- envelope(childcare_tm_ppp, Fest, correction = \"all\", nsim = 999)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGenerating 999 simulated realisations of CSR  ...\n1, 2, 3, ......10.........20.........30.........40.........50.........60..\n.......70.........80.........90.........100.........110.........120.........130\n.........140.........150.........160.........170.........180.........190........\n.200.........210.........220.........230.........240.........250.........260......\n...270.........280.........290.........300.........310.........320.........330....\n.....340.........350.........360.........370.........380.........390.........400..\n.......410.........420.........430.........440.........450.........460.........470\n.........480.........490.........500.........510.........520.........530........\n.540.........550.........560.........570.........580.........590.........600......\n...610.........620.........630.........640.........650.........660.........670....\n.....680.........690.........700.........710.........720.........730.........740..\n.......750.........760.........770.........780.........790.........800.........810\n.........820.........830.........840.........850.........860.........870........\n.880.........890.........900.........910.........920.........930.........940......\n...950.........960.........970.........980.........990........\n999.\n\nDone.\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(F_tm.csr)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex02_files/figure-html/unnamed-chunk-39-1.png){width=864}\n:::\n:::\n\n\n## The K function\n\nRipley's K is the expected number of other points within distance *r*, standardised by\nintensity. It summarises dependence across *all* distances, not just nearest neighbours. Under\nCSR, *K(r) = πr²*. The plot below uses the variance-stabilised form *K(r) − πr²* so the CSR\nbaseline is the horizontal line at zero.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nK_ck <- Kest(childcare_ck_ppp, correction = \"Ripley\")\nplot(K_ck, . - r ~ r, ylab = \"K(d) - r\", xlab = \"d (m)\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex02_files/figure-html/unnamed-chunk-40-1.png){width=864}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nK_ck.csr <- envelope(childcare_ck_ppp, Kest, nsim = 99, rank = 1, glocal = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGenerating 99 simulated realisations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,\n41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,\n61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,\n81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, \n99.\n\nDone.\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(K_ck.csr, . - r ~ r, xlab = \"d\", ylab = \"K(d) - r\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex02_files/figure-html/unnamed-chunk-41-1.png){width=864}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nK_tm <- Kest(childcare_tm_ppp, correction = \"Ripley\")\nK_tm.csr <- envelope(childcare_tm_ppp, Kest, nsim = 99, rank = 1, glocal = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGenerating 99 simulated realisations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,\n41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,\n61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,\n81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, \n99.\n\nDone.\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(K_tm.csr, . - r ~ r, xlab = \"d\", ylab = \"K(d) - r\", xlim = c(0, 500))\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex02_files/figure-html/unnamed-chunk-42-1.png){width=864}\n:::\n:::\n\n\n## The L function\n\nThe L function is the variance-stabilised transform of K: *L(r) = √(K(r)/π) − r*. Under CSR,\n*L(r) = 0* at all distances. Positive *L* indicates clustering; negative *L* indicates\nregularity. The transform makes deviations from CSR easier to read at all scales.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nL_ck.csr <- envelope(childcare_ck_ppp, Lest, nsim = 99, rank = 1, glocal = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGenerating 99 simulated realisations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,\n41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,\n61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,\n81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, \n99.\n\nDone.\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(L_ck.csr, . - r ~ r, xlab = \"d\", ylab = \"L(d) - r\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex02_files/figure-html/unnamed-chunk-43-1.png){width=864}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nL_tm.csr <- envelope(childcare_tm_ppp, Lest, nsim = 99, rank = 1, glocal = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGenerating 99 simulated realisations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,\n41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,\n61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,\n81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, \n99.\n\nDone.\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(L_tm.csr, . - r ~ r, xlab = \"d\", ylab = \"L(d) - r\", xlim = c(0, 500))\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex02_files/figure-html/unnamed-chunk-44-1.png){width=864}\n:::\n:::\n\n\n# Part 3: Beyond the chapters\n\nThe reproduction above is the assignment. This part records what I noticed while working\nthrough it: which choices the chapters let the software make silently, whether the conclusions\nsurvive when those choices are changed, and what changes when the week's readings and slides\nare actually applied rather than read. The sections follow that order.\n\n## Reviewing the chapters' choices\n\n### Checking for coincident points\n\nThis is a prerequisite rather than a criticism, and it belongs before any of the distance\nmethods run. Baddeley, Rubak and Turner (2015), listed in the Lesson 2 references and written\nby the authors of spatstat, set out why in section 3.4.4:\n\n> Duplication of points is important, because statistical methodology for spatial point\n> processes (as used in this book) is based largely on assumption that processes are simple,\n> i.e. that points of the process can never be coincident. When the data have coincident\n> points, some statistical procedures designed for simple point processes will be severely\n> affected. For example, the pair correlation function will have an infinite value at distance\n> zero. It is strongly advisable to check for duplicated points and to decide on a strategy for\n> dealing with them if they are present.\n\nCoincident points are plausible for this data, since several childcare centres can operate in\nthe same mall or HDB block and geocoding would return one coordinate for all of them. So the\ncheck is worth running rather than assuming.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(points = npoints(childcareSG_ppp),\n  unique_locations = npoints(unique(childcareSG_ppp)),\n  duplicated = sum(duplicated(childcareSG_ppp)),\n  nn_distances_of_zero = sum(nndist(childcareSG_ppp) == 0))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              points     unique_locations           duplicated \n                1925                 1925                    0 \nnn_distances_of_zero \n                 338 \n```\n\n\n:::\n:::\n\n\nThis layer is clean: every centre has its own coordinate, no nearest-neighbour distance is\nzero, and the pair correlation function used later in Part 3 is safe to run. Nothing needs\nfixing here, but that is only knowable after running the check.\n\nIt is worth knowing what a failure here would look like, because I met one. An earlier draft of\nthis exercise used a different geocoded childcare file, `CHILDCARE.shp`, distributed with a\nlater chapter of the same book. That version had 174 duplicated coordinates, including one\nlocation carrying 25 centres, and it changed results: the Clark-Evans index read 0.495 instead\nof 0.494, and the adaptive-bandwidth surface in Part 1 peaked at 314 centres per square\nkilometre instead of about 47, because an adaptive kernel shrinks its bandwidth wherever\nintensity is high and a 25-point stack drives that bandwidth towards zero. The resulting map\nwas almost entirely dark, since the colour ramp stretched to a maximum reached by a dozen\npixels. Fixed-bandwidth KDE was unaffected, because it spreads every point over the same\nradius regardless of how many neighbours it has.\n\n\n### A clipregion argument that does nothing\n\nA smaller one. The chapter calls the Clark-Evans test like this:\n\n```r\nclarkevans.test(childcareSG_ppp, correction = \"none\",\n                clipregion = \"sg_owin\", alternative = c(\"clustered\"))\n```\n\n`clipregion` is passed the **string** `\"sg_owin\"` rather than the object `sg_owin`. It reads as\nthough the test is being clipped to the Singapore boundary. It is not: the argument is only\nused by the guard-area correction, and with `correction = \"none\"` it is ignored entirely.\nPassing the object, passing the string, or omitting the argument all return R = 0.49444. The\nline is harmless but misleading, and I dropped the quotes in Part 1.\n\n### The envelopes are pointwise, and one argument does not exist\n\nChapter 5 builds the K and L envelopes like this:\n\n```r\nK_ck.csr <- envelope(childcare_ck_ppp, Kest, nsim = 99, rank = 1, glocal = TRUE)\n```\n\n`glocal` is not an argument of `envelope()`. The argument that controls this behaviour is\ncalled `global`, so `glocal = TRUE` is absorbed by `...`, passed down to `Kest`, and ignored.\nThe envelopes come out **pointwise**, which is the default, and identical to what you get by\nleaving the argument out.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\ne_default <- envelope(childcare_ck_ppp, Lest, nsim = 99, verbose = FALSE)\nset.seed(1)\ne_glocal  <- envelope(childcare_ck_ppp, Lest, nsim = 99, glocal = TRUE, verbose = FALSE)\nset.seed(1)\ne_global  <- envelope(childcare_ck_ppp, Lest, nsim = 99, global = TRUE, verbose = FALSE)\n\nc(glocal_same_as_default = identical(e_glocal$hi, e_default$hi),\n  global_same_as_default = identical(e_global$hi, e_default$hi))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nglocal_same_as_default global_same_as_default \n                  TRUE                  FALSE \n```\n\n\n:::\n:::\n\n\nThe distinction matters, and it is the difference between two questions.\n\nA **pointwise** envelope is built separately at each distance *r*. At any single *r* it has the\nstated error rate, but the plot shows hundreds of distances at once, so the chance that the\nobserved curve strays outside *somewhere* is far higher than the nominal level. Reading a\npointwise band as though a single excursion proves clustering is the multiple-comparison\nproblem in graphical form.\n\nA **global** envelope is built from the largest deviation each simulated curve reaches anywhere\nin the range, so the band is wider and one excursion anywhere is enough to reject at the stated\nlevel.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ni <- round(length(e_default$r) / 2)\ndata.frame(\n  envelope = c(\"pointwise\", \"global\"),\n  lo = round(c(e_default$lo[i], e_global$lo[i]), 1),\n  hi = round(c(e_default$hi[i], e_global$hi[i]), 1),\n  frac_r_outside = round(c(mean(e_default$obs > e_default$hi | e_default$obs < e_default$lo),\n                           mean(e_global$obs  > e_global$hi  | e_global$obs  < e_global$lo)), 3)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   envelope    lo    hi frac_r_outside\n1 pointwise 359.8 447.9          0.431\n2    global 333.8 458.0          0.010\n```\n\n\n:::\n:::\n\n\nFor Choa Chu Kang's L function the pointwise band puts about 43% of the distance range outside\nthe envelope, and the global band about 1%. Same data, same simulations, different question.\n\nBecause of this I report the second-order results below as a yes-or-no answer under a global\nenvelope, rather than as a percentage of the range under a pointwise one. The percentage is\nuseful for describing *where* along the distance axis a departure sits, but it is not a\nsignificance level and should not be read as one.\n\nOne practical detail: the pair correlation function is undefined at *r* = 0 and returns `Inf`\nthere, which a global envelope will always flag. Every test below is evaluated over *r* > 0\nwith non-finite values dropped.\n\n### Choosing the study window\n\nEvery first-order and second-order statistic is computed inside a window, so the window you\nchoose changes the numbers you get. Three things I noticed:\n\n1. **The national window follows the coastline.** `as.owin(sg_boundary)` produces\n   an irregular polygon. The nearest-neighbour distances near the coast are truncated by the\n   boundary, which biases *R* upward (points appear more dispersed than they are) unless an\n   edge correction is applied. `clarkevans.test` with `correction = \"none\"` makes no\n   allowance for this.\n\n2. **The national Clark–Evans index answers a question I did not mean to ask.** *R* = 0.49\n   confirms clustering, but childcare supply follows population, and population in Singapore\n   is itself clustered. A nearest-neighbour test against *uniform* CSR asks the wrong\n   question when the points track an underlying covariate. The same weakness affects the\n   second-order tests in Part 2.\n\n3. **The window changes how strong the result looks.** Clark-Evans compares the observed\n   mean nearest-neighbour distance with the distance\n   expected under CSR, and that expected distance depends on the area of the window through\n   the intensity *n/A*. Enlarge the window without adding points and CSR expects the points to\n   be further apart, so the same points look more clustered by comparison.\n\n   The test below holds the 74 Choa Chu Kang centres fixed and only changes the window.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nck_pts <- childcare_ck_ppp\nwindows <- list(\n  `planning-area polygon` = as.owin(st_union(ck)),\n  `polygon + 500 m buffer` = as.owin(st_buffer(st_union(ck), 500)),\n  `convex hull of points`  = convexhull.xy(ck_pts$x, ck_pts$y),\n  `bounding box`           = owin(range(ck_pts$x), range(ck_pts$y))\n)\ndo.call(rbind, lapply(names(windows), function(nm) {\n  w <- windows[[nm]]\n  Y <- suppressWarnings(ppp(ck_pts$x, ck_pts$y, window = w))\n  t <- suppressWarnings(clarkevans.test(Y, correction = \"none\",\n                                        alternative = \"two.sided\", nsim = 999))\n  data.frame(window = nm, area_km2 = round(spatstat.geom::area(w) / 1e6, 2),\n             R = round(unname(t$statistic), 3), p = round(t$p.value, 3))\n}))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  window area_km2     R     p\n1  planning-area polygon     6.12 0.841 0.009\n2 polygon + 500 m buffer    12.60 0.586 0.000\n3  convex hull of points     5.79 0.865 0.026\n4           bounding box     9.03 0.692 0.000\n```\n\n\n:::\n:::\n\n\n   All four windows agree that the pattern is clustered, which is reassuring, but they do not\n   agree on how strongly. *R* ranges from 0.87 under the convex hull to 0.59 under the buffered\n   polygon, and the p-value moves from 0.026 to below 0.001. Nothing changed but the outline I\n   drew around the same 74 centres. A result reported as \"R = 0.87, p = 0.03\" and one reported\n   as \"R = 0.59, p < 0.001\" would be written up quite differently, even though they describe\n   the same centres. Wartman and Malasavage's insistence that \"the study area should be\n   determined objectively, rather than arbitrarily\" is doing real work here, and neither\n   chapter mentions the issue.\n\n   O'Sullivan and Unwin explain the mechanism behind the buffered case: edge effects arise\n   because \"sites in the center of the study area can have nearby observations in all\n   directions, whereas sites at the edges only have neighbors toward the center\". Padding the\n   window adds empty space full of edge, which is why *R* falls furthest there.\n\n   Two of the applied papers sit usefully side by side here. Borruso and Porceddu write\n   that the bandwidth \"represents the only arbitrary variable which defines the extent of the\n   searching function\", while Wartman and Malasavage insist that \"the study area should be\n   determined objectively, rather than arbitrarily\". Borruso's sentence is about the KDE\n   kernel, so the table above is not a counter-example to it. But his paper never treats the\n   study area as a choice at all, and on this data the study area is what moved the verdict,\n   with no bandwidth involved. Following Borruso alone, an analyst would carefully document\n   the one parameter he names and say nothing about the one that mattered.\n\n### How much the bandwidth choice matters\n\nYin (2020), one of the week's core readings, frames KDE as a bias-variance trade-off: too small\na bandwidth produces a noisy surface that overfits the sample, too large a bandwidth smooths\naway the structure we are looking for. The four automatic selectors sit at different points on\nthat trade-off, and on this data they are far apart.\n\n| Selector | Bandwidth (km) | What it optimises |\n|---|---|---|\n| `bw.diggle` | 0.30 | Edge-corrected minimisation of mean-square error (the book's default) |\n| `bw.ppl` | 0.39 | Likelihood cross-validation, driven by the data rather than a formula |\n| `bw.scott` | 2.16 / 1.40 (x / y) | A rule of thumb based on the pattern's own spread |\n| `bw.CvL` | 4.54 | Coarser smoothing, low variance, high bias |\n\nThe spread is more than tenfold. Since the chapters pick one without saying why, the question\nis how much of the map depends on that choice, so I re-ran the national surface under the two\nextremes alongside the default.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkde_ppl <- density(childcareSG_ppp_km, sigma = bw.ppl, edge = TRUE)\nkde_cvl <- density(childcareSG_ppp_km, sigma = bw.CvL, edge = TRUE)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(1, 3))\nplot(kde_childcareSG_km, main = \"bw.diggle\")\nplot(kde_ppl, main = \"bw.ppl\")\nplot(kde_cvl, main = \"bw.CvL\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex02_files/figure-html/unnamed-chunk-50-1.png){width=864}\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 1))\n```\n:::\n\n\nThe broad pattern is stable across all three: the same dense central-east corridor, the same\nrelative voids in the north. What changes is the granularity. The two small bandwidths break\nthe surface into many separate peaks, while `bw.CvL` merges them into a few large blobs. So the\nstatement \"childcare is concentrated in the central and eastern regions\" is robust, but any\nclaim about a *particular* hotspot is a claim about the bandwidth as much as about the data.\n\nThe trade-off can be measured rather than eyeballed. The coefficient of variation of the\ndensity values says how uneven each surface is.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncv_im <- function(x) { v <- as.vector(x$v); v <- v[!is.na(v)]; sd(v) / mean(v) }\nc(`bw.ppl` = cv_im(kde_ppl), `bw.diggle` = cv_im(kde_childcareSG_km), `bw.CvL` = cv_im(kde_cvl))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   bw.ppl bw.diggle    bw.CvL \n1.5432064 1.6760748 0.6119746 \n```\n\n\n:::\n:::\n\n\nThe ordering follows the bandwidths rather than the reputations of the methods. `bw.diggle`\nreturns the smallest bandwidth here at 0.30 km and gives the most uneven surface, `bw.ppl` at\n0.39 km is close behind, and `bw.CvL` at 4.54 km is far smoother than either. The book's\ndefault therefore sits at the variance-heavy end of the range on this data rather than in the\nmiddle, which is the opposite of what I assumed before measuring it.\n\n\n### A unit mismatch in the KDE map\n\nThe chapters build the KDE map by rescaling the point pattern to **kilometres**, converting\nthe result to a raster, and then assigning the raster the CRS `EPSG:3414`, which is a\n**metre** projection. The raster's extent (about 0–55 in km units) is then interpreted by\ntmap as 0–55 *metres*. The rendered map is a sliver of the coastline about fifty metres wide,\nnot the country, even though the density surface is correct.\n\nThe fix used for the KDE map in Part 1 is to compute the density on the metre-based pattern, so\nthe raster extent\nis genuinely in metres and the CRS assignment is honest, then rescale *only the values* by\n10⁶ for a per-km² legend. The change is small, and the map then shows Singapore properly.\n\nWhat makes this one instructive is that nothing failed. The code ran without error and\nproduced a map that looked reasonable at a glance. I only caught it by reading the graticule\nlabels, which spanned about a hundredth of a degree.\n\n### Why adaptive suits this data\n\nThe default `density()` uses a fixed bandwidth: every point spreads its influence to the same\nradius. Adaptive bandwidth (`adaptive.density`) lets the radius shrink where points are dense.\nFor childcare, whose supply tracks population density, adaptive is the more defensible\nassumption: a centre in a dense town competes with neighbours close by, while one in a\nsparse area stands alone.\n\nIn the comparison plotted in Part 1, the fixed surface smooths the dense corridor into one\ncontinuous mass while the adaptive surface keeps more local structure. Which one is preferable\ndepends on what you are asking, so the choice should be stated rather than left at\nthe default.\n\n### Do the functions agree?\n\nAll four functions describe the same underlying dependence from different angles, so reading\nthem against each other is a way of checking that a result is not an artefact of one\nparticular statistic:\n\n- **G and K/L both detect clustering** in both planning areas, with the observed curves sitting\n  above the CSR band at short distances.\n- **F rarely leaves its band.** F is computed from arbitrary locations, so it reflects the\n  *average* empty-space structure. With only 74 and 117 points in these two areas, F is blunt; it\n  contributes little beyond confirming there is no large-scale regularity.\n- **K and L give the cleaner contrast between the two towns.** G looks only at each point's\n  nearest neighbour and is sensitive to the border correction, while K and L average over all\n  pairs. That stability comes from accumulating counts across distances, which is an advantage\n  here and a liability later: the section on nulls below shows the same accumulation producing\n  a signal that turns out not to be there.\n\n### Why the two towns differ\n\nBoth towns show clustering at short distances, but Tampines is more strongly clustered, with\nits K/L curves rising higher above the band.\n\nThe likely explanation is the housing. Tampines is one of the earliest and densest new towns,\nbuilt around a tight commercial centre with residential blocks close by, while Choa Chu Kang\nis younger and more spread out. Childcare centres locate near homes, so the arrangement of the\ncentres largely follows the arrangement of the flats. That explanation comes from knowing the\ntowns, not from the curves.\n\n## Applying the week's material\n\nI have already used two of the readings above: Yin (2020) for the bandwidth comparison, and\nYuan et al. (2020) for the argument that CSR is the wrong null when points follow population.\nThe two methods below come from material outside r4gdsa Chapters 4 and 5. Quadrat analysis is\ncovered in the Lesson 2 slides and in Anselin's *Point Pattern Analysis: Quadrat Counts*. The\ninhomogeneous null then tests Yuan's warning, which is that CSR treats every location as\nequally likely to hold a centre, so any service that follows the population will be reported as\nclustered whether or not the centres have anything to do with each other.\n\n### Quadrat analysis\n\nNeither r4gdsa Chapter 4 nor Chapter 5 covers quadrat analysis, but the Lesson 2 slides and\nAnselin's *Point Pattern Analysis: Quadrat Counts* both do, so I have added it here as a third\nfirst-order method. It is the oldest of them. You divide the study area into a grid, count the\npoints in each cell, and compare those counts with what CSR would produce. Quadrat analysis\nadds a different kind of evidence from Clark-Evans, which measures distances between\ncentres. Quadrat analysis ignores distance entirely and looks only at how counts vary between\ncells, so if the two agree, the finding does not depend on either way of measuring.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqc <- quadratcount(childcareSG_ppp_km, nx = 6, ny = 6)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqc\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntile\nTile row 1, col 1 Tile row 1, col 2 Tile row 1, col 3 Tile row 1, col 4 \n                0                 0               238                 8 \nTile row 1, col 5 Tile row 1, col 6 Tile row 2, col 1 Tile row 2, col 2 \n                0                 0                 0                95 \nTile row 2, col 3 Tile row 2, col 4 Tile row 2, col 5 Tile row 2, col 6 \n               88               274                48                 0 \nTile row 3, col 1 Tile row 3, col 2 Tile row 3, col 3 Tile row 3, col 4 \n                0               227               135               277 \nTile row 3, col 5 Tile row 3, col 6 Tile row 4, col 1 Tile row 4, col 2 \n              183                 0                 0                15 \nTile row 4, col 3 Tile row 4, col 4 Tile row 4, col 5 Tile row 4, col 6 \n              197               127                 9                 0 \nTile row 5, col 1 Tile row 5, col 2 Tile row 5, col 3 Tile row 5, col 4 \n                0                 0                 4                 0 \nTile row 6, col 1 Tile row 6, col 2 Tile row 6, col 3 \n                0                 0                 0 \n```\n\n\n:::\n:::\n\n\nThe slides give the reading rule through the variance-mean ratio. Under CSR the counts follow\na Poisson distribution, whose variance equals its mean, so VMR ≈ 1 is random, VMR > 1 is\nclustered and VMR < 1 is regular.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounts <- as.vector(qc)\nc(variance = var(counts), mean = mean(counts), VMR = var(counts) / mean(counts))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  variance       mean        VMR \n8885.09032   62.09677  143.08457 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nquadrat.test(childcareSG_ppp_km, nx = 6, ny = 6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tChi-squared test of CSR using quadrat counts\n\ndata:  childcareSG_ppp_km\nX2 = 1388.7, df = 30, p-value < 2.2e-16\nalternative hypothesis: two.sided\n\nQuadrats: 31 tiles (irregular windows)\n```\n\n\n:::\n:::\n\n\nThe chi-square test is unambiguous: X² = 1389 on 30 degrees of freedom, p < 2.2e-16, the same\nstrong clustering Clark-Evans found. The raw VMR of 143 is also far above 1, but it is\ninflated and should not be reported on its own. The count grid inherits the coastline, so\nseveral edge tiles straddle land and sea and sit near zero, while the busiest central tile\nholds 277 centres.\n\nThis is the one method in the exercise where the **modifiable areal unit problem** applies in\nits strict sense, because it is the only one that aggregates points into areal units before\ncomputing anything. O'Sullivan and Unwin describe MAUP as the problem that \"the aggregation\nunits used are arbitrary with respect to the phenomena under investigation, yet the units used\nwill affect statistics determined on the basis of data reported in this way\".\n\nA 6 by 6 grid is exactly such an arbitrary unit. Change `nx` and `ny`, or shift the grid\norigin, and the counts, the VMR and the chi-square statistic all move. That sensitivity, which\nthe Lesson 2 slides list among the weaknesses of quadrat analysis, is why the field moved to\ndistance-based methods.\n\nSo quadrat analysis agrees with Clark-Evans that the pattern is clustered, which is\nreassuring, but its headline number depends on a grid I chose arbitrarily. That dependence is\nthe reason later methods measure distances between points instead of counts inside cells.\n\n### Two functions the chapters leave out\n\nr4gdsa Chapters 4 and 5 stop at G, F, K and L. Two of the other references go further, and both\nadditions\nturned out to matter.\n\nAnselin's *Point Pattern Analysis: F and J Functions* introduces the **J function**, which\ncombines the two\ncurves already computed: `J(r) = (1 - G(r)) / (1 - F(r))`. Under CSR it is flat at 1, below 1\nmeans clustering and above 1 means inhibition. It is a tidier answer to the question I asked\nearlier about whether G and F agree, since it combines them arithmetically instead of leaving\nme to compare two plots by eye.\n\n*Chapter 11 Point Pattern Analysis* of **Intro to GIS and Spatial Analysis**, listed in the\nreferences, makes a second point. K and L are **cumulative**: they count every point within\ndistance *r*, so clustering at short range keeps inflating the curve at longer ranges. The\n**pair correlation function** counts only points in a narrow band at *r*, so each distance is\njudged on its own.\n\n::: {.callout-warning appearance=\"simple\"}\n## Two different functions, one letter\n\nThe pair correlation function is written **lowercase g(r)**, and it is *not* the **G-function**\nfrom the lesson slides and Chapter 5. They are unrelated:\n\n- **G(r)**, `Gest()`, is the cumulative distribution of nearest-neighbour distances, so it uses\n  one distance per point and says nothing about what lies further away.\n- **g(r)**, `pcf()`, is derived from Ripley's K by differentiating it, so it uses all pairs of\n  points and reports the density of pairs at each separation.\n\nGimond introduces g in section 11.3.3 as a modification of K, not of G, which is the clearest\nway to keep them apart. To avoid the collision in code I have named the objects `pcf_*` rather\nthan `g_*`, since Part 2 already uses `G_ck` and `G_tm` for the G-function.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchildcare_tm_ppp_km <- rescale.ppp(childcare_tm_ppp, 1000, \"km\")\nchildcare_ck_ppp_km <- rescale.ppp(childcare_ck_ppp, 1000, \"km\")\n\nset.seed(42)\nJ_tm <- envelope(childcare_tm_ppp_km, Jest, nsim = 99, verbose = FALSE)\npcf_tm <- envelope(childcare_tm_ppp_km, pcf,  nsim = 99, verbose = FALSE)\nJ_ck <- envelope(childcare_ck_ppp_km, Jest, nsim = 99, verbose = FALSE)\npcf_ck <- envelope(childcare_ck_ppp_km, pcf,  nsim = 99, verbose = FALSE)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(1, 2))\nplot(J_tm, main = \"J function: Tampines\", legend = FALSE)\nplot(pcf_tm, main = \"Pair correlation g: Tampines\", legend = FALSE)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex02_files/figure-html/unnamed-chunk-57-1.png){width=864}\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 1))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\noutside <- function(env, side = c(\"above\", \"below\")) {\n  side <- match.arg(side)\n  if (side == \"above\") mean(env$obs > env$hi, na.rm = TRUE)\n  else mean(env$obs < env$lo, na.rm = TRUE)\n}\ndata.frame(\n  town        = c(\"Tampines\", \"Choa Chu Kang\"),\n  J_clustered = c(outside(J_tm, \"below\"), outside(J_ck, \"below\")),\n  g_clustered = c(outside(pcf_tm, \"above\"), outside(pcf_ck, \"above\"))\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           town J_clustered g_clustered\n1      Tampines   0.7704918  0.98437500\n2 Choa Chu Kang   0.2042254  0.06835938\n```\n\n\n:::\n:::\n\n\nThose percentages are pointwise, so they describe where along the distance axis each curve\nleaves its band, not whether the departure is significant overall. The section on envelopes\nabove explains why. Repeating both tests under a global envelope, over *r* > 0, gives the\nanswer that can actually be reported:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexits <- function(e) {\n  k <- is.finite(e$obs) & e$r > 0\n  any(e$obs[k] > e$hi[k] | e$obs[k] < e$lo[k], na.rm = TRUE)\n}\nglob <- function(X, fun, ...) { set.seed(42)\n  envelope(X, fun, nsim = 99, global = TRUE, verbose = FALSE, ...) }\n\ndata.frame(\n  town = c(\"Tampines\", \"Choa Chu Kang\"),\n  J_global   = c(exits(glob(childcare_tm_ppp_km, Jest)),\n                 exits(glob(childcare_ck_ppp_km, Jest))),\n  pcf_global = c(exits(glob(childcare_tm_ppp_km, pcf)),\n                 exits(glob(childcare_ck_ppp_km, pcf)))\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           town J_global pcf_global\n1      Tampines    FALSE       TRUE\n2 Choa Chu Kang    FALSE       TRUE\n```\n\n\n:::\n:::\n\n\nThe two functions part company. The pair correlation function rejects CSR for both towns under\nthe stricter test, so the clustering it reports is not an artefact of scanning many distances.\nThe J function does not reject for either town, even though its pointwise band was left over\n77% of the range in Tampines. J is built from G and F, both of which are cumulative\nnearest-neighbour constructions, and its deviations are correspondingly small and spread out\nrather than concentrated. Under a band sized for the whole curve, they no longer stand out.\n\nSo on the CSR comparison I would report the pair correlation result and treat the J result as\nsuggestive only. Under CSR, Tampines is clustered on both pointwise measures, with J outside\nits band over about 77% of the range and g over 98%, while Choa Chu Kang is much weaker at\nroughly 20% and 7%.\n\nClark-Evans reports both towns as significantly clustered, at R = 0.67 for Tampines and\nR = 0.84 for Choa Chu Kang, and stops there. What the distance-resolved functions add is that\nthe two are clustered in different ways. Tampines departs from randomness at nearly every\ndistance, while Choa Chu Kang does so only over a narrow band. A single nearest-neighbour index\ncannot express that difference, because it collapses the whole pattern into one number before\ndistance enters the picture.\n\nThe non-cumulative view matters again in the next section, where it changes a conclusion I had\nalready written down.\n\n### Choosing a null hypothesis\n\nEverything in Part 2 was tested against Complete Spatial Randomness, which assumes a centre\nwas equally likely to open anywhere in the town. For a service that follows families, that\nassumption is close to guaranteed to report clustering. This section builds two better nulls\nand then sets out what neither of them can settle.\n\n#### A null estimated from the pattern itself\n\nYuan et al. (2020) warn that CSR is a weak null for events that track covariates. The warning is\ntestable directly. The homogeneous L-function in Part 2 compares the observed pattern with a\ncompletely random one, which is loaded here: if childcare follows population density, the\nintensity gradient is counted as clustering. The inhomogeneous L-function removes the trend\nfirst. It estimates the intensity (here, the KDE surface) and tests the pattern against an\ninhomogeneous Poisson process with that intensity, so any clustering that survives is\ninteraction between points that the trend cannot explain.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(42)   # envelope simulations are random; fix the seed so the results are reproducible\nlambda_tm <- density(childcare_tm_ppp_km, sigma = bw.diggle, edge = TRUE)\nlambda_tm$v <- pmax(lambda_tm$v, 0.01)   # Linhom needs strictly positive intensity\nL_tm_inhom <- envelope(childcare_tm_ppp_km, Linhom, lambda = lambda_tm,\n                       nsim = 99, correction = \"Ripley\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGenerating 99 simulated realisations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,\n41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,\n61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,\n81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, \n99.\n\nDone.\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(L_tm_inhom, . - r ~ r, main = \"Inhomogeneous L: Tampines\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex02_files/figure-html/unnamed-chunk-61-1.png){width=864}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlambda_ck <- density(childcare_ck_ppp_km, sigma = bw.diggle, edge = TRUE)\nlambda_ck$v <- pmax(lambda_ck$v, 0.01)\nL_ck_inhom <- envelope(childcare_ck_ppp_km, Linhom, lambda = lambda_ck,\n                       nsim = 99, correction = \"Ripley\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGenerating 99 simulated realisations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,\n41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,\n61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,\n81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, \n99.\n\nDone.\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(L_ck_inhom, . - r ~ r, main = \"Inhomogeneous L: Choa Chu Kang\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex02_files/figure-html/unnamed-chunk-63-1.png){width=864}\n:::\n:::\n\n\nA coarse summary of where the observed curve sits relative to the envelope makes the difference\neasy to read.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfrac_band <- function(env) c(above = mean(env$obs > env$hi, na.rm = TRUE),\n                            below = mean(env$obs < env$lo, na.rm = TRUE))\nlist(Tampines = frac_band(L_tm_inhom),\n     `Choa Chu Kang` = frac_band(L_ck_inhom))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$Tampines\n    above     below \n0.0000000 0.9259259 \n\n$`Choa Chu Kang`\n      above       below \n0.003898635 0.625730994 \n```\n\n\n:::\n:::\n\n\nUnder the homogeneous test, both towns look strongly clustered. Under the inhomogeneous null\nthe picture changes, and the two towns differ. For Tampines the observed curve sits below the\nenvelope for most of the plotted range (about 92% of it), which is the signature of\nregularity, not clustering: once the density of centres is accounted for, centres are further\napart than the trend predicts. For Choa Chu Kang the curve hovers at or below the envelope\n(about 49% of the range below it, essentially none above), so the clustering the homogeneous\ntest reported for this town was almost entirely the intensity trend, with no clear residual\nsignal left.\n\nBoth results line up with Yuan's warning: a homogeneous null will overstate clustering for\nany service that follows population.\n\nThe Tampines curve sitting below the envelope looks like regularity, and my first reading of it\nwas that centres compete and space themselves out. That reading was wrong, and the pair\ncorrelation function from the previous section is what shows it. L is cumulative, so a small\ndeviation repeated across short distances accumulates into a curve that drifts below the band\nwithout any single distance being unusual. Running the same null through the non-cumulative\n`pcfinhom` removes that accumulation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(42)\npcfi_tm <- envelope(childcare_tm_ppp_km, pcfinhom, lambda = lambda_tm,\n                  nsim = 99, verbose = FALSE)\npcfi_ck <- envelope(childcare_ck_ppp_km, pcfinhom, lambda = lambda_ck,\n                  nsim = 99, verbose = FALSE)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(1, 2))\nplot(pcfi_tm, main = \"Inhomogeneous g: Tampines\", legend = FALSE)\nplot(pcfi_ck, main = \"Inhomogeneous g: Choa Chu Kang\", legend = FALSE)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex02_files/figure-html/unnamed-chunk-66-1.png){width=864}\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 1))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata.frame(\n  town = c(\"Tampines\", \"Choa Chu Kang\"),\n  g_inhom_outside_envelope = c(outside(pcfi_tm, \"above\") + outside(pcfi_tm, \"below\"),\n                               outside(pcfi_ck, \"above\") + outside(pcfi_ck, \"below\"))\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           town g_inhom_outside_envelope\n1      Tampines                        0\n2 Choa Chu Kang                        0\n```\n\n\n:::\n:::\n\n\nThe inhomogeneous g never leaves its envelope for either town at any distance. So the\nregularity I thought I had found was an artefact of L accumulating, not a property of the\ncentres. Once the intensity trend is accounted for, there is no detectable interaction between\nchildcare centres at any distance.\n\nThe direction of the correction is worth being clear about. A global band is wider, which\nmakes it harder to reject the null and easier to stay inside. So for a result that rejects,\nlike the pair correlation test above, the global version is the stricter test. For a result\nthat finds nothing, like this one, the narrower pointwise band was already the harder test to\npass, and the global check below is a formality. I ran it so both conclusions are reported on\nthe same footing.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata.frame(\n  town = c(\"Tampines\", \"Choa Chu Kang\"),\n  pcfinhom_global_exits = c(exits(glob(childcare_tm_ppp_km, pcfinhom, lambda = lambda_tm)),\n                            exits(glob(childcare_ck_ppp_km, pcfinhom, lambda = lambda_ck)))\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           town pcfinhom_global_exits\n1      Tampines                 FALSE\n2 Choa Chu Kang                 FALSE\n```\n\n\n:::\n:::\n\n\nNeither town's curve leaves the wider band either, as expected. The absence of residual\ninteraction therefore does not depend on which envelope is used, unlike the J result above.\n\nNeither r4gdsa chapter uses a non-cumulative function, so this correction is not available from\nthem.\n\n#### A null built from resident population\n\nThe inhomogeneous tests above have a circularity in them, which I set out in the section below:\nthe intensity was estimated from a kernel density of the very points being tested, so genuine\nclustering could be absorbed into the \"trend\" before the test runs. Floch et al. say what the\nfix is, namely \"a model that links a covariable to the intensity\". The covariable for childcare\nis obvious and I already have it, since Hands-on Exercise 1 used the same census table:\n**resident children aged 0 to 4 by subzone**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npop_sz <- read_csv(\"../Hands-on_Ex01/data/aspatial/respop_census2020_agesex.csv\",\n                   show_col_types = FALSE) |>\n  filter(!grepl(\"Total\", Number)) |>\n  transmute(SUBZONE_N = toupper(Number),\n            kids = suppressWarnings(as.numeric(Total_0_4)))\n\nmpsz_pop <- mpsz |>\n  left_join(pop_sz, by = \"SUBZONE_N\") |>\n  mutate(kids = replace_na(kids, 0),\n         kids_km2 = kids / as.numeric(st_area(mpsz) / 1e6))\n\nc(subzone_polygons = nrow(mpsz_pop),\n  name_found_in_census = sum(mpsz_pop$SUBZONE_N %in% pop_sz$SUBZONE_N),\n  with_resident_count = sum(mpsz_pop$kids > 0),\n  children_0_4 = sum(mpsz_pop$kids))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    subzone_polygons name_found_in_census  with_resident_count \n                 332                  332                  226 \n        children_0_4 \n              183100 \n```\n\n\n:::\n:::\n\n\nEvery one of the 332 subzone names matches the census table, but only 226 carry a resident\ncount. The other 106 are places like Raffles Place, Boat Quay, Jurong Island and the southern\nislands, where the census reports no resident population because nobody lives there. Treating\nthose as zero is correct rather than a gap in the join, and the total of 183,100 children\nagrees with the published national figure.\n\nThe next step turns this into a surface: rasterise the subzone densities, crop to the town, and\nscale the values so the surface integrates to the number of centres actually observed. That\nlast step is what makes it a candidate intensity for the point process rather than just a\npopulation map.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkids_rast <- terra::rasterize(terra::vect(mpsz_pop),\n                              terra::rast(terra::vect(mpsz_pop), resolution = 200),\n                              field = \"kids_km2\")\n\npop_intensity <- function(town_sf, X) {\n  rr  <- terra::crop(kids_rast, terra::vect(town_sf), mask = TRUE)\n  mat <- terra::as.matrix(rr, wide = TRUE); mat[is.na(mat)] <- 0\n  e   <- as.vector(terra::ext(rr))\n  lam <- im(mat[nrow(mat):1, ], xrange = e[1:2] / 1000, yrange = e[3:4] / 1000)\n  lam <- lam[Window(X), drop = FALSE]\n  lam$v[is.na(lam$v) | lam$v <= 0] <- 1e-6\n  lam$v <- lam$v * X$n / (sum(lam$v, na.rm = TRUE) * lam$xstep * lam$ystep)\n  lam\n}\n\nlam_pop_tm <- pop_intensity(tm, childcare_tm_ppp_km)\nlam_pop_ck <- pop_intensity(ck, childcare_ck_ppp_km)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(1, 2))\nplot(lam_pop_tm, main = \"Children 0-4 intensity: Tampines\")\nplot(lam_pop_ck, main = \"Children 0-4 intensity: Choa Chu Kang\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex02_files/figure-html/unnamed-chunk-71-1.png){width=864}\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 1))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(42)\npcfpop_tm <- envelope(childcare_tm_ppp_km, pcfinhom, lambda = lam_pop_tm,\n                    nsim = 99, verbose = FALSE)\npcfpop_ck <- envelope(childcare_ck_ppp_km, pcfinhom, lambda = lam_pop_ck,\n                    nsim = 99, verbose = FALSE)\ndata.frame(\n  town = c(\"Tampines\", \"Choa Chu Kang\"),\n  clustered = c(outside(pcfpop_tm, \"above\"), outside(pcfpop_ck, \"above\")),\n  regular   = c(outside(pcfpop_tm, \"below\"), outside(pcfpop_ck, \"below\"))\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           town  clustered regular\n1      Tampines 0.01953125       0\n2 Choa Chu Kang 0.00000000       0\n```\n\n\n:::\n:::\n\n\nThe answer barely moves. Against a null built from where the children actually live, rather\nthan from a smoothed version of the centres themselves, Choa Chu Kang shows nothing outside\nits envelope at any distance and Tampines shows a small excess over about 2% of the range.\n\nThe agreement is worth more than the size of the residual. The two nulls are built from\ncompletely different information, one from the childcare points and one from the census, and\nthey point the same way.\nThe circularity I was worried about does not appear to be driving the earlier result, and the\nconclusion now rests on an external covariate of the kind Floch et al. ask for rather than on\nthe pattern explaining itself.\n\nThe small Tampines residual is the one thing I would look at next. It is weak enough to be\nnoise across 99 simulations, but it is in the direction of clustering, and Tampines is the town\nwhere the housing is densest.\n\n#### What none of this can settle\n\nSection 4.3.2 of Floch et al., one of the core readings, is a warning that applies to\neverything above, and it is worth quoting because it states the problem more precisely than I\ncould:\n\n> [T]he same aggregated or dispersed structures can be obtained with an inhomogeneous Poisson\n> process in which the intensity of the process varies in space but the points are independent\n> of each other. **A single observation of a spatial distribution does not allow for any\n> distinction between first- and second-order properties of a process** in the absence of\n> additional information such as that provided by a model that links a covariable to the\n> intensity.\n\nThat is the identification problem this exercise ran into empirically. A clustered-looking map\ncan mean centres attract each other (second-order), or that centres are simply more numerous\nwhere families live (first-order). One snapshot cannot separate them. Floch et al. cite Ellison\nand co-authors on exactly this: natural advantages, which raise intensity, have an effect \"that is\nindistinguishable from that of positive externalities\" causing aggregation. For childcare, \"many\nyoung families here\" and \"operators cluster near each other\" produce the same picture.\n\nIt also names the two standard escapes, and they are the two methods that appear in this\nexercise: the inhomogeneous K function of Baddeley et al., which I used through `Linhom` and\n`pcfinhom`, and the Kd of Duranton and Overman, which I did not.\n\nThis forces an honest qualification of my own result. The escape only works if the intensity\ncomes from **outside** the pattern, from a covariate such as resident population. Mine did not.\nI estimated it with a kernel density of the very points being tested, so any genuine\nshort-range clustering was partly absorbed into the \"trend\" before the test ran. That biases\nthe inhomogeneous result towards finding nothing, which is what it found.\n\nMy conclusion is therefore narrower than it first appears. The pattern is consistent with\ncentres being located wherever demand is, and this data cannot demonstrate interaction on top\nof that. That is not the same as proving no interaction exists.\n\nDoing better needs the covariate, which is the natural next step and the reason the limitation\nbelow is first on the list.\n\n## Limitations\n\nWhere this exercise falls short:\n\n1. **The population null is coarse.** I did test against resident children aged 0 to 4 rather\n   than only against CSR, which was the main gap. But the census gives one figure per subzone,\n   so the intensity surface is a step function that jumps at subzone boundaries rather than a\n   smooth demand surface. Any residual clustering measured at distances shorter than a subzone\n   is partly a product of that blockiness.\n2. **Edge effects at the coast.** All functions were used with their best available edge\n   corrections, but the coastline makes the window irregular and some bias remains at short\n   distances.\n3. **Description, not explanation.** Even with the population covariate, this is still a\n   description of where centres are. It says nothing about capacity, waiting lists or whether\n   supply meets demand, and nothing about change over time. The spatio-temporal extension in\n   Lesson 3 is where the time dimension starts.\n4. **Attribute data is thin.** The current childcare table carries almost no useful attributes\n   (capacity, hours, fees), so I could not stratify the analysis, e.g. cluster analysis for\n   centres with and without infant-care places, which is the policy-relevant question.\n\nNone of these change the results above, but they do limit how far the results can be pushed.\n\n## Summary\n\nAt the national scale childcare supply is heavily concentrated, and the concentration sits in\na central-eastern corridor that survives every bandwidth I tried. Clark-Evans, the quadrat\nchi-square test and the G, K and L functions all agree on that.\n\nThe second-order results need more care than the chapters suggest. Both towns look strongly\nclustered against a homogeneous CSR null, but that null assumes centres could have gone\nanywhere with equal probability, which is not true of a service that follows housing. Testing\nagainst an intensity-adjusted null instead, and using the non-cumulative pair correlation\nfunction rather than K or L, almost all of it goes. Choa Chu Kang shows no departure from its\nenvelope at any distance, and Tampines only a small one, over about 2% of the range.\n\nSo the reading I would defend is that childcare centres are concentrated because people are\nconcentrated, and that this data shows little sign of the centres responding to each other on\ntop of that. That conclusion holds under both a pointwise and a global envelope, which is more\nthan the J function manages.\n\nGetting there took three corrections to my own first answer: one for the null, one for the\ncumulative functions, and one for reading pointwise bands as though they carried a significance\nlevel. None of the three would have surfaced from the chapters alone.\n\n# Reflection\n\nLesson 1 was mostly about getting data into the right shape. This exercise was less about\nmechanics and more about what the tests were comparing against.\n\nThe null hypothesis took up most of my time. Every test in Part 2 ran without complaint and\nreported strong clustering, and none of them were wrong. But CSR treats a reservoir and a\nhousing estate as equally likely places for a childcare centre, so a service that follows\nfamilies gets reported as clustered more or less by construction. When I rebuilt the null from\ncensus counts of children aged 0 to 4, most of the clustering went away. The code was fine\nthroughout. I had not thought about what the comparison assumed.\n\nThe mistake I spent longest on came from using the wrong file. The chapters read\n`ChildCareServices.kml`, which is not in the book's GitHub repository, so I substituted a\ndifferent geocoded childcare layer that is, `CHILDCARE.shp` from a later chapter. Both look\nofficial and both are childcare centres in Singapore. But the substitute had 174 coordinates\nshared by more than one centre, including 25 at a single point, and that made the\nadaptive-bandwidth map in Part 1 look nothing like the book's. I assumed at first that the\nchapters had glossed over something. The real explanation was that I was not using their data.\nOnce I tracked down the actual KML, Choa Chu Kang returned R = 0.84097 and p = 0.008866,\nmatching the chapter exactly.\n\nTwo smaller errors followed the same pattern. I read the inhomogeneous L curve as evidence that\ncentres space themselves out, when it was an artefact of L accumulating small deviations across\ndistances; the pair correlation function showed nothing at any distance. And before finding the\nright file, I assumed a difference from the chapter came from the newer planning boundaries and\nwrote that up, when both boundary editions return the same result. In all three cases I had an\nexplanation that sounded reasonable and did not test it.\n\nThe terminology caught me out once. The pair correlation function is written g(r), and the\nlesson slides use G(r) for the nearest-neighbour function. They are different functions, and I\nhad to go back to Gimond to be sure which one I was reading about.\n\nI only checked the Monte Carlo simulation envelopes properly after a classmate asked on Piazza\nwhether they were pointwise or global. Until then I had been quoting the share of the distance\nrange where a curve sits outside its band as though that were a result, and it is not. Those\nbands are pointwise, so with hundreds of distances on the axis a curve straying outside\nsomewhere is close to expected. The `glocal = TRUE` in the chapters does not guard against\nthis, because no argument by that name exists. Rerunning everything with global envelopes left\nthe main conclusion standing but removed the J function result completely.\n\nIf I did this again I would confirm the exact data file before writing anything, and check for\ncoincident points and settle the study window as a first step rather than partway through. The\nfile I read mattered more than any method I picked, which is not where I expected the\nsensitivity to be.\n\n# References\n\nGrouped as the Lesson 2 page groups them, with a note on where each one is used here. Sources\nlisted on that page but not drawn on are left out rather than padded in.\n\n## Hands-on chapters\n\n- r4gdsa [Chapter 4: First-order Spatial Point Patterns Analysis\n  Methods](https://r4gdsa.netlify.app/chap04.html) and [Chapter 5: 2nd Order Spatial Point\n  Patterns Analysis Methods](https://r4gdsa.netlify.app/chap05.html). Reproduced in Parts 1\n  and 2, and reviewed in Part 3.\n\n## Core readings\n\n- Yuan, Y., Qiang, Y., Bin Asad, K., and Chow, T. E. (2020). *Point Pattern Analysis*. The\n  Geographic Information Science & Technology Body of Knowledge, 1st Quarter 2020 Edition,\n  John P. Wilson (ed.). DOI: 10.22224/gistbok/2020.1.13.\n  Source of the warning that CSR is a weak null for events that track a covariate, which drives\n  the section on choosing a null hypothesis.\n- Yin, P. (2020). *Kernels and Density Estimation*. The Geographic Information Science &\n  Technology Body of Knowledge, 1st Quarter 2020 Edition, John P. Wilson (ed.). DOI:\n  10.22224/gistbok/2020.1.12.\n  The bias-variance framing behind the bandwidth comparison, which I measure rather than\n  restate.\n- Chapter 4 *Spatial distribution of points* of Floch, J.M., Marcon, E. and Puech, F. (2018)\n  *Handbook of Spatial Analysis: Theory and Application with R*.\n  Section 4.3.2 states the identification problem between first- and second-order effects that\n  limits the whole exercise; section 4.5.1 sets out the Kd function I describe but do not run.\n\n## References\n\n- Baddeley, A., Rubak, E. and Turner, R. (2015) *Spatial Point Patterns: Methodology and\n  Applications with R*, Chapman and Hall/CRC.\n  Section 3.4.4 is why the exercise checks for coincident points before running anything.\n- O'Sullivan, D. and Unwin, D. (2010) *Geographic Information Analysis*, Second Edition. John\n  Wiley & Sons, New Jersey.\n  Definitions of the modifiable areal unit problem, used in the quadrat section, and of edge\n  effects, used when the study window is buffered.\n- *Chapter 11 Point Pattern Analysis* of **Intro to GIS and Spatial Analysis**, sections 11.2,\n  11.3, 11.3.1 and 11.4.\n  Section 11.3.3 of the same chapter introduces the pair correlation function as a\n  non-cumulative alternative to K, which is what corrects the reading of the inhomogeneous L\n  curve. Rendered version consulted at\n  <https://rstudio-pubs-static.s3.amazonaws.com/481933_61ed3eff92e74c04a52d44a48b1b4548.html>.\n\n## Applications\n\n- Donthu, N. and Rust, R. T. (1989) \"Estimating Geographic Customer Densities Using Kernel\n  Density Estimation\", *Marketing Science*, 8(2), pp. 191-203.\n  Their normal-reference bandwidth rule is `bw.scott`, tested here against the chapters'\n  default.\n- Wartman, J. and Malasavage, N. E. (2010) \"Spatial Analysis for Identifying Concentrations of\n  Urban Damage\", in *Methods and Techniques in Urban Engineering*, InTech.\n  The argument that the study area must be set objectively, which the window test supports.\n- Borruso, G. and Porceddu, A. (2009) \"A Tale of Two Cities: Density Analysis of CBD on Two\n  Midsize Urban Areas in Northeastern Italy\", in *Studies in Computational Intelligence,\n  Geocomputation and Urban Planning*, pp. 37-56.\n  The claim that bandwidth is the only arbitrary variable, discussed alongside Wartman.\n\n## Enrichment\n\n- Prof. Luc Anselin on point pattern analysis (YouTube). Of the six parts, this exercise uses\n  *Point Pattern Analysis: Quadrat Counts* for the quadrat method and the variance-mean ratio,\n  and *Point Pattern Analysis: F and J Functions* for the J function. *Point Pattern Analysis:\n  K, L and Kd Functions* covers the Kd indicator discussed in Part 3.\n\n## Cited within the above\n\n- Clark, P. J. and Evans, F. C. (1954), for the nearest-neighbour index used throughout Part 1.\n- Duranton, G. and Overman, H. G. (2005), for the Kd function, via Floch et al. and Anselin.\n\n---\n\n*Data: childcare centres, Early Childhood Development Agency via Data.gov.sg (geocoded\nedition); planning subzones, URA 2019 Master Plan, Data.gov.sg; resident population, Singapore\nCensus 2020 via Data.gov.sg. Analysis in R with `spatstat`, `sf`, `terra` and `tmap`.*\n",
    "supporting": [
      "Hands-on_Ex02_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}