{
  "hash": "741bd4b281ed0d911bd93c95b776544a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Hands-on Exercise 1\"\nsubtitle: \"Geospatial Data Wrangling and Choropleth Mapping with R\"\nauthor: \"An Loc\"\ndate: \"last-modified\"\ndate-format: \"D MMM YYYY\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: false\n    code-copy: true\n    fig-width: 9\n    fig-height: 7\nexecute:\n  echo: true\n  eval: true\n  warning: false\n  message: false\n  freeze: true\n---\n\n# Overview\n\nThis exercise has three parts.\n\n**Part 1** covers the data preparation: importing vector data from several sources, getting\ntheir coordinate reference systems to agree, converting a table of coordinates into a spatial\nobject, and answering two questions using geoprocessing.\n\n**Part 2** joins population data to the subzone boundaries and maps it as a choropleth. Most of\nthe work there is about choosing a classification scheme rather than accepting the default.\n\n**Part 3** goes beyond what the chapters ask for. I wanted to check how much the conclusions\ndepend on the classification I picked, whether the pattern holds when the spatial units change,\nand whether bringing in a second dataset could explain the pattern instead of just describing\nit.\n\n::: {.callout-note appearance=\"simple\"}\n## Reference\n\nr4gdsa [Chapter 1 — Geospatial Data Science with R](https://r4gdsa.netlify.app/chap01.html)\nand [Chapter 2 — Thematic Mapping and GeoVisualisation with R](https://r4gdsa.netlify.app/chap02.html).\n:::\n\n::: {.callout-note appearance=\"simple\"}\n## Anselin's four types of spatial data\n\nThe pre-lesson lecture by Luc Anselin, *\"Spatial Data, Spatial Analysis, Spatial Data\nScience\"*, sets out four types of spatial data. Three of them show up in this exercise:\n\n| Anselin's type | In this exercise | Note |\n|---|---|---|\n| **Points** | Pre-schools, Airbnb listings | He separates points that are *events* (crimes, accidents) from points that are *locations of objects* (stores, facilities). Ours are the second kind |\n| **Lattice / areal units** | Subzone polygons | His term for administrative zones. Relevant later, since MAUP is a lattice problem |\n| **Networks** | Cycling paths | Nodes and links. Treated as plain lines here. Network-constrained analysis comes in Lesson 7 |\n| **Surfaces** | *not used* | Continuous fields needing interpolation, like air quality or price surfaces |\n\nHe also names the standard that the `sf` package implements: the **Simple Features\nspecification** from the Open Geospatial Consortium. That is where the name \"sf\" comes from,\nand why every function starts with `st_` (spatial type).\n\nHe also poses the problem that §\"How many pre-schools are in each subzone?\" solves below:\n*\"You look at the map, you know immediately that city is in that county. How would a computer\nknow that that point is inside that polygon?\"* In R, the answer is `st_intersects()`.\n:::\n\n::: {.callout-note appearance=\"simple\"}\n## Xie et al. on the three foundations\n\nThe second pre-lesson reading, Xie et al. (2017), *\"Transdisciplinary Foundations of Geospatial\nData Science\"*, argues that every geospatial technique rests on three foundations, and that\nproblems arise when any of them is treated as a black box. All three appear in this exercise:\n\n| Foundation | Their concern | Where it appears below |\n|---|---|---|\n| **Mathematics** | Geometry, topology, projection | The CRS transform to EPSG:3414, and `st_intersects()` as a topological predicate rather than a lookup |\n| **Statistics** | Spatial data violate the i.i.d. assumption most methods rely on | The correlation in Part 3, and the caveat attached to it |\n| **Computer science** | Efficiency, scalability, filter-and-refine | `st_intersects()` builds a spatial index instead of testing 323 × 2,290 pairs |\n\nOne warning from the paper is useful throughout: *\"traditional density-based clustering methods\nwill generally output chance patterns if applied to geospatial hotspot detection\"*. K-means will\nfind clusters in pure noise, so finding a pattern is not by itself evidence that one exists.\nAnselin makes the same point with his shuffled map.\n:::\n\n# Getting started\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(sf, tmap, tidyverse, ggplot2, knitr, classInt, units)\n```\n:::\n\n\n::: {.callout-note appearance=\"simple\"}\n## `pacman::p_load()` versus `library()`\n\n`p_load()` installs a package if it is missing and then loads it. That means the document will\nstill run on a machine that does not already have every dependency installed, which matters more\nfor a reproducible report than the couple of keystrokes it saves.\n:::\n\n## Note on tmap versions\n\nThe course materials are written for `tmap` v3, but the version installed on my machine is v4,\nwhere several function names and the whole scale and legend argument system changed. The v3 code\nstill runs through a compatibility layer, but it prints `[v3->v4]` deprecation messages\nconstantly, which made the output hard to read.\n\nI used v4 syntax throughout. These are the substitutions I made:\n\n| v3 | v4 |\n|---|---|\n| `tm_fill(col = \"X\", style = \"quantile\", palette = \"Blues\")` | `tm_polygons(fill = \"X\", fill.scale = tm_scale_intervals(style = \"quantile\", values = \"brewer.blues\"))` |\n| `tm_layout(main.title = \"...\")` | `tm_title(\"...\")` |\n| `tm_scale_bar()` | `tm_scalebar()` |\n| `tm_polygons(col = \"X\")` | `tm_polygons(fill = \"X\")`, since `col` now sets the border colour |\n\n\n::: {.cell}\n\n```{.r .cell-code}\npackageVersion(\"tmap\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] '4.4.1'\n```\n\n\n:::\n:::\n\n\n# Data provenance\n\n::: {.callout-important}\n## The dataset named in the chapter has no file attached\n\nChapter 1 specifies **Master Plan 2014 Subzone Boundary (Web)**. Its\n[collection page](https://data.gov.sg/collections/1708/view) is still live on data.gov.sg, but\nthere is no dataset file attached to it. The collections API reports zero child datasets for it,\nwhile every comparable collection (MP2019 Subzone No Sea, MP2019 Region No Sea, and the others\nin the series) reports one. So the page can be browsed but the data cannot be downloaded.\n\n::: {.callout-note appearance=\"simple\"}\n## How I checked, including the wrong way\n\nMy first check was the older URL\n`data.gov.sg/dataset/master-plan-2014-subzone-boundary-web`, which returns \"Dataset not found\".\nI initially took that as proof the dataset had been withdrawn, but it isn't. That older\n`/dataset/<slug>` route returns the same error for datasets that are definitely still available,\nincluding Pre-Schools Location and MP2014 (No Sea), both of which I downloaded for this exercise\nwithout any trouble.\n\nThe check that actually works is the current API, which distinguishes a collection that has\nfiles from one that is empty:\n\n```\nhttps://api-production.data.gov.sg/v2/public/api/collections/{id}/metadata  →  childDatasets[]\n```\n\nI am recording this because the wrong conclusion was easy to reach and looked well evidenced at\nthe time.\n:::\n\nI made two substitutions, and have recorded both rather than changing them silently:\n\n- **Master Plan 2014 Subzone Boundary (No Sea)**\n  ([`d_226cacceceff94f0c8b814962a5307c9`](https://data.gov.sg/datasets/d_226cacceceff94f0c8b814962a5307c9/view))\n  replaces the (Web) variant in Part 1. Both use the same 2014 boundary definition and differ in\n  where the polygons stop at the coast. \"(No Sea)\" is clipped to the coastline, while \"(Web)\" is\n  the version published on URA's website and OneMap, where coastal subzones extend out over\n  territorial waters.\n\n  ⚠️ URA's published descriptions of the two variants are almost identical boilerplate and do\n  not actually state this difference. I am going by the naming convention, and I cannot check it\n  against the (Web) file since that file is not downloadable. What I can measure is that the\n  (No Sea) layer totals\n  **782 km²**\n  against Singapore's ~734 km² land area, the excess being reservoirs and inland water.\n\n  For this exercise (No Sea) is the better choice anyway. Sea polygons contain no pre-schools\n  but would increase subzone areas, which would distort the density measure.\n- **Master Plan 2019 Subzone Boundary (No Sea)** is used for Part 2, matching the current\n  chapter 2 text.\n\nSeparately, data.gov.sg now serves GeoJSON where the chapter expects shapefile or KML. Prof Kam\nconfirmed on Piazza that this is fine. GeoJSON is a single self-describing file that always\ndeclares WGS84 by specification, whereas a shapefile is a bundle of several files whose `.prj`\ncomponent can be missing or wrong, which is the same failure mode the CRS section below deals\nwith.\n:::\n\n| Dataset | Source | Format | Retrieved | Native CRS |\n|---|---|---|---|---|\n| Master Plan 2014 Subzone Boundary (No Sea) | data.gov.sg (URA) | GeoJSON | 25 Aug 2026 | WGS84 (EPSG:4326) |\n| Master Plan 2019 Subzone Boundary (No Sea) | data.gov.sg (URA) | GeoJSON | 25 Aug 2026 | WGS84 (EPSG:4326) |\n| Pre-Schools Location | data.gov.sg (ECDA) | GeoJSON | 25 Aug 2026 | WGS84 (EPSG:4326) |\n| Cycling Path Network | data.gov.sg (LTA) | GeoJSON | 25 Aug 2026 | WGS84 (EPSG:4326) |\n| Singapore Airbnb listings | Inside Airbnb, 29 Jun 2026 snapshot | CSV | 25 Aug 2026 | none — lat/long columns |\n| Resident population by subzone, age and sex | data.gov.sg (SingStat, Census 2020) | CSV | 25 Aug 2026 | none — subzone name key |\n\nAll six can be downloaded without an account or API key. Each one comes from the source listed\nabove, so this page can be reproduced from a clean machine.\n\n# Part 1 — Geospatial Data Wrangling\n\n## Importing geospatial data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz14 <- st_read(\"data/geospatial/MasterPlan2014SubzoneBoundaryNoSea.geojson\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `MP14_SUBZONE_NO_SEA_PL' from data source \n  `/Users/AnLoc/Documents/GitHub/ISSS626-GAA/Hands-on_Ex/Hands-on_Ex01/data/geospatial/MasterPlan2014SubzoneBoundaryNoSea.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 323 features and 13 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 103.6057 ymin: 1.158699 xmax: 104.0885 ymax: 1.470775\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncyclingpath <- st_read(\"data/geospatial/CyclingPathNetwork.geojson\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `CYCLINGPATH' from data source \n  `/Users/AnLoc/Documents/GitHub/ISSS626-GAA/Hands-on_Ex/Hands-on_Ex01/data/geospatial/CyclingPathNetwork.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 8523 features and 6 fields\nGeometry type: MULTILINESTRING\nDimension:     XY\nBounding box:  xmin: 103.637 ymin: 1.265428 xmax: 103.9664 ymax: 1.467361\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npreschool <- st_read(\"data/geospatial/PreSchoolsLocation.geojson\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `PreSchoolsLocation' from data source \n  `/Users/AnLoc/Documents/GitHub/ISSS626-GAA/Hands-on_Ex/Hands-on_Ex01/data/geospatial/PreSchoolsLocation.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 2290 features and 2 fields\nGeometry type: POINT\nDimension:     XYZ\nBounding box:  xmin: 103.6878 ymin: 1.247759 xmax: 103.9897 ymax: 1.462134\nz_range:       zmin: 0 zmax: 0\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\n::: {.callout-tip appearance=\"simple\"}\n## What `st_read()` prints\n\nThere are three useful things in that output.\n\n**Feature count and geometry type.** 323 `POLYGON` subzones, 8,523 `LINESTRING` cycling paths\nand 2,290 `POINT` pre-schools. The geometry type limits which operations make sense. You can\nbuffer a line, but computing its area would be meaningless.\n\n**The bounding box.** The values here are around `103.6` to `104.1` and `1.2` to `1.5`, which\nare longitude and latitude in degrees. If they were in the hundreds of thousands they would be\nmetres in a projected system. This is the quickest way to check the data arrived in the CRS you\nexpected.\n\n**The declared CRS.** `WGS 84` in all three cases. The next section covers why that is a\nproblem.\n:::\n\n## Inspecting the feature data frame\n\nAn `sf` object is a data frame with an extra geometry column. All the `dplyr` verbs work on it,\nand the geometry stays attached to the rows as you filter and mutate.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nst_geometry(mpsz14)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGeometry set for 323 features \nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 103.6057 ymin: 1.158699 xmax: 104.0885 ymax: 1.470775\nGeodetic CRS:  WGS 84\nFirst 5 geometries:\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(mpsz14)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 323\nColumns: 14\n$ OBJECTID_1   <int> 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 3…\n$ SUBZONE_NO   <int> 2, 2, 3, 4, 5, 4, 10, 12, 4, 6, 1, 1, 3, 8, 3, 7, 9, 2, 1…\n$ SUBZONE_N    <chr> \"PEOPLE'S PARK\", \"BUKIT MERAH\", \"CHINATOWN\", \"PHILLIP\", \"…\n$ SUBZONE_C    <chr> \"OTSZ02\", \"BMSZ02\", \"OTSZ03\", \"DTSZ04\", \"DTSZ05\", \"OTSZ04…\n$ CA_IND       <chr> \"Y\", \"N\", \"Y\", \"Y\", \"Y\", \"Y\", \"N\", \"Y\", \"N\", \"Y\", \"Y\", \"Y…\n$ PLN_AREA_N   <chr> \"OUTRAM\", \"BUKIT MERAH\", \"OUTRAM\", \"DOWNTOWN CORE\", \"DOWN…\n$ PLN_AREA_C   <chr> \"OT\", \"BM\", \"OT\", \"DT\", \"DT\", \"OT\", \"BM\", \"DT\", \"BM\", \"DT…\n$ REGION_N     <chr> \"CENTRAL REGION\", \"CENTRAL REGION\", \"CENTRAL REGION\", \"CE…\n$ REGION_C     <chr> \"CR\", \"CR\", \"CR\", \"CR\", \"CR\", \"CR\", \"CR\", \"CR\", \"CR\", \"CR…\n$ INC_CRC      <chr> \"B4120D23006C932A\", \"1C51019439A68700\", \"0FF1661344C84AED…\n$ FMEL_UPD_D   <chr> \"20160511160621\", \"20160511160621\", \"20160511160621\", \"20…\n$ SHAPE_1.AREA <dbl> 93140.44, 411722.82, 587222.68, 39437.94, 188767.49, 1330…\n$ SHAPE_1.LEN  <dbl> 1822.1927, 3074.9632, 4297.5999, 871.5549, 1872.7522, 160…\n$ geometry     <MULTIPOLYGON [°]> MULTIPOLYGON (((103.8432 1...., MULTIPOLYGON…\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(mpsz14, n = 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 3 features and 13 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 103.8131 ymin: 1.274155 xmax: 103.8492 ymax: 1.285248\nGeodetic CRS:  WGS 84\n  OBJECTID_1 SUBZONE_NO     SUBZONE_N SUBZONE_C CA_IND  PLN_AREA_N PLN_AREA_C\n1         21          2 PEOPLE'S PARK    OTSZ02      Y      OUTRAM         OT\n2         22          2   BUKIT MERAH    BMSZ02      N BUKIT MERAH         BM\n3         23          3     CHINATOWN    OTSZ03      Y      OUTRAM         OT\n        REGION_N REGION_C          INC_CRC     FMEL_UPD_D SHAPE_1.AREA\n1 CENTRAL REGION       CR B4120D23006C932A 20160511160621     93140.44\n2 CENTRAL REGION       CR 1C51019439A68700 20160511160621    411722.82\n3 CENTRAL REGION       CR 0FF1661344C84AED 20160511160621    587222.68\n  SHAPE_1.LEN                       geometry\n1    1822.193 MULTIPOLYGON (((103.8432 1....\n2    3074.963 MULTIPOLYGON (((103.8221 1....\n3    4297.600 MULTIPOLYGON (((103.8438 1....\n```\n\n\n:::\n:::\n\n\n::: {.callout-note appearance=\"simple\"}\n## Comparing the three inspection functions\n\n`st_geometry()` shows the geometry type, bounding box and CRS, and nothing about the attributes.\n`glimpse()` shows which columns exist and what type each one is, which is how you catch a numeric\nfield that has arrived as character. `head()` shows what an actual record looks like, with\nattributes and geometry together.\n:::\n\n## Working with projection\n\n\n::: {.cell}\n\n```{.r .cell-code}\nst_crs(mpsz14)$input\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"WGS 84\"\n```\n\n\n:::\n\n```{.r .cell-code}\nst_crs(cyclingpath)$input\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"WGS 84\"\n```\n\n\n:::\n\n```{.r .cell-code}\nst_crs(preschool)$input\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"WGS 84\"\n```\n\n\n:::\n:::\n\n\nAll three arrived as WGS84 (EPSG:4326), a geographic CRS whose units are degrees, which is not\nusable for anything involving distance or area. A one-degree buffer would be roughly 111 km, and\nnear the equator a degree of longitude and a degree of latitude are not the same distance on the\nground anyway.\n\nSingapore's national projected CRS is SVY21, EPSG:3414, and its units are metres.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz14      <- st_transform(mpsz14, crs = 3414)\ncyclingpath <- st_transform(cyclingpath, crs = 3414)\npreschool   <- st_transform(preschool, crs = 3414)\n\nst_bbox(mpsz14)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     xmin      ymin      xmax      ymax \n 2667.538 15748.721 56396.440 50256.334 \n```\n\n\n:::\n:::\n\n\nThe bounding box now shows six-figure easting and northing values instead of degrees, so the\ntransform worked.\n\n::: {.callout-important}\n## Difference between `st_set_crs()` and `st_transform()`\n\nThese two are easy to confuse and I want to be able to state the difference precisely.\n\n`st_set_crs()` changes the label on the coordinates without touching the numbers. It asserts\nthat the numbers were always in that system. It should only be used when the data arrived with a\nmissing or wrong CRS tag and you know what the correct one is.\n\n`st_transform()` changes the numbers, recalculating every coordinate into the target system. It\nis what you use when you actually need the data in a different CRS.\n\nUsing the wrong one produces no error and no warning. You just get a layer sitting off the coast\nof Africa, or distances wrong by a factor of 100,000, and nothing downstream will flag it.\n:::\n\n## Trying the KML version\n\nWhen a classmate asked on Piazza whether GeoJSON was acceptable given that data.gov.sg no longer\nserves KML, Prof Kam replied: *\"It is fine. However, there is nothing wrong to explore the kml\nvery. You will learn more by trying.\"*\n\nSo I tried it. Writing one layer out to KML and reading it straight back shows what the format\ncosts.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndir.create(\"data/geospatial/kml\", recursive = TRUE, showWarnings = FALSE)\n\nst_write(mpsz14,\n         \"data/geospatial/kml/MP14_Subzone.kml\",\n         driver = \"KML\",\n         delete_dsn = TRUE,\n         quiet = TRUE)\n\nmpsz14_kml <- st_read(\"data/geospatial/kml/MP14_Subzone.kml\", quiet = TRUE)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(\n  aspect = c(\"Number of attribute columns\", \"Column names\", \"CRS\", \"Feature count\"),\n  geojson = c(as.character(ncol(mpsz14) - 1),\n              paste(head(setdiff(names(mpsz14), \"geometry\"), 4), collapse = \", \"),\n              st_crs(mpsz14)$input,\n              as.character(nrow(mpsz14))),\n  kml = c(as.character(ncol(mpsz14_kml) - 1),\n          paste(head(setdiff(names(mpsz14_kml), \"geometry\"), 4), collapse = \", \"),\n          st_crs(mpsz14_kml)$input,\n          as.character(nrow(mpsz14_kml)))\n) %>%\n  kable(caption = \"What survives a round trip through KML\")\n```\n\n::: {.cell-output-display}\n\n\nTable: What survives a round trip through KML\n\n|aspect                      |geojson                                      |kml               |\n|:---------------------------|:--------------------------------------------|:-----------------|\n|Number of attribute columns |13                                           |2                 |\n|Column names                |OBJECTID_1, SUBZONE_NO, SUBZONE_N, SUBZONE_C |Name, Description |\n|CRS                         |EPSG:3414                                    |WGS 84            |\n|Feature count               |323                                          |323               |\n\n\n:::\n:::\n\n\n::: {.callout-important}\n## What changed after the KML round trip\n\n**The attribute table collapsed.** All the named columns, `SUBZONE_N`, `PLN_AREA_N`, `REGION_N`\nand the rest, were flattened into a generic `Name` field and a `Description` field containing an\nHTML fragment. The geometry came back intact but the schema did not. To analyse the result I\nwould have to parse the attributes back out of HTML strings, which is the same state the\nPre-Schools GeoJSON arrives in.\n\n**The CRS reverted to WGS84.** The KML specification requires WGS84, so `st_write()` reprojected\nout of the SVY21 metres I had just transformed into, without warning me. Reading it back gives\ndegrees again, and every buffer and area calculation in this document would be wrong until I\ntransformed it a second time.\n\nThis does not mean KML is bad, just that it is a presentation format, designed for drawing\nthings in Google Earth where a person reads the description bubble. GeoJSON and shapefile are\nanalysis formats that keep typed attribute columns and let you declare a projected CRS. The\nchapter's instruction to use shapefile or KML predates data.gov.sg switching to GeoJSON, and for\nthis work GeoJSON is the best of the three.\n:::\n\n## Importing and converting aspatial data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlistings <- read_csv(\"data/aspatial/listings.csv\", show_col_types = FALSE)\nglimpse(listings)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 3,247\nColumns: 19\n$ id                             <dbl> 71609, 71896, 71903, 294281, 344803, 36…\n$ name                           <chr> \"Ensuite Room (Room 1 & 2) near EXPO\", …\n$ host_id                        <dbl> 367042, 367042, 367042, 1521514, 367042…\n$ host_profile_id                <dbl> 1.462517e+18, 1.462517e+18, 1.462517e+1…\n$ host_name                      <chr> \"Belinda\", \"Belinda\", \"Belinda\", \"Elizb…\n$ neighbourhood_group            <chr> \"East Region\", \"East Region\", \"East Reg…\n$ neighbourhood                  <chr> \"Tampines\", \"Tampines\", \"Tampines\", \"Ne…\n$ latitude                       <dbl> 1.34537, 1.34754, 1.34531, 1.31142, 1.3…\n$ longitude                      <dbl> 103.9589, 103.9596, 103.9610, 103.8392,…\n$ room_type                      <chr> \"Private room\", \"Private room\", \"Privat…\n$ price                          <dbl> NA, NA, NA, 32, 15, NA, 26, 11, 28, 48,…\n$ minimum_nights                 <dbl> 92, 92, 92, 92, 92, 92, 92, 92, 92, 92,…\n$ number_of_reviews              <dbl> 19, 24, 46, 131, 60, 81, 163, 20, 0, 17…\n$ last_review                    <date> 2020-01-17, 2019-10-13, 2020-01-09, 20…\n$ reviews_per_month              <dbl> 0.11, 0.13, 0.25, 0.75, 0.34, 0.52, 0.9…\n$ calculated_host_listings_count <dbl> 5, 5, 5, 7, 5, 7, 7, 4, 2, 1, 8, 1, 73,…\n$ availability_365               <dbl> 90, 90, 90, 364, 364, 364, 364, 364, 36…\n$ number_of_reviews_ltm          <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ license                        <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n```\n\n\n:::\n:::\n\n\nThe file has `latitude` and `longitude` columns but no geometry, so R treats it as an ordinary\ntable. `st_as_sf()` converts it into a spatial object.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlistings_sf <- st_as_sf(listings,\n                        coords = c(\"longitude\", \"latitude\"),\n                        crs = 4326) %>%\n  st_transform(crs = 3414)\n\nglimpse(listings_sf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 3,247\nColumns: 18\n$ id                             <dbl> 71609, 71896, 71903, 294281, 344803, 36…\n$ name                           <chr> \"Ensuite Room (Room 1 & 2) near EXPO\", …\n$ host_id                        <dbl> 367042, 367042, 367042, 1521514, 367042…\n$ host_profile_id                <dbl> 1.462517e+18, 1.462517e+18, 1.462517e+1…\n$ host_name                      <chr> \"Belinda\", \"Belinda\", \"Belinda\", \"Elizb…\n$ neighbourhood_group            <chr> \"East Region\", \"East Region\", \"East Reg…\n$ neighbourhood                  <chr> \"Tampines\", \"Tampines\", \"Tampines\", \"Ne…\n$ room_type                      <chr> \"Private room\", \"Private room\", \"Privat…\n$ price                          <dbl> NA, NA, NA, 32, 15, NA, 26, 11, 28, 48,…\n$ minimum_nights                 <dbl> 92, 92, 92, 92, 92, 92, 92, 92, 92, 92,…\n$ number_of_reviews              <dbl> 19, 24, 46, 131, 60, 81, 163, 20, 0, 17…\n$ last_review                    <date> 2020-01-17, 2019-10-13, 2020-01-09, 20…\n$ reviews_per_month              <dbl> 0.11, 0.13, 0.25, 0.75, 0.34, 0.52, 0.9…\n$ calculated_host_listings_count <dbl> 5, 5, 5, 7, 5, 7, 7, 4, 2, 1, 8, 1, 73,…\n$ availability_365               <dbl> 90, 90, 90, 364, 364, 364, 364, 364, 36…\n$ number_of_reviews_ltm          <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ license                        <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ geometry                       <POINT [m]> POINT (41972.5 36390.05), POINT (…\n```\n\n\n:::\n:::\n\n\n::: {.callout-warning}\n## `coords` takes longitude first\n\nThe argument is `coords = c(\"longitude\", \"latitude\")`, x before y. Writing\n`c(\"latitude\",\"longitude\")` does not throw an error. It just places every Singapore listing at\nabout 1°E, 103°N, which is in the Arctic Ocean north of Norway.\n\nThe `crs = 4326` argument here is doing the labelling job described in the previous section. The\nnumbers are already in degrees, so I tag them correctly first and only then transform to metres.\nSetting `crs = 3414` at this point would claim the degree values were metres and put every\nlisting within a kilometre of the origin.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nst_bbox(listings_sf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     xmin      ymin      xmax      ymax \n 5881.388 22827.701 44899.773 48821.856 \n```\n\n\n:::\n:::\n\n\nThe bounding box falls within Singapore, so the coordinate order was right.\n\n## Geoprocessing\n\n### How much land is within 5 m of a cycling path?\n\nThis is a buffer and area problem. The scenario is that LTA wants to know how much land would be\nneeded to widen the entire cycling network by 5 m on each side.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbuffer_cycling <- st_buffer(cyclingpath, dist = 5, nQuadSegs = 30)\nbuffer_cycling$AREA <- st_area(buffer_cycling)\nsum(buffer_cycling$AREA)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n4989654 [m^2]\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntotal_ha <- sum(buffer_cycling$AREA) %>% units::set_units(\"hectares\")\ntotal_ha\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n498.9654 [hectares]\n```\n\n\n:::\n:::\n\n\n::: {.callout-note appearance=\"simple\"}\n## Notes on this figure\n\n**The units are carried by the object.** `st_area()` returns a `units` object, so `sum()`\nreports m² explicitly and `set_units()` converts safely. Whether the `5` meant five metres or\nfive degrees is exactly what the earlier transform to EPSG:3414 settled. In WGS84 this buffer\nwould have been about 555 km wide.\n\n**This total double-counts the overlaps.** Where two cycling paths run close together their\nbuffers intersect, and summing the per-feature areas counts that shared land twice. For a land\nacquisition estimate the buffers should be dissolved first:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndissolved_ha <- buffer_cycling %>%\n  st_union() %>%\n  st_area() %>%\n  units::set_units(\"hectares\")\n\ndissolved_ha\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n431.5118 [hectares]\n```\n\n\n:::\n:::\n\n\nThe difference between the two figures is the overlapping area, and it is not small. Reporting\nthe first number as a land requirement would overstate it.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\noverlap_pct <- as.numeric((total_ha - dissolved_ha) / total_ha * 100)\nsprintf(\"Naive sum overstates the true footprint by %.1f%%\", overlap_pct)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Naive sum overstates the true footprint by 13.5%\"\n```\n\n\n:::\n:::\n\n\n### How many pre-schools are in each subzone?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz14$PreSch_Count <- lengths(st_intersects(mpsz14, preschool))\n\nsummary(mpsz14$PreSch_Count)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n   0.00    0.00    4.00    7.09   10.00   72.00 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz14 %>%\n  st_drop_geometry() %>%\n  select(SUBZONE_N, PLN_AREA_N, PreSch_Count) %>%\n  arrange(desc(PreSch_Count)) %>%\n  head(10) %>%\n  kable(caption = \"Subzones with the most pre-schools\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Subzones with the most pre-schools\n\n|SUBZONE_N            |PLN_AREA_N  | PreSch_Count|\n|:--------------------|:-----------|------------:|\n|TAMPINES EAST        |TAMPINES    |           72|\n|WOODLANDS EAST       |WOODLANDS   |           54|\n|ALJUNIED             |GEYLANG     |           40|\n|TAMPINES WEST        |TAMPINES    |           38|\n|BEDOK NORTH          |BEDOK       |           38|\n|FRANKEL              |BEDOK       |           36|\n|SENGKANG TOWN CENTRE |SENGKANG    |           33|\n|YUNNAN               |JURONG WEST |           32|\n|HONG KAH             |JURONG WEST |           30|\n|BEDOK SOUTH          |BEDOK       |           29|\n\n\n:::\n:::\n\n\n::: {.callout-note appearance=\"simple\"}\n## What `st_intersects()` returns\n\nIt does not return a count. It returns a list with one element per subzone, each holding the row\nindices of every pre-school that falls inside it. `lengths()`, plural, then measures each element\nof that list. Using `length()` instead would return a single number, 323, which is just the\nnumber of subzones.\n\nThe list of indices is more useful than a count would be, since it lets you go back and ask\nwhich pre-schools rather than only how many.\n:::\n\n### Pre-school density\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz14$Area_sqkm <- st_area(mpsz14) %>%\n  units::set_units(\"km^2\") %>%\n  as.numeric()\n\nmpsz14$PreSch_Density <- mpsz14$PreSch_Count / mpsz14$Area_sqkm\n\nmpsz14 %>%\n  st_drop_geometry() %>%\n  select(SUBZONE_N, PreSch_Count, Area_sqkm, PreSch_Density) %>%\n  arrange(desc(PreSch_Density)) %>%\n  head(10) %>%\n  mutate(across(where(is.numeric), ~round(.x, 2))) %>%\n  kable(caption = \"Highest pre-school density (per km squared)\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Highest pre-school density (per km squared)\n\n|SUBZONE_N            | PreSch_Count| Area_sqkm| PreSch_Density|\n|:--------------------|------------:|---------:|--------------:|\n|CECIL                |            7|      0.20|          35.60|\n|MANDAI ESTATE        |            5|      0.14|          34.93|\n|SEMBAWANG CENTRAL    |           27|      0.96|          28.05|\n|PHILLIP              |            1|      0.04|          25.36|\n|SERANGOON NORTH      |           17|      0.68|          24.83|\n|SENGKANG TOWN CENTRE |           33|      1.46|          22.67|\n|WOODLANDS EAST       |           54|      2.55|          21.15|\n|KATONG               |           22|      1.08|          20.39|\n|MIDVIEW              |           19|      0.94|          20.29|\n|KEAT HONG            |           23|      1.14|          20.11|\n\n\n:::\n:::\n\n\nDensity and count rank the subzones quite differently. The highest count is in a large\nresidential town, while the highest density tends to be a small, dense subzone. Which measure is\nright depends on whether the question is about provision relative to land area or provision in\nabsolute terms.\n\n## Exploratory data analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = mpsz14, aes(x = PreSch_Density)) +\n  geom_histogram(bins = 20, color = \"black\", fill = \"#5DA5DA\") +\n  labs(title = \"Pre-school density is strongly right-skewed\",\n       subtitle = \"Most subzones have none; a few have many per square kilometre\",\n       x = \"Pre-schools per square kilometre\",\n       y = \"Number of subzones\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex01_files/figure-html/eda-hist-1.png){width=864}\n:::\n:::\n\n\nThis skew turns out to matter a lot in Part 2. A variable shaped like this gets classified very\ndifferently by an equal-interval scheme than by a quantile scheme, which is what the\nclassification section tests.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = mpsz14, aes(x = PreSch_Count, y = PreSch_Density)) +\n  geom_point(alpha = 0.6, color = \"#4A6FA5\") +\n  labs(title = \"Count and density are only loosely related\",\n       subtitle = \"Large subzones can hold many pre-schools at low density\",\n       x = \"Pre-school count\", y = \"Pre-schools per square kilometre\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex01_files/figure-html/eda-scatter-1.png){width=864}\n:::\n:::\n\n\n# Part 2 — Choropleth Mapping\n\n## Importing the data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz19 <- st_read(\"data/geospatial/MasterPlan2019SubzoneBoundaryNoSea.geojson\") %>%\n  st_transform(crs = 3414)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `URA_MP19_SUBZONE_NO_SEA_PL' from data source \n  `/Users/AnLoc/Documents/GitHub/ISSS626-GAA/Hands-on_Ex/Hands-on_Ex01/data/geospatial/MasterPlan2019SubzoneBoundaryNoSea.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 332 features and 13 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 103.6057 ymin: 1.158699 xmax: 104.0885 ymax: 1.470775\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npopdata <- read_csv(\"data/aspatial/respop_census2020_agesex.csv\", show_col_types = FALSE)\ndim(popdata)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 388  61\n```\n\n\n:::\n:::\n\n\nThe table is in wide format, with one row per area and one column for each age band crossed with\nsex. The `Number` column holds the area name. Planning-area rows are marked with a `\" - Total\"`\nsuffix and subzone rows just carry a bare name.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npopdata %>% select(Number, Total_Total, Total_0_4, Total_65_69) %>% head(6) %>% kable()\n```\n\n::: {.cell-output-display}\n\n\n|Number                 |Total_Total |Total_0_4 |Total_65_69 |\n|:----------------------|:-----------|:---------|:-----------|\n|Total                  |4044210     |183080    |229400      |\n|Ang Mo Kio - Total     |162280      |5280      |11960       |\n|Ang Mo Kio Town Centre |4810        |170       |250         |\n|Cheng San              |28070       |1060      |2170        |\n|Chong Boon             |26500       |860       |2100        |\n|Kebun Bahru            |22620       |660       |1690        |\n\n\n:::\n:::\n\n\n### Every count column arrived as text\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(sapply(popdata, is.character))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 61\n```\n\n\n:::\n:::\n\n\nAll 61 columns came in as character, including the population counts. The cause is one token:\nSingStat writes suppressed or zero cells as `-`, and that forces `readr` to type the whole column\nas text.\n\n::: {.callout-warning}\n## Why the columns imported as text\n\n`rowSums()` on character columns errors immediately, which is the lucky outcome. The version that\nwould have caused real trouble is code that coerces silently and returns a wrong number that\nlooks plausible.\n\n`as.numeric(\"-\")` returns `NA` rather than zero. A straight conversion would push `NA` through\nevery age band containing a suppressed cell and quietly drop those subzones from the map. I read\n`-` as zero here, since the census uses it where the count is nil or has been suppressed for\ndisclosure control, and both cases mean there is no meaningful population in that cell.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nto_count <- function(x) {\n  x <- str_replace_all(x, \",\", \"\")   # thousands separators, if any\n  x[x == \"-\"] <- \"0\"                 # suppressed / nil\n  as.numeric(x)\n}\n\npopdata <- popdata %>%\n  mutate(across(-Number, to_count))\n\nsum(sapply(popdata, is.character))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1\n```\n\n\n:::\n:::\n\n\nOnly `Number` is still character, which is correct since it holds the area name.\n\n## Computing the dependency ratio\n\nThe age dependency ratio is the number of people not usually in the labour force, meaning\nchildren under 15 and adults 65 and over, per person of working age.\n\n$$\\text{Dependency} = \\frac{\\text{population}_{0-14} + \\text{population}_{65+}}{\\text{population}_{15-64}}$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nyoung_cols  <- c(\"Total_0_4\", \"Total_5_9\", \"Total_10_14\")\nactive_cols <- c(\"Total_15_19\",\"Total_20_24\",\"Total_25_29\",\"Total_30_34\",\"Total_35_39\",\n                 \"Total_40_44\",\"Total_45_49\",\"Total_50_54\",\"Total_55_59\",\"Total_60_64\")\naged_cols   <- c(\"Total_65_69\",\"Total_70_74\",\"Total_75_79\",\"Total_80_84\",\n                 \"Total_85_89\",\"Total_90andOver\")\n\npopdata_sz <- popdata %>%\n  filter(Number != \"Total\",\n         !str_detect(Number, \" - Total$\")) %>%\n  mutate(\n    SUBZONE_N = toupper(str_trim(Number)),\n    YOUNG     = rowSums(across(all_of(young_cols))),\n    ACTIVE    = rowSums(across(all_of(active_cols))),\n    AGED      = rowSums(across(all_of(aged_cols))),\n    TOTAL     = Total_Total,\n    DEPENDENCY = (YOUNG + AGED) / ACTIVE\n  ) %>%\n  select(SUBZONE_N, YOUNG, ACTIVE, AGED, TOTAL, DEPENDENCY)\n\nnrow(popdata_sz)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 333\n```\n\n\n:::\n:::\n\n\n## Joining the population data to the boundaries\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz_pop <- left_join(mpsz19 %>% mutate(SUBZONE_N = toupper(SUBZONE_N)),\n                      popdata_sz,\n                      by = \"SUBZONE_N\")\n\nn_total     <- nrow(mpsz_pop)\nn_unmatched <- sum(is.na(mpsz_pop$TOTAL))\nn_zero_act  <- sum(mpsz_pop$ACTIVE == 0, na.rm = TRUE)\n\ntibble(\n  metric = c(\"Subzone polygons\", \"No population record\", \"Matched but zero working-age population\"),\n  n      = c(n_total, n_unmatched, n_zero_act)\n) %>% kable(caption = \"Join diagnostics\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Join diagnostics\n\n|metric                                  |   n|\n|:---------------------------------------|---:|\n|Subzone polygons                        | 332|\n|No population record                    |   0|\n|Matched but zero working-age population |  98|\n\n\n:::\n:::\n\n\n::: {.callout-warning}\n## Checking the join\n\nTwo boundary definitions are being reconciled here. The population table is keyed to Census 2020\nsubzone names and the polygons to Master Plan 2019, so some level of non-match is expected. The\n`toupper()` call on both sides removes a case mismatch that would otherwise have failed most of\nthe join without any error.\n\nThe rows with zero working-age population matter more than they first appear. Dependency is a\nratio with `ACTIVE` in the denominator, so those subzones produce `Inf` rather than a large\nnumber. Industrial estates, reservoirs and military areas genuinely have no residents. Mapping\n`Inf` shows up as an unclassified hole, whereas mapping it as a high value would be inventing\ndata.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz_pop %>%\n  st_drop_geometry() %>%\n  filter(is.na(TOTAL)) %>%\n  select(SUBZONE_N, PLN_AREA_N) %>%\n  head(10) %>%\n  kable(caption = \"Sample of subzones with no matching population record\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Sample of subzones with no matching population record\n\n|SUBZONE_N |PLN_AREA_N |\n|:---------|:----------|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz_pop <- mpsz_pop %>%\n  mutate(DEPENDENCY = ifelse(is.finite(DEPENDENCY), DEPENDENCY, NA_real_))\n\nsummary(mpsz_pop$DEPENDENCY)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.     NAs \n0.08333 0.37552 0.44734 0.47927 0.50000 9.50000      98 \n```\n\n\n:::\n:::\n\n\n::: {.callout-note appearance=\"simple\"}\n## Choropleth as a histogram with location\n\nAnselin's definition is the one I found most useful: a choropleth is a histogram with the\nlocation made explicit. *\"Rather than just having a histogram as such, we will know where these\nbars for the histogram are in geographical space.\"*\n\nThis is useful in two places below. It explains why classification matters, since choosing class\nbreaks is the same act as choosing histogram bins, and nobody would accept arbitrary bins on a\nhistogram. It also sets up the test in Part 3, because if a map and a histogram carried the same\ninformation then the map would add nothing.\n:::\n\n## Plotting a choropleth quickly with `qtm()`\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\nqtm(mpsz_pop, fill = \"DEPENDENCY\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex01_files/figure-html/qtm-1.png){width=864}\n:::\n:::\n\n\nThis is quick and fine for looking at your own data, but not for showing anyone else. There is\nno title, no source, no explanation of the legend, and the classification is whatever the default\nhappens to be.\n\n## Building the map with `tmap` elements\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(mpsz_pop) +\n  tm_polygons(fill = \"DEPENDENCY\",\n              fill.scale = tm_scale_intervals(style = \"quantile\", n = 5,\n                                              values = \"brewer.blues\"),\n              fill.legend = tm_legend(title = \"Dependency\\nratio\"),\n              col = \"grey60\", lwd = 0.3,\n              fill.free = FALSE) +\n  tm_title(\"Age dependency ratio by subzone, Singapore\") +\n  tm_compass(type = \"8star\", size = 2, position = c(\"right\", \"top\")) +\n  tm_scalebar(position = c(\"left\", \"bottom\")) +\n  tm_grid(lwd = 0.1, col = \"grey85\") +\n  tm_credits(\"Source: Census of Population 2020 (SingStat);\\nURA Master Plan 2019 Subzone Boundary\",\n             position = c(\"left\", \"bottom\"), size = 0.6) +\n  tm_layout(frame = TRUE, legend.outside = TRUE)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex01_files/figure-html/tmap-full-1.png){width=864}\n:::\n:::\n\n\n::: {.callout-note appearance=\"simple\"}\n## What each element is for\n\n`tm_shape()` sets the data and every `tm_*` layer after it draws from that. `tm_polygons()`\nhandles fill and border together, and in v4 `fill` is the thematic variable while `col` is the\nborder colour. `tm_grid()` adds coordinate context. `tm_compass()` and `tm_scalebar()` are\nstandard cartographic elements. `tm_credits()` puts the source onto the map image itself, so it\nstays attributable if someone pulls the figure out of this document.\n:::\n\n## Classification methods\n\n`tmap` supports the standard data classification schemes. They are not just style options. Each\none makes a different claim about what the reader should be noticing.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmake_map <- function(style, title) {\n  tm_shape(mpsz_pop) +\n    tm_polygons(fill = \"DEPENDENCY\",\n                fill.scale = tm_scale_intervals(style = style, n = 5,\n                                                values = \"brewer.blues\"),\n                fill.legend = tm_legend(show = FALSE),\n                col = \"grey70\", lwd = 0.2) +\n    tm_title(title, size = 0.9)\n}\n\ntmap_arrange(\n  make_map(\"equal\",    \"equal — equal value ranges\"),\n  make_map(\"quantile\", \"quantile — equal counts\"),\n  make_map(\"jenks\",    \"jenks — natural breaks\"),\n  make_map(\"sd\",       \"sd — deviation from mean\"),\n  ncol = 2\n)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex01_files/figure-html/classification-compare-1.png){width=864}\n:::\n:::\n\n\n::: {.callout-important}\n## Comparing the four classification methods\n\nThese are four maps of the same numbers.\n\n**Equal interval** cuts the value range into equal-width bins. On a skewed variable this pushes\nalmost everything into the lowest class and the map ends up looking empty.\n\n**Quantile** puts an equal count of subzones into each class. It always produces a visually\nbalanced map, including when there is no real variation to show, which is the risk with it.\n\n**Jenks** minimises within-class variance and finds breaks at natural gaps in the distribution.\nIt is usually the most faithful to the structure, but the breaks depend on the data, so two maps\nmade this way cannot be compared to each other.\n\n**Standard deviation** shows distance from the mean. It answers a different question, which\nareas are unusual rather than how much there is.\n:::\n\n### Why two of those maps look empty\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvals_all <- mpsz_pop$DEPENDENCY[is.finite(mpsz_pop$DEPENDENCY)]\n\nclass_counts <- map_dfr(c(\"equal\",\"quantile\",\"jenks\",\"sd\"), function(st) {\n  brks <- classIntervals(vals_all, n = 5, style = st)$brks\n  tab  <- table(cut(vals_all, unique(brks), include.lowest = TRUE))\n  tibble(style = st,\n         `class 1` = tab[1], `class 2` = tab[2], `class 3` = tab[3],\n         `class 4` = tab[4], `class 5` = tab[5])\n})\n\nkable(class_counts, caption = \"How many subzones land in each class\")\n```\n\n::: {.cell-output-display}\n\n\nTable: How many subzones land in each class\n\n|style    | class 1| class 2| class 3| class 4| class 5|\n|:--------|-------:|-------:|-------:|-------:|-------:|\n|equal    |     233|       0|       0|       0|       1|\n|quantile |      47|      47|      46|      47|      47|\n|jenks    |      10|      82|      95|      46|       1|\n|sd       |     146|      87|       0|       0|       1|\n\n\n:::\n:::\n\n\n`equal` puts 233 of 234\nsubzones into the bottom class, and `sd` is almost as bad. Both are being distorted by one\nextreme value:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz_pop %>%\n  st_drop_geometry() %>%\n  filter(is.finite(DEPENDENCY)) %>%\n  arrange(desc(DEPENDENCY)) %>%\n  select(SUBZONE_N, PLN_AREA_N, YOUNG, ACTIVE, AGED, DEPENDENCY) %>%\n  head(5) %>%\n  mutate(DEPENDENCY = round(DEPENDENCY, 2)) %>%\n  kable(caption = \"The subzones driving the top of the range\")\n```\n\n::: {.cell-output-display}\n\n\nTable: The subzones driving the top of the range\n\n|SUBZONE_N          |PLN_AREA_N  | YOUNG| ACTIVE| AGED| DEPENDENCY|\n|:------------------|:-----------|-----:|------:|----:|----------:|\n|LOYANG WEST        |PASIR RIS   |     0|     20|  190|       9.50|\n|LAKESIDE (LEISURE) |JURONG EAST |    60|    600|  410|       0.78|\n|PEARL'S HILL       |OUTRAM      |   550|   3520| 2080|       0.75|\n|CRAWFORD           |KALLANG     |   660|   5110| 2620|       0.64|\n|SELEGIE            |ROCHOR      |    20|    130|   60|       0.62|\n\n\n:::\n:::\n\n\n::: {.callout-important}\n## The effect of one outlier\n\nThe maximum dependency ratio is 9.5 against a median of\n0.45, so roughly twenty times the typical value. It is not a data\nerror. It is a subzone with very few residents where the age mix happens to be extreme, and the\nsmall denominator produces a very large ratio.\n\nEqual-interval and standard-deviation both derive their breaks from the range, so that one\nsubzone stretches the whole scale and every other subzone falls into the first class. Quantile\nand Jenks derive their breaks from the ordering and the distribution instead, so they are not\naffected.\n\nThe practical rule is that range-based classification fails on a variable with outliers. You\neither use a rank or distribution based scheme, or handle the outlier explicitly and say which\nyou did.\n:::\n\n### How much does the choice actually change?\n\nRather than just assert that classification matters, I wanted to measure it. How many subzones\nactually change class when the scheme changes?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvals <- mpsz_pop$DEPENDENCY[!is.na(mpsz_pop$DEPENDENCY)]\n\nstyles <- c(\"equal\", \"quantile\", \"jenks\", \"sd\")\nclass_assign <- sapply(styles, function(s) {\n  brks <- classIntervals(vals, n = 5, style = s)$brks\n  as.integer(cut(vals, breaks = unique(brks), include.lowest = TRUE))\n})\ncolnames(class_assign) <- styles\n\npairs <- combn(styles, 2, simplify = FALSE)\nsens <- map_dfr(pairs, function(p) {\n  changed <- mean(class_assign[, p[1]] != class_assign[, p[2]], na.rm = TRUE) * 100\n  tibble(comparison = paste(p[1], \"vs\", p[2]),\n         pct_subzones_changing_class = round(changed, 1))\n}) %>% arrange(desc(pct_subzones_changing_class))\n\nkable(sens, caption = \"Share of subzones assigned to a different class under each pair of schemes\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Share of subzones assigned to a different class under each pair of schemes\n\n|comparison        | pct_subzones_changing_class|\n|:-----------------|---------------------------:|\n|equal vs jenks    |                        95.3|\n|jenks vs sd       |                        95.3|\n|equal vs quantile |                        79.5|\n|quantile vs sd    |                        79.5|\n|quantile vs jenks |                        56.4|\n|equal vs sd       |                        37.2|\n\n\n:::\n:::\n\n\n::: {.callout-tip}\n## What the sensitivity table shows\n\nEvery one of those maps is correct. The table puts a number on how much of the visual story\ncomes from a choice made in a single argument. Someone who saw only the equal-interval map and\nsomeone who saw only the quantile map would describe Singapore's dependency geography\ndifferently, and neither would have any reason to know it.\n\nFor this variable I would use Jenks for exploration, since it respects the actual distribution,\nand quantile only when comparing across time periods, where fixed relative positions matter more\nthan absolute breaks. Equal interval should not be used on a right-skewed variable at all.\n:::\n\n## Colour scheme\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_arrange(\n  tm_shape(mpsz_pop) +\n    tm_polygons(fill = \"DEPENDENCY\",\n                fill.scale = tm_scale_intervals(style = \"jenks\", n = 5,\n                                                values = \"brewer.greens\"),\n                fill.legend = tm_legend(show = FALSE), col = \"grey70\", lwd = 0.2) +\n    tm_title(\"Sequential (greens)\", size = 0.9),\n  tm_shape(mpsz_pop) +\n    tm_polygons(fill = \"DEPENDENCY\",\n                fill.scale = tm_scale_intervals(style = \"jenks\", n = 5,\n                                                values = \"-brewer.greens\"),\n                fill.legend = tm_legend(show = FALSE), col = \"grey70\", lwd = 0.2) +\n    tm_title(\"Reversed — misleading here\", size = 0.9),\n  ncol = 2\n)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex01_files/figure-html/colour-1.png){width=864}\n:::\n:::\n\n\n::: {.callout-note appearance=\"simple\"}\n## Choosing sequential or diverging\n\nA sequential palette says the variable runs from less to more with no meaningful midpoint. A\ndiverging palette says there is a midpoint that matters, and that deviations on either side of it\ndiffer in kind rather than degree.\n\nFor a dependency ratio a diverging scheme can be justified if the midpoint is chosen for a\nreason, such as the national ratio, because being above or below the national average really are\ndifferent situations. It cannot be justified if the midpoint is just the middle of the data\nrange, since that invents a threshold that does not exist.\n\nThe reversed map above shows what goes wrong. Dark now reads as low dependency, which inverts\nthe intuition most readers bring to a map. The code is correct and the communication is not.\n:::\n\n# Part 3 — Beyond the brief\n\n## Is this actually spatial analysis?\n\nAnselin proposes a test for whether an analysis is genuinely spatial:\n\n> *\"If you change the location of things and it doesn't matter, then it's not spatial analysis.\n> But if it does matter, then it is.\"*\n\nHe demonstrates it with two maps of Milwaukee, one real and one with the same values randomly\nshuffled between census tracts. The histograms are identical but the maps look like two\ndifferent cities.\n\nI wanted to run the same test on this data rather than take it on faith.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\n\nmpsz_shuffled <- mpsz_pop\nmpsz_shuffled$DEPENDENCY <- sample(mpsz_pop$DEPENDENCY)\n```\n:::\n\n\nEvery value is preserved, since `sample()` only reassigns which subzone holds which number. So\nany non-spatial summary should come out exactly the same:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(\n  version = c(\"Real\", \"Shuffled\"),\n  n       = c(sum(is.finite(mpsz_pop$DEPENDENCY)), sum(is.finite(mpsz_shuffled$DEPENDENCY))),\n  mean    = c(mean(mpsz_pop$DEPENDENCY, na.rm = TRUE), mean(mpsz_shuffled$DEPENDENCY, na.rm = TRUE)),\n  sd      = c(sd(mpsz_pop$DEPENDENCY, na.rm = TRUE), sd(mpsz_shuffled$DEPENDENCY, na.rm = TRUE)),\n  median  = c(median(mpsz_pop$DEPENDENCY, na.rm = TRUE), median(mpsz_shuffled$DEPENDENCY, na.rm = TRUE))\n) %>%\n  mutate(across(where(is.numeric), ~round(.x, 4))) %>%\n  kable(caption = \"Identical by every non-spatial measure\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Identical by every non-spatial measure\n\n|version  |   n|   mean|     sd| median|\n|:--------|---:|------:|------:|------:|\n|Real     | 234| 0.4793| 0.5999| 0.4473|\n|Shuffled | 234| 0.4793| 0.5999| 0.4473|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbind_rows(\n  tibble(version = \"Real\",     value = mpsz_pop$DEPENDENCY),\n  tibble(version = \"Shuffled\", value = mpsz_shuffled$DEPENDENCY)\n) %>%\n  filter(is.finite(value), value < 2) %>%\n  ggplot(aes(x = value)) +\n  geom_histogram(bins = 30, fill = \"#4A6FA5\", colour = \"white\", linewidth = 0.2) +\n  facet_wrap(~version) +\n  labs(title = \"The histograms are the same graph twice\",\n       x = \"Dependency ratio\", y = \"Subzones\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex01_files/figure-html/shuffle-hist-1.png){width=864}\n:::\n:::\n\n\nNow the maps:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshuffle_map <- function(dat, ttl) {\n  tm_shape(dat) +\n    tm_polygons(fill = \"DEPENDENCY\",\n                fill.scale = tm_scale_intervals(style = \"quantile\", n = 5,\n                                                values = \"brewer.blues\"),\n                fill.legend = tm_legend(show = FALSE),\n                col = \"grey70\", lwd = 0.2) +\n    tm_title(ttl, size = 0.9)\n}\n\ntmap_arrange(shuffle_map(mpsz_pop,      \"Real Singapore\"),\n             shuffle_map(mpsz_shuffled, \"Same numbers, shuffled\"),\n             ncol = 2)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex01_files/figure-html/shuffle-maps-1.png){width=864}\n:::\n:::\n\n\n::: {.callout-important}\n## What the shuffle test shows\n\nThe mean, standard deviation and median are identical, and so is the histogram. But the two maps\nlook nothing alike. The real one has coherent regions of similar colour and the shuffled one is\nmore or less visual static.\n\nEverything separating those two images is spatial structure, and none of the conventional\nstatistics can detect it. This seems to be the gap the rest of the course fills. Lesson 4's spatial\nweights formalise what neighbouring means, and Lesson 5's Moran's I turns the difference between\nthese two maps into a single number with a significance test.\n\nIt also answers a question I had at the start, which was why not just use pandas for this. A\nnon-spatial toolkit would report these two datasets as identical, because on every measure it\ncan compute, they are.\n:::\n\n## Does the pattern survive a change of spatial unit? (MAUP)\n\nThe Modifiable Areal Unit Problem is that statistical results change when the zoning or the\nscale of the spatial units changes. It applies to most of what this course covers, and it can be\ntested directly here because subzones nest inside planning areas.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz_pa <- mpsz_pop %>%\n  st_drop_geometry() %>%\n  filter(!is.na(TOTAL)) %>%\n  group_by(PLN_AREA_N) %>%\n  summarise(YOUNG = sum(YOUNG), ACTIVE = sum(ACTIVE), AGED = sum(AGED),\n            n_subzones = n(), .groups = \"drop\") %>%\n  mutate(DEPENDENCY_PA = (YOUNG + AGED) / ACTIVE) %>%\n  filter(is.finite(DEPENDENCY_PA))\n\ncomparison <- tibble(\n  unit = c(\"Subzone\", \"Planning area\"),\n  n = c(sum(is.finite(mpsz_pop$DEPENDENCY)), nrow(mpsz_pa)),\n  min = c(min(mpsz_pop$DEPENDENCY, na.rm = TRUE), min(mpsz_pa$DEPENDENCY_PA)),\n  median = c(median(mpsz_pop$DEPENDENCY, na.rm = TRUE), median(mpsz_pa$DEPENDENCY_PA)),\n  max = c(max(mpsz_pop$DEPENDENCY, na.rm = TRUE), max(mpsz_pa$DEPENDENCY_PA))\n) %>% mutate(across(where(is.numeric), ~round(.x, 3)))\n\nkable(comparison, caption = \"The same variable at two spatial scales\")\n```\n\n::: {.cell-output-display}\n\n\nTable: The same variable at two spatial scales\n\n|unit          |   n|   min| median|   max|\n|:-------------|---:|-----:|------:|-----:|\n|Subzone       | 234| 0.083|  0.447| 9.500|\n|Planning area |  42| 0.208|  0.441| 0.601|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbind_rows(\n  tibble(unit = \"Subzone\", value = mpsz_pop$DEPENDENCY[is.finite(mpsz_pop$DEPENDENCY)]),\n  tibble(unit = \"Planning area\", value = mpsz_pa$DEPENDENCY_PA)\n) %>%\n  ggplot(aes(x = value, fill = unit)) +\n  geom_density(alpha = 0.45) +\n  labs(title = \"Aggregation compresses the distribution\",\n       subtitle = \"Same population, same ratio definition, different spatial units\",\n       x = \"Dependency ratio\", y = \"Density\", fill = NULL) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex01_files/figure-html/maup-plot-1.png){width=864}\n:::\n:::\n\n\nThe planning-area distribution is noticeably narrower. Aggregating averages away the extremes,\nso a map drawn at planning-area level would understate how uneven dependency actually is across\nSingapore. Neither scale is the correct one. The best I can do is state which scale I used and\nnote that the result depends on it.\n\n::: {.callout-note appearance=\"simple\"}\n## The two components of MAUP\n\nAnselin separates MAUP into two distinct problems:\n\n- **The scale problem.** Results change with the size of the unit, which is what the table above\n  measures, moving from subzone up to planning area.\n- **The zoning problem.** Results change with the arrangement of the units even when their size\n  stays constant. Redrawing the boundaries into equally sized but differently shaped subzones\n  would move the answer again.\n\nThe standard demonstration is Openshaw's *\"A Million Spatial Autocorrelation Coefficients\"*,\nwhich recomputed the same statistic on Iowa election data across progressively larger units and\nfound that the magnitude changed and so did the sign.\n\nOnly the scale problem can be tested here, because Singapore's subzones nest inside planning\nareas and there is no alternative zoning available. I am noting that rather than implying the\ntest covered both.\n:::\n\n::: {.callout-warning}\n## Change of support\n\nThis is Anselin's term for combining data recorded on units that do not align. This document has\na mild case of it, since Part 1 uses Master Plan 2014 boundaries and Part 2 uses 2019, which is\nwhat the chapters specify. Subzone definitions changed between the two versions, so the\npre-school counts and the dependency ratios are not measured on quite the same geography.\n\nBecause of that, the cross-dataset section below recalculates pre-school counts against the 2019\nboundaries instead of reusing the numbers from Part 1.\n:::\n\n## The choropleth's built-in bias\n\nA choropleth encodes a rate using area. The eye reads area as quantity, so large sparsely\npopulated subzones dominate the map while the dense subzones where most people actually live\nbarely register.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz_pop %>%\n  st_drop_geometry() %>%\n  filter(!is.na(TOTAL)) %>%\n  mutate(area_km2 = as.numeric(units::set_units(st_area(mpsz_pop %>% filter(!is.na(TOTAL))), \"km^2\"))) %>%\n  summarise(\n    `Share of map area held by the least-populated half of subzones (%)` =\n      round(sum(area_km2[TOTAL <= median(TOTAL)]) / sum(area_km2) * 100, 1),\n    `Share of population they hold (%)` =\n      round(sum(TOTAL[TOTAL <= median(TOTAL)]) / sum(TOTAL) * 100, 1)\n  ) %>%\n  pivot_longer(everything(), names_to = \"measure\", values_to = \"value\") %>%\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|measure                                                            | value|\n|:------------------------------------------------------------------|-----:|\n|Share of map area held by the least-populated half of subzones (%) |  69.9|\n|Share of population they hold (%)                                  |   2.4|\n\n\n:::\n:::\n\n\nThe less-populated half of the subzones takes up most of the visual field while holding a small\nminority of the population. Anyone forming an impression from this map is effectively weighting\nland rather than people.\n\n## Does provision follow need? Joining two datasets\n\nEverything up to this point describes the data. This section is an attempt to explain something,\nby asking whether pre-school provision tracks the child population. It brings the pre-school data\nfrom Part 1 together with the demographics from Part 2.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npreschool_by_sz <- mpsz19 %>%\n  mutate(SUBZONE_N = toupper(SUBZONE_N),\n         PreSch_Count = lengths(st_intersects(., preschool))) %>%\n  st_drop_geometry() %>%\n  select(SUBZONE_N, PreSch_Count)\n\nprovision <- mpsz_pop %>%\n  st_drop_geometry() %>%\n  filter(!is.na(TOTAL), YOUNG > 0) %>%\n  left_join(preschool_by_sz, by = \"SUBZONE_N\") %>%\n  mutate(children_per_preschool = YOUNG / pmax(PreSch_Count, 1),\n         has_none = PreSch_Count == 0)\n\nnrow(provision)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 230\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(provision, aes(x = YOUNG, y = PreSch_Count)) +\n  geom_point(aes(color = has_none), alpha = 0.7) +\n  geom_smooth(method = \"lm\", se = TRUE, color = \"grey30\", linewidth = 0.6) +\n  scale_color_manual(values = c(\"FALSE\" = \"#4A6FA5\", \"TRUE\" = \"#D1495B\"),\n                     labels = c(\"has pre-schools\", \"none\"), name = NULL) +\n  labs(title = \"Pre-school provision broadly tracks child population\",\n       subtitle = \"Each point is a subzone; red points have resident children but no pre-school\",\n       x = \"Residents aged 0-14\", y = \"Pre-schools in subzone\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex01_files/figure-html/provision-plot-1.png){width=864}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nct <- cor.test(provision$YOUNG, provision$PreSch_Count, method = \"spearman\", exact = FALSE)\nsprintf(\"Spearman rho = %.3f (p = %.3g), n = %d\",\n        ct$estimate, ct$p.value, nrow(provision))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Spearman rho = 0.855 (p = 5.42e-67), n = 230\"\n```\n\n\n:::\n:::\n\n\n::: {.callout-warning}\n## Why the p-value here is not reliable\n\nSpearman's ρ treats the 230 subzones as independent observations, and they are not. Adjacent\nsubzones have similar child populations for the same underlying reasons, such as housing type,\nestate age and planning policy, so the observations are spatially autocorrelated.\n\nXie et al. describe this as the central statistical issue in the field: *\"Geospatial data are\noften spatially auto-correlated, which violates the i.i.d. assumption of many data mining and\nmachine learning techniques.\"*\n\nWhat this means in practice is that the effective sample size is smaller than 230, because\nneighbouring subzones carry partly redundant information. The correlation coefficient is still\nfine as a description. The p-value is not, because it is anti-conservative, meaning too small,\nand the significance is overstated by an amount I cannot quantify.\n\nSo I am reading ρ = 0.86 as a strong association and ignoring the p-value\nrather than reporting it as if the test were valid. Doing this properly needs a method that\nmodels the spatial dependence, which is what Lessons 4 and 5 introduce, and presumably why they\ncome before the regression lessons.\n\nXie et al. add a second point that applies here, which is that a p-value alone is never enough to\nrule out a chance pattern and should be paired with an effect size.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprovision %>%\n  filter(has_none) %>%\n  arrange(desc(YOUNG)) %>%\n  select(SUBZONE_N, PLN_AREA_N, YOUNG, TOTAL) %>%\n  head(10) %>%\n  kable(caption = \"Subzones with the most children but no pre-school within their boundary\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Subzones with the most children but no pre-school within their boundary\n\n|SUBZONE_N       |PLN_AREA_N    | YOUNG| TOTAL|\n|:---------------|:-------------|-----:|-----:|\n|CHANGI WEST     |CHANGI        |   380|  1300|\n|SUNGEI ROAD     |ROCHOR        |   230|  2050|\n|MONK'S HILL     |NEWTON        |   200|  1030|\n|NEE SOON        |YISHUN        |   130|   890|\n|CENTRAL SUBZONE |DOWNTOWN CORE |   110|   880|\n|MOUNT PLEASANT  |NOVENA        |   100|   690|\n|CHINA SQUARE    |OUTRAM        |    90|  1430|\n|KAMPONG BUGIS   |KALLANG       |    80|   920|\n|TURF CLUB       |SUNGEI KADUT  |    80|   670|\n|TANGLIN         |ORCHARD       |    70|   370|\n\n\n:::\n:::\n\n\n::: {.callout-important}\n## Limits of this finding\n\nThe correlation is strong and positive, so provision does broadly follow population. The table\nthen does something the correlation cannot, which is name specific subzones where children live\nand no pre-school falls inside the boundary.\n\nThat is a starting point rather than a conclusion, for four reasons:\n\n1. **The denominator problem.** Anselin's car theft example applies here: *\"wouldn't there be\n   more car thefts where there are more cars?\"* A raw count of pre-schools mostly tells you\n   where the children are, not where provision is good or bad. I framed this against child\n   population instead of using a bare count for that reason, and the earlier density section\n   divided by area rather than mapping counts for the same reason.\n2. **Edge effects.** A subzone boundary is not a catchment area. A pre-school 50 m outside the\n   line still serves those children. Doing this properly would involve buffering, or computing\n   distance to the nearest facility, rather than counting inside polygons, which is the\n   accessibility modelling covered in Lesson 9.\n3. **Capacity is not measured.** Counting facilities treats a 30-place centre and a 300-place\n   centre as the same thing.\n4. **The demographic data is from Census 2020** while the pre-school locations are current. A\n   six-year gap matters in a country that builds new towns as quickly as Singapore does.\n\nSo this identifies candidates worth investigating, and the right next step would be a\ndistance-based accessibility measure rather than a count.\n\nXie et al. make the point that a false positive is not a neutral error, using the example of a\ncommunity *\"being incorrectly identified as a cancer cluster\"*. Naming a subzone as underserved\nis a much smaller version of the same thing, but it still directs attention and possibly\nresources, so I have listed these caveats here rather than leaving them out.\n:::\n\n::: {.callout-warning}\n## Ecological fallacy\n\nAnselin describes this as the classic trap in aggregate spatial work: *\"confusing individual\nbehaviour with aggregate behaviour... the mistake happens at the end, when the conclusions are\nwritten as if they are about individual behaviour, but really they're based on aggregate\nmagnitudes.\"*\n\nEverything above is measured on subzones rather than on families, so these statements would not\nbe supported by this data:\n\n- ✗ \"Families in these subzones cannot find pre-school places.\"\n- ✗ \"Children here are less likely to attend pre-school.\"\n\nWhat the data does support:\n\n- ✓ \"These subzones have resident children and no pre-school within their boundary.\"\n- ✓ \"Across subzones, pre-school count rises with child population (ρ = 0.86).\"\n\nThe gap between those two lists is the ecological fallacy. As Anselin puts it, an aggregate only\nrepresents individuals well when the individuals are alike. A subzone containing both high and\nlow income households has an average that describes nobody living in it.\n:::\n\n## Limitations\n\n- **Two boundary vintages.** Part 1 uses Master Plan 2014 and Part 2 uses 2019, since that is\n  what the chapters specify. Subzone definitions changed between the two, so figures are not\n  strictly comparable across the two parts.\n- **Census 2020 population against 2026 facility locations**, as discussed above.\n- **Point-in-polygon counting ignores catchments**, as discussed above.\n- **The dependency ratio assumes 15 to 64 is working age.** With rising retirement ages and high\n  tertiary participation this is a convention rather than a fact.\n- **`Inf` dependency values were set to `NA`.** Subzones that have residents but no working-age\n  residents are dropped from every map. There are only a few, but they are dropped rather than\n  shown as zero.\n\n# Reflection\n\nMost of the mechanics here were familiar from Python. Reading files, joining tables and plotting\nare the same ideas with different function names. Three things were new to me.\n\nThe first is that CRS is a correctness problem rather than a formatting one. The difference\nbetween `st_set_crs()` and `st_transform()` does not really have an equivalent in ordinary data\nwork, and getting it wrong produces no error at all. The numbers are just wrong.\n\nThe second is that classification is a decision you make whether or not you think about it.\nAccepting the `qtm()` default is still a choice. Building the sensitivity table was the most\nuseful thing I did in this exercise, because it turned a vague warning into an actual number.\n\nThe third is how much of the work turned out to be checking rather than analysis. The join\ndiagnostics, the `Inf` handling and the buffer overlap correction are not in the chapter, and\neach one was somewhere I could have got a wrong answer that looked reasonable.\n\nIf I did this again I would run the join diagnostic before drawing the map instead of after. I\nhad already produced a choropleth over data I had not verified, and it looked completely fine.\n\n# About this document\n\nWritten and executed in Quarto with R 4.6.1. All figures are generated at render time\nfrom the data in `data/`, so nothing on this page is pasted in.\n\nI used AI assistance while working out the approach and the extensions in Part 3. The analysis\nwas run and checked by me.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.6.1 (2026-06-24)\nPlatform: aarch64-apple-darwin23\nRunning under: macOS Tahoe 26.0.1\n\nMatrix products: default\nBLAS:   /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRblas.0.dylib \nLAPACK: /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1\n\nlocale:\n[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8\n\ntime zone: Asia/Singapore\ntzcode source: internal\n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nother attached packages:\n [1] units_1.0-1     classInt_0.4-11 knitr_1.51      lubridate_1.9.5\n [5] forcats_1.0.1   stringr_1.6.0   dplyr_1.2.1     purrr_1.2.2    \n [9] readr_2.2.0     tidyr_1.3.2     tibble_3.3.1    ggplot2_4.0.3  \n[13] tidyverse_2.0.0 tmap_4.4-1      sf_1.1-2       \n\nloaded via a namespace (and not attached):\n [1] tidyselect_1.2.1   farver_2.1.2       S7_0.2.2           fastmap_1.2.0     \n [5] leaflegend_1.2.8   leaflet_2.2.3      pacman_0.5.1       XML_3.99-0.23     \n [9] digest_0.6.39      timechange_0.4.0   lifecycle_1.0.5    terra_1.9-34      \n[13] magrittr_2.0.5     compiler_4.6.1     rlang_1.3.0        tools_4.6.1       \n[17] yaml_2.3.12        data.table_1.18.4  labeling_0.4.3     htmlwidgets_1.6.4 \n[21] bit_4.6.0          sp_2.2-3           RColorBrewer_1.1-3 abind_1.4-8       \n[25] KernSmooth_2.23-26 withr_3.0.3        leafsync_0.1.0     grid_4.6.1        \n[29] cols4all_0.10      e1071_1.7-17       leafem_0.2.5       colorspace_2.1-3  \n[33] spacesXYZ_1.6-0    scales_1.4.0       cli_3.6.6          crayon_1.5.3      \n[37] rmarkdown_2.31     generics_0.1.4     otel_0.2.0         tzdb_0.5.0        \n[41] tmaptools_3.3      DBI_1.3.0          proxy_0.4-29       splines_4.6.1     \n[45] stars_0.7-3        parallel_4.6.1     s2_1.1.11          base64enc_0.1-6   \n[49] vctrs_0.7.3        Matrix_1.7-5       jsonlite_2.0.0     hms_1.1.4         \n[53] bit64_4.8.2        crosstalk_1.2.2    maptiles_0.12.0    glue_1.8.1        \n[57] lwgeom_0.2-17      codetools_0.2-20   stringi_1.8.7      gtable_0.3.6      \n[61] raster_3.6-32      logger_0.4.2       pillar_1.11.1      htmltools_0.5.9   \n[65] R6_2.6.1           wk_0.9.5           vroom_1.7.1        evaluate_1.0.5    \n[69] lattice_0.22-9     png_0.1-9          class_7.3-23       Rcpp_1.1.2        \n[73] nlme_3.1-169       mgcv_1.9-4         xfun_0.60          pkgconfig_2.0.3   \n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "Hands-on_Ex01_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}