{
  "hash": "a30e8dc2c3a90ffa1b0057df2f09e30d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Hands-on Exercise 3\"\nsubtitle: \"Spatio-Temporal Point Patterns Analysis with R\"\nauthor: \"An Loc\"\ndate: \"10 September 2026\"\ndate-modified: \"last-modified\"\ndate-format: \"D MMM YYYY\"\nformat:\n  html:\n    toc: true\n    toc-depth: 4\n    toc-expand: true\n    code-fold: false\n    code-copy: true\n    fig-width: 9\n    fig-height: 7\nexecute:\n  echo: true\n  eval: true\n  warning: false\n  message: false\n  freeze: true\n---\n\n# Overview\n\nThis exercise applies **Spatio-Temporal Point Patterns Analysis (STPPA)** to forest fire\ndetections in Kepulauan Bangka Belitung, Indonesia, during 2023. It follows r4gdsa Chapter 6,\nthe chapter assigned for Lesson 3. Where I write \"the chapter\" below, I mean that one.\n\nLesson 2 treated a point pattern as a set of locations. A spatio-temporal point pattern adds the\ntime of each event, so the same two questions from last week are asked again in three dimensions.\n\n**Part 1** reproduces Chapter 6. It has two halves: a first-order analysis of how fire intensity\nvaries across space and time, using `sparr`, and a second-order analysis of whether events\ninteract, using the space-time K-function in `stpp`. **Part 2** examines the chapter's method and adds one\nanalysis it does not attempt.\n\n## The questions being asked\n\nThe chapter asks:\n\n1. Are the locations of forest fire in Kepulauan Bangka Belitung spatial and spatio-temporally\n   independent?\n2. If the answer is no, where and when do the observed fire locations tend to cluster?\n\nIndependence is a second-order property, so the first question is addressed by the K-function in\nsection 3.2. The second requires both halves: the density estimate locates the concentrations in\nspace and time, and the K-function establishes whether they exceed what chance would produce.\n\n::: {.callout-note appearance=\"simple\"}\n\n## Reference\n\nr4gdsa [Chapter 6: Spatio-Temporal Point Patterns\nAnalysis](https://r4gdsa.netlify.app/chap06.html).\n:::\n\n## Differences from the chapter\n\n| | The chapter | This page | Why | Where |\n|---|---|---|---|---|\n| **Study area** | Bangka island, 11,534 km², described as the whole province | Bangka island, 11,887 km², named as such | The chapter's file does not cover the area its text names. Part 1 follows the chapter's actual window | 3.1.1, 4.1 |\n| **Boundary source** | Indonesia Geospatial portal | GADM 4.1, level 2 | The portal distributes files through a blog page linking to Google Drive, with no stable URL to cite | 2.2 |\n| **Fire data source** | FIRMS download portal, account required | FIRMS public archive, direct URL | Same MODIS data from a stable URL that can be cited in the document | 2.2 |\n| **Data extent** | `forestfires.csv`, already cut to the study area | All 52,156 Indonesian detections, cut in code | The cut is the step that decides the answer, so it belongs in the document | 3.1.3 |\n| **`set.seed()`** | Only before `BOOT.spattemp()` | Once at the top | Asked for in the Lesson 2 class: without it the render is not reproducible | 2.1 |\n| **Months plotted** | July to December | All twelve, in two blocks | Shows the instability that sparse monthly counts produce | 3.1.5.4 |\n| **Duplicate check** | `any(duplicated())` | `sum(duplicated())` | A count says how many, which is what a data-quality check needs to report | 3.1.5.1 |\n| **Facet function** | `tm_facets()` | `tm_facets_wrap()` | `tm_facets()` is tmap 3; this machine runs tmap 4.4.1 and emits a deprecation message | 3.1.4.2 |\n| **Figure heights** | default | set per chunk | The study area is nearly twice as wide as it is tall, so the default canvas leaves white bands inside every map | 3.1.4.1 |\n| **Pipe** | `%>%` | <code>&#124;&gt;</code> | Both were covered in the Lesson 2 class and the choice was left to us. The native pipe does not need tidyverse loaded | throughout |\n| **Offshore islets** | not applicable, single polygon | 53 pieces reduced to 11 by dropping anything under 1 km² | A fire cannot occur on a rock of a few thousandths of a square kilometre, and the fragments change the bandwidth the model selects. Keeps 99.97% of the area and all 766 fires | 3.1.1, 4.2 |\n| **Regency breakdown** | not present | added | Shows the first-order variation the density surface smooths over, and regency is the administrative unit required for Take-home Exercise 1 | 4.3 |\n\n::: {.callout-note collapse=\"true\"}\n## Mapping of Chapter 6 sections to this page\n\nEvery section of Chapter 6 is covered. The order is regrouped into two parts.\n\n| Chapter 6 | This page |\n|---|---|\n| 6.1 Overview | 1 Overview |\n| 6.2.1 The research questions | 1.1 The questions being asked |\n| 6.3 The data | 2.2 The data |\n| 6.4 Installing and loading the R packages | 2.1 Packages |\n| 6.5.1 Importing study area | 3.1.1 The study area |\n| 6.5.2 Converting OWIN | 3.1.2 Converting to an owin |\n| 6.6 Importing and preparing forest fire data | 3.1.3 The fire data |\n| 6.7.1 Overall plot | 3.1.4.1 Overall distribution |\n| 6.7.2 Distribution by month | 3.1.4.2 By month |\n| 6.8.1 Extracting forest fires by month | 3.1.5 STKDE by month |\n| 6.8.2 Creating ppp | 3.1.5, and the duplicate check in 3.1.5.1 |\n| 6.8.3 Including owin object | 3.1.5.2 Applying the observation window |\n| 6.8.4 Computing spatio-temporal KDE | 3.1.5.3 Computing the density |\n| 6.8.5 Plotting the spatio-temporal KDE object | 3.1.5.4 Plotting the result |\n| 6.9.1 Creating ppp object | 3.1.6 STKDE by day of year |\n| 6.9.2 Including owin object | 3.1.6 |\n| 6.9.3 *(untitled in the chapter)* | 3.1.6 |\n| 6.10 `set.seed()` | 2.1, moved to the top of the document |\n| 6.10.1 Computing spatio-temporal KDE | 3.1.7 Choosing the bandwidths |\n| 6.10.2 Plotting the output spatio-temporal KDE | 3.1.7 |\n| 6.11.1 Preparing the stpp object | 3.2.1 Building the stpp object |\n| 6.11.2 Computing spatio-temporal K-function | 3.2.2 Computing the K-function |\n| 6.11.3 Guide to interpret the plot | 3.2.3 Reading the plot |\n| 6.12 Reference | 6 References |\n\nTwo chapter sections have no code and no content of their own, 6.2 Learning Outcome and 6.9.3,\nwhich is untitled. Both are covered by the rows above.\n:::\n\n# Getting started\n\n## Packages\n\nSix packages are used. `sparr` and `stpp` are new this week. The rest carry over from Hands-on\nExercise 2.\n\n- `sf` for reading and transforming the geospatial layers\n- `spatstat` for the `ppp` and `owin` classes, which `sparr` builds on\n- `sparr` for spatio-temporal kernel density estimation and bandwidth selection\n- `tmap` for the point maps\n- `stpp` for the space-time K-function\n- `tidyverse` for the data wrangling, including `lubridate` for the date handling\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(sf, spatstat, sparr, tmap, stpp, tidyverse)\n```\n:::\n\n\nThe chapter does not set a seed. This came up in the Lesson 2 class: without one, the bootstrap\nand simulation results change on every render, preventing reproducible rendering. One seed is set\nhere, at the top, before anything random runs.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\n```\n:::\n\n\n## The data\n\nTwo datasets are needed: the fire detections and the boundary of the study area. The chapter\nnames its sources but distributes neither file, so both were retrieved directly.\n\n### Fire detections\n\nThe chapter uses `forestfires.csv`, described as MODIS detections from NASA's [Fire Information\nfor Resource Management System](https://firms.modaps.eosdis.nasa.gov/download/). The download\npage it links requires an account and delivers the file by email. The same archive is also published as a direct download with no account, one file per country per year:\n\n```\nhttps://firms.modaps.eosdis.nasa.gov/data/country/modis/2023/modis_2023_Indonesia.csv\n```\n\nThat is the file used here. It holds every MODIS detection in Indonesia for 2023 and is kept\nwhole, so the cut to Bangka is done in the code below and stays visible.\n\n### Study area boundary\n\nThe chapter reads an ESRI shapefile named `Kepulauan_Bangka_Belitung`, extracted from a national\nfile on the [Indonesia Geospatial portal](https://www.indonesia-geospasial.com/2023/05/download-shapefile-batas-administrasi.html).\nThat portal distributes its files through a blog page linking to Google Drive, so there is no\nstable URL to cite.\n\nI used [GADM](https://gadm.org/) instead, level 2, which is the regency and city level\n(*kabupaten* and *kota*):\n\n```\nhttps://geodata.ucdavis.edu/gadm/gadm4.1/json/gadm41_IDN_2.json.zip\n```\n\nThe chapter's file is at *kelurahan* level, one step finer, but the chapter immediately\ndissolves it with `st_union()`, so the boundary that reaches the analysis is identical either\nway. Level 2 also keeps the regencies available, which is the administrative unit required for Take-home Exercise 1.\n\n### Coordinate reference system\n\nEverything is transformed to **EPSG:32748**, WGS 84 / UTM zone 48S, which is the projected\nsystem the chapter uses and the correct UTM zone for Bangka Belitung. Units are metres, so\nevery bandwidth and distance below reads in metres.\n\n# Part 1: Following the chapter\n\nChapter 6 divides into two analytical parts. Sections 6.5 to 6.10 estimate how fire intensity\nvaries across space and time, a first-order question. Section 6.11 asks whether events interact\nonce that intensity is accounted for, a second-order question. As section 1.1 notes, these do not\nmap onto the two research questions in order: independence is settled by the second-order\nanalysis, and the question of where and when fires cluster needs both.\n\n## First-order: spatio-temporal KDE\n\n### The study area\n\nThe GADM file covers the whole country, so the study area is selected by name and then merged\ninto a single polygon. `st_zm()` drops the Z dimension, which `as.owin()` will not accept, and the\ntransform puts the result in metres.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbangka_raw <- st_read(\"data/rawdata/gadm41_IDN_2.json\", quiet = TRUE) |>\n  filter(NAME_1 == \"BangkaBelitung\",\n         !grepl(\"^Belitung\", NAME_2)) |>\n  st_union() |>\n  st_zm(drop = TRUE, what = \"ZM\") |>\n  st_transform(crs = 32748)\n```\n:::\n\n\nThe filter takes the five regencies on Bangka island: Bangka, Bangka Barat, Bangka Selatan,\nBangka Tengah and the city of Pangkalpinang. The chapter's own study area is Bangka rather than\nthe whole province, though the chapter never says so.\n\nEvery offshore rock is a separate polygon in the GADM file, so this boundary is made up of 53\npieces.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nparts <- st_cast(bangka_raw, \"POLYGON\", warn = FALSE)\npart_km2 <- as.numeric(st_area(parts)) / 1e6\n\nc(parts = length(parts),\n  largest_km2 = round(max(part_km2), 1),\n  smallest_km2 = round(min(part_km2), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       parts  largest_km2 smallest_km2 \n     53.0000   11602.5000       0.0013 \n```\n\n\n:::\n:::\n\n\nThe main island is 11,603 km². The smallest pieces are a few thousandths of a square kilometre.\nFires cannot occur on those, so anything under 1 km² is dropped. Dropping these slivers prevents\ninflation of the selected bandwidth, as shown in section 4.2.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkbb_sf <- st_union(parts[part_km2 >= 1])\n\nc(parts_kept = length(st_cast(kbb_sf, \"POLYGON\", warn = FALSE)),\n  area_km2 = round(as.numeric(st_area(kbb_sf)) / 1e6, 1),\n  pct_of_original = round(100 * as.numeric(st_area(kbb_sf)) /\n                            as.numeric(st_area(bangka_raw)), 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     parts_kept        area_km2 pct_of_original \n          11.00        11886.90           99.97 \n```\n\n\n:::\n:::\n\n\n11 pieces remain, holding 99.97% of the land area, about 11,887 km².\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkbb_regencies <- st_read(\"data/rawdata/gadm41_IDN_2.json\", quiet = TRUE) |>\n  filter(NAME_1 == \"BangkaBelitung\",\n         !grepl(\"^Belitung\", NAME_2)) |>\n  st_zm(drop = TRUE, what = \"ZM\") |>\n  st_transform(crs = 32748)\n\nkbb_regencies$NAME_2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Bangka\"        \"BangkaBarat\"   \"BangkaSelatan\" \"BangkaTengah\" \n[5] \"Pangkalpinang\"\n```\n\n\n:::\n:::\n\n\n### Converting to an owin\n\n`spatstat` needs the study area as an `owin` object, the observation window that every\nsubsequent calculation is bounded by.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkbb_owin <- as.owin(kbb_sf)\nkbb_owin\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nwindow: polygonal boundary\nenclosing rectangle: [512010.2, 732848.4] x [9655542, 9833973] units\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclass(kbb_owin)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"owin\"\n```\n\n\n:::\n:::\n\n\n### The fire data\n\nThe CSV holds one row per detection, with `latitude`, `longitude` and `acq_date` among the\ncolumns. The points are read as WGS 84 geographic coordinates and then projected.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_all <- read_csv(\"data/rawdata/modis_2023_Indonesia.csv\",\n                     show_col_types = FALSE) |>\n  st_as_sf(coords = c(\"longitude\", \"latitude\"), crs = 4326) |>\n  st_transform(crs = 32748)\n\nnrow(fire_all)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 52156\n```\n\n\n:::\n:::\n\n\n52,156 detections across the whole of Indonesia in 2023. Bangka is a small part of that,\nso the next step cuts the data to the study area. The chapter's file is already cut to the study area, which hides this step. It is done explicitly\nhere because the choice of cutting boundary changes the answer.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_sf <- fire_all[lengths(st_intersects(fire_all, kbb_sf)) > 0, ]\n\nc(indonesia = nrow(fire_all),\n  bangka = nrow(fire_sf))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nindonesia    bangka \n    52156       766 \n```\n\n\n:::\n:::\n\n\n766 detections fall inside the study area.\n\n#### Deriving the temporal marks\n\nA `ppp` object accepts marks that are numeric or factor, so the acquisition date has to be\nconverted before it can be used as the temporal dimension. Three fields are derived below, covering the two temporal\nresolutions used later: month and day of year.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_sf <- fire_sf |>\n  mutate(DayofYear = yday(acq_date),\n         Month_num = month(acq_date),\n         Month_fac = month(acq_date, label = TRUE, abbr = FALSE))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrange(fire_sf$acq_date)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2023-01-10\" \"2023-12-18\"\n```\n\n\n:::\n:::\n\n\nThe detections run from 10 January to 18 December 2023. The gaps at either end are days on\nwhich the satellite recorded no fire on Bangka, so the record is complete for the year.\n\n### Visualising the fire points\n\n#### Overall distribution\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(kbb_sf) +\n  tm_polygons() +\n  tm_shape(fire_sf) +\n  tm_dots()\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-13-1.png){width=864}\n:::\n:::\n\n\n#### By month\n\nDrawing one map per month is the first look at the time dimension. If every month looked much\nthe same, a spatio-temporal method would have nothing to add over the methods used in Lesson 2.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(kbb_sf) +\n  tm_polygons() +\n  tm_shape(fire_sf) +\n  tm_dots(size = 0.1) +\n  tm_facets_wrap(by = \"Month_fac\",\n                 free.coords = FALSE,\n                 drop.units = TRUE)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-14-1.png){width=864}\n:::\n:::\n\n\nThe counts behind those panels:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_sf |>\n  st_drop_geometry() |>\n  count(Month_fac, name = \"fires\") |>\n  as.data.frame()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Month_fac fires\n1    January    11\n2   February     2\n3      March    12\n4      April    10\n5        May    21\n6       June    34\n7       July    83\n8     August   147\n9  September   151\n10   October   190\n11  November    94\n12  December    11\n```\n\n\n:::\n:::\n\n\nThe year is strongly seasonal. January to June carry 90 detections between them, while July to\nDecember carry 676. October alone has 190, more than twice the whole first half of the year.\nThat peak is the dry season.\n\n### STKDE by month\n\n`spattemp.density()` from `sparr` estimates a density in space and time together. It needs a\n`ppp` whose marks hold the temporal coordinate, so everything except the mark and the geometry\nis dropped first.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_month <- fire_sf |>\n  select(Month_num)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_month_ppp <- as.ppp(fire_month)\nfire_month_ppp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMarked planar point pattern: 766 points\nmarks are numeric, of storage type  'double'\nwindow: rectangle = [521564.1, 728908.3] x [9658137, 9828767] units\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(fire_month_ppp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMarked planar point pattern:  766 points\nAverage intensity 2.165125e-08 points per square unit\n\nCoordinates are given to 10 decimal places\n\nmarks are numeric, of type 'double'\nSummary:\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  1.000   8.000   9.000   8.593  10.000  12.000 \n\nWindow: rectangle = [521564.1, 728908.3] x [9658137, 9828767] units\n                    (207300 x 170600 units)\nWindow area = 3.5379e+10 square units\n```\n\n\n:::\n:::\n\n\n#### Checking for duplicates\n\nLesson 2 established that coincident points break the distance-based methods, so the same check\nruns here.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(points = npoints(fire_month_ppp),\n  duplicated = sum(duplicated(fire_month_ppp)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    points duplicated \n       766          0 \n```\n\n\n:::\n:::\n\n\nZero duplicates. In a purely spatial pattern, co-located points break the distance functions.\nWith time as the mark, repeat detections of the same pixel on different dates are valid\nobservations. They do not arise here because MODIS geolocation shifts slightly between overpasses,\nso the reported pixel centre moves with it.\n\n#### Applying the observation window\n\nBy default the `ppp`'s window is the rectangular bounding box of the points, so the study area\n`owin` has to be applied.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_month_owin <- fire_month_ppp[kbb_owin]\nfire_month_owin\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMarked planar point pattern: 766 points\nmarks are numeric, of storage type  'double'\nwindow: polygonal boundary\nenclosing rectangle: [512010.2, 732848.4] x [9655542, 9833973] units\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(before = npoints(fire_month_ppp),\n  after = npoints(fire_month_owin))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nbefore  after \n   766    766 \n```\n\n\n:::\n:::\n\n\nNo points are lost, because the data was already cut to the same polygon when `fire_sf` was\nbuilt. Had the cut been made with a bounding box instead, this step would have dropped points\nwithout a warning.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(fire_month_owin)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-22-1.png){width=864}\n:::\n:::\n\n\n#### Computing the density\n\n\n::: {.cell}\n\n```{.r .cell-code}\nst_kde <- spattemp.density(fire_month_owin)\nsummary(st_kde)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpatiotemporal Kernel Density Estimate\n\nBandwidths\n  h = 15504.12 (spatial)\n  lambda = 0.0305 (temporal)\n\nNo. of observations\n  766 \n\nSpatial bound\n  Type: polygonal\n  2D enclosure: [512010.2, 732848.4] x [9655542, 9833973]\n\nTemporal bound\n  [1, 12]\n\nEvaluation\n  128 x 128 x 12 trivariate lattice\n  Density range: [7.740464e-27, 7.925003e-10]\n```\n\n\n:::\n:::\n\n\n#### Plotting the result\n\nThe chapter plots months 7 to 12 only. The monthly counts explain why: the first half of the\nyear has too few points for a stable surface. Plotting both halves shows the instability that\nsparse monthly counts produce.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntims <- c(1, 2, 3, 4, 5, 6)\npar(mfcol = c(2, 3))\nfor (i in tims) {\n  plot(st_kde, i,\n       override.par = FALSE,\n       fix.range = TRUE,\n       main = paste(\"KDE at month\", i))\n}\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-24-1.png){width=864}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntims <- c(7, 8, 9, 10, 11, 12)\npar(mfcol = c(2, 3))\nfor (i in tims) {\n  plot(st_kde, i,\n       override.par = FALSE,\n       fix.range = TRUE,\n       main = paste(\"KDE at month\", i))\n}\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-25-1.png){width=864}\n:::\n:::\n\n\nWith `fix.range = TRUE` the colour scale is shared across panels, so the panels are comparable.\nThe first half of the year is close to flat. From July the density builds, peaks in October, and\nfalls back in December.\n\n### STKDE by day of year\n\nMonth is a coarse temporal unit. The same estimate at daily resolution uses `DayofYear` as the\nmark.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_yday_ppp <- fire_sf |>\n  select(DayofYear) |>\n  as.ppp()\n\nfire_yday_owin <- fire_yday_ppp[kbb_owin]\nfire_yday_owin\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMarked planar point pattern: 766 points\nmarks are numeric, of storage type  'double'\nwindow: polygonal boundary\nenclosing rectangle: [512010.2, 732848.4] x [9655542, 9833973] units\n```\n\n\n:::\n:::\n\n\n`summary()` is avoided on this object. Because the window is 11 separate pieces, it prints one\nrow per polygon, so the three summary numbers are printed directly instead.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(points = npoints(fire_yday_owin),\n  window_km2 = round(spatstat.geom::area(Window(fire_yday_owin)) / 1e6, 1),\n  intensity_per_1000km2 = round(npoints(fire_yday_owin) /\n    (spatstat.geom::area(Window(fire_yday_owin)) / 1e9), 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               points            window_km2 intensity_per_1000km2 \n                766.0               11886.9                  64.4 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkde_yday <- spattemp.density(fire_yday_owin)\nsummary(kde_yday)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpatiotemporal Kernel Density Estimate\n\nBandwidths\n  h = 15504.12 (spatial)\n  lambda = 6.3903 (temporal)\n\nNo. of observations\n  766 \n\nSpatial bound\n  Type: polygonal\n  2D enclosure: [512010.2, 732848.4] x [9655542, 9833973]\n\nTemporal bound\n  [10, 352]\n\nEvaluation\n  128 x 128 x 343 trivariate lattice\n  Density range: [1.924135e-26, 2.562364e-12]\n```\n\n\n:::\n:::\n\n\nLeft as it is, `plot()` on a daily estimate draws one panel for every day in the range, which is\n351 images here. Section 4.2 covers why. `tselect` picks which days to draw. Six are used here, spaced across the year, and the same six\nappear again in the next section so that the two bandwidth choices can be compared day by day.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(2, 3))\nfor (d in c(60, 152, 213, 259, 305, 350)) {\n  plot(kde_yday, tselect = d,\n       override.par = FALSE,\n       fix.range = TRUE,\n       main = paste(\"Day\", d))\n}\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-1.png){width=864}\n:::\n:::\n\n\n`fix.range = TRUE` puts all six panels on one colour scale, so a colour means the same density\nin every panel. That is what makes them comparable, and it is also why days 60, 152 and 350 look\nlike flat blue. Those days are quiet relative to October, so they sit at the bottom of a scale\nset by the busiest day. Section 3.1.7 quantifies the difference and redraws the same six days with each panel on its own\nscale.\n\nIn the busy panels the density rises through the year and the concentration also moves. On\nday 213 it sits in the north-west of Bangka, on day 259 it has shifted to the centre and south,\nand by day 305 it is in the far south, around Bangka Selatan. A single map of the whole year\nwould average these positions together.\n\nThese use the default bandwidths.\n\n### Choosing the bandwidths\n\nEverything above used the defaults. In Lesson 2 the bandwidth turned out to be the choice that\nmoved the KDE most, and the same applies here, with a second bandwidth now controlling smoothing\nin time.\n\n`BOOT.spattemp()` selects both by bootstrap estimation of the mean integrated squared error,\nfollowing Hall (1990). It returns an isotropic spatial bandwidth `h` in map units, so metres\nhere, and a scalar temporal bandwidth `lambda` in days.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbw <- BOOT.spattemp(fire_yday_owin, verbose = FALSE)\nbw\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         h     lambda \n6599.76862   23.76416 \n```\n\n\n:::\n:::\n\n\nThe chapter uses `h = 9000` and `lambda = 19` at this point. On the same window the bootstrap\nreturns 6,600 m, the same order of magnitude, and 23.8 days. Section 4.1.3 examines where those\nnumbers come from and how far the selectors disagree.\n\nThe three candidates side by side:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata.frame(\n  source = c(\"spattemp.density default\", \"BOOT.spattemp on this data\", \"chapter's hard-coded\"),\n  h_metres = c(round(kde_yday$h), round(bw[\"h\"]), 9000),\n  lambda_days = round(c(kde_yday$lambda, bw[\"lambda\"], 19), 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                      source h_metres lambda_days\n1   spattemp.density default    15504        6.39\n2 BOOT.spattemp on this data     6600       23.76\n3       chapter's hard-coded     9000       19.00\n```\n\n\n:::\n:::\n\n\nThe bootstrap is narrower in space and much wider in time than the default: 6.6 km against 15.5\nkm, and 23.8 days against 6.4 days. The bootstrap values are used below. The procedure minimises estimation\nerror for the particular point pattern and window it is given, and this is a different study area\nfrom the chapter's, so the chapter's numbers do not carry over.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkde_yday_boot <- spattemp.density(fire_yday_owin,\n                                  h = bw[\"h\"],\n                                  lambda = bw[\"lambda\"])\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(2, 3))\nfor (d in c(60, 152, 213, 259, 305, 350)) {\n  plot(kde_yday_boot, tselect = d,\n       override.par = FALSE,\n       fix.range = FALSE,\n       main = paste(\"Day\", d))\n}\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-33-1.png){width=864}\n:::\n:::\n\n\nCompared with the default bandwidths in section 3.1.6, the peaks are broader and lower, and the\nsurface changes less from one day to the next. That is the expected effect of 23.8 days of\ntemporal smoothing against the default 6.4 days. The seasonal pattern and the movement of the concentration are the\nsame under both.\n\nThese panels use `fix.range = FALSE`, the default, which is also what the chapter uses here. Each\npanel is stretched to its own maximum.\n\n## Second-order: the K-function\n\nGiven the intensity estimated above, do the events still cluster more than chance would produce?\nThe space-time inhomogeneous K-function in `stpp` addresses this.\n\n### Building the stpp object\n\n`stpp` does not integrate with `sf` or `ppp`. `as.3dpoints()` requires a three-column matrix or\ndata frame of coordinates (x, y, t), with t integer-valued.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoords <- st_coordinates(fire_sf)\n\nfire_df <- data.frame(\n  x = coords[, 1],\n  y = coords[, 2],\n  t = fire_sf$DayofYear)\n\nhead(fire_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         x       y  t\n1 606178.8 9703062 10\n2 661410.6 9683536 10\n3 637808.8 9682757 10\n4 654882.2 9690665 10\n5 669933.6 9697468 10\n6 609133.5 9700119 10\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_stpp <- as.3dpoints(fire_df)\nclass(fire_stpp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"stpp\"\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(fire_stpp)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-36-1.png){width=864}\n:::\n:::\n\n\nThe left panel is the map. The right panel plots time against the cumulative count, so its slope\nis the rate of detections. The flat stretch to day 180 and the steep climb through the second\nhalf are the same seasonality the monthly maps showed.\n\n### Computing the K-function\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkbb_stik <- STIKhat(fire_stpp)\n```\n:::\n\n\nThe chapter's next step is `plotK(kbb_stik)`. That call produces no figure inside a rendered\ndocument, for reasons set out in section 4.1.5, so it is shown but not run.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplotK(kbb_stik)\n```\n:::\n\n\nThe surface can be drawn directly from the object `STIKhat()` returns. `Khat` holds the estimate\nand `Ktheo` the value expected under space-time independence, so the difference between them is\nwhat `plotK(L = TRUE)` would show.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nk_diff <- kbb_stik$Khat - kbb_stik$Ktheo\nlv <- pretty(c(-max(abs(k_diff)), max(abs(k_diff))), n = 15)\n\nfilled.contour(x = kbb_stik$dist,\n               y = kbb_stik$times,\n               z = k_diff,\n               levels = lv,\n               color.palette = colorRampPalette(c(\"red\", \"white\", \"blue\")),\n               xlab = \"spatial distance u (metres)\",\n               ylab = \"time lag v (days)\",\n               main = expression(hat(K)[ST](u, v) - K[theo]))\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-39-1.png){width=864}\n:::\n:::\n\n\n### Reading the plot\n\nBlue is positive, meaning more pairs of fires at that combination of distance and time lag than\nspace-time independence would produce. Red would be fewer. The whole surface here is positive,\nand it rises steadily along both axes, reaching about 4.9 x 10^12 at the far corner.\n\nAt short time lags the excess grows with spatial distance, so fires occurring within a few days\nof each other are distributed across the island rather than concentrated at one location. At\nlarge distances the excess also grows with time lag. Fires are clustered in both space and time. Most occur in\nthe dry season, and during that season they occur across a wide area.\n\nThe estimate is computed over spatial distances from 3.2 km to 47.6 km and time lags from 6 to\n89 days, which `STIKhat()` chose from the data.\n\n`STIKhat()` was called without a `lambda` argument, so it uses its own internal intensity\nestimate as the reference, and a different intensity model would move the surface. No envelope\nwas computed, so the plot does not establish whether the excess exceeds sampling variation. Hohl\net al. test significance by comparing the observed function against upper and lower simulation\nenvelopes at each combination of spatial and temporal bandwidth, which is the step missing here.\n\n# Part 2: Review and extension\n\nSections 4.1 and 4.2 examine the chapter's method. Section 4.3 adds an analysis it does not\nattempt.\n\n## Methodology review\n\nSix issues in Chapter 6 that affect a computed result, ordered by the size of that effect.\n\n### Observation window: K-function versus KDE\n\nSection 6.11.2 calls `STIKhat(fire_stpp)` with no `s.region`. The default is a bounding box:\n\n```r\nif (missing(s.region))\n    s.region <- sbox(xyt[, 1:2], xfrac = 0.01, yfrac = 0.01)\n```\n\nSo the first half of the chapter estimates density inside the coastline, using `kbb_owin`, and\nthe second half tests for interaction against a null model spread over a rectangle.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbox <- sbox(coords[, 1:2], xfrac = 0.01, yfrac = 0.01)\n\nc(bounding_box_km2 = round(diff(range(box[, 1])) * diff(range(box[, 2])) / 1e6),\n  land_km2 = round(as.numeric(st_area(kbb_sf)) / 1e6),\n  sea_pct = round(100 * (1 - as.numeric(st_area(kbb_sf)) /\n                    (diff(range(box[, 1])) * diff(range(box[, 2]))))))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nbounding_box_km2         land_km2          sea_pct \n           36808            11887               68 \n```\n\n\n:::\n:::\n\n\nThe box is 3.1 times the land area and 68% of it is water. Under complete randomness the null model places fires at\nsea. That lowers the expected number of nearby pairs, which in turn makes the observed excess\nlook bigger than it is.\n\nThe area also enters the estimator itself. Hohl et al. normalise the space-time K-function by the product\nof two terms: *L*, \"the area of the study region\", and *R*, the duration of the study period.\nTogether these give \"the volume of the irregular prism that is formed by the study area (base)\nand the study period (height)\". González et al. (2016) give the isotropic edge-correction weight\nas |W ⊗ T| w<sub>ij</sub><sup>(u)</sup> w<sub>ij</sub><sup>(v)</sup>, with the study region's area\nagain a multiplicative factor, and note that isotropic correction is the most widely used in\npractice, which is also `STIKhat()`'s default. So an inflated region enlarges both the reference volume\nand the correction weights.\n\nPassing the region explicitly is standard practice in the sources below. The `stpp` authors'\nown worked example is `STIKhat(xyt = FMD, s.region = Northcumbria, t.region = c(1, 200), ...)`.\nA separate paper, González and Moraga (2023), also listed on the Lesson 3 page, builds\n`s.region` from the observation window's boundary before calling the same function. Juan et al. (2012), analysing wildfires,\nconstruct their pattern as `ppp(X, Y, window = polyowinCTN)`. Chapter 6 supplies neither region.\n\n`s.region` takes one polygon, so the main island is used, thinned to keep the boundary tractable.\nThe 11-piece window from section 3.1.1 cannot be passed directly, which is itself a limit of\n`stpp` relative to `spatstat`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmain_island <- st_cast(bangka_raw, \"POLYGON\", warn = FALSE)[\n  which.max(as.numeric(st_area(st_cast(bangka_raw, \"POLYGON\", warn = FALSE))))]\nmc <- st_coordinates(main_island)[, 1:2]\nland_region <- mc[seq(1, nrow(mc), by = 20), ]\n\nstik_land <- STIKhat(fire_stpp, s.region = land_region)\n\nc(chapter_bbox_window = signif(max(kbb_stik$Khat - kbb_stik$Ktheo), 4),\n  land_window = signif(max(stik_land$Khat - stik_land$Ktheo), 4),\n  ratio = round(max(kbb_stik$Khat - kbb_stik$Ktheo) /\n                max(stik_land$Khat - stik_land$Ktheo), 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nchapter_bbox_window         land_window               ratio \n          2.811e+12           1.172e+12           2.400e+00 \n```\n\n\n:::\n:::\n\n\nCorrecting the window reduces the peak excess by a factor of 2.4. The qualitative conclusion in\nsection 3.2.3 holds, since the surface stays positive throughout. The magnitude the chapter\nreports depends on its choice of window.\n\n### Study area definition\n\nA spatial point process is defined relative to its observation window, so the boundary supplied\ngoverns both the density estimate and the edge correction. Chapter 6 states its study area as\nKepulauan Bangka Belitung, and its first research question asks about Kepulauan Bangka Belitung.\nThe window it actually uses is smaller, and that difference is nowhere stated.\n\nIts own printed output shows the truncation:\n\n```\nBounding box:  xmin: 105.1085  xmax: 106.8488\nsingle connected closed polygon\nWindow area = 11533600000\n```\n\nBelitung island spans 107.11 to 108.85 degrees east, past that `xmax`, and the province is 46\nseparate islands, which cannot form one connected polygon. The window holds Bangka alone, 11,534\nkm² against the province's 16,761 km².\n\nWhether the province would be the better window is a genuine trade-off:\n\n- **Excluding Belitung discards data.** It carries 132 MODIS detections across nine months of\n  2023, so the estimate describes one island rather than the province the research question\n  names.\n- **Including it degrades the estimate on both islands.** `spattemp.density()` fits a single isotropic\n  spatial bandwidth across the whole window, with no way to vary it by region. Bangka's main\n  landmass sits 85 km from Belitung's, with 15 km of open water at the nearest approach, and\n  adding the second island moves the selected bandwidth from 6,600 m to 29,251 m.\n\nPart 1 uses Bangka, which is the chapter's actual window, and names it as Bangka. Estimating each\nisland separately with `spattemp.density()` would give each its own bandwidth and is the better\ntreatment of two disjoint landmasses. That is beyond what section 6.10 covers and is recorded\nhere as a limitation.\n\n### Bandwidth selection and hard-coded values\n\nSection 6.10.1 uses `h = 9000` and `lambda = 19` without showing the `BOOT.spattemp()` output\nthey came from. Those values are specific to the window they were derived on.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbw_of <- function(poly) {\n  pts <- fire_all[lengths(st_intersects(fire_all, poly)) > 0, ] |>\n    mutate(DayofYear = yday(acq_date))\n  pp <- (pts |> select(DayofYear) |> as.ppp())[as.owin(poly)]\n  c(parts = length(st_cast(poly, \"POLYGON\", warn = FALSE)),\n    n = npoints(pp),\n    BOOT.spattemp(pp, verbose = FALSE))\n}\n\nprovince <- st_read(\"data/rawdata/gadm41_IDN_2.json\", quiet = TRUE) |>\n  filter(NAME_1 == \"BangkaBelitung\") |>\n  st_union() |> st_zm(drop = TRUE, what = \"ZM\") |> st_transform(32748)\nprov_parts <- st_cast(province, \"POLYGON\", warn = FALSE)\nprovince_clean <- st_union(prov_parts[as.numeric(st_area(prov_parts)) / 1e6 >= 1])\n\nrbind(`Bangka, all 53 pieces`     = bw_of(bangka_raw),\n      `Bangka, pieces >= 1 km2`   = bw_of(kbb_sf),\n      `province, pieces >= 1 km2` = bw_of(province_clean)) |>\n  round(1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                          parts   n       h lambda\nBangka, all 53 pieces        53 766 54139.1   13.7\nBangka, pieces >= 1 km2      11 766  6599.8   23.8\nprovince, pieces >= 1 km2    41 898 29250.8   19.9\n```\n\n\n:::\n:::\n\n\nDropping fragments that hold 0.03% of the area moves `h` from 54,139 m to 6,600 m. Adding\nBelitung moves it back to 29,251 m. The shift is driven almost entirely by the boundary geometry\nrather than by point density: a single isotropic bandwidth has to balance the whole window at\nonce, so remote fragments inflate `h`. Filtering the islets in section 3.1.1 therefore changes\nwhich bandwidth the estimator selects.\n\nThe choice of selector matters as much as the window. `sparr` provides five, and Chapter 6 uses\none of them and then discards its output for a fixed number.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nselectors <- c(\"NS.spattemp\", \"OS.spattemp\", \"LIK.spattemp\", \"LSCV.spattemp\")\nsel <- t(sapply(selectors, function(nm) get(nm)(fire_yday_owin)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nh = 15504.12 \b; lambda = 6.390331 \nh = 17054.53 \b; lambda = 6.390331 \nh = 15504.12 \b; lambda = 1556.802 \nh = 15891.72 \b; lambda = 781.5961 \nh = 16085.52 \b; lambda = 393.9932 \nh = 16182.42 \b; lambda = 200.1918 \nh = 16230.87 \b; lambda = 103.2911 \nh = 16255.1 \b; lambda = 54.84069 \nh = 16267.21 \b; lambda = 30.61551 \nh = 16273.26 \b; lambda = 18.50292 \nh = 16276.29 \b; lambda = 12.44663 \nh = 16282.35 \b; lambda = 0.334036 \nh = 14731.94 \b; lambda = 0.334036 \nh = 15312.59 \b; lambda = 1.84811 \nh = 15650.79 \b; lambda = 3.740702 \nh = 15724.13 \b; lambda = 2.415887 \nh = 14754.37 \b; lambda = 3.929961 \nh = 15900.35 \b; lambda = 1.233017 \nh = 15488.81 \b; lambda = 0.6652396 \nh = 16076.58 \b; lambda = 0.05014715 \nh = 15503.58 \b; lambda = 1.398619 \nh = 15885.58 \b; lambda = 0.4996378 \nh = 15790.08 \b; lambda = 0.7243831 \nh = 15378.54 \b; lambda = 0.1566055 \nh = 15769.9 \b; lambda = 0.9639143 \nh = 16071.17 \b; lambda = 1.023058 \nh = 15925.58 \b; lambda = 0.9336033 \nh = 15945.76 \b; lambda = 0.6940721 \nh = 16033.69 \b; lambda = 0.559151 \nh = 15810.26 \b; lambda = 0.4848519 \nh = 15896.75 \b; lambda = 0.8214154 \nh = 16052.43 \b; lambda = 0.7911044 \nh = 16183.61 \b; lambda = 0.824465 \nh = 16134.6 \b; lambda = 0.9518084 \nh = 15992.97 \b; lambda = 0.7585062 \nh = 16279.83 \b; lambda = 0.7615557 \nh = 16471.36 \b; lambda = 0.7316259 \nh = 16662 \b; lambda = 0.7975848 \nh = 16996.52 \b; lambda = 0.8171241 \nh = 17284.27 \b; lambda = 0.7242849 \nh = 17834.61 \b; lambda = 0.6741949 \nh = 18359.76 \b; lambda = 0.7596931 \nh = 19303.96 \b; lambda = 0.7737267 \nh = 20142.05 \b; lambda = 0.6307975 \nh = 21714.81 \b; lambda = 0.5376342 \nh = 23184.16 \b; lambda = 0.6371659 \nh = 21846.78 \b; lambda = 0.6464232 \nh = 25595.02 \b; lambda = 0.4010735 \nh = 28740.55 \b; lambda = 0.2147469 \nh = 24125.67 \b; lambda = 0.3015417 \nh = 23419.54 \b; lambda = 0.5532599 \nh = 27299.75 \b; lambda = 0.4166992 \nh = 30092.22 \b; lambda = 0.3562317 \nh = 32267.7 \b; lambda = 0.2040453 \nh = 25631.58 \b; lambda = 0.4659562 \nh = 30055.66 \b; lambda = 0.2913489 \nh = 26737.6 \b; lambda = 0.4223044 \nh = 31234.79 \b; lambda = 0.3774626 \nh = 34054.68 \b; lambda = 0.3656572 \nh = 34589.41 \b; lambda = 0.3113899 \nh = 28700.55 \b; lambda = 0.3945758 \nh = 29843.13 \b; lambda = 0.4158067 \nh = 29905.4 \b; lambda = 0.4009129 \nh = 32439.64 \b; lambda = 0.3837998 \nh = 34309.19 \b; lambda = 0.3784118 \nh = 33769.03 \b; lambda = 0.3603494 \nh = 32803.13 \b; lambda = 0.3704903 \nh = 34007.98 \b; lambda = 0.3768275 \nh = 33314.68 \b; lambda = 0.3769863 \nh = 32951.2 \b; lambda = 0.3902957 \nh = 32914.18 \b; lambda = 0.3853444 \nh = 32039.14 \b; lambda = 0.3921579 \nh = 32358.03 \b; lambda = 0.388365 \nh = 32995.79 \b; lambda = 0.3807792 \nh = 32517.47 \b; lambda = 0.3864685 \nh = 32992 \b; lambda = 0.3880131 \nh = 32853.91 \b; lambda = 0.3869598 \nh = 33250.62 \b; lambda = 0.3858356 \nh = 32700.76 \b; lambda = 0.3863103 \nh = 32640.49 \b; lambda = 0.3879257 \nh = 32845.76 \b; lambda = 0.3859897 \nh = 32692.6 \b; lambda = 0.3853402 \nh = 32813.59 \b; lambda = 0.3865549 \nh = 32958.59 \b; lambda = 0.3862343 \nh = 32765.21 \b; lambda = 0.3862913 \nh = 32733.04 \b; lambda = 0.3868565 \nh = 32761.22 \b; lambda = 0.3866398 \nh = 15504.12 \b; lambda = 6.390331 \nh = 17054.53 \b; lambda = 6.390331 \nh = 15504.12 \b; lambda = 1556.802 \nh = 15891.72 \b; lambda = 781.5961 \nh = 16085.52 \b; lambda = 393.9932 \nh = 16182.42 \b; lambda = 200.1918 \nh = 16230.87 \b; lambda = 103.2911 \nh = 16255.1 \b; lambda = 54.84069 \nh = 16267.21 \b; lambda = 30.61551 \nh = 16273.26 \b; lambda = 18.50292 \nh = 16276.29 \b; lambda = 12.44663 \nh = 16282.35 \b; lambda = 0.334036 \nh = 14731.94 \b; lambda = 0.334036 \nh = 15505.63 \b; lambda = 3.362184 \nh = 15506.39 \b; lambda = 1.84811 \nh = 15506.77 \b; lambda = 1.091073 \nh = 15506.95 \b; lambda = 0.7125544 \nh = 15507.05 \b; lambda = 0.5232952 \nh = 15507.24 \b; lambda = 0.1447768 \nh = 13956.83 \b; lambda = 0.1447768 \nh = 12794.07 \b; lambda = 0.05014715 \nh = 14441.29 \b; lambda = 0.215749 \nh = 14295.97 \b; lambda = 0.1566055 \nh = 14005.33 \b; lambda = 0.03831845 \nh = 14453.47 \b; lambda = 0.09450478 \nh = 13926.58 \b; lambda = 0.06936879 \nh = 12872.81 \b; lambda = 0.01909681 \nh = 14084.08 \b; lambda = 0.007268107 \nh = 13741.89 \b; lambda = 0.02575045 \nh = 13215 \b; lambda = 0.0006144627 \nh = 13261.18 \b; lambda = 0.01151905 \nh = 13455.36 \b; lambda = 0.007730166 \nh = 13843.72 \b; lambda = 0.000152404 \nh = 13806.72 \b; lambda = 0.00382577 \nh = 13668.04 \b; lambda = 0.002104602 \nh = 13598.7 \b; lambda = 0.001244018 \nh = 13564.03 \b; lambda = 0.0008137255 \nh = 13546.7 \b; lambda = 0.0005985794 \nh = 14175.42 \b; lambda = 0.0001365208 \nh = 13778.13 \b; lambda = 0.0003715209 \nh = 13893.85 \b; lambda = 0.0002579917 \nh = 14125.29 \b; lambda = 3.093316e-05 \nh = 14456.98 \b; lambda = 1.504989e-05 \nh = 14233.28 \b; lambda = 7.975615e-05 \nh = 14262.21 \b; lambda = 5.137384e-05 \nh = 14276.67 \b; lambda = 3.718268e-05 \nh = 14305.6 \b; lambda = 8.800371e-06 \nh = 14253.29 \b; lambda = 2.142915e-05 \nh = 14509.29 \b; lambda = 2.421119e-06 \nh = 14432.21 \b; lambda = 1.033032e-05 \nh = 14382.68 \b; lambda = 8.911697e-07 \nh = 14375.79 \b; lambda = 5.228257e-06 \nh = 14410.89 \b; lambda = 3.442201e-06 \nh = 14428.44 \b; lambda = 2.549172e-06 \nh = 14463.53 \b; lambda = 7.631158e-07 \nh = 14466.2 \b; lambda = 1.624131e-06 \nh = 14380.01 \b; lambda = 3.015487e-08 \nh = 14402.23 \b; lambda = 6.439025e-07 \nh = 14427.33 \b; lambda = 5.500723e-07 \nh = 14402.95 \b; lambda = 4.67008e-07 \nh = 14409.4 \b; lambda = 3.993269e-07 \nh = 14398.83 \b; lambda = 3.408745e-07 \nh = 14399.41 \b; lambda = 2.924208e-07 \nh = 14394.27 \b; lambda = 2.510811e-07 \nh = 14393.28 \b; lambda = 2.165194e-07 \nh = 14390.46 \b; lambda = 1.872091e-07 \nh = 14377.19 \b; lambda = 8.446178e-10 \nh = 14384.53 \b; lambda = 1.013544e-07 \nh = 14381.57 \b; lambda = 5.842709e-08 \nh = 14380.08 \b; lambda = 3.696342e-08 \nh = 14379.34 \b; lambda = 2.623158e-08 \nh = 14379.14 \b; lambda = 2.184648e-08 \nh = 14378.75 \b; lambda = 1.878857e-08 \nh = 14378.56 \b; lambda = 1.583154e-08 \nh = 14378.31 \b; lambda = 1.356332e-08 \nh = 14378.16 \b; lambda = 1.151775e-08 \nh = 14377.99 \b; lambda = 9.872254e-09 \nh = 14377.87 \b; lambda = 8.438095e-09 \nh = 14377.76 \b; lambda = 7.256805e-09 \nh = 14377.68 \b; lambda = 6.244403e-09 \nh = 14377.6 \b; lambda = 5.400658e-09 \nh = 14377.12 \b; lambda = 8.725035e-13 \nh = 14377.38 \b; lambda = 2.911701e-09 \nh = 14377.27 \b; lambda = 1.667223e-09 \nh = 14377.21 \b; lambda = 1.044984e-09 \nh = 14377.18 \b; lambda = 7.338647e-10 \nh = 14377.17 \b; lambda = 6.059932e-10 \nh = 14377.16 \b; lambda = 5.186488e-10 \nh = 14377.15 \b; lambda = 4.328769e-10 \nh = 14377.15 \b; lambda = 3.677618e-10 \nh = 14377.14 \b; lambda = 3.08597e-10 \nh = 14377.14 \b; lambda = 2.612483e-10 \nh = 14377.14 \b; lambda = 2.198287e-10 \nh = 14377.13 \b; lambda = 1.857994e-10 \nh = 14377.13 \b; lambda = 1.565823e-10 \nh = 14377.13 \b; lambda = 1.322634e-10 \nh = 14377.13 \b; lambda = 1.115752e-10 \nh = 14377.12 \b; lambda = 9.424363e-11 \nh = 14377.12 \b; lambda = 7.956661e-11 \nh = 14377.12 \b; lambda = 6.723159e-11 \nh = 14377.12 \b; lambda = 5.680933e-11 \nh = 14377.12 \b; lambda = 4.803625e-11 \nh = 14377.12 \b; lambda = 4.063185e-11 \nh = 14377.12 \b; lambda = 3.439422e-11 \nh = 14377.12 \b; lambda = 2.913261e-11 \nh = 14377.12 \b; lambda = 2.469839e-11 \nh = 14377.12 \b; lambda = 2.095903e-11 \nh = 14377.12 \b; lambda = 1.780707e-11 \nh = 14377.12 \b; lambda = 1.514941e-11 \nh = 14377.12 \b; lambda = 1.290902e-11 \nh = 14377.12 \b; lambda = 1.102008e-11 \nh = 14377.12 \b; lambda = 9.427654e-12 \nh = 14377.12 \b; lambda = 8.085081e-12 \nh = 14377.12 \b; lambda = 6.953223e-12 \nh = 14377.12 \b; lambda = 5.998972e-12 \nh = 14377.12 \b; lambda = 5.194481e-12 \nh = 14377.12 \b; lambda = 6.801178e-14 \nh = 14377.12 \b; lambda = 2.832369e-12 \nh = 14377.12 \b; lambda = 1.651313e-12 \nh = 14377.12 \b; lambda = 1.060785e-12 \nh = 14377.12 \b; lambda = 7.655216e-13 \nh = 14377.12 \b; lambda = 6.446351e-13 \nh = 14377.12 \b; lambda = 5.609225e-13 \nh = 14377.12 \b; lambda = 4.795511e-13 \nh = 14377.12 \b; lambda = 4.17352e-13 \nh = 14377.12 \b; lambda = 5.81265e-15 \nh = 14377.12 \b; lambda = 2.271321e-13 \nh = 14377.12 \b; lambda = 1.320222e-13 \nh = 14377.12 \b; lambda = 8.446719e-14 \nh = 14377.12 \b; lambda = 6.06897e-14 \nh = 14377.12 \b; lambda = 5.063148e-14 \nh = 14377.12 \b; lambda = 4.445588e-14 \nh = 14377.12 \b; lambda = 3.788287e-14 \nh = 14377.12 \b; lambda = 3.315182e-14 \nh = 14377.12 \b; lambda = 1.081599e-15 \nh = 14377.12 \b; lambda = 1.829947e-14 \nh = 14377.12 \b; lambda = 1.08733e-14 \nh = 14377.12 \b; lambda = 7.160212e-15 \nh = 14377.12 \b; lambda = 5.303668e-15 \nh = 14377.12 \b; lambda = 5.726174e-16 \nh = 14377.12 \b; lambda = 3.065388e-15 \nh = 14377.12 \b; lambda = 1.946248e-15 \nh = 14377.12 \b; lambda = 1.386678e-15 \nh = 14377.12 \b; lambda = 2.675383e-16 \nh = 14377.12 \b; lambda = 7.508386e-16 \nh = 14377.12 \b; lambda = 8.931721e-17 \nh = 14377.12 \b; lambda = 3.755226e-16 \nh = 14377.12 \b; lambda = 2.769752e-16 \nh = 14377.12 \b; lambda = 7.988037e-17 \nh = 14377.12 \b; lambda = 1.760686e-16 \nh = 14377.12 \b; lambda = 1.303337e-16 \nh = 14377.12 \b; lambda = 3.88639e-17 \nh = 14377.12 \b; lambda = 2.942705e-17 \nh = 14377.12 \b; lambda = 5.701292e-17 \nh = 14377.12 \b; lambda = 1.127803e-17 \nh = 14377.12 \b; lambda = 1.841187e-18 \nh = 14377.12 \b; lambda = 1.799333e-17 \nh = 14377.12 \b; lambda = 1.227647e-17 \nh = 14377.12 \b; lambda = 8.427488e-19 \nh = 14377.12 \b; lambda = 6.31e-18 \nh = 14377.12 \b; lambda = 3.825984e-18 \nh = 14377.12 \b; lambda = 2.583976e-18 \nh = 14377.12 \b; lambda = 9.996007e-20 \nh = 14377.12 \b; lambda = 1.156271e-18 \nh = 14377.12 \b; lambda = 8.138127e-19 \nh = 14377.12 \b; lambda = 7.102395e-20 \nh = 14377.12 \b; lambda = 4.496523e-19 \nh = 14377.12 \b; lambda = 2.675722e-19 \nh = 14377.12 \b; lambda = 1.765321e-19 \nh = 14377.12 \b; lambda = 1.310121e-19 \nh = 14377.12 \b; lambda = 3.997197e-20 \nh = 14377.12 \b; lambda = 1.103585e-20 \nh = 14377.12 \b; lambda = 4.826393e-20 \nh = 14377.12 \b; lambda = 2.743887e-21 \nh = 14377.12 \b; lambda = 2.343092e-20 \nh = 14377.12 \b; lambda = 1.516039e-20 \nh = 14377.12 \b; lambda = 1.102513e-20 \nh = 14377.12 \b; lambda = 2.733168e-21 \nh = 14377.12 \b; lambda = 6.881829e-21 \nh = 14377.12 \b; lambda = 4.810178e-21 \nh = 14377.12 \b; lambda = 6.668765e-22 \nh = 14377.12 \b; lambda = 6.561572e-22 \nh = 14377.12 \b; lambda = 1.697342e-21 \nh = 14377.12 \b; lambda = 1.17943e-21 \nh = 14377.12 \b; lambda = 1.436041e-22 \nh = 14377.12 \b; lambda = 1.328847e-22 \nh = 14377.12 \b; lambda = 3.972008e-22 \nh = 14377.12 \b; lambda = 2.677226e-22 \nh = 14377.12 \b; lambda = 8.766253e-24 \nh = 14377.12 \b; lambda = 1.072148e-22 \nh = 14377.12 \b; lambda = 9.543764e-23 \nh = 14377.12 \b; lambda = 7.965838e-23 \nh = 14377.12 \b; lambda = 6.982498e-23 \nh = 14377.12 \b; lambda = 5.9477e-23 \nh = 14377.12 \b; lambda = 5.19733e-23 \nh = 14377.12 \b; lambda = 1.262557e-24 \nh = 14377.12 \b; lambda = 2.849385e-23 \nh = 14377.12 \b; lambda = 1.675413e-23 \nh = 14377.12 \b; lambda = 1.088427e-23 \nh = 14377.12 \b; lambda = 7.949336e-24 \nh = 14377.12 \b; lambda = 4.456404e-25 \nh = 14377.12 \b; lambda = 4.401717e-24 \nh = 14377.12 \b; lambda = 2.627908e-24 \nh = 14377.12 \b; lambda = 1.741003e-24 \nh = 14377.12 \b; lambda = 1.297551e-24 \nh = 14377.12 \b; lambda = 4.106465e-25 \nh = 14377.12 \b; lambda = 8.453503e-25 \nh = 14377.12 \b; lambda = 1.09366e-26 \nh = 14377.12 \b; lambda = 3.28216e-25 \nh = 14377.12 \b; lambda = 2.901114e-25 \nh = 14377.12 \b; lambda = 2.3937e-25 \nh = 14377.12 \b; lambda = 2.076323e-25 \nh = 14377.12 \b; lambda = 1.743272e-25 \nh = 14377.12 \b; lambda = 1.501321e-25 \nh = 14377.12 \b; lambda = 1.274308e-25 \nh = 14377.12 \b; lambda = 1.096579e-25 \nh = 14377.12 \b; lambda = 9.386403e-26 \nh = 14377.12 \b; lambda = 8.102912e-26 \nh = 14377.12 \b; lambda = 6.992344e-26 \nh = 14377.12 \b; lambda = 6.072957e-26 \nh = 14377.12 \b; lambda = 1.742726e-27 \nh = 14377.12 \b; lambda = 3.353462e-26 \nh = 14377.12 \b; lambda = 1.993714e-26 \nh = 14377.12 \b; lambda = 1.31384e-26 \nh = 14377.12 \b; lambda = 9.739033e-27 \nh = 14377.12 \b; lambda = 5.45158e-28 \nh = 14377.12 \b; lambda = 5.441488e-27 \nh = 14377.12 \b; lambda = 3.292715e-27 \nh = 14377.12 \b; lambda = 2.218329e-27 \nh = 14377.12 \b; lambda = 6.955584e-29 \nh = 14377.12 \b; lambda = 1.025042e-27 \nh = 14377.12 \b; lambda = 6.661993e-28 \nh = 14377.12 \b; lambda = 4.867781e-28 \nh = 14377.12 \b; lambda = 1.117593e-29 \nh = 14377.12 \b; lambda = 2.63572e-28 \nh = 14377.12 \b; lambda = 1.519689e-28 \nh = 14377.12 \b; lambda = 9.616742e-29 \nh = 14377.12 \b; lambda = 6.826665e-29 \nh = 14377.12 \b; lambda = 9.886737e-30 \nh = 14377.12 \b; lambda = 3.939899e-29 \nh = 14377.12 \b; lambda = 2.496516e-29 \nh = 14377.12 \b; lambda = 1.774825e-29 \nh = 14377.12 \b; lambda = 3.314419e-30 \nh = 14377.12 \b; lambda = 2.025226e-30 \nh = 14377.12 \b; lambda = 6.27828e-30 \nh = 14377.12 \b; lambda = 4.474051e-30 \nh = 14377.12 \b; lambda = 8.655936e-31 \nh = 14377.12 \b; lambda = 2.379914e-30 \nh = 14377.12 \b; lambda = 5.10905e-31 \nh = 14377.12 \b; lambda = 1.356737e-30 \nh = 14377.12 \b; lambda = 1.976113e-32 \nh = 14377.12 \b; lambda = 5.654633e-31 \nh = 14377.12 \b; lambda = 4.153982e-31 \n```\n\n\n:::\n\n```{.r .cell-code}\nrbind(sel,\n      BOOT.spattemp = bw,\n      `chapter (hard-coded)` = c(h = 9000, lambda = 19)) |>\n  round(2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                            h lambda\nNS.spattemp          14295.15  12.81\nOS.spattemp          15504.12  16.28\nLIK.spattemp         32765.21   0.39\nLSCV.spattemp        14377.12   0.00\nBOOT.spattemp         6599.77  23.76\nchapter (hard-coded)  9000.00  19.00\n```\n\n\n:::\n:::\n\n\nSpatial bandwidths run from 6,600 m to 32,765 m, a factor of five, on identical data and an\nidentical window. The two cross-validation selectors do not merely disagree: `LSCV.spattemp`\nreturns a temporal bandwidth of 0.00 days and `LIK.spattemp` returns 0.39. Both are close enough\nto zero to mean no temporal smoothing at all, which reduces the estimate to plotting each day\nseparately. Daily counts here are\nsparse and strongly seasonal, which is the likely cause. The three that behave, `NS`, `OS` and\nthe bootstrap, fall between 12.8 and 23.8 days.\n\nThe bare `spattemp.density(fire_yday_owin)` call in section 6.9 is not bandwidth-free either.\nIts source sets `h <- OS(pp)` and `lambda <- bw.SJ(tt)`, so it silently uses the oversmoothing\nselector for space and Sheather-Jones for time. Chapter 6 does not say so.\n\nTonini et al. (2017) use a different method, reading the bandwidth off the K-function by taking\n\"the distance values showing a maximum cluster behaviour\" as the scale that avoids under- or\nover-smoothing. That does not transfer here. The K surface in section 3.2.2 rises monotonically\nand its maximum sits at 44,085 m, the largest distance evaluated, so there is no interior peak\nto read.\n\nThe Lesson 3 readings do not agree on how to choose a bandwidth. Chapter 6 presents one number as\nthough the question were settled.\n\n| Source | How the bandwidth is chosen |\n|---|---|\n| Chapter 6 | `BOOT.spattemp()`, then a fixed value carried over from another dataset |\n| Tonini et al. (2017) | Read off the K-function, at the distance of maximum clustering |\n| González and Moraga (2023) | Spatially varying, using an adaptive estimate |\n| Hohl et al. | Not chosen at all. They sweep 50 m to 1,000 m in 50 m steps and 0 to 14 days in 1-day steps, then report the scales at which the observed function departs furthest from the simulation envelope |\n\nHohl et al. use a different approach. They vary the bandwidth itself and report clustering as a\nfunction of scale, which sidesteps the selector disagreement above at the cost of much more\ncomputation.\n\nOn the observation window there is no such disagreement. All three sources that call these\nfunctions pass the study region explicitly, which is why section 4.1.1 treats the chapter's\nomission as an error rather than one of several accepted approaches.\n\nA further limitation: everything above uses a fixed bandwidth. González and Moraga (2023) note\nthat \"the estimation can be improved by using a spatially varying bandwidth despite its\ncomputational complexity\", and Tonini et al. compared fixed against adaptive and chose adaptive.\n`sparr` supports adaptive smoothing and this exercise does not use it.\n\n### Colour scaling across sections\n\nPlotting a density surface at several time slices requires a choice: one colour scale shared by\nevery panel, or a separate scale fitted to each. Chapter 6 makes both choices without saying so.\nSection 6.8.5 passes `fix.range = TRUE`, section 6.10.2 takes the `FALSE` default, and the text\ndoes not mention the change.\n\nThe choice matters here because the year is very uneven.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndays <- c(60, 152, 213, 259, 305, 350)\n\nday_max <- sapply(days, function(d) {\n  nm <- names(kde_yday_boot$z)[which.min(abs(as.numeric(names(kde_yday_boot$z)) - d))]\n  v <- kde_yday_boot$z[[nm]]$v\n  max(v[is.finite(v)])\n})\n\ndata.frame(day = days,\n           date = format(as.Date(days - 1, origin = \"2023-01-01\"), \"%d %b\"),\n           peak_density = signif(day_max, 3),\n           pct_of_highest = round(100 * day_max / max(day_max), 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  day   date peak_density pct_of_highest\n1  60 01 Mar     2.02e-13            7.1\n2 152 01 Jun     4.69e-13           16.6\n3 213 01 Aug     2.21e-12           78.3\n4 259 16 Sep     2.24e-12           79.4\n5 305 01 Nov     2.83e-12          100.0\n6 350 16 Dec     1.47e-12           51.9\n```\n\n\n:::\n:::\n\n\nPeak density on 1 November is 14 times that on 1 March.\n\nWith `fix.range = FALSE`, the default, each panel gets its own colour scale running from that\nday's own minimum to that day's own maximum. Every panel therefore uses the full range of\ncolours, and 1 March is drawn as brightly as 1 November even though its peak density is a\nfourteenth as high. What the colours show is where the fires were on that day.\n\nWith `fix.range = TRUE`, one scale is set by the busiest day and used for all six panels. The\nsame colour then means the same density everywhere, so 1 March is almost uniformly dark. That is\ncorrect about the season and it hides the variation within the quiet days.\n\nThe chapter switches between the two without saying which question it is answering. `TRUE` shows\nthe timing of the fire season; `FALSE` shows where the fires fell on a given day.\n\n### Graphics device handling in plotK()\n\n`plotK()` manages the graphics device itself, which works in an interactive session and does not\nsurvive document rendering. It checks the active devices with `dev.list()`, closes any it finds\nwith `dev.off()`, and opens a new one with `dev.new()`. During a render, the open device is the\none knitr is using to capture chunk output into a figure file. Closing it sends the plot to a\ndevice nothing is recording, and the chunk completes with no image and no warning.\n\nThis is a limitation of the function rather than an error in the chapter, and the chapter's own\npublished page shows the effect: section 6.11.2 carries the code with no figure below it, and the\nlast image on the page is `plot(fire_stpp)` from 6.11.1.\n\nSection 3.2.2 does not call `plotK()`. It draws K̂(u,v) − K_theo from the object `STIKhat()`\nreturns, using `filled.contour()`.\n\n### Seed placement\n\n`BOOT.spattemp()` is a bootstrap. The chapter sets one seed inside section 6.10, immediately\nbefore that call, and nowhere else. Anything added before or after is unseeded, so the numbers\nthat the prose quotes can change on re-rendering. This page sets one seed in section 2.1 before anything runs.\n\nAcross two seeds `BOOT.spattemp()` returned identical bandwidths on this dataset. That stability\nis specific to this call and does not extend to the envelopes and simulations the take-home will\nneed.\n\n## Other observations\n\nFurther points about how the chapter's code behaves. None of them change a result.\n\n**The duplicate check.** Section 6.8.2 runs `any(duplicated(fire_month_ppp))` and does nothing\nwith the output. Section 3.1.5.1 reports the count instead, which is zero.\n\n**One image per day.** `plot()` on a daily estimate draws a separate panel for every day in the\nrange. In an interactive session those appear in sequence as an animation,\nwhich is why `plot.stden()` has a `sleep` argument. On a web page there is nothing to animate, so each frame is\nwritten out as its own image file instead. Section 6.9.3 produces 343 of these, section 6.10.2\nanother 343, and the published page carries 686 in total. The `tselect` argument selects which\ndays to draw. It goes unused in both sections.\n\n## Fire counts and rates by regency\n\nChapter 6 does not break the fires down by administrative unit. The density surface it produces\nis continuous across space, so it smooths over the differences between those units.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_counts <- st_join(fire_sf, kbb_regencies[\"NAME_2\"]) |>\n  st_drop_geometry() |>\n  count(NAME_2, name = \"fires\")\n\nkbb_regencies |>\n  mutate(area_km2 = round(as.numeric(st_area(kbb_regencies)) / 1e6)) |>\n  st_drop_geometry() |>\n  select(NAME_2, area_km2) |>\n  left_join(fire_counts, by = \"NAME_2\") |>\n  mutate(fires = replace_na(fires, 0),\n         per_1000km2 = round(fires / area_km2 * 1000, 1)) |>\n  arrange(desc(fires)) |>\n  as.data.frame()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         NAME_2 area_km2 fires per_1000km2\n1 BangkaSelatan     3617   357        98.7\n2  BangkaTengah     2220   141        63.5\n3   BangkaBarat     2889   135        46.7\n4        Bangka     3057   133        43.5\n5 Pangkalpinang      109     0         0.0\n```\n\n\n:::\n:::\n\n\nCounts and rates rank the regencies differently, where the rate is each regency's fire count\ndivided by its area. Pangkalpinang records none at all. It is the only city in the table and the\nsmallest unit at 109 km².\n\nCounting by regency also matches the administrative unit Take-home Exercise 1 requires students\nto select.\n\n# Reflection\n\nThe chapter asks two questions. On the first, the fires are not independent in space and time:\nthe K-function excess is positive across every distance and time lag evaluated. On the second,\nthey concentrate in the south of Bangka, where Bangka Selatan carries 357 of the 766 detections\non 30% of the land area, and in the second half of the year, where October alone accounts for\n190. The concentration also moves through the season, sitting in the north-west in August and in\nthe far south by November. Section 4.1.1 shows the chapter's own K-function call overstates the\nsize of that clustering by a factor of 2.4; the direction is the same either way.\n\nThe reproduction in Part 1 took a few hours. Almost all the remaining time went on Part 2, and\nmost of that on checking things I had assumed were fine.\n\nThe chapter left three decisions to me.\n\n**The study area.** Chapter 6 says its study area is the province and its file contains one\nisland. I found this because the map I produced had a second island that the chapter's map does\nnot have. I checked the chapter's printed bounding box against two independent boundary sources,\nGADM and geoBoundaries, which agree with each other and not with the chapter. Part 1 follows the\nchapter's actual window because reproducing the chapter is the exercise, and names that window\ncorrectly. Analysing the province is the other reasonable choice, and I measured what it costs: a single\nisotropic bandwidth serving two landmasses 85 km apart moves from 6,600 m to 29,251 m.\n\n**Dropping the offshore islets.** I filtered pieces under 1 km² at the start, expecting it to be\nhousekeeping. With all 53 pieces the bootstrap selects 54,139 m; with 11 it selects 6,600 m.\nFragments holding 0.03% of the area were setting the smoothing scale for the whole island. I\nfound this because a number in Part 2 disagreed with one I had computed earlier.\n\n**Using the bootstrap's own output.** The chapter hard-codes `h = 9000`. I wrote that this was\nwrong and then, in the same section, hard-coded it myself instead of passing the value the\nbootstrap returned. The version here runs `BOOT.spattemp()` and uses what it returns.\n\nWith more time I would estimate each island separately. `spattemp.density()` fits one bandwidth\nacross the whole window, so two disjoint landmasses cannot both be served well. The readings\nagree: González and Moraga recommend a spatially varying bandwidth, and Tonini et al. compared\nfixed against adaptive and chose adaptive. This exercise uses a fixed bandwidth throughout.\n\nThe analysis does not establish two things. The K-function has no simulation envelope, so nothing\nhere shows the observed excess is larger than sampling variation would produce; Hohl et al. do\nthis by comparing against upper and lower envelopes at each combination of bandwidths. And\n`STIKhat()` was run without a `lambda`, so it uses its own internal intensity estimate as the\nreference rather than one I specified.\n\nThree of the findings across Part 2 are calls that return without error and without effect:\n`plotK()` draws to a device that has been discarded, section 6.8.2 computes a duplicate check and\ndoes not read it, and `STIKhat()` substitutes a bounding box for the study region. None of them warn. In Ex 2\nthe same pattern appeared as a `clipregion` argument passed as a string instead of an object. In\neach case the output had to be inspected before the problem was visible.\n\n# References\n\n- r4gdsa, [Chapter 6: Spatio-Temporal Point Patterns\n  Analysis](https://r4gdsa.netlify.app/chap06.html).\n\nLesson 3 reading list:\n\n- González, J.A., Rodríguez-Cortés, F.J., Cronie, O. and Mateu, J. (2016), \"Spatio-temporal point\n  process statistics: A review\", *Spatial Statistics*, 18(B), 505-544.\n- Hohl, A., Zheng, M., Tang, W., Delmelle, E. and Casas, I., \"Spatiotemporal Point Pattern\n  Analysis Using Ripley's K Function\", in *Geospatial Data Science Techniques and Applications*,\n  ch. 7, 155-175.\n- Tonini, M., Pereira, M.G., Parente, J. and Vega Orozco, C. (2017), \"Evolution of forest fires in\n  Portugal: from spatio-temporal point events to smoothed density maps\", *Natural Hazards*,\n  85(3), 1489-1510.\n- Juan, P., Mateu, J. and Saez, M. (2012), \"Pinpointing spatio-temporal interactions in wildfire\n  patterns\", *Stochastic Environmental Research and Risk Assessment*, 26(8), 1131-1150.\n- González, J.A. and Moraga, P. (2023), [\"Non-Parametric Analysis of Spatial and Spatio-Temporal\n  Point Patterns\"](https://journal.r-project.org/articles/RJ-2023-025/), *The R Journal*, 15(2).\n- Gabriel, E., Rowlingson, B. and Diggle, P.J. (2013), [\"stpp: An R Package for Plotting,\n  Simulating and Analyzing Spatio-Temporal Point\n  Patterns\"](https://www.jstatsoft.org/article/view/v053i02), *Journal of Statistical Software*,\n  53(2).\n\nMethods and packages:\n\n- Davies, T.M. and Hazelton, M.L. (2010), \"Adaptive kernel estimation of spatial relative risk\",\n  *Statistics in Medicine*, 29(23), 2423-2437. The method behind `sparr`.\n- Hall, P. (1990), \"Using the Bootstrap to Estimate Mean Squared Error and Select Smoothing\n  Parameter in Nonparametric Problems\", *Journal of Multivariate Analysis*, 32, 177-203. The\n  bootstrap behind `BOOT.spattemp()`.\n\nData:\n\n- NASA FIRMS, [Fire Information for Resource Management\n  System](https://firms.modaps.eosdis.nasa.gov/), MODIS Collection 6.1 archive for Indonesia,\n  2023.\n- GADM, [Database of Global Administrative Areas](https://gadm.org/), version 4.1, Indonesia\n  level 2.\n",
    "supporting": [
      "Hands-on_Ex03_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}