{
  "hash": "c2e1b732e3ec3bfa6b0a04e97135b810",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"In-class Exercise 5\"\nsubtitle: \"Emerging Hot Spot Analysis\"\nauthor: \"An Loc\"\ndate: \"26 September 2026\"\ndate-modified: \"last-modified\"\ndate-format: \"D MMM YYYY\"\nformat:\n  html:\n    toc: true\n    toc-depth: 4\n    toc-expand: true\n    code-copy: true\n    fig-width: 9\n    fig-height: 7\nexecute:\n  echo: true\n  eval: true\n  warning: false\n  message: false\n  freeze: true\n---\n\n# Getting started\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(sf, sfdep, spdep, tmap, plotly, tidyverse)\n```\n:::\n\n\n# The data\n\n## County boundaries\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan <- st_read(dsn = \"data/geospatial\", layer = \"Hunan\", quiet = TRUE) %>%\n  st_transform(crs = 32649)\n\nnrow(hunan)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 88\n```\n\n\n:::\n:::\n\n\n## Development indicators for 2012\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan2012 <- read_csv(\"data/aspatial/Hunan_2012.csv\")\n\nhunan_GDPPC <- hunan %>%\n  left_join(hunan2012, by = \"County\") %>%\n  select(NAME_2, ID_3, NAME_3, ENGTYPE_3,\n         Shape_Leng, Shape_Area, County, GDPPC, GIO)\n\nnames(hunan_GDPPC)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"NAME_2\"     \"ID_3\"       \"NAME_3\"     \"ENGTYPE_3\"  \"Shape_Leng\"\n [6] \"Shape_Area\" \"County\"     \"GDPPC\"      \"GIO\"        \"geometry\"  \n```\n\n\n:::\n:::\n\n\n::: {.callout-note collapse=\"false\" title=\"How the code works\"}\nThe block uses three functions:\n\n``` r\nread_csv(...)                   # readr\nleft_join(..., by = \"County\")   # dplyr\nselect(...)                     # dplyr\n```\n\n- `read_csv()` reads the 29 development indicators for 2012.\n- `left_join()` matches each boundary to its row of indicators on the county name. All 88 names match, so no row is lost.\n- `select()` keeps nine of the columns the join produces: the six geography fields, plus `County`, `GDPPC` and `GIO`. The other 26 indicators are dropped because only GDP per capita is analysed here.\n\n`select()` keeps the geometry column automatically, so the result is still an sf object.\n:::\n\n# Spatial weights\n\n## Queen contiguity, row-standardised\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_q <- hunan_GDPPC %>%\n  mutate(nb = st_contiguity(geometry),\n         wt = st_weights(nb, style = \"W\"),\n         .before = 1)\n```\n:::\n\n\n::: {.callout-note collapse=\"false\" title=\"How the code works\"}\nThe block uses three functions:\n\n``` r\nst_contiguity(geometry)        # sfdep\nst_weights(nb, style = \"W\")    # sfdep\nmutate(..., .before = 1)       # dplyr\n```\n\n- `st_contiguity()` builds the neighbour list from the polygons. Queen contiguity is its default, so counties meeting only at a corner count as neighbours. `queen = FALSE` gives Rook contiguity instead, which drops the mean neighbour count from 5.09 to 5.00.\n- `st_weights()` turns the neighbour list into weights. `style = \"W\"` row-standardises them so each county's weights sum to 1 (default setting). The value is case-sensitive: `\"w\"` raises `Style w invalid`.\n- `mutate()` adds `nb` and `wt` as list-columns, and `.before = 1` places them ahead in front of the other attributes.\n\nThe result is an sf object rather than a bare weights matrix. `sfdep` functions read `nb` and `wt` directly.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_q %>%\n  st_drop_geometry() %>%\n  summarise(counties = n(), mean_neighbours = mean(lengths(nb)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  counties mean_neighbours\n1       88        5.090909\n```\n\n\n:::\n:::\n\n\n## Reading the neighbour list\n\n::: {.callout-note collapse=\"false\" title=\"How to read nb and wt\"}\n`nb` and `wt` are list-columns, so each cell holds a vector rather than a single value. Row 1 is Anxiang:\n\n| Column | Cell 1 | Reads as |\n|------------------------|------------------------|------------------------|\n| `nb` | `c(2, 3, 4, 57, 85)` | rows 2, 3, 4, 57 and 85 of `wm_q` are Anxiang's neighbours |\n| `wt` | `c(0.2, 0.2, 0.2, 0.2, 0.2)` | the weight for each of those five neighbours, in the same order |\n\n- `nb` stores **row positions inside `wm_q`**, not county names and not `ID_3` values. Row 1 is Anxiang, so the value 2 points at row 2.\n- `wt` is always the same length as `nb`, one weight per neighbour.\n- Each weight is 1 divided by the number of neighbours, because the weights are row-standardised. Anxiang has 5 neighbours so each gets 0.2, Jinshi in row 3 has 4 so each gets 0.25, and the six neighbours in row 9 each get 0.1667. Every county's weights sum to 1.\n- RStudio's viewer wraps the values in quotes, as `c(\"2\", \"3\", \"4\", ...)`. That is how it displays list-column elements, not the data type.\n:::\n\n# Global measures of spatial autocorrelation\n\n## Moran's I\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmoranI <- global_moran(wm_q$GDPPC, wm_q$nb, wm_q$wt)\n\nglimpse(moranI)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nList of 2\n $ I: num 0.301\n $ K: num 7.64\n```\n\n\n:::\n:::\n\n\n::: {.callout-note collapse=\"false\" title=\"How the code works\"}\nThe block uses two functions:\n\n``` r\nglobal_moran(wm_q$GDPPC, wm_q$nb, wm_q$wt)   # sfdep\nglimpse(...)                                 # tibble\n```\n\n- `global_moran()` takes the variable, then the neighbour list, then the weights. It returns a list of two numbers, and reproduces the value of `spdep::moran()`.\n- `glimpse()` prints one line per element.\n\n`I` is **0.301**, against a null expectation of −1/(n−1) = −0.011, so GDP per capita is positively spatially autocorrelated: neighbouring counties tend to hold similar values. The value carries no p-value of its own, because `global_moran()` computes the statistic only. `global_moran_test()` adds an analytic test and `global_moran_perm()` a permutation one.\n\n`K` is the kurtosis of the variable, **7.64**. A normal distribution has a kurtosis of 3, so GDP per capita is strongly heavy-tailed. This matters: the randomisation variance of Moran's I is a function of the kurtosis.\n:::\n\n## Moran's I by permutation\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\n\nmoranI_perm <- global_moran_perm(wm_q$GDPPC, wm_q$nb, wm_q$wt,\n                                 nsim = 99)\n\nmoranI_perm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Moran I\n\ndata:  x \nweights: listw  \nnumber of simulations + 1: 100 \n\nstatistic = 0.30075, observed rank = 100, p-value < 2.2e-16\nalternative hypothesis: two.sided\n```\n\n\n:::\n:::\n\n\n::: {.callout-note collapse=\"false\" title=\"How the code works\"}\nThe block uses two functions:\n\n``` r\nset.seed(1234)                                  # base\nglobal_moran_perm(..., nsim = 99)               # sfdep\n```\n\n- `set.seed()` fixes the random draw. The permutation test shuffles the values, so without a seed the p-value changes on every run.\n- `global_moran_perm()` wraps `spdep::moran.mc()`, which builds a reference distribution by shuffling the values across the counties while the weights stay fixed.\n\n**The number of simulations is always `nsim + 1`.** The reference distribution holds the `nsim` permutations plus the observed statistic, which spdep stores last. So `nsim = 99` produces 100 values, and the output says so:\n\n```         \nnumber of simulations + 1: 100\n```\n\nThat \"+1\" sets the smallest p-value the test can report, which is 1/(nsim + 1) = 0.01. A permutation test cannot return anything more extreme than that, however strong the pattern.\n:::\n\n⚠️ On this data the two-sided branch returns `p < 2.2e-16`, the stored value being exactly 0. That sits below the 0.01 floor, so it cannot be a real permutation p-value?\n\n# Local measures of spatial autocorrelation\n\n## Local Moran's I\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\n\nlisa <- wm_q %>%\n  mutate(local_moran = local_moran(GDPPC, nb, wt, nsim = 99), .before = 1) %>%\n  unnest(local_moran)\n```\n:::\n\n\n::: {.callout-note collapse=\"false\" title=\"How the code works\"}\nThe block uses three functions:\n\n``` r\nlocal_moran(GDPPC, nb, wt, nsim = 99)   # sfdep\nmutate(..., .before = 1)                # dplyr\nunnest(local_moran)                     # tidyr\n```\n\n- `local_moran()` computes the statistic for every county in one call and returns a list per county. It takes the same three arguments as the global version, and `nsim` behaves the same way.\n- `mutate()` stores that list in a new column, and `.before = 1` puts it first.\n- `unnest()` expands the list column, giving each county 11 new columns. The ones that matter here are `ii` (the local statistic), `z_ii`, `p_ii`, `p_ii_sim` and `p_folded_sim`, together with `mean` and `median`, which hold the quadrant labels that the cluster map colours.\n\nThe result is an sf object of 88 rows and 24 columns.\n:::\n\n## Reading the quadrant columns\n\n::: {.callout-note collapse=\"false\" title=\"How to read mean, median and pysal\"}\nThese three columns hold quadrant label for every county:\n\n- `mean` compares each county against the **mean** of GDPPC and the mean of its spatial lag. Above both is High-High, below both is Low-Low, and a county above one and below the other is High-Low or Low-High.\n- `median` applies the identical rule using the **median** as the cut point.\n- `pysal` is PySAL's label for the same classification.\n\n| Cut point | High-High | High-Low | Low-High | Low-Low |\n|-----------|-----------|----------|----------|---------|\n| `mean`    | 21        | 11       | 13       | 43      |\n| `median`  | 31        | 13       | 13       | 31      |\n| `pysal`   | 21        | 11       | 13       | 43      |\n:::\n\n## LISA cluster map\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlisa_sig <- lisa %>%\n  filter(p_ii_sim < 0.05)\n\ntmap_mode(\"plot\")\n\ntm_shape(lisa) +\n  tm_polygons() +\n  tm_borders(fill_alpha = 0.5) +\n  tm_shape(lisa_sig) +\n  tm_polygons(fill = \"mean\",\n              fill.legend = tm_legend(text.size = 1.15, width = 6)) +\n  tm_borders(fill_alpha = 0.4) +\n  tm_layout(legend.title.size = 1.25)\n```\n\n::: {.cell-output-display}\n![](In-class_Ex05_files/figure-html/unnamed-chunk-9-1.png){width=864}\n:::\n:::\n\n\n::: {.callout-note collapse=\"false\" title=\"How the code works\"}\nThe block uses four functions:\n\n``` r\nfilter(p_ii_sim < 0.05)   # dplyr\ntmap_mode(\"plot\")         # tmap\ntm_shape(...)             # tmap\ntm_polygons(...)          # tmap\n```\n\n- `filter()` keeps the counties whose permutation p-value is below 0.05. These are the clusters. The other are not distinguishable from spatial randomness.\n- `tmap_mode(\"plot\")` switches tmap from interactive to static output.\n- The map is built in **two layers**. The first `tm_shape(lisa)` draws all 88 counties as a light backdrop, so the clusters can be read against the whole province. The second `tm_shape(lisa_sig)` draws only the significant counties on top, coloured by quadrant.\n\nBoth layers are needed. Without the first, the coloured counties float with nothing to place them against.\n:::\n",
    "supporting": [
      "In-class_Ex05_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}