{
  "hash": "88da1cdde5abbea6885ee940f7b4cda3",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Hands-on Exercise 4\"\nsubtitle: \"Spatial Weights and Applications\"\nauthor: \"An Loc\"\ndate: \"14 September 2026\"\ndate-modified: \"last-modified\"\ndate-format: \"D MMM YYYY\"\nformat:\n  html:\n    toc: true\n    toc-depth: 4\n    toc-expand: true\n    code-fold: false\n    code-copy: true\n    fig-width: 9\n    fig-height: 7\nexecute:\n  echo: true\n  eval: true\n  warning: false\n  message: false\n  freeze: true\n---\n\n# Overview\n\nEvery method in the rest of this course needs an answer to one question first: for a given area,\nwhich other areas count as its neighbours, and how much does each one count? A spatial weights\nmatrix is that answer written down. Lesson 5 feeds it to Moran's I, Lesson 6 to a constrained\nclustering algorithm, Lesson 7 to a local regression. Each of those inherits the weights matrix built\nhere.\n\nThis exercise builds spatial weights for the 88 counties of Hunan province, China, and uses them\nto compute four spatially lagged versions of GDP per capita. It follows r4gdsa Chapter 8, the\nchapter assigned for Lesson 4.\n\n**Part 1** reproduces Chapter 8: contiguity weights by the Queen and Rook rules, distance weights\nat a fixed band and at an adaptive k, inverse distance weights, row standardisation, and the four\nlag variables. **Part 2** examines the chapter's method and adds the part of the lecture that\nChapter 8 does not cover.\n\n::: {.callout-note appearance=\"simple\"}\n\n## Sources\n\nThe hands-on exercise is r4gdsa [Chapter 8: Spatial Weights and\nApplications](https://r4gdsa.netlify.app/chap08.html).\n\nThe Lesson 4 slides close on three references. Each is used in a specific section, listed below.\n\n| Reading | What it contributes | Used in |\n|---|---|---|\n| **de Bellefon, Loonis and Le Gleut (2018)**, chapter 2 of INSEE's *Handbook of Spatial Analysis*. The assigned pre-class reading, called the INSEE chapter below | The standardisation schemes beyond `W` and `B`; an explicit warning about the rule chapter 8 uses to set its distance band; why centroid distance loses information that contiguity keeps; the graph-based neighbour definitions | 4.2, 4.3, 4.4, 4.5 |\n| **Bavaud (1998)**, \"Models for Spatial Weights: A Systematic Look\" | The general position that no weights matrix is universally correct, and that a choice has to suit the phenomenon | 5 |\n| **Grubesic and Rosso (2014)**, \"The Use of Spatially Lagged Explanatory Variables\" | What a lagged variable is actually for, and a way to measure how much lagging changes the picture that can be compared against their published result | 4.7 |\n\nThe slide dates Bavaud to 2010. The paper itself states that the final version appeared in\n*Geographical Analysis* 30, pp. 153-171, in **1998**, and the DOI on the slide resolves to the\n1998 article. This page uses 1998.\n:::\n\n## Differences from the chapter\n\n| | The chapter | This page | Why | Where |\n|---|---|---|---|---|\n| **Inverse distance weights** | `style = \"B\"`, described as row standardised | mismatch identified in 3.5, the two styles weighed in 4.4 | The chapter's text and its code do not describe the same matrix, and 4.4.1 argues its code may be the better of the two | 3.5, 4.4 |\n| **Centroids** | `st_centroid` on WGS 84 degrees | same in Part 1, projected comparison in Part 2 | The shortcut leaves the fixed distance band unchanged and moves 17 of 88 counties in the k-nearest list | 4.2 |\n| **Cut-off distance** | 62 km, from a figure computed two ways | same band, with the metric mismatch identified | `knearneigh()` finds the nearest neighbour in degrees and `nbdists()` measures it in kilometres, so the chapter's 61.79 km is not the largest first nearest neighbour distance | 4.3 |\n| **Queen against Rook** | link totals reported, difference not examined | the eight counties identified | The difference is four mutual pairs touching at a single corner, which is the slide 11 quiz | 4.1 |\n| **Geographically weighted statistics** | not covered | added, using `GWmodel::gwss()` | Four slides of the lecture cover it and the chapter stops before it | 4.6 |\n| **Standardisation styles** | `W` and `B` only | all five compared | The INSEE chapter describes four schemes citing Tiefelsdorf, and `S` is the one designed to even out neighbour-count heterogeneity | 4.4 |\n| **Neighbour definitions** | contiguity, distance band, adaptive k | four graph methods added | The INSEE chapter's argument for them is that they cannot leave a county isolated, which is the failure mode measured in 4.5 | 4.5 |\n| **Use of the lagged variable** | four lags computed, never used | the cross-regressive use and a concordance measure | Grubesic and Rosso give both, and a published number to compare against | 4.7 |\n| **`left_join()`** | join column inferred | `by = \"County\"` stated | The inferred join works here. Naming the column means a renamed field fails loudly instead of quietly | 2.3 |\n| **Pipe** | `%>%` | <code>&#124;&gt;</code> | Carried over from Exercise 3 | throughout |\n| **Figure heights** | default | set per chunk | Hunan is taller than it is wide, aspect 0.889, so the default canvas leaves white bands inside every map | throughout |\n| **Map classification** | `qtm()` default, equal interval | quantile, 5 classes, on every map | GDPPC is right skewed, so equal interval puts 79 of the 88 counties in the lowest two classes and flattens the map | 3.1 |\n| **`tmap` version** | v3 idiom | v4 idiom | This machine runs tmap 4.4.1 and the v3 calls emit deprecation messages | throughout |\n\n::: {.callout-note collapse=\"true\"}\n## Mapping of Chapter 8 sections to this page\n\nEvery section of Chapter 8 is covered.\n\n| Chapter 8 | This page |\n|---|---|\n| 8.1 Overview | 1 Overview |\n| 8.2 The study area and data | 2.2 The data |\n| 8.2.1 Getting started | 2.1 Packages |\n| 8.3.1 Import shapefile | 2.2.1 County boundaries |\n| 8.3.2 Import csv | 2.2.2 Development indicators |\n| 8.3.3 Performing relational join | 2.3 Joining the two |\n| 8.4 Visualising regional development indicator | 3.1 Mapping GDPPC |\n| 8.5.1 Computing Queen contiguity | 3.2.1 Queen contiguity |\n| 8.5.2 Creating Rook contiguity | 3.2.2 Rook contiguity |\n| 8.5.3 Visualising contiguity weights | 3.2.3 Connectivity graphs |\n| 8.6.1 Determine the cut-off distance | 3.3.1 The cut-off distance |\n| 8.6.2 Computing fixed distance weight matrix | 3.3.2 Fixed distance band |\n| 8.6.3 Computing adaptive distance weight matrix | 3.3.3 Adaptive k nearest neighbours |\n| 8.7 Weights based on IDW | 3.4 Inverse distance weights |\n| 8.8 Row-standardised weights matrix | 3.5 Row standardisation |\n| 8.9.1 Spatial lag with row-standardized weights | 3.6.1 Spatial lag |\n| 8.9.2 Spatial lag as a sum of neighboring values | 3.6.2 Lag as a sum |\n| 8.9.3 Spatial window average | 3.6.3 Window average |\n| 8.9.4 Spatial window sum | 3.6.4 Window sum |\n| 8.10 References | 6 References |\n:::\n\n# Getting started\n\n## Packages\n\n`spdep` provides every weights function used here. `GWmodel` is needed only for the geographically\nweighted statistics in Part 2, and `sp` because `gwss()` predates `sf` and still takes a\n`Spatial*` object.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(sf, spdep, tmap, tidyverse, knitr, GWmodel, sp)\n```\n:::\n\n\n`tmap` is 4.4.1 on this machine while the chapter was written against v3, so this page uses the\nv4 spelling of every mapping call.\n\n## The data\n\nChapter 8 names both files and links neither.\n\n| Layer | Format | Features | Native CRS | Contents |\n|---|---|---|---|---|\n| `Hunan` | ESRI shapefile | 88 polygons | WGS 84, EPSG:4326 | County boundaries of Hunan province |\n| `Hunan_2012` | CSV | 88 rows, 29 fields | not spatial | 2012 development indicators by county |\n\nThe shapefile has no projected CRS. It is in geographic degrees, and section 4.2 measures the\neffect of that on the neighbour lists.\n\n### County boundaries\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan <- st_read(dsn = \"data/geospatial\", layer = \"Hunan\", quiet = TRUE)\nhunan\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 88 features and 7 fields\nGeometry type: POLYGON\nDimension:     XY\nBounding box:  xmin: 108.7831 ymin: 24.6342 xmax: 114.2544 ymax: 30.12812\nGeodetic CRS:  WGS 84\nFirst 10 features:\n     NAME_2  ID_3    NAME_3   ENGTYPE_3 Shape_Leng Shape_Area    County\n1   Changde 21098   Anxiang      County   1.869074 0.10056190   Anxiang\n2   Changde 21100   Hanshou      County   2.360691 0.19978745   Hanshou\n3   Changde 21101    Jinshi County City   1.425620 0.05302413    Jinshi\n4   Changde 21102        Li      County   3.474325 0.18908121        Li\n5   Changde 21103     Linli      County   2.289506 0.11450357     Linli\n6   Changde 21104    Shimen      County   4.171918 0.37194707    Shimen\n7  Changsha 21109   Liuyang County City   4.060579 0.46016789   Liuyang\n8  Changsha 21110 Ningxiang      County   3.323754 0.26614198 Ningxiang\n9  Changsha 21111 Wangcheng      County   2.292093 0.13049161 Wangcheng\n10 Chenzhou 21112     Anren      County   2.240739 0.13343936     Anren\n                         geometry\n1  POLYGON ((112.0625 29.75523...\n2  POLYGON ((112.2288 29.11684...\n3  POLYGON ((111.8927 29.6013,...\n4  POLYGON ((111.3731 29.94649...\n5  POLYGON ((111.6324 29.76288...\n6  POLYGON ((110.8825 30.11675...\n7  POLYGON ((113.9905 28.5682,...\n8  POLYGON ((112.7181 28.38299...\n9  POLYGON ((112.7914 28.52688...\n10 POLYGON ((113.1757 26.82734...\n```\n\n\n:::\n:::\n\n\n88 features, 7 fields, POLYGON geometry, WGS 84.\n\n### Development indicators\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan2012 <- read_csv(\"data/aspatial/Hunan_2012.csv\", show_col_types = FALSE)\ndim(hunan2012)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 88 29\n```\n\n\n:::\n:::\n\n\n29 fields covering wages, deposits, investment, government revenue and expenditure, GDP,\npopulation and employment. This exercise uses one of them, `GDPPC`, GDP per capita in yuan.\n\n## Joining the two\n\nThe join key is `County`, present in both. The chapter lets `left_join()` infer it; naming it\nmeans that a renamed field produces an error rather than a silent cross join.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan <- left_join(hunan, hunan2012, by = \"County\") |>\n  select(1:4, 7, 15)\nnames(hunan)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"NAME_2\"    \"ID_3\"      \"NAME_3\"    \"ENGTYPE_3\" \"County\"    \"GDPPC\"    \n[7] \"geometry\" \n```\n\n\n:::\n:::\n\n\n`select(1:4, 7, 15)` keeps the four name fields, `County` and `GDPPC`. It selects by position, so\nit depends on the column order the join happens to produce. It is correct here, verified against\nthe printed names above.\n\n# Part 1: Following the chapter\n\n## Mapping GDPPC\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbasemap <- tm_shape(hunan) +\n  tm_polygons() +\n  tm_text(\"NAME_3\", size = 0.35)\n\ngdppc <- tm_shape(hunan) +\n  tm_polygons(\"GDPPC\",\n              fill.scale = tm_scale_intervals(style = \"quantile\", n = 5),\n              fill.legend = tm_legend(title = \"GDPPC (yuan)\", position = c(\"left\", \"bottom\")))\n\ntmap_arrange(basemap, gdppc, ncol = 2)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex04_files/figure-html/unnamed-chunk-5-1.png){width=864}\n:::\n:::\n\n\nThe chapter uses `qtm()`, whose default equal-interval classes put most counties in the lowest\ntwo, because GDPPC is right skewed. Quantile classes are used here and on every later map so the\nspatial pattern is visible.\n\nThe high values sit in the north east, around Changsha, and along the eastern edge. The low\nvalues run through the west.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(hunan$GDPPC)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n   8497   14566   20433   24405   27224   88656 \n```\n\n\n:::\n:::\n\n\n## Contiguity weights\n\n`poly2nb()` builds a neighbours list from shared boundaries. Its `queen` argument chooses the\nrule: `TRUE` counts any shared point, `FALSE` requires a shared edge.\n\n### Queen contiguity\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_q <- poly2nb(hunan, queen = TRUE)\nsummary(wm_q)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNeighbour list object:\nNumber of regions: 88 \nNumber of nonzero links: 448 \nPercentage nonzero weights: 5.785124 \nAverage number of links: 5.090909 \nLink number distribution:\n\n 1  2  3  4  5  6  7  8  9 11 \n 2  2 12 16 24 14 11  4  2  1 \n2 least connected regions:\n30 65 with 1 link\n1 most connected region:\n85 with 11 links\n```\n\n\n:::\n:::\n\n\n88 regions, 448 links, 5.09 neighbours on average. The summary also reports one county with 11\nneighbours, the most, and two with only one.\n\nThe neighbours of county 1 and their GDPPC:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_q[[1]]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  2  3  4 57 85\n```\n\n\n:::\n\n```{.r .cell-code}\nhunan$County[wm_q[[1]]]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Hanshou\" \"Jinshi\"  \"Li\"      \"Nan\"     \"Taoyuan\"\n```\n\n\n:::\n\n```{.r .cell-code}\nhunan$GDPPC[wm_q[[1]]]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 20981 34592 24473 21311 22879\n```\n\n\n:::\n:::\n\n\n### Rook contiguity\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_r <- poly2nb(hunan, queen = FALSE)\nsummary(wm_r)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNeighbour list object:\nNumber of regions: 88 \nNumber of nonzero links: 440 \nPercentage nonzero weights: 5.681818 \nAverage number of links: 5 \nLink number distribution:\n\n 1  2  3  4  5  6  7  8  9 10 \n 2  2 12 20 21 14 11  3  2  1 \n2 least connected regions:\n30 65 with 1 link\n1 most connected region:\n85 with 10 links\n```\n\n\n:::\n:::\n\n\n440 links against the Queen rule's 448. Eight fewer, which is four pairs of counties counted once\nfrom each side. Section 4.1 identifies them.\n\n### Connectivity graphs\n\nPlotting a neighbours list needs a point per polygon. The chapter takes the centroid of each\ngeometry with `map_dbl()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlongitude <- map_dbl(hunan$geometry, ~st_centroid(.x)[[1]])\nlatitude  <- map_dbl(hunan$geometry, ~st_centroid(.x)[[2]])\ncoords <- cbind(longitude, latitude)\nhead(coords)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     longitude latitude\n[1,]  112.1531 29.44362\n[2,]  112.0372 28.86489\n[3,]  111.8917 29.47107\n[4,]  111.7031 29.74499\n[5,]  111.6138 29.49258\n[6,]  111.0341 29.79863\n```\n\n\n:::\n:::\n\n\nThese are degrees, and `st_centroid` treats them as if they were planar. Section 4.2 measures how\nfar the centroids move as a result, and which neighbour lists change.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(1, 2))\nplot(hunan$geometry, border = \"lightgrey\", main = \"Queen contiguity\")\nplot(wm_q, coords, pch = 19, cex = 0.6, add = TRUE, col = \"red\")\nplot(hunan$geometry, border = \"lightgrey\", main = \"Rook contiguity\")\nplot(wm_r, coords, pch = 19, cex = 0.6, add = TRUE, col = \"red\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex04_files/figure-html/unnamed-chunk-11-1.png){width=864}\n:::\n:::\n\n\nThe two graphs are hard to tell apart at this scale: the difference is eight links out of 448,\nidentified in section 4.1.\n\n## Distance weights\n\n### The cut-off distance\n\nA fixed distance band needs an upper bound. If it is set too low, some counties end up with no\nneighbours at all. `nb2listw()` then stops with `Empty neighbour sets found` unless\n`zero.policy = TRUE` is set, and with that set the lagged value at an isolated county comes back\nas 0 rather than as missing. The chapter sets the bound from the largest first nearest neighbour\ndistance, so every county keeps at least one.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nk1 <- knn2nb(knearneigh(coords))\nk1dists <- unlist(nbdists(k1, coords, longlat = TRUE))\nsummary(k1dists)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  24.79   32.57   38.01   39.07   44.52   61.79 \n```\n\n\n:::\n:::\n\n\nThe chapter reads 61.79 km as the largest first nearest neighbour distance and sets the band just\nabove it, at 62 km, so that every county keeps at least one neighbour. Section 4.3 checks both the\nnumber and the claim.\n\n`longlat = TRUE` tells `nbdists()` the coordinates are degrees and to return great circle\ndistances in kilometres. Without it the numbers would be degrees, which are not a distance.\n\n### Fixed distance band\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_d62 <- dnearneigh(coords, 0, 62, longlat = TRUE)\nwm_d62\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNeighbour list object:\nNumber of regions: 88 \nNumber of nonzero links: 324 \nPercentage nonzero weights: 4.183884 \nAverage number of links: 3.681818 \n```\n\n\n:::\n:::\n\n\n324 links, 3.68 on average, against the Queen rule's 448 and 5.09.\n\n> **Quiz from the chapter:** what does \"Average number of links: 3.681818\" mean?\n\nAcross the 88 counties, each has 3.68 neighbours within 62 km on average: 324 links divided by\n88 counties. It is an average over a range from 1 to 6, not a typical value. Six counties are at\nthe minimum of 1. `card()` below returns each county's neighbour count.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(card(wm_d62))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n 1  2  3  4  5  6 \n 6 15 14 26 20  7 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(1, 2))\nplot(hunan$geometry, border = \"lightgrey\", main = \"1st nearest neighbour\")\nplot(k1, coords, add = TRUE, col = \"red\", length = 0.08)\nplot(hunan$geometry, border = \"lightgrey\", main = \"Within 62 km\")\nplot(wm_d62, coords, add = TRUE, pch = 19, cex = 0.6)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex04_files/figure-html/unnamed-chunk-15-1.png){width=864}\n:::\n:::\n\n\nThe right panel shows the characteristic problem with a fixed band: dense areas accumulate\nneighbours, sparse areas keep one or two.\n\n### Adaptive k nearest neighbours\n\nFixing the count instead of the distance gives every county the same number of neighbours,\nletting the radius vary.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknn6 <- knn2nb(knearneigh(coords, k = 6))\nknn6\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNeighbour list object:\nNumber of regions: 88 \nNumber of nonzero links: 528 \nPercentage nonzero weights: 6.818182 \nAverage number of links: 6 \nNon-symmetric neighbours list\n```\n\n\n:::\n:::\n\n\n528 links, exactly 6 each. The output reports it as non-symmetric: if B is among A's six\nnearest, A need not be among B's.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nis.symmetric.nb(knn6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] FALSE\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(hunan$geometry, border = \"lightgrey\", main = \"6 nearest neighbours\")\nplot(knn6, coords, pch = 19, cex = 0.6, add = TRUE, col = \"red\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex04_files/figure-html/unnamed-chunk-18-1.png){width=864}\n:::\n:::\n\n\n## Inverse distance weights\n\nRather than treating every neighbour equally, weight each by the reciprocal of its distance, so\nthat near neighbours count more.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndist <- nbdists(wm_q, coords, longlat = TRUE)\nids <- lapply(dist, function(x) 1 / (x))\nids[[1]]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.01535405 0.03916350 0.01820896 0.02807922 0.01145113\n```\n\n\n:::\n:::\n\n\nThese are 1/km, between about 0.008 and 0.040 across the whole province.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(unlist(ids))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. \n0.008218 0.015088 0.018739 0.019614 0.022823 0.040338 \n```\n\n\n:::\n:::\n\n\n## Row standardisation\n\n`nb2listw()` turns a neighbours list into a weights list. `style = \"W\"` divides each row by its\nnumber of neighbours, so the weights in every row sum to 1.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrswm_q <- nb2listw(wm_q, style = \"W\", zero.policy = TRUE)\nrswm_q\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCharacteristics of weights list object:\nNeighbour list object:\nNumber of regions: 88 \nNumber of nonzero links: 448 \nPercentage nonzero weights: 5.785124 \nAverage number of links: 5.090909 \n\nWeights style: W \nWeights constants summary:\n   n   nn S0       S1       S2\nW 88 7744 88 37.86334 365.9147\n```\n\n\n:::\n:::\n\n\nCounty 10 has eight neighbours, so each gets 0.125:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrswm_q$weights[10]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1]]\n[1] 0.125 0.125 0.125 0.125 0.125 0.125 0.125 0.125\n```\n\n\n:::\n:::\n\n\nThe chapter then writes that it derives \"a row standardised distance weight matrix\" with the code\nbelow.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrswm_ids <- nb2listw(wm_q, glist = ids, style = \"B\", zero.policy = TRUE)\nrswm_ids$weights[1]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1]]\n[1] 0.01535405 0.03916350 0.01820896 0.02807922 0.01145113\n```\n\n\n:::\n:::\n\n\nThose are the raw 1/distance values, unchanged from `ids[[1]]` above. `style = \"B\"` is the binary\nstyle, which uses `glist` as given. Nothing was standardised. Row standardised means the row sums\nto 1, and `style = \"W\"` does that:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrswm_ids_W <- nb2listw(wm_q, glist = ids, style = \"W\", zero.policy = TRUE)\nc(B = sum(rswm_ids$weights[[1]]), W = sum(rswm_ids_W$weights[[1]]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        B         W \n0.1122569 1.0000000 \n```\n\n\n:::\n:::\n\n\nRow standardised rows sum to 1, and these do not, so the chapter's sentence and its code do not\ndescribe the same matrix. Section 4.4 measures the gap and takes up which of the two an inverse\ndistance weighting should use.\n\n## The four lag variables\n\nA spatially lagged variable summarises each county's neighbourhood into one number. Four versions\nfollow from two binary choices: whether the weights are row standardised, and whether the county\ncounts as its own neighbour.\n\n|  | Excludes self | Includes self |\n|---|---|---|\n| **Row standardised** | spatial lag | window average |\n| **Binary** | lag as a sum | window sum |\n\n### Spatial lag\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan$lag_GDPPC <- lag.listw(rswm_q, hunan$GDPPC)\nhead(hunan[, c(\"County\", \"GDPPC\", \"lag_GDPPC\")])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 6 features and 3 fields\nGeometry type: POLYGON\nDimension:     XY\nBounding box:  xmin: 110.4922 ymin: 28.61762 xmax: 112.3013 ymax: 30.12812\nGeodetic CRS:  WGS 84\n   County GDPPC lag_GDPPC                       geometry\n1 Anxiang 23667  24847.20 POLYGON ((112.0625 29.75523...\n2 Hanshou 20981  22724.80 POLYGON ((112.2288 29.11684...\n3  Jinshi 34592  24143.25 POLYGON ((111.8927 29.6013,...\n4      Li 24473  27737.50 POLYGON ((111.3731 29.94649...\n5   Linli 25554  27270.25 POLYGON ((111.6324 29.76288...\n6  Shimen 27137  21248.80 POLYGON ((110.8825 30.11675...\n```\n\n\n:::\n:::\n\n\nAnxiang's neighbours have GDPPC 20981, 34592, 24473, 21311 and 22879. Their mean is 24847.2,\nwhich is the lagged value. With row standardised weights the spatial lag is the neighbourhood\nmean, and it is on the same scale as the variable itself, so the two can be mapped against each\nother.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_arrange(\n  tm_shape(hunan) + tm_polygons(\"GDPPC\",\n    fill.scale = tm_scale_intervals(style = \"quantile\", n = 5),\n    fill.legend = tm_legend(title = \"GDPPC\", position = c(\"left\", \"bottom\"))),\n  tm_shape(hunan) + tm_polygons(\"lag_GDPPC\",\n    fill.scale = tm_scale_intervals(style = \"quantile\", n = 5),\n    fill.legend = tm_legend(title = \"lag GDPPC\", position = c(\"left\", \"bottom\"))),\n  ncol = 2)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex04_files/figure-html/unnamed-chunk-26-1.png){width=864}\n:::\n:::\n\n\nThe lagged map is smoother. Isolated high counties are pulled down by poorer neighbours and the\nbroad north-eastern cluster survives. The lag is useful for that reason: a value that survives\naveraging with its neighbours belongs to a regional pattern rather than to one county.\n\n### Lag as a sum\n\nBinary weights, no standardisation, so the result is a total rather than a mean.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nb_weights <- lapply(wm_q, function(x) 0 * x + 1)\nb_weights2 <- nb2listw(wm_q, glist = b_weights, style = \"B\")\nhunan$lag_sum_GDPPC <- lag.listw(b_weights2, hunan$GDPPC)\nhead(hunan[, c(\"County\", \"GDPPC\", \"lag_GDPPC\", \"lag_sum_GDPPC\")])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 6 features and 4 fields\nGeometry type: POLYGON\nDimension:     XY\nBounding box:  xmin: 110.4922 ymin: 28.61762 xmax: 112.3013 ymax: 30.12812\nGeodetic CRS:  WGS 84\n   County GDPPC lag_GDPPC lag_sum_GDPPC                       geometry\n1 Anxiang 23667  24847.20        124236 POLYGON ((112.0625 29.75523...\n2 Hanshou 20981  22724.80        113624 POLYGON ((112.2288 29.11684...\n3  Jinshi 34592  24143.25         96573 POLYGON ((111.8927 29.6013,...\n4      Li 24473  27737.50        110950 POLYGON ((111.3731 29.94649...\n5   Linli 25554  27270.25        109081 POLYGON ((111.6324 29.76288...\n6  Shimen 27137  21248.80        106244 POLYGON ((110.8825 30.11675...\n```\n\n\n:::\n:::\n\n\nAnxiang's 124236 is the sum of those same five neighbours. This version confounds two things: how\nrich the neighbours are, and how many of them there are.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_arrange(\n  tm_shape(hunan) + tm_polygons(\"GDPPC\",\n    fill.scale = tm_scale_intervals(style = \"quantile\", n = 5),\n    fill.legend = tm_legend(title = \"GDPPC\", position = c(\"left\", \"bottom\"))),\n  tm_shape(hunan) + tm_polygons(\"lag_sum_GDPPC\",\n    fill.scale = tm_scale_intervals(style = \"quantile\", n = 5),\n    fill.legend = tm_legend(title = \"lag sum\", position = c(\"left\", \"bottom\"))),\n  ncol = 2)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex04_files/figure-html/unnamed-chunk-28-1.png){width=864}\n:::\n:::\n\n\nThe right map is partly a map of connectivity. Taoyuan has the most neighbours of any county at\n11, so its total is high because it borders many counties rather than because they are\nprosperous. Reading the lag sum means reading how rich the neighbours are and how many of them\nthere are at the same time.\n\n### Window average\n\n`include.self()` adds each county to its own neighbours list, then row standardisation over the\nenlarged list gives the mean of the neighbourhood including the county itself.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_qs <- include.self(wm_q)\nwm_qs\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNeighbour list object:\nNumber of regions: 88 \nNumber of nonzero links: 536 \nPercentage nonzero weights: 6.921488 \nAverage number of links: 6.090909 \n```\n\n\n:::\n:::\n\n\n536 links against 448, which is 448 plus the 88 diagonal entries.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_qs_lw <- nb2listw(wm_qs)\nhunan$lag_window_avg_GDPPC <- lag.listw(wm_qs_lw, hunan$GDPPC)\n```\n:::\n\n\nThe chapter's text at this point says \"Again, we use `nb2listw()` and `glist()` to explicitly\nassign weight values.\" No `glist` is passed. The call relies on the default `style = \"W\"`, and\nthat is the right setting for a window average. Only the sentence is wrong.\n\n### Window sum\n\nBinary weights over the same self-inclusive list.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nb_weights_s <- lapply(wm_qs, function(x) 0 * x + 1)\nb_weights_s2 <- nb2listw(wm_qs, glist = b_weights_s, style = \"B\")\nhunan$w_sum_GDPPC <- lag.listw(b_weights_s2, hunan$GDPPC)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_arrange(\n  tm_shape(hunan) + tm_polygons(\"lag_sum_GDPPC\",\n    fill.scale = tm_scale_intervals(style = \"quantile\", n = 5),\n    fill.legend = tm_legend(title = \"lag sum\", position = c(\"left\", \"bottom\"))),\n  tm_shape(hunan) + tm_polygons(\"w_sum_GDPPC\",\n    fill.scale = tm_scale_intervals(style = \"quantile\", n = 5),\n    fill.legend = tm_legend(title = \"window sum\", position = c(\"left\", \"bottom\"))),\n  ncol = 2)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex04_files/figure-html/unnamed-chunk-32-1.png){width=864}\n:::\n:::\n\n\nThese two are hard to tell apart, and the reason is the spread between counties rather than the\nsize of any one contribution. Totals differ enormously across Hunan because some counties border\none neighbour and some border eleven, so adding one more value does not reorder them. A mean has\nno such spread, and including the county pulls the average toward that county's own value.\nSection 3.6.5 maps the two side by side.\n\n### The four compared\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan |>\n  st_drop_geometry() |>\n  select(County, GDPPC, lag_GDPPC, lag_sum_GDPPC, lag_window_avg_GDPPC, w_sum_GDPPC) |>\n  head(10) |>\n  kable(digits = 0, format.args = list(big.mark = \",\"))\n```\n\n::: {.cell-output-display}\n\n\n|County    |  GDPPC| lag_GDPPC| lag_sum_GDPPC| lag_window_avg_GDPPC| w_sum_GDPPC|\n|:---------|------:|---------:|-------------:|--------------------:|-----------:|\n|Anxiang   | 23,667|    24,847|       124,236|               24,650|     147,903|\n|Hanshou   | 20,981|    22,725|       113,624|               22,434|     134,605|\n|Jinshi    | 34,592|    24,143|        96,573|               26,233|     131,165|\n|Li        | 24,473|    27,738|       110,950|               27,085|     135,423|\n|Linli     | 25,554|    27,270|       109,081|               26,927|     134,635|\n|Shimen    | 27,137|    21,249|       106,244|               22,230|     133,381|\n|Liuyang   | 63,118|    43,747|       174,988|               47,621|     238,106|\n|Ningxiang | 62,202|    33,583|       235,079|               37,160|     297,281|\n|Wangcheng | 70,666|    45,651|       273,907|               49,225|     344,573|\n|Anren     | 12,761|    32,028|       256,221|               29,887|     268,982|\n\n\n:::\n:::\n\n\nTwo identities hold by construction:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nall.equal(hunan$w_sum_GDPPC, hunan$lag_sum_GDPPC + hunan$GDPPC)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code}\nall.equal(hunan$lag_window_avg_GDPPC, hunan$w_sum_GDPPC / (card(wm_q) + 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_arrange(\n  tm_shape(hunan) + tm_polygons(\"lag_GDPPC\",\n    fill.scale = tm_scale_intervals(style = \"quantile\", n = 5),\n    fill.legend = tm_legend(title = \"lag\", position = c(\"left\", \"bottom\"))),\n  tm_shape(hunan) + tm_polygons(\"lag_window_avg_GDPPC\",\n    fill.scale = tm_scale_intervals(style = \"quantile\", n = 5),\n    fill.legend = tm_legend(title = \"window avg\", position = c(\"left\", \"bottom\"))),\n  ncol = 2)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex04_files/figure-html/unnamed-chunk-35-1.png){width=864}\n:::\n:::\n\n\nThe window average differs from the lag most where a county's own value is far from its\nneighbours'. The table above shows it: where the two columns diverge, the county itself is\npulling against the neighbourhood around it.\n\n# Part 2: Review and extension\n\nPart 1 reproduced the chapter. This part examines its method, and adds what the lecture and the\nreadings cover that Chapter 8 does not.\n\nThe INSEE chapter divides the problem in two: which areas count as neighbours, its section 2.1,\nand how much each one counts, its 2.2. Its 2.2.2 reports that opinions in the field diverge on how\nmuch those choices affect results.\n\nChapter 8 makes a decision at four points in that scheme, and the first four sections below\nmeasure what each one changes. Which areas count as neighbours: the contiguity rule (4.1), the\ncentroids the distances are measured between (4.2), and the distance band (4.3). How much\neach counts: the standardisation scheme (4.4). The sections after that are extensions beyond\nthe chapter.\n\n## Queen and Rook contiguity\n\nSection 3.2 built both contiguity matrices and printed the totals: 448 links under Queen, 440\nunder Rook. Eight links is a 1.8% difference in the structure. Which eight, and does dropping\nthem change any county's lagged value?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndiffers <- which(card(wm_q) != card(wm_r))\ntibble(\n  county = hunan$County[differs],\n  queen = card(wm_q)[differs],\n  rook = card(wm_r)[differs],\n  `corner-only contact` = sapply(differs, function(i)\n    paste(hunan$County[setdiff(wm_q[[i]], wm_r[[i]])], collapse = \", \"))\n) |> kable()\n```\n\n::: {.cell-output-display}\n\n\n|county   | queen| rook|corner-only contact |\n|:--------|-----:|----:|:-------------------|\n|Anxiang  |     5|    4|Hanshou             |\n|Hanshou  |     5|    4|Anxiang             |\n|Anren    |     8|    7|Zixing              |\n|Yongxing |     5|    4|Yanling             |\n|Zixing   |     7|    6|Anren               |\n|Nan      |     6|    5|Taoyuan             |\n|Yanling  |     5|    4|Yongxing            |\n|Taoyuan  |    11|   10|Nan                 |\n\n\n:::\n:::\n\n\nFour pairs, each appearing twice because contiguity is symmetric: Anxiang with Hanshou, Anren\nwith Zixing, Yongxing with Yanling, Nan with Taoyuan. In each case the two counties meet at a\nsingle point rather than along a boundary. This is the slide 11 quiz in the lecture deck, where\nthe Queen row for area 1202 has seven entries and the Rook answer has five.\n\nWhether it matters for the analysis:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlag_q <- lag.listw(nb2listw(wm_q, style = \"W\"), hunan$GDPPC)\nlag_r <- lag.listw(nb2listw(wm_r, style = \"W\"), hunan$GDPPC)\nmoved <- which(abs(lag_q - lag_r) > 1e-9)\ncat(\"counties whose lagged GDPPC changes:\", length(moved), \"of 88\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ncounties whose lagged GDPPC changes: 8 of 88\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"largest change:\", round(max(abs(lag_q - lag_r))), \"yuan, at\",\n    hunan$County[which.max(abs(lag_q - lag_r))], \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlargest change: 4811 yuan, at Anren \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"as a share of that county's Rook lag:\",\n    round(100 * max(abs(lag_q - lag_r) / lag_r), 1), \"%\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nas a share of that county's Rook lag: 17.7 %\n```\n\n\n:::\n:::\n\n\nEight counties move, and the largest move is 4811 yuan at Anren, 17.7% of its value. Province\nwide the choice is close to irrelevant; for those eight counties it is not. The general point is\nthat a difference of eight links out of 448 is not a difference of 1.8% in the result, because\nthe links are not spread evenly.\n\nQueen is the right default here. A corner contact between two Chinese counties is a real\nadministrative adjacency, and the Rook rule discards it on what amounts to an artefact of where\nthe boundary vertices were digitised.\n\n## Centroids: unprojected versus projected\n\nEvery distance in section 3.3 was measured between county centroids, because a distance band\nneeds a single point to stand for each polygon. Two questions follow: whether a centroid is the\nright thing to measure between at all, and whether these ones were computed correctly.\n\nThe INSEE chapter takes up the first question, and its answer is no. Its\nExample 2.1 sets out three zones where R2 and R3 are separated in space and both touch R1, and\nshows that their centroids are nonetheless equidistant from each other:\n\n> Summarising the proximity between zones by the distance between the centroids results in a\n> partial loss of the richness of the spatial relationships.\n\nThe INSEE chapter is arguing for contiguity over centroid distance on areal data, and that applies to\n§3.3 and §3.4 of this page. It adds that contiguity is the usual choice for\ndemographic and social data, \"in which it may be more important to be on either side of an\nadministrative boundary than to be located at a certain distance from one another.\" GDP per\ncapita by county is that kind of data.\n\nChapter 8 uses centroids regardless, so the rest of this section asks whether it computes them\naccurately.\n\nThe chapter runs `st_centroid` on WGS 84 longitude and latitude. `st_centroid` computes a planar\ncentroid, so on geographic coordinates it treats one degree of longitude as equal to one degree\nof latitude. At Hunan's latitude of about 27 degrees, a degree of longitude is roughly 89% of a\ndegree of latitude, so the centroids are pulled slightly. The comparison below reprojects to\nEPSG:4547, the CGCS2000 Gauss-Kruger zone covering Hunan, whose units are metres.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan_proj <- st_transform(hunan, 4547)\ncent_proj <- st_centroid(st_geometry(hunan_proj))\ncent_chap <- st_as_sf(data.frame(x = coords[, 1], y = coords[, 2]),\n                      coords = c(\"x\", \"y\"), crs = 4326)\nshift <- as.numeric(st_distance(cent_chap, st_transform(cent_proj, 4326), by_element = TRUE))\nsummary(shift)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n 0.8718  9.4058 17.5424 20.6475 26.1506 62.2015 \n```\n\n\n:::\n:::\n\n\nThe centroids move by 18 m at the median and 62 m at most. Against a 62 km distance band that is\nnothing, and the fixed band is in fact unaffected:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoords_p <- st_coordinates(cent_proj)\nband_chap <- dnearneigh(coords,   0, 62,    longlat = TRUE)\nband_proj <- dnearneigh(coords_p, 0, 62000)\nidentical(lapply(band_chap, sort), lapply(band_proj, sort))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\nThe k nearest neighbour list is a different matter. It has no distance threshold to absorb a\nsmall error: it takes the nearest six whatever the distances are, so a shift of tens of metres\ncan reorder the sixth and seventh candidates.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknn6_chap <- knn2nb(knearneigh(coords,   k = 6))\nknn6_proj <- knn2nb(knearneigh(coords_p, k = 6))\nchanged <- sum(sapply(1:88, function(i)\n  !identical(sort(knn6_chap[[i]]), sort(knn6_proj[[i]]))))\ncat(\"counties whose 6 nearest neighbours change:\", changed, \"of 88\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ncounties whose 6 nearest neighbours change: 17 of 88\n```\n\n\n:::\n:::\n\n\n17 of 88 counties get a different neighbour set. Following it through to the lagged variable:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlag_knn_chap <- lag.listw(nb2listw(knn6_chap, style = \"W\"), hunan$GDPPC)\nlag_knn_proj <- lag.listw(nb2listw(knn6_proj, style = \"W\"), hunan$GDPPC)\nd <- lag_knn_chap - lag_knn_proj\ncat(\"largest change:\", round(max(abs(d))), \"yuan at\", hunan$County[which.max(abs(d))], \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlargest change: 8691 yuan at Longhui \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"as a share:\", round(100 * max(abs(d / lag_knn_proj)), 1), \"%\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nas a share: 41.4 %\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Spearman correlation of the two lag vectors:\",\n    round(cor(lag_knn_chap, lag_knn_proj, method = \"spearman\"), 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpearman correlation of the two lag vectors: 0.9844 \n```\n\n\n:::\n:::\n\n\nLonghui's neighbourhood mean moves by 8691 yuan, 41.4% of its value, because a swapped sixth\nneighbour was far richer than the one it replaced. The rank correlation across all 88 stays at\n0.984, so the province-wide picture is intact and one county's number is badly wrong.\n\nSo the shortcut holds for the fixed band, which is the only place the chapter uses these\ncoordinates, and fails for the k nearest list. Projecting first takes one line, and then both\nresults are the same whichever coordinates are used:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan_proj <- st_transform(hunan, 4547)   # CGCS2000 Gauss-Kruger zone, metres\ncoords <- st_coordinates(st_centroid(st_geometry(hunan_proj)))\n```\n:::\n\n\n## The 62 km cut-off distance\n\nThe 62 km band in section 3.3.2 came from one number: the largest distance between any county\nand its nearest neighbour, 61.79 km. Setting the band there guarantees nobody is left isolated.\nIt is a different question whether counties 62 km apart influence each other, which is the claim\na distance band makes. The table below varies the band and counts the counties left with no\nneighbour at all.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbands <- c(45, 50, 55, 58, 59, 60, 62, 65, 70, 75, 80)\nmap_dfr(bands, function(d) {\n  w <- dnearneigh(coords, 0, d, longlat = TRUE)\n  tibble(`band (km)` = d, links = sum(card(w)),\n         `avg links` = mean(card(w)), isolated = sum(card(w) == 0))\n}) |> kable(digits = 2)\n```\n\n::: {.cell-output-display}\n\n\n| band (km)| links| avg links| isolated|\n|---------:|-----:|---------:|--------:|\n|        45|   128|      1.45|       18|\n|        50|   192|      2.18|        7|\n|        55|   246|      2.80|        4|\n|        58|   272|      3.09|        2|\n|        59|   298|      3.39|        0|\n|        60|   310|      3.52|        0|\n|        62|   324|      3.68|        0|\n|        65|   358|      4.07|        0|\n|        70|   440|      5.00|        0|\n|        75|   506|      5.75|        0|\n|        80|   568|      6.45|        0|\n\n\n:::\n:::\n\n\nAt 58 km and below some counties have no neighbour at all. From 59 km up every county has at\nleast one. So the threshold is 59 km, and not the 61.79 km the chapter derives. The gap between\nthe two has a cause.\n\n`knearneigh(coords)` finds each county's nearest neighbour by planar distance on longitude and\nlatitude. `nbdists(coords, longlat = TRUE)` then measures those pairs as great circle kilometres.\nThe two steps use different metrics, so 61.79 km is the distance to the nearest county *in\ndegrees*, which is not always the nearest county in kilometres.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nk1_deg <- knn2nb(knearneigh(coords))\nk1_km  <- knn2nb(knearneigh(coords, longlat = TRUE))\n\ntibble(\n  `nearest neighbour found in` = c(\"degrees, as the chapter does\", \"great circle kilometres\"),\n  `largest such distance (km)` = c(max(unlist(nbdists(k1_deg, coords, longlat = TRUE))),\n                                   max(unlist(nbdists(k1_km,  coords, longlat = TRUE))))\n) |> kable(digits = 2)\n```\n\n::: {.cell-output-display}\n\n\n|nearest neighbour found in   | largest such distance (km)|\n|:----------------------------|--------------------------:|\n|degrees, as the chapter does |                      61.79|\n|great circle kilometres      |                      58.39|\n\n\n:::\n\n```{.r .cell-code}\nsum(sapply(seq_along(k1_deg), function(i) k1_deg[[i]] != k1_km[[i]]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 6\n```\n\n\n:::\n:::\n\n\nMeasured consistently in kilometres the largest first nearest neighbour distance is 58.39 km, and\n6 of the 88 counties have a different nearest neighbour under the two metrics. 62 km is above\n58.39 km as well, so every county still keeps at least one neighbour and the chapter's band\nworks.\n\nThis is the same fault as §4.2, planar arithmetic on angular coordinates, and here it affects the\nnumber the chapter uses to justify its choice.\n\nThe INSEE chapter describes the same procedure and warns against using it:\n\n> This \"minimum distance\" method is not adapted to irregularly spaced data, as the minimum\n> distance required for a relatively isolated point having at least one neighbour is much higher\n> than the distance to the closest neighbour of a point located in a dense zone. There will\n> therefore be significant disparities in the number of neighbours.\n\nThe disparity is visible in §3.3.2 above: at 62 km the neighbour counts run from 1 to 6, and six\ncounties have only one neighbour. The band is set by the most isolated county in the province and then\napplied everywhere, so guaranteeing Xinhuang a neighbour gives every dense county a\nneighbourhood wider than its own spatial scale.\n\nThis is the argument for the adaptive k of §3.3.3, and for the graph methods in §4.5.\n\nThe lower end of the band is fixed by the isolated counties. The upper end is not fixed by\nanything. Going from 62 km to 80 km more than doubles the link count, from 324 to 570, and there\nis nothing in the GDPPC data to show which band is closer to the distance over which counties\naffect each other.\n\n## The C, U and S standardisation schemes\n\nSections 3.5 and 3.6 used two styles without comparing them: `W` for the lagged mean and `B` for\nthe lagged sum. The style decides whether every county's weights add up to the same total, or\nwhether counties with more neighbours count for more.\n\n`nb2listw()` offers five. The INSEE chapter describes four, citing Tiefelsdorf (1998), and the\nfifth is the unstandardised binary case.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstyles <- c(\"B\", \"W\", \"C\", \"U\", \"S\")\nmap_dfr(styles, function(st) {\n  lw <- nb2listw(wm_q, style = st)\n  rs <- sapply(lw$weights, sum)\n  tibble(style = st,\n         `min row sum` = min(rs), `max row sum` = max(rs),\n         `CV of row sums` = sd(rs) / mean(rs),\n         `all weights total` = sum(unlist(lw$weights)))\n}) |> kable(digits = 4)\n```\n\n::: {.cell-output-display}\n\n\n|style | min row sum| max row sum| CV of row sums| all weights total|\n|:-----|-----------:|-----------:|--------------:|-----------------:|\n|B     |      1.0000|     11.0000|         0.3494|               448|\n|W     |      1.0000|      1.0000|         0.0000|                88|\n|C     |      0.1964|      2.1607|         0.3494|                88|\n|U     |      0.0022|      0.0246|         0.3494|                 1|\n|S     |      0.4506|      1.4944|         0.1842|                88|\n\n\n:::\n:::\n\n\nThe INSEE chapter's account of each:\n\n| Style | What it does | Consequence |\n|---|---|---|\n| `B` | binary, no standardisation | A county's total weight is its neighbour count, so Taoyuan with 11 neighbours exerts 11 times Xinhuang's pull |\n| `W` | row standardisation | Every row sums to 1. Gives more weight to border counties, which have few neighbours |\n| `C` | global standardisation, all weights scaled so they total $n$ | Central counties with many neighbours take more external influence than border ones |\n| `U` | uniform, all weights total 1 | Same shape as `C`, different scale |\n| `S` | variance stabilisation, Tiefelsdorf | Introduced to reduce the heterogeneity that differences in neighbour count create |\n\nThe sum of all elements is exactly $n = 88$ for `W`, `C` and `S`. The INSEE chapter gives this as the\nreason autocorrelation statistics computed from different matrices can be compared. `U` totals 1 by\ndefinition and `B` totals 448, the link count.\n\nThe row sums of `S` vary less than `B`, `C` and `U` and more than `W`: a coefficient of variation\nof 0.184 against 0.349 and 0.000. That is the reduction in heterogeneity `S` was designed for.\n\n`B`, `C` and `U` share a coefficient of variation of exactly 0.349 because all three are the same\nbinary matrix under a single scalar multiplier. They differ in scale and not in shape, so any\nstatistic invariant to scale cannot tell them apart.\n\nMoran's I in Lesson 5 is computed from the weights list, so `W` and `S` will not give the same\nanswer there.\n\n### Which style inverse distance weights should use\n\nThe obvious fix is to change `style = \"B\"` to `style = \"W\"`, matching the chapter's\nsentence. The INSEE chapter argues against doing that.\n\nInside Chapter 8 the question never arises, because `rswm_ids` is built, printed, and then never\nused: every lag in its section 8.9 runs on plain Queen contiguity or binary weights, so the\ndistance decay computed in 8.7 is never applied to anything.\n\nde Bellefon, Loonis and Le Gleut set out what row standardisation means and then add a caveat\ndirectly about this case:\n\n> Each weight $w_{ij}$ can be interpreted as the fraction of spatial influence on observation $i$\n> ascribable to $j$. In contrast, such standardisation implies a certain degree of competition\n> between neighbours: the fewer neighbours a zone has, the greater their weight. Moreover, when\n> weights are inversely proportional to the distance between the zones, row standardisation makes\n> them difficult to interpret.\n\nRow standardisation divides by a row sum that is itself a function of distance, so the result\nmixes two things: how far a neighbour is, and how far all the other neighbours happen to be. Every\ncounty's weights are forced to total 1 however far away its neighbours are, so the decay is\npreserved between one county's neighbours and erased between counties.\n\nThe two produce lagged variables on different scales:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlag_B <- lag.listw(rswm_ids,   hunan$GDPPC)\nlag_W <- lag.listw(rswm_ids_W, hunan$GDPPC)\n\ntibble(quantity = c(\"GDPPC itself\", \"lag, style B\", \"lag, style W\"),\n       min = c(min(hunan$GDPPC), min(lag_B), min(lag_W)),\n       max = c(max(hunan$GDPPC), max(lag_B), max(lag_W))) |>\n  kable(digits = 0, format.args = list(big.mark = \",\"))\n```\n\n::: {.cell-output-display}\n\n\n|quantity     |    min|    max|\n|:------------|------:|------:|\n|GDPPC itself |  8,497| 88,656|\n|lag, style B |    429|  7,282|\n|lag, style W | 11,729| 54,908|\n\n\n:::\n\n```{.r .cell-code}\ncor(lag_B, lag_W)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7818471\n```\n\n\n:::\n:::\n\n\nThe `W` version stays on the scale of GDPPC. The `B` version is a sum of yuan-per-kilometre\nterms, which cannot be read as a neighbourhood income or plotted against one, and the two still\ncorrelate closely enough that a map of either looks reasonable.\n\nSo the chapter's code may be the better choice. Which style is right depends on the use: a\nneighbourhood **mean** comparable to GDPPC, as in §3.6.1, requires `W`, while preserving the\ndistance decay at its true magnitude requires `B`. The text names one and the code does the\nother, so a reader cannot tell which was intended. That is the error, whichever style is correct.\n\nThis page uses `W` wherever a lagged value is compared against GDPPC.\n\n## Graph-based neighbour definitions\n\nSection 4.3 showed that a fixed band leaves counties with no neighbour below 60 km, which is why\nthe chapter sets the band from the most isolated county in the province. The INSEE chapter covers\na family of neighbour definitions where that cannot happen, built from the geometry of the point\nset rather than from a distance threshold: \"they have the advantage that it leaves no unit\nwithout neighbours.\"\n\nAll four are in `spdep`, and each applies a different rule. Delaunay triangulation connects\npoints into triangles that maximise the minimum angle. The sphere of influence graph joins two\ncounties when the circles centred on each, drawn out to its own nearest neighbour, overlap.\nGabriel's graph joins two counties when no third county falls inside the circle having them as\nits diameter. The relative neighbour graph joins two counties only when no third county is closer\nto both of them than they are to each other. Each is a subgraph of the one before it.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngraphs <- list(\n  \"Delaunay\"            = tri2nb(coords),\n  \"Sphere of influence\" = graph2nb(soi.graph(tri2nb(coords), coords)),\n  \"Gabriel\"             = graph2nb(gabrielneigh(coords), sym = TRUE),\n  \"Relative neighbour\"  = graph2nb(relativeneigh(coords), sym = TRUE),\n  \"Queen contiguity\"    = wm_q,\n  \"Fixed band, 62 km\"   = wm_d62,\n  \"Adaptive, k = 6\"     = knn6)\n\nmap_dfr(names(graphs), function(nm) {\n  n <- graphs[[nm]]\n  tibble(method = nm, links = sum(card(n)), `avg links` = mean(card(n)),\n         min = min(card(n)), max = max(card(n)), isolated = sum(card(n) == 0))\n}) |> kable(digits = 2)\n```\n\n::: {.cell-output-display}\n\n\n|method              | links| avg links| min| max| isolated|\n|:-------------------|-----:|---------:|---:|---:|--------:|\n|Delaunay            |   498|      5.66|   3|   9|        0|\n|Sphere of influence |   428|      4.86|   2|   9|        0|\n|Gabriel             |   380|      4.32|   2|   8|        0|\n|Relative neighbour  |   238|      2.70|   1|   4|        0|\n|Queen contiguity    |   448|      5.09|   1|  11|        0|\n|Fixed band, 62 km   |   324|      3.68|   1|   6|        0|\n|Adaptive, k = 6     |   528|      6.00|   6|   6|        0|\n\n\n:::\n:::\n\n\nNone of the four graph methods isolates a county, as the INSEE chapter claims. Neither does\nQueen contiguity on this data, so the advantage is over the distance band rather than over\ncontiguity, and only below 60 km does that distinction start to matter.\n\nThe graphs change the spread. Queen contiguity runs from 1 neighbour to 11; Delaunay\nruns from 3 to 9 and the sphere of influence from 2 to 9. Taoyuan's 11 neighbours in §3.2.1 come\nfrom it being a large county surrounded by small ones, which the INSEE chapter names as a known\nproperty of contiguity: \"a very large zone surrounded by smaller zones will have a far greater\nnumber of neighbours than its neighbouring zones.\" The graph methods are built on the centroids\nand so do not inherit that.\n\nThe relative neighbour graph is much the sparsest at 2.70 links on average, which matches\nToussaint's design goal quoted in the INSEE chapter, that it \"adapts better to data by requiring the\nfewest links.\"\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(1, 2))\nplot(hunan$geometry, border = \"lightgrey\", main = \"Delaunay\")\nplot(graphs$Delaunay, coords, pch = 19, cex = 0.5, add = TRUE, col = \"red\")\nplot(hunan$geometry, border = \"lightgrey\", main = \"Relative neighbour\")\nplot(graphs$`Relative neighbour`, coords, pch = 19, cex = 0.5, add = TRUE, col = \"red\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex04_files/figure-html/unnamed-chunk-48-1.png){width=864}\n:::\n:::\n\n\nThe left panel shows the artefact these methods are known for. Delaunay spans the convex hull of\nthe point set, so counties along the provincial border are joined to each other by long edges\nthat run outside Hunan and across counties they do not touch. The INSEE chapter does not raise\nthis, and it is the reason the sparser subgraphs exist: the relative neighbour graph on the right\nkeeps 238 links against Delaunay's 498, and the long border edges are the first to go.\n\nThese are Euclidean-only in R, which the INSEE chapter flags as their limitation: great circle distance\nis not available, so on a province the size of Hunan they inherit the same planar assumption\n§4.2 measured.\n\n## Geographically weighted summary statistics\n\nSection 3.6.3 computed a mean for each county's neighbourhood instead of one mean for the whole\nprovince. Geographically weighted summary statistics work the same way, but the\nweighting and the neighbourhood are both adjustable. The window average uses uniform weights over\nthe contiguity neighbours; `gwss()` lets the weights decay with distance and lets the\nneighbourhood be a fixed count or a fixed radius.\n\nThe last four content slides of the Lesson 4 deck cover these and their robust versions, and\nChapter 8 stops before them. `GWmodel::gwss()` computes them, and the deck's slide 21 table is\nexactly its output.\n\nBandwidth is set to 6 adaptive, which is the queen contiguity average of 5.09 neighbours plus the\ncounty itself, so these statistics cover about the same neighbourhood as Part 1.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan_sp <- as_Spatial(st_transform(hunan, 4547))\ngw <- gwss(hunan_sp, vars = \"GDPPC\", bw = 6, kernel = \"bisquare\",\n           adaptive = TRUE, longlat = FALSE, quantile = TRUE)\nnames(as.data.frame(gw$SDF))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"GDPPC_LM\"     \"GDPPC_LSD\"    \"GDPPC_LVar\"   \"GDPPC_LSKe\"   \"GDPPC_LCV\"   \n[6] \"GDPPC_Median\" \"GDPPC_IQR\"    \"GDPPC_QI\"    \n```\n\n\n:::\n:::\n\n\n`LM` is the local mean, `LSD` the local standard deviation, `LVar` the variance, `LSKe` the skew\nand `LCV` the coefficient of variation; `Median`, `IQR` and `QI` are the robust three.\n\n`quantile = TRUE` is required to get those last three. Without it `gwss()` returns only the first\nfive and silently omits the median, IQR and quantile imbalance. There is no warning; the columns are simply absent, and code that goes on to read\n`GDPPC_Median` fails later with a message about the wrong thing.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngwr <- as.data.frame(gw$SDF)\nhunan$gw_mean   <- gwr$GDPPC_LM\nhunan$gw_median <- gwr$GDPPC_Median\nhunan$gw_iqr    <- gwr$GDPPC_IQR\n\ntibble(\n  statistic = c(\"GW mean\", \"GW median\"),\n  min = c(min(hunan$gw_mean), min(hunan$gw_median)),\n  max = c(max(hunan$gw_mean), max(hunan$gw_median))\n) |> kable(digits = 0, format.args = list(big.mark = \",\"))\n```\n\n::: {.cell-output-display}\n\n\n|statistic |    min|    max|\n|:---------|------:|------:|\n|GW mean   | 10,312| 73,533|\n|GW median |  8,497| 65,706|\n\n\n:::\n:::\n\n\nThe single global mean of 24405 yuan stands in for local means running from 10312 to 73533. The\nprovince has no representative county. The deck makes that argument on slide 18 for computing\nstatistics locally.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_arrange(\n  tm_shape(hunan) + tm_polygons(\"GDPPC\",\n    fill.scale = tm_scale_intervals(style = \"quantile\", n = 5),\n    fill.legend = tm_legend(title = \"GDPPC\", position = c(\"left\", \"bottom\"))),\n  tm_shape(hunan) + tm_polygons(\"gw_mean\",\n    fill.scale = tm_scale_intervals(style = \"quantile\", n = 5),\n    fill.legend = tm_legend(title = \"GW mean\", position = c(\"left\", \"bottom\"))),\n  tm_shape(hunan) + tm_polygons(\"gw_median\",\n    fill.scale = tm_scale_intervals(style = \"quantile\", n = 5),\n    fill.legend = tm_legend(title = \"GW median\", position = c(\"left\", \"bottom\"))),\n  ncol = 3)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex04_files/figure-html/unnamed-chunk-51-1.png){width=864}\n:::\n:::\n\n\nThe mean and the median diverge where one neighbour is an outlier. That is the case the deck's\nrobust statistics slides address.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngap <- abs(hunan$gw_mean - hunan$gw_median)\ncat(\"largest gap between GW mean and GW median:\", round(max(gap)), \"yuan at\",\n    hunan$County[which.max(gap)], \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlargest gap between GW mean and GW median: 17161 yuan at Xinshao \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  GW mean:  \", round(hunan$gw_mean[which.max(gap)]), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  GW mean:   28447 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  GW median:\", round(hunan$gw_median[which.max(gap)]), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  GW median: 11286 \n```\n\n\n:::\n:::\n\n\nAt Xinshao the local mean is 28447 and the local median 11286. One rich neighbour is carrying the\nmean and the median ignores it. Reading the mean alone would put Xinshao's neighbourhood in the\nmiddle of the province's distribution when most of it is near the bottom.\n\n### Kernel choice and the quantile imbalance\n\nThe quantile imbalance records where the local median sits between the local quartiles. Write\nthat position as $t = (\\text{Med} - Q_1)/(Q_3 - Q_1)$, so $t = 0$ puts the median on the lower\nquartile and $t = 1$ on the upper. The deck's formula then reduces to $QI = 2t - 1$: negative means the median sits\nnearer the lower quartile, positive nearer the upper, and zero means it is centred. It divides by\nthe weighted IQR, so it is undefined wherever that IQR is zero.\n\nThe bisquare kernel reaches exactly zero at the bandwidth, so at `bw = 6` adaptive the outermost\nof the six points is given a weight of 0 and only five carry any weight. With that few, the weighted\nfirst and third quartiles can land on the same observation. A Gaussian kernel never assigns a\nzero weight, so every neighbour contributes something.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngw_g <- gwss(hunan_sp, vars = \"GDPPC\", bw = 6, kernel = \"gaussian\",\n             adaptive = TRUE, longlat = FALSE, quantile = TRUE)\ngwr_g <- as.data.frame(gw_g$SDF)\ntibble(kernel = c(\"bisquare\", \"gaussian\"),\n       `IQR of 0` = c(sum(gwr$GDPPC_IQR == 0), sum(gwr_g$GDPPC_IQR == 0)),\n       `NaN imbalance` = c(sum(is.nan(gwr$GDPPC_QI)), sum(is.nan(gwr_g$GDPPC_QI)))) |> kable()\n```\n\n::: {.cell-output-display}\n\n\n|kernel   | IQR of 0| NaN imbalance|\n|:--------|--------:|-------------:|\n|bisquare |       10|            10|\n|gaussian |        0|             0|\n\n\n:::\n:::\n\n\nTen counties against none. Under the Gaussian kernel the quantile imbalance runs from -0.777 to\n0.632 across the province, so no county's median sits at a quartile but several come close.\n\nThe bisquare kernel is the usual default and is the wrong default at a bandwidth this small. The\nfailure surfaces as `NaN` in a column rather than as an error, the same shape as the\n`style = \"B\"` problem above.\n\n## Lagged explanatory variables in regression\n\nChapter 8 computes four lagged variables and never says what they are used for. Grubesic and\nRosso are a worked case. Their definition, the one the lecture puts on slide 15, excludes the\ncounty itself from its own lag:\n\n$$[Wx]_i = \\sum_{j \\neq i} w_{ij} x_j$$\n\nSection 3.6.1 follows that definition, and the two window versions in §3.6.3 and §3.6.4 are a\ndeliberate departure from it.\n\nTheir use for it is as an explanatory variable rather than a mapped quantity. They contrast it\nwith the more familiar model where the **dependent** variable is lagged:\n\n> rather than creating a multiplier effect as with spatially lagged dependent variables, spatial\n> cross-regressive terms can be used directly in a standard regression framework. In other words,\n> even ordinary least squares regressions would work with these data and not bias $\\gamma$.\n\nSo a lagged explanatory variable can go straight into an ordinary regression, where a lagged\ndependent variable cannot. They used a queen's contiguity matrix to build theirs. Section 4.1\nsettled on the same default here for a different reason.\n\nThey also give a way to say how much lagging alters the picture: cut both the variable and its\nlag into tertiles and measure agreement. On Philadelphia census tracts they report 44% of tracts\nin the same tertile, with a Cohen's kappa of 0.2.\n\nThe same measurement on Hunan:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntertile <- function(x) cut(x, breaks = quantile(x, c(0, 1/3, 2/3, 1)),\n                           include.lowest = TRUE, labels = c(\"low\", \"mid\", \"high\"))\nt_own <- tertile(hunan$GDPPC)\nt_lag <- tertile(hunan$lag_GDPPC)\ntab <- table(own = t_own, lagged = t_lag)\ntab\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      lagged\nown    low mid high\n  low   17   9    4\n  mid    9  14    6\n  high   4   6   19\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npo <- sum(diag(tab)) / sum(tab)\npe <- sum(rowSums(tab) * colSums(tab)) / sum(tab)^2\ntibble(study = c(\"Hunan GDPPC, this page\", \"Philadelphia amenity diversity, Grubesic and Rosso\"),\n       `same tertile` = c(po, 0.44),\n       kappa = c((po - pe) / (1 - pe), 0.2)) |>\n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|study                                              | same tertile| kappa|\n|:--------------------------------------------------|------------:|-----:|\n|Hunan GDPPC, this page                             |        0.568| 0.352|\n|Philadelphia amenity diversity, Grubesic and Rosso |        0.440| 0.200|\n\n\n:::\n:::\n\n\nA Hunan county aligns more closely with its surrounding neighbours than a Philadelphia tract\ndoes: 56.8% fall in the same tertile as their neighbourhood, against 44%. Cohen's kappa, which\ndiscounts the agreement that would arise by chance alone, is 0.35 against 0.2. Neither is high. Even here, 43% of counties fall in a different tertile from the\nneighbourhood around them, and Lesson 5 identifies those as spatial outliers.\n\nThe paper connects its own figure to its result. In their models the lagged variable was not\nsignificant, every interaction term came back above p = 0.2, and the fit did not improve. They\ngive their own concordance of 0.2 as part of the reason, and set one alternative beside it:\n\"measures at the participant's own census tract are sufficient to capture relevant neighbourhood\ncharacteristics.\"\n\n## The lag scatter and Moran's I\n\nThe spatial lag from section 3.6.1 is one step away from Lesson 5. Plotting each county's GDPPC\nagainst its neighbourhood mean gives the scatter that Moran's I summarises.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(hunan, aes(x = GDPPC, y = lag_GDPPC)) +\n  geom_point(alpha = 0.7) +\n  geom_smooth(method = \"lm\", se = FALSE, colour = \"firebrick\") +\n  geom_vline(xintercept = mean(hunan$GDPPC), linetype = \"dashed\", colour = \"grey50\") +\n  geom_hline(yintercept = mean(hunan$lag_GDPPC), linetype = \"dashed\", colour = \"grey50\") +\n  labs(x = \"GDPPC (yuan)\", y = \"Spatially lagged GDPPC (yuan)\",\n       title = \"County GDPPC against its neighbourhood mean\",\n       subtitle = \"Queen contiguity, row standardised weights\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex04_files/figure-html/unnamed-chunk-56-1.png){width=864}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(hunan$GDPPC, hunan$lag_GDPPC)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.4846051\n```\n\n\n:::\n:::\n\n\nThe upward slope means prosperous counties tend to sit beside prosperous counties, with a Pearson\ncorrelation of 0.485.\n\nThe dashed lines mark the two means and split the counties into four groups: prosperous beside\nprosperous (top right), poor beside poor (bottom left), and the two mismatched groups off the\ndiagonal. Lesson 5 names these four and tests which memberships are stronger than chance.\n\nEvery value on the vertical axis depends on the weights matrix built in Part 1.\n\n# Reflection\n\nWhether the weights matrix matters is an open question in the readings themselves.\n\nThe INSEE chapter quotes both positions. Bhattacharjee and Jensen-Butler found that results vary\nconsiderably depending on how the weights are defined, and Harris, Moffat and Kravtsova argue\nthat a researcher picks a weights structure and then has no way of checking whether it was the\nright one. LeSage and Pace disagree, calling that worry \"the biggest myth in spatial\neconometrics\" and putting it down to misreading the model's coefficients.\n\nMy own results support both, depending on whether the claim is about the province or about one\ncounty.\n\nAcross the province, LeSage and Pace look right. Queen and Rook contiguity give different lagged\nvalues for only 8 counties out of 88. Computing centroids in degrees rather than metres moves\nthem 18 m at the median, which the 62 km band absorbs completely. The k nearest neighbour lists\nare disturbed by that shift, and still rank the counties almost identically, at a rank\ncorrelation of 0.984. The north east is prosperous and the west is not, under every weights\nchoice tested here.\n\nCounty by county, the critics look right. Longhui's neighbourhood mean moves 41.4% on that same\ncentroid shift, because a k nearest list has no distance threshold to absorb a small error. Anren\nmoves 17.7% when one corner contact is dropped. And `style = \"B\"` returns a figure in yuan per\nkilometre, which cannot be read as a neighbourhood income at all, yet it still correlates 0.78\nwith the correct version, so a map of it looks fine. A claim about one county is a claim about\nthe weights matrix as much as about the data, the same way Exercise 2 found that a claim about\none hotspot was a claim about the bandwidth.\n\nBavaud puts the general case: \"there is no such thing as 'true', 'universal' spatial weights,\noptimal in all situations: good candidates must reflect the properties of the particular\nphenomenon.\" So the weights have to be named and the alternatives shown.\n\nOne of my own conclusions changed while reading. I had written that the `style = \"B\"` problem was\na one-character fix. The INSEE chapter argues that row standardising inverse distance weights\nmakes them hard to interpret, which means the chapter's code may be the better choice and only\nits sentence wrong.\n\nThe recurring hazard in this exercise was software that fails quietly. Four calls ran with no\nerror and no warning while doing something other than what the text around them described:\n`style = \"B\"` returning yuan per kilometre where a neighbourhood mean was described, `gwss()`\ndropping the median, IQR and quantile imbalance because `quantile = TRUE` was left out, the\nbisquare kernel producing ten `NaN` values, and `knearneigh()` finding each county's nearest\nneighbour in degrees while `nbdists()` measured it in kilometres, so 61.79 km was not the largest\nfirst nearest neighbour distance.\n\nWith more time I would test the bandwidth in section 4.6 instead of choosing it. Setting it to 6\nmatches the average number of contiguity neighbours, which is a reason but not a test. `GWmodel`\nhas no automatic selector for `gwss()`, so the alternative is a sensitivity table across several\nbandwidths, like the one in section 4.3.\n\nThis page does not test whether Hunan's spatial pattern is stronger than chance would produce.\nThe scatter in section 4.8 slopes upwards, and Moran's I in Lesson 5 decides whether that slope\nmeans anything.\n\n# References\n\nCourse materials:\n\n- Kam, T.S. (2026), [Lesson 4: Spatial Weights and\n  Applications](https://isss626-ay2026-27aug.netlify.app/lesson/lesson04/lesson04-spatial_weights),\n  ISSS626 Geospatial Analytics and Applications, SMU.\n- Kam, T.S. (2026), [Chapter 8: Spatial Weights and\n  Applications](https://r4gdsa.netlify.app/chap08.html), *R for Geospatial Data Science and\n  Analytics*.\n\nMethod:\n\nThe three named on the Lesson 4 slides, all read in full:\n\n- de Bellefon, M.-P., Loonis, V. and Le Gleut, R. (2018), [\"Codifying the neighbourhood\n  structure\"](https://www.insee.fr/en/statistiques/fichier/3635545/imet131-f-chapitre-2.pdf),\n  chapter 2 of *Handbook of Spatial Analysis: Theory and Application with R*, INSEE. The assigned\n  pre-class reading.\n- Bavaud, F. (1998), [\"Models for Spatial Weights: A Systematic\n  Look\"](https://onlinelibrary.wiley.com/doi/abs/10.1111/j.1538-4632.1998.tb00394.x),\n  *Geographical Analysis*, 30(2), 153-171. The slide dates this 2010; the paper and the DOI both\n  give 1998.\n- Grubesic, T.H. and Rosso, A.L. (2014), [\"The Use of Spatially Lagged Explanatory Variables for\n  Modeling Neighborhood Amenities and Mobility in Older\n  Adults\"](https://www.jstor.org/stable/26326897), *Cityscape*, 16(2), 205-214.\n\nCited within those, and used in sections 4.4, 4.5 and 5:\n\n- Tiefelsdorf, M. (1998), *Modelling spatial processes: the identification and analysis of spatial\n  relationships in regression residuals by means of Moran's I*, PhD thesis. The source of the `S`\n  variance-stabilising scheme.\n- Bhattacharjee, A. and Jensen-Butler, C. (2005), \"Estimation of spatial weights matrix in a\n  spatial error model\", *CRIEFF Discussion Papers*.\n- Harris, R., Moffat, J. and Kravtsova, V. (2011), \"In search of 'W'\", *Spatial Economic\n  Analysis*, 6(3), 249-270.\n- LeSage, J.P. and Pace, R.K. (2010), \"The biggest myth in spatial econometrics\", SSRN 1725503.\n- Toussaint, G.T. (1980), \"The relative neighbourhood graph of a finite planar set\", *Pattern\n  Recognition*, 12(4), 261-268.\n- Anselin, L. (2002), \"Under the hood: issues in the specification and interpretation of spatial\n  regression models\", *Agricultural Economics*, 27(3), 247-267. The source of the\n  cross-regressive argument in 4.7.\n\nAlternative reading named on the outline, not used here:\n\n- Bivand, R.S., Pebesma, E. and Gómez-Rubio, V. (2013), *Applied Spatial Data Analysis with R*,\n  2nd edition, chapter 9 to section 9.3.1. Springer.\n- Brunsdon, C., Fotheringham, A.S. and Charlton, M. (2002), \"Geographically weighted summary\n  statistics: a framework for localised exploratory data analysis\", *Computers, Environment and\n  Urban Systems*, 26(6), 501-524. The method behind `gwss()`.\n\nPackages:\n\n- Bivand, R.S. and Wong, D.W.S. (2018), [\"Comparing implementations of global and local indicators\n  of spatial association\"](https://doi.org/10.1007/s11749-018-0599-x), *TEST*, 27(3), 716-748.\n  The `spdep` reference.\n- Gollini, I., Lu, B., Charlton, M., Brunsdon, C. and Harris, P. (2015), [\"GWmodel: An R Package\n  for Exploring Spatial Heterogeneity Using Geographically Weighted\n  Models\"](https://www.jstatsoft.org/article/view/v063i17), *Journal of Statistical Software*,\n  63(17).\n\nData:\n\n- Hunan county boundary layer and `Hunan_2012.csv`, the two files named in Chapter 8.\n\n# About this document\n\nWritten and executed in Quarto with R 4.6.1. All figures are generated at render time\nfrom the data in `data/`, so nothing on this page is pasted in.\n\nI used AI assistance while working out the approach and the extensions in Part 2. The analysis\nwas run and checked by me.\n",
    "supporting": [
      "Hands-on_Ex04_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}