<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="An Loc">
<meta name="dcterms.date" content="2026-09-10">

<title>Hands-on Exercise 3 – ISSS626 Geospatial Analytics</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-b85bc7c33db8c58e0ec93c3465666fed.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-656ab5d6a413202a350e6c7af9bef9dc.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-2b587f210acc1d131e2f46a7d4bf607a.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../site_libs/bootstrap/bootstrap-656ab5d6a413202a350e6c7af9bef9dc.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">ISSS626 Geospatial Analytics</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercises" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Hands-on Exercises</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-exercises">    
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html">
 <span class="dropdown-text">Hands-on Ex 1: Geospatial Data Wrangling &amp; Choropleth Mapping</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html">
 <span class="dropdown-text">Hands-on Ex 2: Spatial Point Patterns Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html">
 <span class="dropdown-text">Hands-on Ex 3: Spatio-Temporal Point Patterns Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html">
 <span class="dropdown-text">Hands-on Ex 4: Spatial Weights and Applications</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-in-class-exercises" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">In-class Exercises</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-in-class-exercises">    
        <li>
    <a class="dropdown-item" href="../../index.html">
 <span class="dropdown-text">(none yet)</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-take-home-exercises" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Take-home Exercises</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-take-home-exercises">    
        <li>
    <a class="dropdown-item" href="../../index.html">
 <span class="dropdown-text">(none yet)</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/ngdvol/ISSS626-GAA"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="99">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview"><span class="header-section-number">1</span> Overview</a>
  <ul>
  <li><a href="#the-questions-being-asked" id="toc-the-questions-being-asked" class="nav-link" data-scroll-target="#the-questions-being-asked"><span class="header-section-number">1.1</span> The questions being asked</a></li>
  <li><a href="#differences-from-the-chapter" id="toc-differences-from-the-chapter" class="nav-link" data-scroll-target="#differences-from-the-chapter"><span class="header-section-number">1.2</span> Differences from the chapter</a></li>
  </ul></li>
  <li><a href="#getting-started" id="toc-getting-started" class="nav-link" data-scroll-target="#getting-started"><span class="header-section-number">2</span> Getting started</a>
  <ul>
  <li><a href="#packages" id="toc-packages" class="nav-link" data-scroll-target="#packages"><span class="header-section-number">2.1</span> Packages</a></li>
  <li><a href="#the-data" id="toc-the-data" class="nav-link" data-scroll-target="#the-data"><span class="header-section-number">2.2</span> The data</a>
  <ul class="collapse">
  <li><a href="#fire-detections" id="toc-fire-detections" class="nav-link" data-scroll-target="#fire-detections"><span class="header-section-number">2.2.1</span> Fire detections</a></li>
  <li><a href="#study-area-boundary" id="toc-study-area-boundary" class="nav-link" data-scroll-target="#study-area-boundary"><span class="header-section-number">2.2.2</span> Study area boundary</a></li>
  <li><a href="#coordinate-reference-system" id="toc-coordinate-reference-system" class="nav-link" data-scroll-target="#coordinate-reference-system"><span class="header-section-number">2.2.3</span> Coordinate reference system</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#part-1-following-the-chapter" id="toc-part-1-following-the-chapter" class="nav-link" data-scroll-target="#part-1-following-the-chapter"><span class="header-section-number">3</span> Part 1: Following the chapter</a>
  <ul>
  <li><a href="#first-order-spatio-temporal-kde" id="toc-first-order-spatio-temporal-kde" class="nav-link" data-scroll-target="#first-order-spatio-temporal-kde"><span class="header-section-number">3.1</span> First-order: spatio-temporal KDE</a>
  <ul class="collapse">
  <li><a href="#the-study-area" id="toc-the-study-area" class="nav-link" data-scroll-target="#the-study-area"><span class="header-section-number">3.1.1</span> The study area</a></li>
  <li><a href="#converting-to-an-owin" id="toc-converting-to-an-owin" class="nav-link" data-scroll-target="#converting-to-an-owin"><span class="header-section-number">3.1.2</span> Converting to an owin</a></li>
  <li><a href="#the-fire-data" id="toc-the-fire-data" class="nav-link" data-scroll-target="#the-fire-data"><span class="header-section-number">3.1.3</span> The fire data</a>
  <ul class="collapse">
  <li><a href="#deriving-the-temporal-marks" id="toc-deriving-the-temporal-marks" class="nav-link" data-scroll-target="#deriving-the-temporal-marks"><span class="header-section-number">3.1.3.1</span> Deriving the temporal marks</a></li>
  </ul></li>
  <li><a href="#visualising-the-fire-points" id="toc-visualising-the-fire-points" class="nav-link" data-scroll-target="#visualising-the-fire-points"><span class="header-section-number">3.1.4</span> Visualising the fire points</a>
  <ul class="collapse">
  <li><a href="#overall-distribution" id="toc-overall-distribution" class="nav-link" data-scroll-target="#overall-distribution"><span class="header-section-number">3.1.4.1</span> Overall distribution</a></li>
  <li><a href="#by-month" id="toc-by-month" class="nav-link" data-scroll-target="#by-month"><span class="header-section-number">3.1.4.2</span> By month</a></li>
  </ul></li>
  <li><a href="#stkde-by-month" id="toc-stkde-by-month" class="nav-link" data-scroll-target="#stkde-by-month"><span class="header-section-number">3.1.5</span> STKDE by month</a>
  <ul class="collapse">
  <li><a href="#checking-for-duplicates" id="toc-checking-for-duplicates" class="nav-link" data-scroll-target="#checking-for-duplicates"><span class="header-section-number">3.1.5.1</span> Checking for duplicates</a></li>
  <li><a href="#applying-the-observation-window" id="toc-applying-the-observation-window" class="nav-link" data-scroll-target="#applying-the-observation-window"><span class="header-section-number">3.1.5.2</span> Applying the observation window</a></li>
  <li><a href="#computing-the-density" id="toc-computing-the-density" class="nav-link" data-scroll-target="#computing-the-density"><span class="header-section-number">3.1.5.3</span> Computing the density</a></li>
  <li><a href="#plotting-the-result" id="toc-plotting-the-result" class="nav-link" data-scroll-target="#plotting-the-result"><span class="header-section-number">3.1.5.4</span> Plotting the result</a></li>
  </ul></li>
  <li><a href="#stkde-by-day-of-year" id="toc-stkde-by-day-of-year" class="nav-link" data-scroll-target="#stkde-by-day-of-year"><span class="header-section-number">3.1.6</span> STKDE by day of year</a></li>
  <li><a href="#choosing-the-bandwidths" id="toc-choosing-the-bandwidths" class="nav-link" data-scroll-target="#choosing-the-bandwidths"><span class="header-section-number">3.1.7</span> Choosing the bandwidths</a></li>
  </ul></li>
  <li><a href="#second-order-the-k-function" id="toc-second-order-the-k-function" class="nav-link" data-scroll-target="#second-order-the-k-function"><span class="header-section-number">3.2</span> Second-order: the K-function</a>
  <ul class="collapse">
  <li><a href="#building-the-stpp-object" id="toc-building-the-stpp-object" class="nav-link" data-scroll-target="#building-the-stpp-object"><span class="header-section-number">3.2.1</span> Building the stpp object</a></li>
  <li><a href="#computing-the-k-function" id="toc-computing-the-k-function" class="nav-link" data-scroll-target="#computing-the-k-function"><span class="header-section-number">3.2.2</span> Computing the K-function</a></li>
  <li><a href="#reading-the-plot" id="toc-reading-the-plot" class="nav-link" data-scroll-target="#reading-the-plot"><span class="header-section-number">3.2.3</span> Reading the plot</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#part-2-review-and-extension" id="toc-part-2-review-and-extension" class="nav-link" data-scroll-target="#part-2-review-and-extension"><span class="header-section-number">4</span> Part 2: Review and extension</a>
  <ul>
  <li><a href="#methodology-review" id="toc-methodology-review" class="nav-link" data-scroll-target="#methodology-review"><span class="header-section-number">4.1</span> Methodology review</a>
  <ul class="collapse">
  <li><a href="#observation-window-k-function-versus-kde" id="toc-observation-window-k-function-versus-kde" class="nav-link" data-scroll-target="#observation-window-k-function-versus-kde"><span class="header-section-number">4.1.1</span> Observation window: K-function versus KDE</a></li>
  <li><a href="#study-area-definition" id="toc-study-area-definition" class="nav-link" data-scroll-target="#study-area-definition"><span class="header-section-number">4.1.2</span> Study area definition</a></li>
  <li><a href="#bandwidth-selection-and-hard-coded-values" id="toc-bandwidth-selection-and-hard-coded-values" class="nav-link" data-scroll-target="#bandwidth-selection-and-hard-coded-values"><span class="header-section-number">4.1.3</span> Bandwidth selection and hard-coded values</a></li>
  <li><a href="#colour-scaling-across-sections" id="toc-colour-scaling-across-sections" class="nav-link" data-scroll-target="#colour-scaling-across-sections"><span class="header-section-number">4.1.4</span> Colour scaling across sections</a></li>
  <li><a href="#graphics-device-handling-in-plotk" id="toc-graphics-device-handling-in-plotk" class="nav-link" data-scroll-target="#graphics-device-handling-in-plotk"><span class="header-section-number">4.1.5</span> Graphics device handling in plotK()</a></li>
  <li><a href="#seed-placement" id="toc-seed-placement" class="nav-link" data-scroll-target="#seed-placement"><span class="header-section-number">4.1.6</span> Seed placement</a></li>
  </ul></li>
  <li><a href="#other-observations" id="toc-other-observations" class="nav-link" data-scroll-target="#other-observations"><span class="header-section-number">4.2</span> Other observations</a></li>
  <li><a href="#fire-counts-and-rates-by-regency" id="toc-fire-counts-and-rates-by-regency" class="nav-link" data-scroll-target="#fire-counts-and-rates-by-regency"><span class="header-section-number">4.3</span> Fire counts and rates by regency</a></li>
  </ul></li>
  <li><a href="#reflection" id="toc-reflection" class="nav-link" data-scroll-target="#reflection"><span class="header-section-number">5</span> Reflection</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">6</span> References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Hands-on Exercise 3</h1>
<p class="subtitle lead">Spatio-Temporal Point Patterns Analysis with R</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>An Loc </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">10 Sep 2026</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">11 Sep 2026</p>
    </div>
  </div>
    
  </div>
  


</header>


<section id="overview" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Overview</h1>
<p>This exercise applies <strong>Spatio-Temporal Point Patterns Analysis (STPPA)</strong> to forest fire detections in Kepulauan Bangka Belitung, Indonesia, during 2023. It follows r4gdsa Chapter 6, the chapter assigned for Lesson 3. Where I write “the chapter” below, I mean that one.</p>
<p>Lesson 2 treated a point pattern as a set of locations. A spatio-temporal point pattern adds the time of each event, so the same two questions from last week are asked again in three dimensions.</p>
<p><strong>Part 1</strong> reproduces Chapter 6. It has two halves: a first-order analysis of how fire intensity varies across space and time, using <code>sparr</code>, and a second-order analysis of whether events interact, using the space-time K-function in <code>stpp</code>. <strong>Part 2</strong> examines the chapter’s method and adds one analysis it does not attempt.</p>
<section id="the-questions-being-asked" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="the-questions-being-asked"><span class="header-section-number">1.1</span> The questions being asked</h2>
<p>The chapter asks:</p>
<ol type="1">
<li>Are the locations of forest fire in Kepulauan Bangka Belitung spatial and spatio-temporally independent?</li>
<li>If the answer is no, where and when do the observed fire locations tend to cluster?</li>
</ol>
<p>Independence is a second-order property, so the first question is addressed by the K-function in section 3.2. The second requires both halves: the density estimate locates the concentrations in space and time, and the K-function establishes whether they exceed what chance would produce.</p>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Reference
</div>
</div>
<div class="callout-body-container callout-body">
<p>r4gdsa <a href="https://r4gdsa.netlify.app/chap06.html">Chapter 6: Spatio-Temporal Point Patterns Analysis</a>.</p>
</div>
</div>
</section>
<section id="differences-from-the-chapter" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="differences-from-the-chapter"><span class="header-section-number">1.2</span> Differences from the chapter</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>The chapter</th>
<th>This page</th>
<th>Why</th>
<th>Where</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Study area</strong></td>
<td>Bangka island, 11,534 km², described as the whole province</td>
<td>Bangka island, 11,887 km², named as such</td>
<td>The chapter’s file does not cover the area its text names. Part 1 follows the chapter’s actual window</td>
<td>3.1.1, 4.1</td>
</tr>
<tr class="even">
<td><strong>Boundary source</strong></td>
<td>Indonesia Geospatial portal</td>
<td>GADM 4.1, level 2</td>
<td>The portal distributes files through a blog page linking to Google Drive, with no stable URL to cite</td>
<td>2.2</td>
</tr>
<tr class="odd">
<td><strong>Fire data source</strong></td>
<td>FIRMS download portal, account required</td>
<td>FIRMS public archive, direct URL</td>
<td>Same MODIS data from a stable URL that can be cited in the document</td>
<td>2.2</td>
</tr>
<tr class="even">
<td><strong>Data extent</strong></td>
<td><code>forestfires.csv</code>, already cut to the study area</td>
<td>All 52,156 Indonesian detections, cut in code</td>
<td>The cut is the step that decides the answer, so it belongs in the document</td>
<td>3.1.3</td>
</tr>
<tr class="odd">
<td><strong><code>set.seed()</code></strong></td>
<td>Only before <code>BOOT.spattemp()</code></td>
<td>Once at the top</td>
<td>Asked for in the Lesson 2 class: without it the render is not reproducible</td>
<td>2.1</td>
</tr>
<tr class="even">
<td><strong>Months plotted</strong></td>
<td>July to December</td>
<td>All twelve, in two blocks</td>
<td>Shows the instability that sparse monthly counts produce</td>
<td>3.1.5.4</td>
</tr>
<tr class="odd">
<td><strong>Duplicate check</strong></td>
<td><code>any(duplicated())</code></td>
<td><code>sum(duplicated())</code></td>
<td>A count says how many, which is what a data-quality check needs to report</td>
<td>3.1.5.1</td>
</tr>
<tr class="even">
<td><strong>Facet function</strong></td>
<td><code>tm_facets()</code></td>
<td><code>tm_facets_wrap()</code></td>
<td><code>tm_facets()</code> is tmap 3; this machine runs tmap 4.4.1 and emits a deprecation message</td>
<td>3.1.4.2</td>
</tr>
<tr class="odd">
<td><strong>Figure heights</strong></td>
<td>default</td>
<td>set per chunk</td>
<td>The study area is nearly twice as wide as it is tall, so the default canvas leaves white bands inside every map</td>
<td>3.1.4.1</td>
</tr>
<tr class="even">
<td><strong>Pipe</strong></td>
<td><code>%&gt;%</code></td>
<td><code>|&gt;</code></td>
<td>Both were covered in the Lesson 2 class and the choice was left to us. The native pipe does not need tidyverse loaded</td>
<td>throughout</td>
</tr>
<tr class="odd">
<td><strong>Offshore islets</strong></td>
<td>not applicable, single polygon</td>
<td>53 pieces reduced to 11 by dropping anything under 1 km²</td>
<td>A fire cannot occur on a rock of a few thousandths of a square kilometre, and the fragments change the bandwidth the model selects. Keeps 99.97% of the area and all 766 fires</td>
<td>3.1.1, 4.2</td>
</tr>
<tr class="even">
<td><strong>Regency breakdown</strong></td>
<td>not present</td>
<td>added</td>
<td>Shows the first-order variation the density surface smooths over, and regency is the administrative unit required for Take-home Exercise 1</td>
<td>4.3</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Mapping of Chapter 6 sections to this page
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Every section of Chapter 6 is covered. The order is regrouped into two parts.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Chapter 6</th>
<th>This page</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>6.1 Overview</td>
<td>1 Overview</td>
</tr>
<tr class="even">
<td>6.2.1 The research questions</td>
<td>1.1 The questions being asked</td>
</tr>
<tr class="odd">
<td>6.3 The data</td>
<td>2.2 The data</td>
</tr>
<tr class="even">
<td>6.4 Installing and loading the R packages</td>
<td>2.1 Packages</td>
</tr>
<tr class="odd">
<td>6.5.1 Importing study area</td>
<td>3.1.1 The study area</td>
</tr>
<tr class="even">
<td>6.5.2 Converting OWIN</td>
<td>3.1.2 Converting to an owin</td>
</tr>
<tr class="odd">
<td>6.6 Importing and preparing forest fire data</td>
<td>3.1.3 The fire data</td>
</tr>
<tr class="even">
<td>6.7.1 Overall plot</td>
<td>3.1.4.1 Overall distribution</td>
</tr>
<tr class="odd">
<td>6.7.2 Distribution by month</td>
<td>3.1.4.2 By month</td>
</tr>
<tr class="even">
<td>6.8.1 Extracting forest fires by month</td>
<td>3.1.5 STKDE by month</td>
</tr>
<tr class="odd">
<td>6.8.2 Creating ppp</td>
<td>3.1.5, and the duplicate check in 3.1.5.1</td>
</tr>
<tr class="even">
<td>6.8.3 Including owin object</td>
<td>3.1.5.2 Applying the observation window</td>
</tr>
<tr class="odd">
<td>6.8.4 Computing spatio-temporal KDE</td>
<td>3.1.5.3 Computing the density</td>
</tr>
<tr class="even">
<td>6.8.5 Plotting the spatio-temporal KDE object</td>
<td>3.1.5.4 Plotting the result</td>
</tr>
<tr class="odd">
<td>6.9.1 Creating ppp object</td>
<td>3.1.6 STKDE by day of year</td>
</tr>
<tr class="even">
<td>6.9.2 Including owin object</td>
<td>3.1.6</td>
</tr>
<tr class="odd">
<td>6.9.3 <em>(untitled in the chapter)</em></td>
<td>3.1.6</td>
</tr>
<tr class="even">
<td>6.10 <code>set.seed()</code></td>
<td>2.1, moved to the top of the document</td>
</tr>
<tr class="odd">
<td>6.10.1 Computing spatio-temporal KDE</td>
<td>3.1.7 Choosing the bandwidths</td>
</tr>
<tr class="even">
<td>6.10.2 Plotting the output spatio-temporal KDE</td>
<td>3.1.7</td>
</tr>
<tr class="odd">
<td>6.11.1 Preparing the stpp object</td>
<td>3.2.1 Building the stpp object</td>
</tr>
<tr class="even">
<td>6.11.2 Computing spatio-temporal K-function</td>
<td>3.2.2 Computing the K-function</td>
</tr>
<tr class="odd">
<td>6.11.3 Guide to interpret the plot</td>
<td>3.2.3 Reading the plot</td>
</tr>
<tr class="even">
<td>6.12 Reference</td>
<td>6 References</td>
</tr>
</tbody>
</table>
<p>Two chapter sections have no code and no content of their own, 6.2 Learning Outcome and 6.9.3, which is untitled. Both are covered by the rows above.</p>
</div>
</div>
</div>
</section>
</section>
<section id="getting-started" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Getting started</h1>
<section id="packages" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="packages"><span class="header-section-number">2.1</span> Packages</h2>
<p>Six packages are used. <code>sparr</code> and <code>stpp</code> are new this week. The rest carry over from Hands-on Exercise 2.</p>
<ul>
<li><code>sf</code> for reading and transforming the geospatial layers</li>
<li><code>spatstat</code> for the <code>ppp</code> and <code>owin</code> classes, which <code>sparr</code> builds on</li>
<li><code>sparr</code> for spatio-temporal kernel density estimation and bandwidth selection</li>
<li><code>tmap</code> for the point maps</li>
<li><code>stpp</code> for the space-time K-function</li>
<li><code>tidyverse</code> for the data wrangling, including <code>lubridate</code> for the date handling</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(sf, spatstat, sparr, tmap, stpp, tidyverse)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The chapter does not set a seed. This came up in the Lesson 2 class: without one, the bootstrap and simulation results change on every render, preventing reproducible rendering. One seed is set here, at the top, before anything random runs.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="the-data" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="the-data"><span class="header-section-number">2.2</span> The data</h2>
<p>Two datasets are needed: the fire detections and the boundary of the study area. The chapter names its sources but distributes neither file, so both were retrieved directly.</p>
<section id="fire-detections" class="level3" data-number="2.2.1">
<h3 data-number="2.2.1" class="anchored" data-anchor-id="fire-detections"><span class="header-section-number">2.2.1</span> Fire detections</h3>
<p>The chapter uses <code>forestfires.csv</code>, described as MODIS detections from NASA’s <a href="https://firms.modaps.eosdis.nasa.gov/download/">Fire Information for Resource Management System</a>. The download page it links requires an account and delivers the file by email. The same archive is also published as a direct download with no account, one file per country per year:</p>
<pre><code>https://firms.modaps.eosdis.nasa.gov/data/country/modis/2023/modis_2023_Indonesia.csv</code></pre>
<p>That is the file used here. It holds every MODIS detection in Indonesia for 2023 and is kept whole, so the cut to Bangka is done in the code below and stays visible.</p>
</section>
<section id="study-area-boundary" class="level3" data-number="2.2.2">
<h3 data-number="2.2.2" class="anchored" data-anchor-id="study-area-boundary"><span class="header-section-number">2.2.2</span> Study area boundary</h3>
<p>The chapter reads an ESRI shapefile named <code>Kepulauan_Bangka_Belitung</code>, extracted from a national file on the <a href="https://www.indonesia-geospasial.com/2023/05/download-shapefile-batas-administrasi.html">Indonesia Geospatial portal</a>. That portal distributes its files through a blog page linking to Google Drive, so there is no stable URL to cite.</p>
<p>I used <a href="https://gadm.org/">GADM</a> instead, level 2, which is the regency and city level (<em>kabupaten</em> and <em>kota</em>):</p>
<pre><code>https://geodata.ucdavis.edu/gadm/gadm4.1/json/gadm41_IDN_2.json.zip</code></pre>
<p>The chapter’s file is at <em>kelurahan</em> level, one step finer, but the chapter immediately dissolves it with <code>st_union()</code>, so the boundary that reaches the analysis is identical either way. Level 2 also keeps the regencies available, which is the administrative unit required for Take-home Exercise 1.</p>
</section>
<section id="coordinate-reference-system" class="level3" data-number="2.2.3">
<h3 data-number="2.2.3" class="anchored" data-anchor-id="coordinate-reference-system"><span class="header-section-number">2.2.3</span> Coordinate reference system</h3>
<p>Everything is transformed to <strong>EPSG:32748</strong>, WGS 84 / UTM zone 48S, which is the projected system the chapter uses and the correct UTM zone for Bangka Belitung. Units are metres, so every bandwidth and distance below reads in metres.</p>
</section>
</section>
</section>
<section id="part-1-following-the-chapter" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Part 1: Following the chapter</h1>
<p>Chapter 6 divides into two analytical parts. Sections 6.5 to 6.10 estimate how fire intensity varies across space and time, a first-order question. Section 6.11 asks whether events interact once that intensity is accounted for, a second-order question. As section 1.1 notes, these do not map onto the two research questions in order: independence is settled by the second-order analysis, and the question of where and when fires cluster needs both.</p>
<section id="first-order-spatio-temporal-kde" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="first-order-spatio-temporal-kde"><span class="header-section-number">3.1</span> First-order: spatio-temporal KDE</h2>
<section id="the-study-area" class="level3" data-number="3.1.1">
<h3 data-number="3.1.1" class="anchored" data-anchor-id="the-study-area"><span class="header-section-number">3.1.1</span> The study area</h3>
<p>The GADM file covers the whole country, so the study area is selected by name and then merged into a single polygon. <code>st_zm()</code> drops the Z dimension, which <code>as.owin()</code> will not accept, and the transform puts the result in metres.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>bangka_raw <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="st">"data/rawdata/gadm41_IDN_2.json"</span>, <span class="at">quiet =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(NAME_1 <span class="sc">==</span> <span class="st">"BangkaBelitung"</span>,</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>         <span class="sc">!</span><span class="fu">grepl</span>(<span class="st">"^Belitung"</span>, NAME_2)) <span class="sc">|&gt;</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_union</span>() <span class="sc">|&gt;</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_zm</span>(<span class="at">drop =</span> <span class="cn">TRUE</span>, <span class="at">what =</span> <span class="st">"ZM"</span>) <span class="sc">|&gt;</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">32748</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The filter takes the five regencies on Bangka island: Bangka, Bangka Barat, Bangka Selatan, Bangka Tengah and the city of Pangkalpinang. The chapter’s own study area is Bangka rather than the whole province, though the chapter never says so.</p>
<p>Every offshore rock is a separate polygon in the GADM file, so this boundary is made up of 53 pieces.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>parts <span class="ot">&lt;-</span> <span class="fu">st_cast</span>(bangka_raw, <span class="st">"POLYGON"</span>, <span class="at">warn =</span> <span class="cn">FALSE</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>part_km2 <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">st_area</span>(parts)) <span class="sc">/</span> <span class="fl">1e6</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">parts =</span> <span class="fu">length</span>(parts),</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">largest_km2 =</span> <span class="fu">round</span>(<span class="fu">max</span>(part_km2), <span class="dv">1</span>),</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">smallest_km2 =</span> <span class="fu">round</span>(<span class="fu">min</span>(part_km2), <span class="dv">4</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       parts  largest_km2 smallest_km2 
     53.0000   11602.5000       0.0013 </code></pre>
</div>
</div>
<p>The main island is 11,603 km². The smallest pieces are a few thousandths of a square kilometre. Fires cannot occur on those, so anything under 1 km² is dropped. Dropping these slivers prevents inflation of the selected bandwidth, as shown in section 4.2.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>kbb_sf <span class="ot">&lt;-</span> <span class="fu">st_union</span>(parts[part_km2 <span class="sc">&gt;=</span> <span class="dv">1</span>])</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">parts_kept =</span> <span class="fu">length</span>(<span class="fu">st_cast</span>(kbb_sf, <span class="st">"POLYGON"</span>, <span class="at">warn =</span> <span class="cn">FALSE</span>)),</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">area_km2 =</span> <span class="fu">round</span>(<span class="fu">as.numeric</span>(<span class="fu">st_area</span>(kbb_sf)) <span class="sc">/</span> <span class="fl">1e6</span>, <span class="dv">1</span>),</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">pct_of_original =</span> <span class="fu">round</span>(<span class="dv">100</span> <span class="sc">*</span> <span class="fu">as.numeric</span>(<span class="fu">st_area</span>(kbb_sf)) <span class="sc">/</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>                            <span class="fu">as.numeric</span>(<span class="fu">st_area</span>(bangka_raw)), <span class="dv">2</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     parts_kept        area_km2 pct_of_original 
          11.00        11886.90           99.97 </code></pre>
</div>
</div>
<p>11 pieces remain, holding 99.97% of the land area, about 11,887 km².</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>kbb_regencies <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="st">"data/rawdata/gadm41_IDN_2.json"</span>, <span class="at">quiet =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(NAME_1 <span class="sc">==</span> <span class="st">"BangkaBelitung"</span>,</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>         <span class="sc">!</span><span class="fu">grepl</span>(<span class="st">"^Belitung"</span>, NAME_2)) <span class="sc">|&gt;</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_zm</span>(<span class="at">drop =</span> <span class="cn">TRUE</span>, <span class="at">what =</span> <span class="st">"ZM"</span>) <span class="sc">|&gt;</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">32748</span>)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>kbb_regencies<span class="sc">$</span>NAME_2</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Bangka"        "BangkaBarat"   "BangkaSelatan" "BangkaTengah" 
[5] "Pangkalpinang"</code></pre>
</div>
</div>
</section>
<section id="converting-to-an-owin" class="level3" data-number="3.1.2">
<h3 data-number="3.1.2" class="anchored" data-anchor-id="converting-to-an-owin"><span class="header-section-number">3.1.2</span> Converting to an owin</h3>
<p><code>spatstat</code> needs the study area as an <code>owin</code> object, the observation window that every subsequent calculation is bounded by.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>kbb_owin <span class="ot">&lt;-</span> <span class="fu">as.owin</span>(kbb_sf)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>kbb_owin</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>window: polygonal boundary
enclosing rectangle: [512010.2, 732848.4] x [9655542, 9833973] units</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(kbb_owin)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "owin"</code></pre>
</div>
</div>
</section>
<section id="the-fire-data" class="level3" data-number="3.1.3">
<h3 data-number="3.1.3" class="anchored" data-anchor-id="the-fire-data"><span class="header-section-number">3.1.3</span> The fire data</h3>
<p>The CSV holds one row per detection, with <code>latitude</code>, <code>longitude</code> and <code>acq_date</code> among the columns. The points are read as WGS 84 geographic coordinates and then projected.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>fire_all <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/rawdata/modis_2023_Indonesia.csv"</span>,</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">show_col_types =</span> <span class="cn">FALSE</span>) <span class="sc">|&gt;</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_as_sf</span>(<span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"longitude"</span>, <span class="st">"latitude"</span>), <span class="at">crs =</span> <span class="dv">4326</span>) <span class="sc">|&gt;</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">32748</span>)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(fire_all)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 52156</code></pre>
</div>
</div>
<p>52,156 detections across the whole of Indonesia in 2023. Bangka is a small part of that, so the next step cuts the data to the study area. The chapter’s file is already cut to the study area, which hides this step. It is done explicitly here because the choice of cutting boundary changes the answer.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>fire_sf <span class="ot">&lt;-</span> fire_all[<span class="fu">lengths</span>(<span class="fu">st_intersects</span>(fire_all, kbb_sf)) <span class="sc">&gt;</span> <span class="dv">0</span>, ]</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">indonesia =</span> <span class="fu">nrow</span>(fire_all),</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">bangka =</span> <span class="fu">nrow</span>(fire_sf))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>indonesia    bangka 
    52156       766 </code></pre>
</div>
</div>
<p>766 detections fall inside the study area.</p>
<section id="deriving-the-temporal-marks" class="level4" data-number="3.1.3.1">
<h4 data-number="3.1.3.1" class="anchored" data-anchor-id="deriving-the-temporal-marks"><span class="header-section-number">3.1.3.1</span> Deriving the temporal marks</h4>
<p>A <code>ppp</code> object accepts marks that are numeric or factor, so the acquisition date has to be converted before it can be used as the temporal dimension. Three fields are derived below, covering the two temporal resolutions used later: month and day of year.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>fire_sf <span class="ot">&lt;-</span> fire_sf <span class="sc">|&gt;</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">DayofYear =</span> <span class="fu">yday</span>(acq_date),</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">Month_num =</span> <span class="fu">month</span>(acq_date),</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">Month_fac =</span> <span class="fu">month</span>(acq_date, <span class="at">label =</span> <span class="cn">TRUE</span>, <span class="at">abbr =</span> <span class="cn">FALSE</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">range</span>(fire_sf<span class="sc">$</span>acq_date)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "2023-01-10" "2023-12-18"</code></pre>
</div>
</div>
<p>The detections run from 10 January to 18 December 2023. The gaps at either end are days on which the satellite recorded no fire on Bangka, so the record is complete for the year.</p>
</section>
</section>
<section id="visualising-the-fire-points" class="level3" data-number="3.1.4">
<h3 data-number="3.1.4" class="anchored" data-anchor-id="visualising-the-fire-points"><span class="header-section-number">3.1.4</span> Visualising the fire points</h3>
<section id="overall-distribution" class="level4" data-number="3.1.4.1">
<h4 data-number="3.1.4.1" class="anchored" data-anchor-id="overall-distribution"><span class="header-section-number">3.1.4.1</span> Overall distribution</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(kbb_sf) <span class="sc">+</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>() <span class="sc">+</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(fire_sf) <span class="sc">+</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_dots</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Hands-on_Ex03_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="864"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="by-month" class="level4" data-number="3.1.4.2">
<h4 data-number="3.1.4.2" class="anchored" data-anchor-id="by-month"><span class="header-section-number">3.1.4.2</span> By month</h4>
<p>Drawing one map per month is the first look at the time dimension. If every month looked much the same, a spatio-temporal method would have nothing to add over the methods used in Lesson 2.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(kbb_sf) <span class="sc">+</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>() <span class="sc">+</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(fire_sf) <span class="sc">+</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_dots</span>(<span class="at">size =</span> <span class="fl">0.1</span>) <span class="sc">+</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_facets_wrap</span>(<span class="at">by =</span> <span class="st">"Month_fac"</span>,</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>                 <span class="at">free.coords =</span> <span class="cn">FALSE</span>,</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>                 <span class="at">drop.units =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Hands-on_Ex03_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="864"></p>
</figure>
</div>
</div>
</div>
<p>The counts behind those panels:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>fire_sf <span class="sc">|&gt;</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_drop_geometry</span>() <span class="sc">|&gt;</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(Month_fac, <span class="at">name =</span> <span class="st">"fires"</span>) <span class="sc">|&gt;</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Month_fac fires
1    January    11
2   February     2
3      March    12
4      April    10
5        May    21
6       June    34
7       July    83
8     August   147
9  September   151
10   October   190
11  November    94
12  December    11</code></pre>
</div>
</div>
<p>The year is strongly seasonal. January to June carry 90 detections between them, while July to December carry 676. October alone has 190, more than twice the whole first half of the year. That peak is the dry season.</p>
</section>
</section>
<section id="stkde-by-month" class="level3" data-number="3.1.5">
<h3 data-number="3.1.5" class="anchored" data-anchor-id="stkde-by-month"><span class="header-section-number">3.1.5</span> STKDE by month</h3>
<p><code>spattemp.density()</code> from <code>sparr</code> estimates a density in space and time together. It needs a <code>ppp</code> whose marks hold the temporal coordinate, so everything except the mark and the geometry is dropped first.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>fire_month <span class="ot">&lt;-</span> fire_sf <span class="sc">|&gt;</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Month_num)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>fire_month_ppp <span class="ot">&lt;-</span> <span class="fu">as.ppp</span>(fire_month)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>fire_month_ppp</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Marked planar point pattern: 766 points
marks are numeric, of storage type  'double'
window: rectangle = [521564.1, 728908.3] x [9658137, 9828767] units</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fire_month_ppp)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Marked planar point pattern:  766 points
Average intensity 2.165125e-08 points per square unit

Coordinates are given to 10 decimal places

marks are numeric, of type 'double'
Summary:
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  1.000   8.000   9.000   8.593  10.000  12.000 

Window: rectangle = [521564.1, 728908.3] x [9658137, 9828767] units
                    (207300 x 170600 units)
Window area = 3.5379e+10 square units</code></pre>
</div>
</div>
<section id="checking-for-duplicates" class="level4" data-number="3.1.5.1">
<h4 data-number="3.1.5.1" class="anchored" data-anchor-id="checking-for-duplicates"><span class="header-section-number">3.1.5.1</span> Checking for duplicates</h4>
<p>Lesson 2 established that coincident points break the distance-based methods, so the same check runs here.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">points =</span> <span class="fu">npoints</span>(fire_month_ppp),</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">duplicated =</span> <span class="fu">sum</span>(<span class="fu">duplicated</span>(fire_month_ppp)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>    points duplicated 
       766          0 </code></pre>
</div>
</div>
<p>Zero duplicates. In a purely spatial pattern, co-located points break the distance functions. With time as the mark, repeat detections of the same pixel on different dates are valid observations. They do not arise here because MODIS geolocation shifts slightly between overpasses, so the reported pixel centre moves with it.</p>
</section>
<section id="applying-the-observation-window" class="level4" data-number="3.1.5.2">
<h4 data-number="3.1.5.2" class="anchored" data-anchor-id="applying-the-observation-window"><span class="header-section-number">3.1.5.2</span> Applying the observation window</h4>
<p>By default the <code>ppp</code>’s window is the rectangular bounding box of the points, so the study area <code>owin</code> has to be applied.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>fire_month_owin <span class="ot">&lt;-</span> fire_month_ppp[kbb_owin]</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>fire_month_owin</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Marked planar point pattern: 766 points
marks are numeric, of storage type  'double'
window: polygonal boundary
enclosing rectangle: [512010.2, 732848.4] x [9655542, 9833973] units</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">before =</span> <span class="fu">npoints</span>(fire_month_ppp),</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">after =</span> <span class="fu">npoints</span>(fire_month_owin))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>before  after 
   766    766 </code></pre>
</div>
</div>
<p>No points are lost, because the data was already cut to the same polygon when <code>fire_sf</code> was built. Had the cut been made with a bounding box instead, this step would have dropped points without a warning.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(fire_month_owin)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Hands-on_Ex03_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="864"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="computing-the-density" class="level4" data-number="3.1.5.3">
<h4 data-number="3.1.5.3" class="anchored" data-anchor-id="computing-the-density"><span class="header-section-number">3.1.5.3</span> Computing the density</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>st_kde <span class="ot">&lt;-</span> <span class="fu">spattemp.density</span>(fire_month_owin)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(st_kde)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Spatiotemporal Kernel Density Estimate

Bandwidths
  h = 15504.12 (spatial)
  lambda = 0.0305 (temporal)

No. of observations
  766 

Spatial bound
  Type: polygonal
  2D enclosure: [512010.2, 732848.4] x [9655542, 9833973]

Temporal bound
  [1, 12]

Evaluation
  128 x 128 x 12 trivariate lattice
  Density range: [7.740464e-27, 7.925003e-10]</code></pre>
</div>
</div>
</section>
<section id="plotting-the-result" class="level4" data-number="3.1.5.4">
<h4 data-number="3.1.5.4" class="anchored" data-anchor-id="plotting-the-result"><span class="header-section-number">3.1.5.4</span> Plotting the result</h4>
<p>The chapter plots months 7 to 12 only. The monthly counts explain why: the first half of the year has too few points for a stable surface. Plotting both halves shows the instability that sparse monthly counts produce.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>tims <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfcol =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">3</span>))</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> tims) {</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(st_kde, i,</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">override.par =</span> <span class="cn">FALSE</span>,</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">fix.range =</span> <span class="cn">TRUE</span>,</span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">main =</span> <span class="fu">paste</span>(<span class="st">"KDE at month"</span>, i))</span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Hands-on_Ex03_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="864"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>tims <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">7</span>, <span class="dv">8</span>, <span class="dv">9</span>, <span class="dv">10</span>, <span class="dv">11</span>, <span class="dv">12</span>)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfcol =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">3</span>))</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> tims) {</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(st_kde, i,</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">override.par =</span> <span class="cn">FALSE</span>,</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">fix.range =</span> <span class="cn">TRUE</span>,</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">main =</span> <span class="fu">paste</span>(<span class="st">"KDE at month"</span>, i))</span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Hands-on_Ex03_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="864"></p>
</figure>
</div>
</div>
</div>
<p>With <code>fix.range = TRUE</code> the colour scale is shared across panels, so the panels are comparable. The first half of the year is close to flat. From July the density builds, peaks in October, and falls back in December.</p>
</section>
</section>
<section id="stkde-by-day-of-year" class="level3" data-number="3.1.6">
<h3 data-number="3.1.6" class="anchored" data-anchor-id="stkde-by-day-of-year"><span class="header-section-number">3.1.6</span> STKDE by day of year</h3>
<p>Month is a coarse temporal unit. The same estimate at daily resolution uses <code>DayofYear</code> as the mark.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>fire_yday_ppp <span class="ot">&lt;-</span> fire_sf <span class="sc">|&gt;</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(DayofYear) <span class="sc">|&gt;</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.ppp</span>()</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>fire_yday_owin <span class="ot">&lt;-</span> fire_yday_ppp[kbb_owin]</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>fire_yday_owin</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Marked planar point pattern: 766 points
marks are numeric, of storage type  'double'
window: polygonal boundary
enclosing rectangle: [512010.2, 732848.4] x [9655542, 9833973] units</code></pre>
</div>
</div>
<p><code>summary()</code> is avoided on this object. Because the window is 11 separate pieces, it prints one row per polygon, so the three summary numbers are printed directly instead.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">points =</span> <span class="fu">npoints</span>(fire_yday_owin),</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">window_km2 =</span> <span class="fu">round</span>(spatstat.geom<span class="sc">::</span><span class="fu">area</span>(<span class="fu">Window</span>(fire_yday_owin)) <span class="sc">/</span> <span class="fl">1e6</span>, <span class="dv">1</span>),</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">intensity_per_1000km2 =</span> <span class="fu">round</span>(<span class="fu">npoints</span>(fire_yday_owin) <span class="sc">/</span></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>    (spatstat.geom<span class="sc">::</span><span class="fu">area</span>(<span class="fu">Window</span>(fire_yday_owin)) <span class="sc">/</span> <span class="fl">1e9</span>), <span class="dv">1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>               points            window_km2 intensity_per_1000km2 
                766.0               11886.9                  64.4 </code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>kde_yday <span class="ot">&lt;-</span> <span class="fu">spattemp.density</span>(fire_yday_owin)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(kde_yday)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Spatiotemporal Kernel Density Estimate

Bandwidths
  h = 15504.12 (spatial)
  lambda = 6.3903 (temporal)

No. of observations
  766 

Spatial bound
  Type: polygonal
  2D enclosure: [512010.2, 732848.4] x [9655542, 9833973]

Temporal bound
  [10, 352]

Evaluation
  128 x 128 x 343 trivariate lattice
  Density range: [1.924135e-26, 2.562364e-12]</code></pre>
</div>
</div>
<p>Left as it is, <code>plot()</code> on a daily estimate draws one panel for every day in the range, which is 351 images here. Section 4.2 covers why. <code>tselect</code> picks which days to draw. Six are used here, spaced across the year, and the same six appear again in the next section so that the two bandwidth choices can be compared day by day.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">3</span>))</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (d <span class="cf">in</span> <span class="fu">c</span>(<span class="dv">60</span>, <span class="dv">152</span>, <span class="dv">213</span>, <span class="dv">259</span>, <span class="dv">305</span>, <span class="dv">350</span>)) {</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(kde_yday, <span class="at">tselect =</span> d,</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">override.par =</span> <span class="cn">FALSE</span>,</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">fix.range =</span> <span class="cn">TRUE</span>,</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">main =</span> <span class="fu">paste</span>(<span class="st">"Day"</span>, d))</span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Hands-on_Ex03_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid figure-img" width="864"></p>
</figure>
</div>
</div>
</div>
<p><code>fix.range = TRUE</code> puts all six panels on one colour scale, so a colour means the same density in every panel. That is what makes them comparable, and it is also why days 60, 152 and 350 look like flat blue. Those days are quiet relative to October, so they sit at the bottom of a scale set by the busiest day. Section 3.1.7 quantifies the difference and redraws the same six days with each panel on its own scale.</p>
<p>In the busy panels the density rises through the year and the concentration also moves. On day 213 it sits in the north-west of Bangka, on day 259 it has shifted to the centre and south, and by day 305 it is in the far south, around Bangka Selatan. A single map of the whole year would average these positions together.</p>
<p>These use the default bandwidths.</p>
</section>
<section id="choosing-the-bandwidths" class="level3" data-number="3.1.7">
<h3 data-number="3.1.7" class="anchored" data-anchor-id="choosing-the-bandwidths"><span class="header-section-number">3.1.7</span> Choosing the bandwidths</h3>
<p>Everything above used the defaults. In Lesson 2 the bandwidth turned out to be the choice that moved the KDE most, and the same applies here, with a second bandwidth now controlling smoothing in time.</p>
<p><code>BOOT.spattemp()</code> selects both by bootstrap estimation of the mean integrated squared error, following Hall (1990). It returns an isotropic spatial bandwidth <code>h</code> in map units, so metres here, and a scalar temporal bandwidth <code>lambda</code> in days.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>bw <span class="ot">&lt;-</span> <span class="fu">BOOT.spattemp</span>(fire_yday_owin, <span class="at">verbose =</span> <span class="cn">FALSE</span>)</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>bw</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         h     lambda 
6599.76862   23.76416 </code></pre>
</div>
</div>
<p>The chapter uses <code>h = 9000</code> and <code>lambda = 19</code> at this point. On the same window the bootstrap returns 6,600 m, the same order of magnitude, and 23.8 days. Section 4.1.3 examines where those numbers come from and how far the selectors disagree.</p>
<p>The three candidates side by side:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">source =</span> <span class="fu">c</span>(<span class="st">"spattemp.density default"</span>, <span class="st">"BOOT.spattemp on this data"</span>, <span class="st">"chapter's hard-coded"</span>),</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">h_metres =</span> <span class="fu">c</span>(<span class="fu">round</span>(kde_yday<span class="sc">$</span>h), <span class="fu">round</span>(bw[<span class="st">"h"</span>]), <span class="dv">9000</span>),</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">lambda_days =</span> <span class="fu">round</span>(<span class="fu">c</span>(kde_yday<span class="sc">$</span>lambda, bw[<span class="st">"lambda"</span>], <span class="dv">19</span>), <span class="dv">2</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                      source h_metres lambda_days
1   spattemp.density default    15504        6.39
2 BOOT.spattemp on this data     6600       23.76
3       chapter's hard-coded     9000       19.00</code></pre>
</div>
</div>
<p>The bootstrap is narrower in space and much wider in time than the default: 6.6 km against 15.5 km, and 23.8 days against 6.4 days. The bootstrap values are used below. The procedure minimises estimation error for the particular point pattern and window it is given, and this is a different study area from the chapter’s, so the chapter’s numbers do not carry over.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>kde_yday_boot <span class="ot">&lt;-</span> <span class="fu">spattemp.density</span>(fire_yday_owin,</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">h =</span> bw[<span class="st">"h"</span>],</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">lambda =</span> bw[<span class="st">"lambda"</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">3</span>))</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (d <span class="cf">in</span> <span class="fu">c</span>(<span class="dv">60</span>, <span class="dv">152</span>, <span class="dv">213</span>, <span class="dv">259</span>, <span class="dv">305</span>, <span class="dv">350</span>)) {</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(kde_yday_boot, <span class="at">tselect =</span> d,</span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">override.par =</span> <span class="cn">FALSE</span>,</span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">fix.range =</span> <span class="cn">FALSE</span>,</span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">main =</span> <span class="fu">paste</span>(<span class="st">"Day"</span>, d))</span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Hands-on_Ex03_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid figure-img" width="864"></p>
</figure>
</div>
</div>
</div>
<p>Compared with the default bandwidths in section 3.1.6, the peaks are broader and lower, and the surface changes less from one day to the next. That is the expected effect of 23.8 days of temporal smoothing against the default 6.4 days. The seasonal pattern and the movement of the concentration are the same under both.</p>
<p>These panels use <code>fix.range = FALSE</code>, the default, which is also what the chapter uses here. Each panel is stretched to its own maximum.</p>
</section>
</section>
<section id="second-order-the-k-function" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="second-order-the-k-function"><span class="header-section-number">3.2</span> Second-order: the K-function</h2>
<p>Given the intensity estimated above, do the events still cluster more than chance would produce? The space-time inhomogeneous K-function in <code>stpp</code> addresses this.</p>
<section id="building-the-stpp-object" class="level3" data-number="3.2.1">
<h3 data-number="3.2.1" class="anchored" data-anchor-id="building-the-stpp-object"><span class="header-section-number">3.2.1</span> Building the stpp object</h3>
<p><code>stpp</code> does not integrate with <code>sf</code> or <code>ppp</code>. <code>as.3dpoints()</code> requires a three-column matrix or data frame of coordinates (x, y, t), with t integer-valued.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>coords <span class="ot">&lt;-</span> <span class="fu">st_coordinates</span>(fire_sf)</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>fire_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> coords[, <span class="dv">1</span>],</span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> coords[, <span class="dv">2</span>],</span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">t =</span> fire_sf<span class="sc">$</span>DayofYear)</span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(fire_df)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         x       y  t
1 606178.8 9703062 10
2 661410.6 9683536 10
3 637808.8 9682757 10
4 654882.2 9690665 10
5 669933.6 9697468 10
6 609133.5 9700119 10</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>fire_stpp <span class="ot">&lt;-</span> <span class="fu">as.3dpoints</span>(fire_df)</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(fire_stpp)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "stpp"</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(fire_stpp)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Hands-on_Ex03_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid figure-img" width="864"></p>
</figure>
</div>
</div>
</div>
<p>The left panel is the map. The right panel plots time against the cumulative count, so its slope is the rate of detections. The flat stretch to day 180 and the steep climb through the second half are the same seasonality the monthly maps showed.</p>
</section>
<section id="computing-the-k-function" class="level3" data-number="3.2.2">
<h3 data-number="3.2.2" class="anchored" data-anchor-id="computing-the-k-function"><span class="header-section-number">3.2.2</span> Computing the K-function</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>kbb_stik <span class="ot">&lt;-</span> <span class="fu">STIKhat</span>(fire_stpp)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The chapter’s next step is <code>plotK(kbb_stik)</code>. That call produces no figure inside a rendered document, for reasons set out in section 4.1.5, so it is shown but not run.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plotK</span>(kbb_stik)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The surface can be drawn directly from the object <code>STIKhat()</code> returns. <code>Khat</code> holds the estimate and <code>Ktheo</code> the value expected under space-time independence, so the difference between them is what <code>plotK(L = TRUE)</code> would show.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>k_diff <span class="ot">&lt;-</span> kbb_stik<span class="sc">$</span>Khat <span class="sc">-</span> kbb_stik<span class="sc">$</span>Ktheo</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>lv <span class="ot">&lt;-</span> <span class="fu">pretty</span>(<span class="fu">c</span>(<span class="sc">-</span><span class="fu">max</span>(<span class="fu">abs</span>(k_diff)), <span class="fu">max</span>(<span class="fu">abs</span>(k_diff))), <span class="at">n =</span> <span class="dv">15</span>)</span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a><span class="fu">filled.contour</span>(<span class="at">x =</span> kbb_stik<span class="sc">$</span>dist,</span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a>               <span class="at">y =</span> kbb_stik<span class="sc">$</span>times,</span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a>               <span class="at">z =</span> k_diff,</span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a>               <span class="at">levels =</span> lv,</span>
<span id="cb63-8"><a href="#cb63-8" aria-hidden="true" tabindex="-1"></a>               <span class="at">color.palette =</span> <span class="fu">colorRampPalette</span>(<span class="fu">c</span>(<span class="st">"red"</span>, <span class="st">"white"</span>, <span class="st">"blue"</span>)),</span>
<span id="cb63-9"><a href="#cb63-9" aria-hidden="true" tabindex="-1"></a>               <span class="at">xlab =</span> <span class="st">"spatial distance u (metres)"</span>,</span>
<span id="cb63-10"><a href="#cb63-10" aria-hidden="true" tabindex="-1"></a>               <span class="at">ylab =</span> <span class="st">"time lag v (days)"</span>,</span>
<span id="cb63-11"><a href="#cb63-11" aria-hidden="true" tabindex="-1"></a>               <span class="at">main =</span> <span class="fu">expression</span>(<span class="fu">hat</span>(K)[ST](u, v) <span class="sc">-</span> K[theo]))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Hands-on_Ex03_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid figure-img" width="864"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="reading-the-plot" class="level3" data-number="3.2.3">
<h3 data-number="3.2.3" class="anchored" data-anchor-id="reading-the-plot"><span class="header-section-number">3.2.3</span> Reading the plot</h3>
<p>Blue is positive, meaning more pairs of fires at that combination of distance and time lag than space-time independence would produce. Red would be fewer. The whole surface here is positive, and it rises steadily along both axes, reaching about 4.9 x 10^12 at the far corner.</p>
<p>At short time lags the excess grows with spatial distance, so fires occurring within a few days of each other are distributed across the island rather than concentrated at one location. At large distances the excess also grows with time lag. Fires are clustered in both space and time. Most occur in the dry season, and during that season they occur across a wide area.</p>
<p>The estimate is computed over spatial distances from 3.2 km to 47.6 km and time lags from 6 to 89 days, which <code>STIKhat()</code> chose from the data.</p>
<p><code>STIKhat()</code> was called without a <code>lambda</code> argument, so it uses its own internal intensity estimate as the reference, and a different intensity model would move the surface. No envelope was computed, so the plot does not establish whether the excess exceeds sampling variation. Hohl et al.&nbsp;test significance by comparing the observed function against upper and lower simulation envelopes at each combination of spatial and temporal bandwidth, which is the step missing here.</p>
</section>
</section>
</section>
<section id="part-2-review-and-extension" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Part 2: Review and extension</h1>
<p>Sections 4.1 and 4.2 examine the chapter’s method. Section 4.3 adds an analysis it does not attempt.</p>
<section id="methodology-review" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="methodology-review"><span class="header-section-number">4.1</span> Methodology review</h2>
<p>Six issues in Chapter 6 that affect a computed result, ordered by the size of that effect.</p>
<section id="observation-window-k-function-versus-kde" class="level3" data-number="4.1.1">
<h3 data-number="4.1.1" class="anchored" data-anchor-id="observation-window-k-function-versus-kde"><span class="header-section-number">4.1.1</span> Observation window: K-function versus KDE</h3>
<p>Section 6.11.2 calls <code>STIKhat(fire_stpp)</code> with no <code>s.region</code>. The default is a bounding box:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">missing</span>(s.region))</span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>    s.region <span class="ot">&lt;-</span> <span class="fu">sbox</span>(xyt[, <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>], <span class="at">xfrac =</span> <span class="fl">0.01</span>, <span class="at">yfrac =</span> <span class="fl">0.01</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>So the first half of the chapter estimates density inside the coastline, using <code>kbb_owin</code>, and the second half tests for interaction against a null model spread over a rectangle.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>box <span class="ot">&lt;-</span> <span class="fu">sbox</span>(coords[, <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>], <span class="at">xfrac =</span> <span class="fl">0.01</span>, <span class="at">yfrac =</span> <span class="fl">0.01</span>)</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">bounding_box_km2 =</span> <span class="fu">round</span>(<span class="fu">diff</span>(<span class="fu">range</span>(box[, <span class="dv">1</span>])) <span class="sc">*</span> <span class="fu">diff</span>(<span class="fu">range</span>(box[, <span class="dv">2</span>])) <span class="sc">/</span> <span class="fl">1e6</span>),</span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">land_km2 =</span> <span class="fu">round</span>(<span class="fu">as.numeric</span>(<span class="fu">st_area</span>(kbb_sf)) <span class="sc">/</span> <span class="fl">1e6</span>),</span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">sea_pct =</span> <span class="fu">round</span>(<span class="dv">100</span> <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fu">as.numeric</span>(<span class="fu">st_area</span>(kbb_sf)) <span class="sc">/</span></span>
<span id="cb65-6"><a href="#cb65-6" aria-hidden="true" tabindex="-1"></a>                    (<span class="fu">diff</span>(<span class="fu">range</span>(box[, <span class="dv">1</span>])) <span class="sc">*</span> <span class="fu">diff</span>(<span class="fu">range</span>(box[, <span class="dv">2</span>]))))))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>bounding_box_km2         land_km2          sea_pct 
           36808            11887               68 </code></pre>
</div>
</div>
<p>The box is 3.1 times the land area and 68% of it is water. Under complete randomness the null model places fires at sea. That lowers the expected number of nearby pairs, which in turn makes the observed excess look bigger than it is.</p>
<p>The area also enters the estimator itself. Hohl et al.&nbsp;normalise the space-time K-function by the product of two terms: <em>L</em>, “the area of the study region”, and <em>R</em>, the duration of the study period. Together these give “the volume of the irregular prism that is formed by the study area (base) and the study period (height)”. González et al.&nbsp;(2016) give the isotropic edge-correction weight as |W ⊗ T| w<sub>ij</sub><sup>(u)</sup> w<sub>ij</sub><sup>(v)</sup>, with the study region’s area again a multiplicative factor, and note that isotropic correction is the most widely used in practice, which is also <code>STIKhat()</code>’s default. So an inflated region enlarges both the reference volume and the correction weights.</p>
<p>Passing the region explicitly is standard practice in the sources below. The <code>stpp</code> authors’ own worked example is <code>STIKhat(xyt = FMD, s.region = Northcumbria, t.region = c(1, 200), ...)</code>. A separate paper, González and Moraga (2023), also listed on the Lesson 3 page, builds <code>s.region</code> from the observation window’s boundary before calling the same function. Juan et al.&nbsp;(2012), analysing wildfires, construct their pattern as <code>ppp(X, Y, window = polyowinCTN)</code>. Chapter 6 supplies neither region.</p>
<p><code>s.region</code> takes one polygon, so the main island is used, thinned to keep the boundary tractable. The 11-piece window from section 3.1.1 cannot be passed directly, which is itself a limit of <code>stpp</code> relative to <code>spatstat</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>main_island <span class="ot">&lt;-</span> <span class="fu">st_cast</span>(bangka_raw, <span class="st">"POLYGON"</span>, <span class="at">warn =</span> <span class="cn">FALSE</span>)[</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">which.max</span>(<span class="fu">as.numeric</span>(<span class="fu">st_area</span>(<span class="fu">st_cast</span>(bangka_raw, <span class="st">"POLYGON"</span>, <span class="at">warn =</span> <span class="cn">FALSE</span>))))]</span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>mc <span class="ot">&lt;-</span> <span class="fu">st_coordinates</span>(main_island)[, <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>]</span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a>land_region <span class="ot">&lt;-</span> mc[<span class="fu">seq</span>(<span class="dv">1</span>, <span class="fu">nrow</span>(mc), <span class="at">by =</span> <span class="dv">20</span>), ]</span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-6"><a href="#cb67-6" aria-hidden="true" tabindex="-1"></a>stik_land <span class="ot">&lt;-</span> <span class="fu">STIKhat</span>(fire_stpp, <span class="at">s.region =</span> land_region)</span>
<span id="cb67-7"><a href="#cb67-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-8"><a href="#cb67-8" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">chapter_bbox_window =</span> <span class="fu">signif</span>(<span class="fu">max</span>(kbb_stik<span class="sc">$</span>Khat <span class="sc">-</span> kbb_stik<span class="sc">$</span>Ktheo), <span class="dv">4</span>),</span>
<span id="cb67-9"><a href="#cb67-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">land_window =</span> <span class="fu">signif</span>(<span class="fu">max</span>(stik_land<span class="sc">$</span>Khat <span class="sc">-</span> stik_land<span class="sc">$</span>Ktheo), <span class="dv">4</span>),</span>
<span id="cb67-10"><a href="#cb67-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">ratio =</span> <span class="fu">round</span>(<span class="fu">max</span>(kbb_stik<span class="sc">$</span>Khat <span class="sc">-</span> kbb_stik<span class="sc">$</span>Ktheo) <span class="sc">/</span></span>
<span id="cb67-11"><a href="#cb67-11" aria-hidden="true" tabindex="-1"></a>                <span class="fu">max</span>(stik_land<span class="sc">$</span>Khat <span class="sc">-</span> stik_land<span class="sc">$</span>Ktheo), <span class="dv">2</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>chapter_bbox_window         land_window               ratio 
          2.811e+12           1.172e+12           2.400e+00 </code></pre>
</div>
</div>
<p>Correcting the window reduces the peak excess by a factor of 2.4. The qualitative conclusion in section 3.2.3 holds, since the surface stays positive throughout. The magnitude the chapter reports depends on its choice of window.</p>
</section>
<section id="study-area-definition" class="level3" data-number="4.1.2">
<h3 data-number="4.1.2" class="anchored" data-anchor-id="study-area-definition"><span class="header-section-number">4.1.2</span> Study area definition</h3>
<p>A spatial point process is defined relative to its observation window, so the boundary supplied governs both the density estimate and the edge correction. Chapter 6 states its study area as Kepulauan Bangka Belitung, and its first research question asks about Kepulauan Bangka Belitung. The window it actually uses is smaller, and that difference is nowhere stated.</p>
<p>Its own printed output shows the truncation:</p>
<pre><code>Bounding box:  xmin: 105.1085  xmax: 106.8488
single connected closed polygon
Window area = 11533600000</code></pre>
<p>Belitung island spans 107.11 to 108.85 degrees east, past that <code>xmax</code>, and the province is 46 separate islands, which cannot form one connected polygon. The window holds Bangka alone, 11,534 km² against the province’s 16,761 km².</p>
<p>Whether the province would be the better window is a genuine trade-off:</p>
<ul>
<li><strong>Excluding Belitung discards data.</strong> It carries 132 MODIS detections across nine months of 2023, so the estimate describes one island rather than the province the research question names.</li>
<li><strong>Including it degrades the estimate on both islands.</strong> <code>spattemp.density()</code> fits a single isotropic spatial bandwidth across the whole window, with no way to vary it by region. Bangka’s main landmass sits 85 km from Belitung’s, with 15 km of open water at the nearest approach, and adding the second island moves the selected bandwidth from 6,600 m to 29,251 m.</li>
</ul>
<p>Part 1 uses Bangka, which is the chapter’s actual window, and names it as Bangka. Estimating each island separately with <code>spattemp.density()</code> would give each its own bandwidth and is the better treatment of two disjoint landmasses. That is beyond what section 6.10 covers and is recorded here as a limitation.</p>
</section>
<section id="bandwidth-selection-and-hard-coded-values" class="level3" data-number="4.1.3">
<h3 data-number="4.1.3" class="anchored" data-anchor-id="bandwidth-selection-and-hard-coded-values"><span class="header-section-number">4.1.3</span> Bandwidth selection and hard-coded values</h3>
<p>Section 6.10.1 uses <code>h = 9000</code> and <code>lambda = 19</code> without showing the <code>BOOT.spattemp()</code> output they came from. Those values are specific to the window they were derived on.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>bw_of <span class="ot">&lt;-</span> <span class="cf">function</span>(poly) {</span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>  pts <span class="ot">&lt;-</span> fire_all[<span class="fu">lengths</span>(<span class="fu">st_intersects</span>(fire_all, poly)) <span class="sc">&gt;</span> <span class="dv">0</span>, ] <span class="sc">|&gt;</span></span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">DayofYear =</span> <span class="fu">yday</span>(acq_date))</span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a>  pp <span class="ot">&lt;-</span> (pts <span class="sc">|&gt;</span> <span class="fu">select</span>(DayofYear) <span class="sc">|&gt;</span> <span class="fu">as.ppp</span>())[<span class="fu">as.owin</span>(poly)]</span>
<span id="cb70-5"><a href="#cb70-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">c</span>(<span class="at">parts =</span> <span class="fu">length</span>(<span class="fu">st_cast</span>(poly, <span class="st">"POLYGON"</span>, <span class="at">warn =</span> <span class="cn">FALSE</span>)),</span>
<span id="cb70-6"><a href="#cb70-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">npoints</span>(pp),</span>
<span id="cb70-7"><a href="#cb70-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">BOOT.spattemp</span>(pp, <span class="at">verbose =</span> <span class="cn">FALSE</span>))</span>
<span id="cb70-8"><a href="#cb70-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb70-9"><a href="#cb70-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-10"><a href="#cb70-10" aria-hidden="true" tabindex="-1"></a>province <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="st">"data/rawdata/gadm41_IDN_2.json"</span>, <span class="at">quiet =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb70-11"><a href="#cb70-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(NAME_1 <span class="sc">==</span> <span class="st">"BangkaBelitung"</span>) <span class="sc">|&gt;</span></span>
<span id="cb70-12"><a href="#cb70-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_union</span>() <span class="sc">|&gt;</span> <span class="fu">st_zm</span>(<span class="at">drop =</span> <span class="cn">TRUE</span>, <span class="at">what =</span> <span class="st">"ZM"</span>) <span class="sc">|&gt;</span> <span class="fu">st_transform</span>(<span class="dv">32748</span>)</span>
<span id="cb70-13"><a href="#cb70-13" aria-hidden="true" tabindex="-1"></a>prov_parts <span class="ot">&lt;-</span> <span class="fu">st_cast</span>(province, <span class="st">"POLYGON"</span>, <span class="at">warn =</span> <span class="cn">FALSE</span>)</span>
<span id="cb70-14"><a href="#cb70-14" aria-hidden="true" tabindex="-1"></a>province_clean <span class="ot">&lt;-</span> <span class="fu">st_union</span>(prov_parts[<span class="fu">as.numeric</span>(<span class="fu">st_area</span>(prov_parts)) <span class="sc">/</span> <span class="fl">1e6</span> <span class="sc">&gt;=</span> <span class="dv">1</span>])</span>
<span id="cb70-15"><a href="#cb70-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-16"><a href="#cb70-16" aria-hidden="true" tabindex="-1"></a><span class="fu">rbind</span>(<span class="st">`</span><span class="at">Bangka, all 53 pieces</span><span class="st">`</span>     <span class="ot">=</span> <span class="fu">bw_of</span>(bangka_raw),</span>
<span id="cb70-17"><a href="#cb70-17" aria-hidden="true" tabindex="-1"></a>      <span class="st">`</span><span class="at">Bangka, pieces &gt;= 1 km2</span><span class="st">`</span>   <span class="ot">=</span> <span class="fu">bw_of</span>(kbb_sf),</span>
<span id="cb70-18"><a href="#cb70-18" aria-hidden="true" tabindex="-1"></a>      <span class="st">`</span><span class="at">province, pieces &gt;= 1 km2</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">bw_of</span>(province_clean)) <span class="sc">|&gt;</span></span>
<span id="cb70-19"><a href="#cb70-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">round</span>(<span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                          parts   n       h lambda
Bangka, all 53 pieces        53 766 54139.1   13.7
Bangka, pieces &gt;= 1 km2      11 766  6599.8   23.8
province, pieces &gt;= 1 km2    41 898 29250.8   19.9</code></pre>
</div>
</div>
<p>Dropping fragments that hold 0.03% of the area moves <code>h</code> from 54,139 m to 6,600 m. Adding Belitung moves it back to 29,251 m. The shift is driven almost entirely by the boundary geometry rather than by point density: a single isotropic bandwidth has to balance the whole window at once, so remote fragments inflate <code>h</code>. Filtering the islets in section 3.1.1 therefore changes which bandwidth the estimator selects.</p>
<p>The choice of selector matters as much as the window. <code>sparr</code> provides five, and Chapter 6 uses one of them and then discards its output for a fixed number.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>selectors <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"NS.spattemp"</span>, <span class="st">"OS.spattemp"</span>, <span class="st">"LIK.spattemp"</span>, <span class="st">"LSCV.spattemp"</span>)</span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>sel <span class="ot">&lt;-</span> <span class="fu">t</span>(<span class="fu">sapply</span>(selectors, <span class="cf">function</span>(nm) <span class="fu">get</span>(nm)(fire_yday_owin)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>h = 15504.12 ; lambda = 6.390331 
h = 17054.53 ; lambda = 6.390331 
h = 15504.12 ; lambda = 1556.802 
h = 15891.72 ; lambda = 781.5961 
h = 16085.52 ; lambda = 393.9932 
h = 16182.42 ; lambda = 200.1918 
h = 16230.87 ; lambda = 103.2911 
h = 16255.1 ; lambda = 54.84069 
h = 16267.21 ; lambda = 30.61551 
h = 16273.26 ; lambda = 18.50292 
h = 16276.29 ; lambda = 12.44663 
h = 16282.35 ; lambda = 0.334036 
h = 14731.94 ; lambda = 0.334036 
h = 15312.59 ; lambda = 1.84811 
h = 15650.79 ; lambda = 3.740702 
h = 15724.13 ; lambda = 2.415887 
h = 14754.37 ; lambda = 3.929961 
h = 15900.35 ; lambda = 1.233017 
h = 15488.81 ; lambda = 0.6652396 
h = 16076.58 ; lambda = 0.05014715 
h = 15503.58 ; lambda = 1.398619 
h = 15885.58 ; lambda = 0.4996378 
h = 15790.08 ; lambda = 0.7243831 
h = 15378.54 ; lambda = 0.1566055 
h = 15769.9 ; lambda = 0.9639143 
h = 16071.17 ; lambda = 1.023058 
h = 15925.58 ; lambda = 0.9336033 
h = 15945.76 ; lambda = 0.6940721 
h = 16033.69 ; lambda = 0.559151 
h = 15810.26 ; lambda = 0.4848519 
h = 15896.75 ; lambda = 0.8214154 
h = 16052.43 ; lambda = 0.7911044 
h = 16183.61 ; lambda = 0.824465 
h = 16134.6 ; lambda = 0.9518084 
h = 15992.97 ; lambda = 0.7585062 
h = 16279.83 ; lambda = 0.7615557 
h = 16471.36 ; lambda = 0.7316259 
h = 16662 ; lambda = 0.7975848 
h = 16996.52 ; lambda = 0.8171241 
h = 17284.27 ; lambda = 0.7242849 
h = 17834.61 ; lambda = 0.6741949 
h = 18359.76 ; lambda = 0.7596931 
h = 19303.96 ; lambda = 0.7737267 
h = 20142.05 ; lambda = 0.6307975 
h = 21714.81 ; lambda = 0.5376342 
h = 23184.16 ; lambda = 0.6371659 
h = 21846.78 ; lambda = 0.6464232 
h = 25595.02 ; lambda = 0.4010735 
h = 28740.55 ; lambda = 0.2147469 
h = 24125.67 ; lambda = 0.3015417 
h = 23419.54 ; lambda = 0.5532599 
h = 27299.75 ; lambda = 0.4166992 
h = 30092.22 ; lambda = 0.3562317 
h = 32267.7 ; lambda = 0.2040453 
h = 25631.58 ; lambda = 0.4659562 
h = 30055.66 ; lambda = 0.2913489 
h = 26737.6 ; lambda = 0.4223044 
h = 31234.79 ; lambda = 0.3774626 
h = 34054.68 ; lambda = 0.3656572 
h = 34589.41 ; lambda = 0.3113899 
h = 28700.55 ; lambda = 0.3945758 
h = 29843.13 ; lambda = 0.4158067 
h = 29905.4 ; lambda = 0.4009129 
h = 32439.64 ; lambda = 0.3837998 
h = 34309.19 ; lambda = 0.3784118 
h = 33769.03 ; lambda = 0.3603494 
h = 32803.13 ; lambda = 0.3704903 
h = 34007.98 ; lambda = 0.3768275 
h = 33314.68 ; lambda = 0.3769863 
h = 32951.2 ; lambda = 0.3902957 
h = 32914.18 ; lambda = 0.3853444 
h = 32039.14 ; lambda = 0.3921579 
h = 32358.03 ; lambda = 0.388365 
h = 32995.79 ; lambda = 0.3807792 
h = 32517.47 ; lambda = 0.3864685 
h = 32992 ; lambda = 0.3880131 
h = 32853.91 ; lambda = 0.3869598 
h = 33250.62 ; lambda = 0.3858356 
h = 32700.76 ; lambda = 0.3863103 
h = 32640.49 ; lambda = 0.3879257 
h = 32845.76 ; lambda = 0.3859897 
h = 32692.6 ; lambda = 0.3853402 
h = 32813.59 ; lambda = 0.3865549 
h = 32958.59 ; lambda = 0.3862343 
h = 32765.21 ; lambda = 0.3862913 
h = 32733.04 ; lambda = 0.3868565 
h = 32761.22 ; lambda = 0.3866398 
h = 15504.12 ; lambda = 6.390331 
h = 17054.53 ; lambda = 6.390331 
h = 15504.12 ; lambda = 1556.802 
h = 15891.72 ; lambda = 781.5961 
h = 16085.52 ; lambda = 393.9932 
h = 16182.42 ; lambda = 200.1918 
h = 16230.87 ; lambda = 103.2911 
h = 16255.1 ; lambda = 54.84069 
h = 16267.21 ; lambda = 30.61551 
h = 16273.26 ; lambda = 18.50292 
h = 16276.29 ; lambda = 12.44663 
h = 16282.35 ; lambda = 0.334036 
h = 14731.94 ; lambda = 0.334036 
h = 15505.63 ; lambda = 3.362184 
h = 15506.39 ; lambda = 1.84811 
h = 15506.77 ; lambda = 1.091073 
h = 15506.95 ; lambda = 0.7125544 
h = 15507.05 ; lambda = 0.5232952 
h = 15507.24 ; lambda = 0.1447768 
h = 13956.83 ; lambda = 0.1447768 
h = 12794.07 ; lambda = 0.05014715 
h = 14441.29 ; lambda = 0.215749 
h = 14295.97 ; lambda = 0.1566055 
h = 14005.33 ; lambda = 0.03831845 
h = 14453.47 ; lambda = 0.09450478 
h = 13926.58 ; lambda = 0.06936879 
h = 12872.81 ; lambda = 0.01909681 
h = 14084.08 ; lambda = 0.007268107 
h = 13741.89 ; lambda = 0.02575045 
h = 13215 ; lambda = 0.0006144627 
h = 13261.18 ; lambda = 0.01151905 
h = 13455.36 ; lambda = 0.007730166 
h = 13843.72 ; lambda = 0.000152404 
h = 13806.72 ; lambda = 0.00382577 
h = 13668.04 ; lambda = 0.002104602 
h = 13598.7 ; lambda = 0.001244018 
h = 13564.03 ; lambda = 0.0008137255 
h = 13546.7 ; lambda = 0.0005985794 
h = 14175.42 ; lambda = 0.0001365208 
h = 13778.13 ; lambda = 0.0003715209 
h = 13893.85 ; lambda = 0.0002579917 
h = 14125.29 ; lambda = 3.093316e-05 
h = 14456.98 ; lambda = 1.504989e-05 
h = 14233.28 ; lambda = 7.975615e-05 
h = 14262.21 ; lambda = 5.137384e-05 
h = 14276.67 ; lambda = 3.718268e-05 
h = 14305.6 ; lambda = 8.800371e-06 
h = 14253.29 ; lambda = 2.142915e-05 
h = 14509.29 ; lambda = 2.421119e-06 
h = 14432.21 ; lambda = 1.033032e-05 
h = 14382.68 ; lambda = 8.911697e-07 
h = 14375.79 ; lambda = 5.228257e-06 
h = 14410.89 ; lambda = 3.442201e-06 
h = 14428.44 ; lambda = 2.549172e-06 
h = 14463.53 ; lambda = 7.631158e-07 
h = 14466.2 ; lambda = 1.624131e-06 
h = 14380.01 ; lambda = 3.015487e-08 
h = 14402.23 ; lambda = 6.439025e-07 
h = 14427.33 ; lambda = 5.500723e-07 
h = 14402.95 ; lambda = 4.67008e-07 
h = 14409.4 ; lambda = 3.993269e-07 
h = 14398.83 ; lambda = 3.408745e-07 
h = 14399.41 ; lambda = 2.924208e-07 
h = 14394.27 ; lambda = 2.510811e-07 
h = 14393.28 ; lambda = 2.165194e-07 
h = 14390.46 ; lambda = 1.872091e-07 
h = 14377.19 ; lambda = 8.446178e-10 
h = 14384.53 ; lambda = 1.013544e-07 
h = 14381.57 ; lambda = 5.842709e-08 
h = 14380.08 ; lambda = 3.696342e-08 
h = 14379.34 ; lambda = 2.623158e-08 
h = 14379.14 ; lambda = 2.184648e-08 
h = 14378.75 ; lambda = 1.878857e-08 
h = 14378.56 ; lambda = 1.583154e-08 
h = 14378.31 ; lambda = 1.356332e-08 
h = 14378.16 ; lambda = 1.151775e-08 
h = 14377.99 ; lambda = 9.872254e-09 
h = 14377.87 ; lambda = 8.438095e-09 
h = 14377.76 ; lambda = 7.256805e-09 
h = 14377.68 ; lambda = 6.244403e-09 
h = 14377.6 ; lambda = 5.400658e-09 
h = 14377.12 ; lambda = 8.725035e-13 
h = 14377.38 ; lambda = 2.911701e-09 
h = 14377.27 ; lambda = 1.667223e-09 
h = 14377.21 ; lambda = 1.044984e-09 
h = 14377.18 ; lambda = 7.338647e-10 
h = 14377.17 ; lambda = 6.059932e-10 
h = 14377.16 ; lambda = 5.186488e-10 
h = 14377.15 ; lambda = 4.328769e-10 
h = 14377.15 ; lambda = 3.677618e-10 
h = 14377.14 ; lambda = 3.08597e-10 
h = 14377.14 ; lambda = 2.612483e-10 
h = 14377.14 ; lambda = 2.198287e-10 
h = 14377.13 ; lambda = 1.857994e-10 
h = 14377.13 ; lambda = 1.565823e-10 
h = 14377.13 ; lambda = 1.322634e-10 
h = 14377.13 ; lambda = 1.115752e-10 
h = 14377.12 ; lambda = 9.424363e-11 
h = 14377.12 ; lambda = 7.956661e-11 
h = 14377.12 ; lambda = 6.723159e-11 
h = 14377.12 ; lambda = 5.680933e-11 
h = 14377.12 ; lambda = 4.803625e-11 
h = 14377.12 ; lambda = 4.063185e-11 
h = 14377.12 ; lambda = 3.439422e-11 
h = 14377.12 ; lambda = 2.913261e-11 
h = 14377.12 ; lambda = 2.469839e-11 
h = 14377.12 ; lambda = 2.095903e-11 
h = 14377.12 ; lambda = 1.780707e-11 
h = 14377.12 ; lambda = 1.514941e-11 
h = 14377.12 ; lambda = 1.290902e-11 
h = 14377.12 ; lambda = 1.102008e-11 
h = 14377.12 ; lambda = 9.427654e-12 
h = 14377.12 ; lambda = 8.085081e-12 
h = 14377.12 ; lambda = 6.953223e-12 
h = 14377.12 ; lambda = 5.998972e-12 
h = 14377.12 ; lambda = 5.194481e-12 
h = 14377.12 ; lambda = 6.801178e-14 
h = 14377.12 ; lambda = 2.832369e-12 
h = 14377.12 ; lambda = 1.651313e-12 
h = 14377.12 ; lambda = 1.060785e-12 
h = 14377.12 ; lambda = 7.655216e-13 
h = 14377.12 ; lambda = 6.446351e-13 
h = 14377.12 ; lambda = 5.609225e-13 
h = 14377.12 ; lambda = 4.795511e-13 
h = 14377.12 ; lambda = 4.17352e-13 
h = 14377.12 ; lambda = 5.81265e-15 
h = 14377.12 ; lambda = 2.271321e-13 
h = 14377.12 ; lambda = 1.320222e-13 
h = 14377.12 ; lambda = 8.446719e-14 
h = 14377.12 ; lambda = 6.06897e-14 
h = 14377.12 ; lambda = 5.063148e-14 
h = 14377.12 ; lambda = 4.445588e-14 
h = 14377.12 ; lambda = 3.788287e-14 
h = 14377.12 ; lambda = 3.315182e-14 
h = 14377.12 ; lambda = 1.081599e-15 
h = 14377.12 ; lambda = 1.829947e-14 
h = 14377.12 ; lambda = 1.08733e-14 
h = 14377.12 ; lambda = 7.160212e-15 
h = 14377.12 ; lambda = 5.303668e-15 
h = 14377.12 ; lambda = 5.726174e-16 
h = 14377.12 ; lambda = 3.065388e-15 
h = 14377.12 ; lambda = 1.946248e-15 
h = 14377.12 ; lambda = 1.386678e-15 
h = 14377.12 ; lambda = 2.675383e-16 
h = 14377.12 ; lambda = 7.508386e-16 
h = 14377.12 ; lambda = 8.931721e-17 
h = 14377.12 ; lambda = 3.755226e-16 
h = 14377.12 ; lambda = 2.769752e-16 
h = 14377.12 ; lambda = 7.988037e-17 
h = 14377.12 ; lambda = 1.760686e-16 
h = 14377.12 ; lambda = 1.303337e-16 
h = 14377.12 ; lambda = 3.88639e-17 
h = 14377.12 ; lambda = 2.942705e-17 
h = 14377.12 ; lambda = 5.701292e-17 
h = 14377.12 ; lambda = 1.127803e-17 
h = 14377.12 ; lambda = 1.841187e-18 
h = 14377.12 ; lambda = 1.799333e-17 
h = 14377.12 ; lambda = 1.227647e-17 
h = 14377.12 ; lambda = 8.427488e-19 
h = 14377.12 ; lambda = 6.31e-18 
h = 14377.12 ; lambda = 3.825984e-18 
h = 14377.12 ; lambda = 2.583976e-18 
h = 14377.12 ; lambda = 9.996007e-20 
h = 14377.12 ; lambda = 1.156271e-18 
h = 14377.12 ; lambda = 8.138127e-19 
h = 14377.12 ; lambda = 7.102395e-20 
h = 14377.12 ; lambda = 4.496523e-19 
h = 14377.12 ; lambda = 2.675722e-19 
h = 14377.12 ; lambda = 1.765321e-19 
h = 14377.12 ; lambda = 1.310121e-19 
h = 14377.12 ; lambda = 3.997197e-20 
h = 14377.12 ; lambda = 1.103585e-20 
h = 14377.12 ; lambda = 4.826393e-20 
h = 14377.12 ; lambda = 2.743887e-21 
h = 14377.12 ; lambda = 2.343092e-20 
h = 14377.12 ; lambda = 1.516039e-20 
h = 14377.12 ; lambda = 1.102513e-20 
h = 14377.12 ; lambda = 2.733168e-21 
h = 14377.12 ; lambda = 6.881829e-21 
h = 14377.12 ; lambda = 4.810178e-21 
h = 14377.12 ; lambda = 6.668765e-22 
h = 14377.12 ; lambda = 6.561572e-22 
h = 14377.12 ; lambda = 1.697342e-21 
h = 14377.12 ; lambda = 1.17943e-21 
h = 14377.12 ; lambda = 1.436041e-22 
h = 14377.12 ; lambda = 1.328847e-22 
h = 14377.12 ; lambda = 3.972008e-22 
h = 14377.12 ; lambda = 2.677226e-22 
h = 14377.12 ; lambda = 8.766253e-24 
h = 14377.12 ; lambda = 1.072148e-22 
h = 14377.12 ; lambda = 9.543764e-23 
h = 14377.12 ; lambda = 7.965838e-23 
h = 14377.12 ; lambda = 6.982498e-23 
h = 14377.12 ; lambda = 5.9477e-23 
h = 14377.12 ; lambda = 5.19733e-23 
h = 14377.12 ; lambda = 1.262557e-24 
h = 14377.12 ; lambda = 2.849385e-23 
h = 14377.12 ; lambda = 1.675413e-23 
h = 14377.12 ; lambda = 1.088427e-23 
h = 14377.12 ; lambda = 7.949336e-24 
h = 14377.12 ; lambda = 4.456404e-25 
h = 14377.12 ; lambda = 4.401717e-24 
h = 14377.12 ; lambda = 2.627908e-24 
h = 14377.12 ; lambda = 1.741003e-24 
h = 14377.12 ; lambda = 1.297551e-24 
h = 14377.12 ; lambda = 4.106465e-25 
h = 14377.12 ; lambda = 8.453503e-25 
h = 14377.12 ; lambda = 1.09366e-26 
h = 14377.12 ; lambda = 3.28216e-25 
h = 14377.12 ; lambda = 2.901114e-25 
h = 14377.12 ; lambda = 2.3937e-25 
h = 14377.12 ; lambda = 2.076323e-25 
h = 14377.12 ; lambda = 1.743272e-25 
h = 14377.12 ; lambda = 1.501321e-25 
h = 14377.12 ; lambda = 1.274308e-25 
h = 14377.12 ; lambda = 1.096579e-25 
h = 14377.12 ; lambda = 9.386403e-26 
h = 14377.12 ; lambda = 8.102912e-26 
h = 14377.12 ; lambda = 6.992344e-26 
h = 14377.12 ; lambda = 6.072957e-26 
h = 14377.12 ; lambda = 1.742726e-27 
h = 14377.12 ; lambda = 3.353462e-26 
h = 14377.12 ; lambda = 1.993714e-26 
h = 14377.12 ; lambda = 1.31384e-26 
h = 14377.12 ; lambda = 9.739033e-27 
h = 14377.12 ; lambda = 5.45158e-28 
h = 14377.12 ; lambda = 5.441488e-27 
h = 14377.12 ; lambda = 3.292715e-27 
h = 14377.12 ; lambda = 2.218329e-27 
h = 14377.12 ; lambda = 6.955584e-29 
h = 14377.12 ; lambda = 1.025042e-27 
h = 14377.12 ; lambda = 6.661993e-28 
h = 14377.12 ; lambda = 4.867781e-28 
h = 14377.12 ; lambda = 1.117593e-29 
h = 14377.12 ; lambda = 2.63572e-28 
h = 14377.12 ; lambda = 1.519689e-28 
h = 14377.12 ; lambda = 9.616742e-29 
h = 14377.12 ; lambda = 6.826665e-29 
h = 14377.12 ; lambda = 9.886737e-30 
h = 14377.12 ; lambda = 3.939899e-29 
h = 14377.12 ; lambda = 2.496516e-29 
h = 14377.12 ; lambda = 1.774825e-29 
h = 14377.12 ; lambda = 3.314419e-30 
h = 14377.12 ; lambda = 2.025226e-30 
h = 14377.12 ; lambda = 6.27828e-30 
h = 14377.12 ; lambda = 4.474051e-30 
h = 14377.12 ; lambda = 8.655936e-31 
h = 14377.12 ; lambda = 2.379914e-30 
h = 14377.12 ; lambda = 5.10905e-31 
h = 14377.12 ; lambda = 1.356737e-30 
h = 14377.12 ; lambda = 1.976113e-32 
h = 14377.12 ; lambda = 5.654633e-31 
h = 14377.12 ; lambda = 4.153982e-31 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rbind</span>(sel,</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>      <span class="at">BOOT.spattemp =</span> bw,</span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>      <span class="st">`</span><span class="at">chapter (hard-coded)</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="at">h =</span> <span class="dv">9000</span>, <span class="at">lambda =</span> <span class="dv">19</span>)) <span class="sc">|&gt;</span></span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">round</span>(<span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            h lambda
NS.spattemp          14295.15  12.81
OS.spattemp          15504.12  16.28
LIK.spattemp         32765.21   0.39
LSCV.spattemp        14377.12   0.00
BOOT.spattemp         6599.77  23.76
chapter (hard-coded)  9000.00  19.00</code></pre>
</div>
</div>
<p>Spatial bandwidths run from 6,600 m to 32,765 m, a factor of five, on identical data and an identical window. The two cross-validation selectors do not merely disagree: <code>LSCV.spattemp</code> returns a temporal bandwidth of 0.00 days and <code>LIK.spattemp</code> returns 0.39. Both are close enough to zero to mean no temporal smoothing at all, which reduces the estimate to plotting each day separately. Daily counts here are sparse and strongly seasonal, which is the likely cause. The three that behave, <code>NS</code>, <code>OS</code> and the bootstrap, fall between 12.8 and 23.8 days.</p>
<p>The bare <code>spattemp.density(fire_yday_owin)</code> call in section 6.9 is not bandwidth-free either. Its source sets <code>h &lt;- OS(pp)</code> and <code>lambda &lt;- bw.SJ(tt)</code>, so it silently uses the oversmoothing selector for space and Sheather-Jones for time. Chapter 6 does not say so.</p>
<p>Tonini et al.&nbsp;(2017) use a different method, reading the bandwidth off the K-function by taking “the distance values showing a maximum cluster behaviour” as the scale that avoids under- or over-smoothing. That does not transfer here. The K surface in section 3.2.2 rises monotonically and its maximum sits at 44,085 m, the largest distance evaluated, so there is no interior peak to read.</p>
<p>The Lesson 3 readings do not agree on how to choose a bandwidth. Chapter 6 presents one number as though the question were settled.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Source</th>
<th>How the bandwidth is chosen</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Chapter 6</td>
<td><code>BOOT.spattemp()</code>, then a fixed value carried over from another dataset</td>
</tr>
<tr class="even">
<td>Tonini et al.&nbsp;(2017)</td>
<td>Read off the K-function, at the distance of maximum clustering</td>
</tr>
<tr class="odd">
<td>González and Moraga (2023)</td>
<td>Spatially varying, using an adaptive estimate</td>
</tr>
<tr class="even">
<td>Hohl et al.</td>
<td>Not chosen at all. They sweep 50 m to 1,000 m in 50 m steps and 0 to 14 days in 1-day steps, then report the scales at which the observed function departs furthest from the simulation envelope</td>
</tr>
</tbody>
</table>
<p>Hohl et al.&nbsp;use a different approach. They vary the bandwidth itself and report clustering as a function of scale, which sidesteps the selector disagreement above at the cost of much more computation.</p>
<p>On the observation window there is no such disagreement. All three sources that call these functions pass the study region explicitly, which is why section 4.1.1 treats the chapter’s omission as an error rather than one of several accepted approaches.</p>
<p>A further limitation: everything above uses a fixed bandwidth. González and Moraga (2023) note that “the estimation can be improved by using a spatially varying bandwidth despite its computational complexity”, and Tonini et al.&nbsp;compared fixed against adaptive and chose adaptive. <code>sparr</code> supports adaptive smoothing and this exercise does not use it.</p>
</section>
<section id="colour-scaling-across-sections" class="level3" data-number="4.1.4">
<h3 data-number="4.1.4" class="anchored" data-anchor-id="colour-scaling-across-sections"><span class="header-section-number">4.1.4</span> Colour scaling across sections</h3>
<p>Plotting a density surface at several time slices requires a choice: one colour scale shared by every panel, or a separate scale fitted to each. Chapter 6 makes both choices without saying so. Section 6.8.5 passes <code>fix.range = TRUE</code>, section 6.10.2 takes the <code>FALSE</code> default, and the text does not mention the change.</p>
<p>The choice matters here because the year is very uneven.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>days <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">60</span>, <span class="dv">152</span>, <span class="dv">213</span>, <span class="dv">259</span>, <span class="dv">305</span>, <span class="dv">350</span>)</span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>day_max <span class="ot">&lt;-</span> <span class="fu">sapply</span>(days, <span class="cf">function</span>(d) {</span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a>  nm <span class="ot">&lt;-</span> <span class="fu">names</span>(kde_yday_boot<span class="sc">$</span>z)[<span class="fu">which.min</span>(<span class="fu">abs</span>(<span class="fu">as.numeric</span>(<span class="fu">names</span>(kde_yday_boot<span class="sc">$</span>z)) <span class="sc">-</span> d))]</span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a>  v <span class="ot">&lt;-</span> kde_yday_boot<span class="sc">$</span>z[[nm]]<span class="sc">$</span>v</span>
<span id="cb76-6"><a href="#cb76-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">max</span>(v[<span class="fu">is.finite</span>(v)])</span>
<span id="cb76-7"><a href="#cb76-7" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb76-8"><a href="#cb76-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-9"><a href="#cb76-9" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="at">day =</span> days,</span>
<span id="cb76-10"><a href="#cb76-10" aria-hidden="true" tabindex="-1"></a>           <span class="at">date =</span> <span class="fu">format</span>(<span class="fu">as.Date</span>(days <span class="sc">-</span> <span class="dv">1</span>, <span class="at">origin =</span> <span class="st">"2023-01-01"</span>), <span class="st">"%d %b"</span>),</span>
<span id="cb76-11"><a href="#cb76-11" aria-hidden="true" tabindex="-1"></a>           <span class="at">peak_density =</span> <span class="fu">signif</span>(day_max, <span class="dv">3</span>),</span>
<span id="cb76-12"><a href="#cb76-12" aria-hidden="true" tabindex="-1"></a>           <span class="at">pct_of_highest =</span> <span class="fu">round</span>(<span class="dv">100</span> <span class="sc">*</span> day_max <span class="sc">/</span> <span class="fu">max</span>(day_max), <span class="dv">1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  day   date peak_density pct_of_highest
1  60 01 Mar     2.02e-13            7.1
2 152 01 Jun     4.69e-13           16.6
3 213 01 Aug     2.21e-12           78.3
4 259 16 Sep     2.24e-12           79.4
5 305 01 Nov     2.83e-12          100.0
6 350 16 Dec     1.47e-12           51.9</code></pre>
</div>
</div>
<p>Peak density on 1 November is 14 times that on 1 March.</p>
<p>With <code>fix.range = FALSE</code>, the default, each panel gets its own colour scale running from that day’s own minimum to that day’s own maximum. Every panel therefore uses the full range of colours, and 1 March is drawn as brightly as 1 November even though its peak density is a fourteenth as high. What the colours show is where the fires were on that day.</p>
<p>With <code>fix.range = TRUE</code>, one scale is set by the busiest day and used for all six panels. The same colour then means the same density everywhere, so 1 March is almost uniformly dark. That is correct about the season and it hides the variation within the quiet days.</p>
<p>The chapter switches between the two without saying which question it is answering. <code>TRUE</code> shows the timing of the fire season; <code>FALSE</code> shows where the fires fell on a given day.</p>
</section>
<section id="graphics-device-handling-in-plotk" class="level3" data-number="4.1.5">
<h3 data-number="4.1.5" class="anchored" data-anchor-id="graphics-device-handling-in-plotk"><span class="header-section-number">4.1.5</span> Graphics device handling in plotK()</h3>
<p><code>plotK()</code> manages the graphics device itself, which works in an interactive session and does not survive document rendering. It checks the active devices with <code>dev.list()</code>, closes any it finds with <code>dev.off()</code>, and opens a new one with <code>dev.new()</code>. During a render, the open device is the one knitr is using to capture chunk output into a figure file. Closing it sends the plot to a device nothing is recording, and the chunk completes with no image and no warning.</p>
<p>This is a limitation of the function rather than an error in the chapter, and the chapter’s own published page shows the effect: section 6.11.2 carries the code with no figure below it, and the last image on the page is <code>plot(fire_stpp)</code> from 6.11.1.</p>
<p>Section 3.2.2 does not call <code>plotK()</code>. It draws K̂(u,v) − K_theo from the object <code>STIKhat()</code> returns, using <code>filled.contour()</code>.</p>
</section>
<section id="seed-placement" class="level3" data-number="4.1.6">
<h3 data-number="4.1.6" class="anchored" data-anchor-id="seed-placement"><span class="header-section-number">4.1.6</span> Seed placement</h3>
<p><code>BOOT.spattemp()</code> is a bootstrap. The chapter sets one seed inside section 6.10, immediately before that call, and nowhere else. Anything added before or after is unseeded, so the numbers that the prose quotes can change on re-rendering. This page sets one seed in section 2.1 before anything runs.</p>
<p>Across two seeds <code>BOOT.spattemp()</code> returned identical bandwidths on this dataset. That stability is specific to this call and does not extend to the envelopes and simulations the take-home will need.</p>
</section>
</section>
<section id="other-observations" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="other-observations"><span class="header-section-number">4.2</span> Other observations</h2>
<p>Further points about how the chapter’s code behaves. None of them change a result.</p>
<p><strong>The duplicate check.</strong> Section 6.8.2 runs <code>any(duplicated(fire_month_ppp))</code> and does nothing with the output. Section 3.1.5.1 reports the count instead, which is zero.</p>
<p><strong>One image per day.</strong> <code>plot()</code> on a daily estimate draws a separate panel for every day in the range. In an interactive session those appear in sequence as an animation, which is why <code>plot.stden()</code> has a <code>sleep</code> argument. On a web page there is nothing to animate, so each frame is written out as its own image file instead. Section 6.9.3 produces 343 of these, section 6.10.2 another 343, and the published page carries 686 in total. The <code>tselect</code> argument selects which days to draw. It goes unused in both sections.</p>
</section>
<section id="fire-counts-and-rates-by-regency" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="fire-counts-and-rates-by-regency"><span class="header-section-number">4.3</span> Fire counts and rates by regency</h2>
<p>Chapter 6 does not break the fires down by administrative unit. The density surface it produces is continuous across space, so it smooths over the differences between those units.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>fire_counts <span class="ot">&lt;-</span> <span class="fu">st_join</span>(fire_sf, kbb_regencies[<span class="st">"NAME_2"</span>]) <span class="sc">|&gt;</span></span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_drop_geometry</span>() <span class="sc">|&gt;</span></span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(NAME_2, <span class="at">name =</span> <span class="st">"fires"</span>)</span>
<span id="cb78-4"><a href="#cb78-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-5"><a href="#cb78-5" aria-hidden="true" tabindex="-1"></a>kbb_regencies <span class="sc">|&gt;</span></span>
<span id="cb78-6"><a href="#cb78-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">area_km2 =</span> <span class="fu">round</span>(<span class="fu">as.numeric</span>(<span class="fu">st_area</span>(kbb_regencies)) <span class="sc">/</span> <span class="fl">1e6</span>)) <span class="sc">|&gt;</span></span>
<span id="cb78-7"><a href="#cb78-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_drop_geometry</span>() <span class="sc">|&gt;</span></span>
<span id="cb78-8"><a href="#cb78-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(NAME_2, area_km2) <span class="sc">|&gt;</span></span>
<span id="cb78-9"><a href="#cb78-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(fire_counts, <span class="at">by =</span> <span class="st">"NAME_2"</span>) <span class="sc">|&gt;</span></span>
<span id="cb78-10"><a href="#cb78-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">fires =</span> <span class="fu">replace_na</span>(fires, <span class="dv">0</span>),</span>
<span id="cb78-11"><a href="#cb78-11" aria-hidden="true" tabindex="-1"></a>         <span class="at">per_1000km2 =</span> <span class="fu">round</span>(fires <span class="sc">/</span> area_km2 <span class="sc">*</span> <span class="dv">1000</span>, <span class="dv">1</span>)) <span class="sc">|&gt;</span></span>
<span id="cb78-12"><a href="#cb78-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(fires)) <span class="sc">|&gt;</span></span>
<span id="cb78-13"><a href="#cb78-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         NAME_2 area_km2 fires per_1000km2
1 BangkaSelatan     3617   357        98.7
2  BangkaTengah     2220   141        63.5
3   BangkaBarat     2889   135        46.7
4        Bangka     3057   133        43.5
5 Pangkalpinang      109     0         0.0</code></pre>
</div>
</div>
<p>Counts and rates rank the regencies differently, where the rate is each regency’s fire count divided by its area. Pangkalpinang records none at all. It is the only city in the table and the smallest unit at 109 km².</p>
<p>Counting by regency also matches the administrative unit Take-home Exercise 1 requires students to select.</p>
</section>
</section>
<section id="reflection" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Reflection</h1>
<p>The chapter asks two questions. On the first, the fires are not independent in space and time: the K-function excess is positive across every distance and time lag evaluated. On the second, they concentrate in the south of Bangka, where Bangka Selatan carries 357 of the 766 detections on 30% of the land area, and in the second half of the year, where October alone accounts for 190. The concentration also moves through the season, sitting in the north-west in August and in the far south by November. Section 4.1.1 shows the chapter’s own K-function call overstates the size of that clustering by a factor of 2.4; the direction is the same either way.</p>
<p>The reproduction in Part 1 took a few hours. Almost all the remaining time went on Part 2, and most of that on checking things I had assumed were fine.</p>
<p>The chapter left three decisions to me.</p>
<p><strong>The study area.</strong> Chapter 6 says its study area is the province and its file contains one island. I found this because the map I produced had a second island that the chapter’s map does not have. I checked the chapter’s printed bounding box against two independent boundary sources, GADM and geoBoundaries, which agree with each other and not with the chapter. Part 1 follows the chapter’s actual window because reproducing the chapter is the exercise, and names that window correctly. Analysing the province is the other reasonable choice, and I measured what it costs: a single isotropic bandwidth serving two landmasses 85 km apart moves from 6,600 m to 29,251 m.</p>
<p><strong>Dropping the offshore islets.</strong> I filtered pieces under 1 km² at the start, expecting it to be housekeeping. With all 53 pieces the bootstrap selects 54,139 m; with 11 it selects 6,600 m. Fragments holding 0.03% of the area were setting the smoothing scale for the whole island. I found this because a number in Part 2 disagreed with one I had computed earlier.</p>
<p><strong>Using the bootstrap’s own output.</strong> The chapter hard-codes <code>h = 9000</code>. I wrote that this was wrong and then, in the same section, hard-coded it myself instead of passing the value the bootstrap returned. The version here runs <code>BOOT.spattemp()</code> and uses what it returns.</p>
<p>With more time I would estimate each island separately. <code>spattemp.density()</code> fits one bandwidth across the whole window, so two disjoint landmasses cannot both be served well. The readings agree: González and Moraga recommend a spatially varying bandwidth, and Tonini et al.&nbsp;compared fixed against adaptive and chose adaptive. This exercise uses a fixed bandwidth throughout.</p>
<p>The analysis does not establish two things. The K-function has no simulation envelope, so nothing here shows the observed excess is larger than sampling variation would produce; Hohl et al.&nbsp;do this by comparing against upper and lower envelopes at each combination of bandwidths. And <code>STIKhat()</code> was run without a <code>lambda</code>, so it uses its own internal intensity estimate as the reference rather than one I specified.</p>
<p>Three of the findings across Part 2 are calls that return without error and without effect: <code>plotK()</code> draws to a device that has been discarded, section 6.8.2 computes a duplicate check and does not read it, and <code>STIKhat()</code> substitutes a bounding box for the study region. None of them warn. In Ex 2 the same pattern appeared as a <code>clipregion</code> argument passed as a string instead of an object. In each case the output had to be inspected before the problem was visible.</p>
</section>
<section id="references" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> References</h1>
<ul>
<li>r4gdsa, <a href="https://r4gdsa.netlify.app/chap06.html">Chapter 6: Spatio-Temporal Point Patterns Analysis</a>.</li>
</ul>
<p>Lesson 3 reading list:</p>
<ul>
<li>González, J.A., Rodríguez-Cortés, F.J., Cronie, O. and Mateu, J. (2016), “Spatio-temporal point process statistics: A review”, <em>Spatial Statistics</em>, 18(B), 505-544.</li>
<li>Hohl, A., Zheng, M., Tang, W., Delmelle, E. and Casas, I., “Spatiotemporal Point Pattern Analysis Using Ripley’s K Function”, in <em>Geospatial Data Science Techniques and Applications</em>, ch.&nbsp;7, 155-175.</li>
<li>Tonini, M., Pereira, M.G., Parente, J. and Vega Orozco, C. (2017), “Evolution of forest fires in Portugal: from spatio-temporal point events to smoothed density maps”, <em>Natural Hazards</em>, 85(3), 1489-1510.</li>
<li>Juan, P., Mateu, J. and Saez, M. (2012), “Pinpointing spatio-temporal interactions in wildfire patterns”, <em>Stochastic Environmental Research and Risk Assessment</em>, 26(8), 1131-1150.</li>
<li>González, J.A. and Moraga, P. (2023), <a href="https://journal.r-project.org/articles/RJ-2023-025/">“Non-Parametric Analysis of Spatial and Spatio-Temporal Point Patterns”</a>, <em>The R Journal</em>, 15(2).</li>
<li>Gabriel, E., Rowlingson, B. and Diggle, P.J. (2013), <a href="https://www.jstatsoft.org/article/view/v053i02">“stpp: An R Package for Plotting, Simulating and Analyzing Spatio-Temporal Point Patterns”</a>, <em>Journal of Statistical Software</em>, 53(2).</li>
</ul>
<p>Methods and packages:</p>
<ul>
<li>Davies, T.M. and Hazelton, M.L. (2010), “Adaptive kernel estimation of spatial relative risk”, <em>Statistics in Medicine</em>, 29(23), 2423-2437. The method behind <code>sparr</code>.</li>
<li>Hall, P. (1990), “Using the Bootstrap to Estimate Mean Squared Error and Select Smoothing Parameter in Nonparametric Problems”, <em>Journal of Multivariate Analysis</em>, 32, 177-203. The bootstrap behind <code>BOOT.spattemp()</code>.</li>
</ul>
<p>Data:</p>
<ul>
<li>NASA FIRMS, <a href="https://firms.modaps.eosdis.nasa.gov/">Fire Information for Resource Management System</a>, MODIS Collection 6.1 archive for Indonesia,
<ol start="2023" type="1">
<li></li>
</ol></li>
<li>GADM, <a href="https://gadm.org/">Database of Global Administrative Areas</a>, version 4.1, Indonesia level 2.</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/isss626-gaa\.vercel\.app");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>